/**
 * Needlework illustration-guided engine — driver.
 *
 * Flux illustration -> `bitmapToStitches` (src/lib/needlework/illustration-engine, the
 * reusable pure core) -> loom `renderHero`. With `--publish` it persists end-to-end
 * through the SAME pipeline as needlework-seed-pattern.ts (Media + buildPatternDocument
 * + toStoredVectorData + NeedleworkPattern) so the design goes live on its page.
 *
 *   cd apps/web && npx tsx scripts/needlework-paint.ts <slug ...> [--none] [--publish] [--rerender]
 *
 * --none = frameless (else round->hoop). --publish = write to DB + R2 (UNLISTED house
 * pattern). Run from the MAIN checkout (needs node_modules + @homemade/db). Build-time
 * tooling: tsconfig-excluded. See NEEDLEWORK_ENGINE.md for the full process.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
function loadEnv(path: string): void {
  try { for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line)
    if (m && m[1] && !process.env[m[1]]) process.env[m[1]] = m[2]!.replace(/^["']|["']$/g, '')
  } } catch { /* shell env */ }
}
loadEnv('C:/Users/Rebecca/Projects/code/homemade/.env.credentials')

import sharp from 'sharp'
import { fluxIllustration } from '../src/lib/studio/generation/sources'
import { bitmapToStitches } from '../src/lib/needlework/illustration-engine'
import { buildPatternDocument } from '../src/lib/needlework/engine/document'
import { toStoredVectorData, type NeedleworkSurfacePattern } from '../src/lib/needlework/pattern'
import { renderHero } from './loom-render-hero'
import { r2UploadScript } from './import-lib/r2-script'

const OUT = resolve(process.cwd(), '../../.loom-scratch/needlework/paint')
const FABRIC = '#ece4d2'

interface Job {
  slug: string
  prompt: string
  name?: string
  description?: string
  widthMm?: number
  mode?: 'dense' | 'line'
  frame?: 'round' | 'square' | 'rect'
  tameWarm?: boolean
  detail?: boolean
  bleed?: boolean
}
const PLAIN = ', centered, filling the frame, plain pale cream background, no text, no border'
const DELICATE = ', thin clean dark outlines, soft watercolour colours, centered, plain off-white background, lots of negative space, no text'
const JOBS: Record<string, Job> = {
  fox: { slug: 'fox', name: 'Red Fox', description: 'A red fox sitting alert, worked in bold directional long-and-short fur.', prompt: 'a highly detailed naturalistic illustration of a single red fox sitting and facing forward, fluffy fur, bright amber eyes, bushy tail, soft woodland colours' + PLAIN, frame: 'rect', widthMm: 250 },
  peacock: { slug: 'peacock', name: 'Peacock in Full Display', description: 'A peacock with its tail fanned in iridescent blue, teal and gold — a symmetrical showpiece.', prompt: 'a stunning highly detailed illustration of a peacock with its tail fanned out, iridescent blue and teal and gold feathers with eye spots, ornate, symmetrical' + PLAIN, frame: 'round', widthMm: 280 },
  cat: { slug: 'cat', name: 'Sleeping Cat', description: 'A cosy ginger cat curled asleep, worked in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a fluffy ginger cat curled up asleep, soft fur, cosy' + PLAIN, frame: 'square', widthMm: 240 },
  hare: { slug: 'hare', name: 'Brown Hare', description: 'A brown hare sitting alert in profile, with soft directional fur and whiskers.', prompt: 'a highly detailed naturalistic illustration of a brown hare sitting alert in profile, soft fur, long ears' + PLAIN, frame: 'round', widthMm: 200 },
  robin: { slug: 'robin', name: 'Robin & Berries', description: 'A plump robin on a berried twig, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a plump European robin perched on a twig with a few red berries, orange-red breast' + PLAIN, frame: 'round', widthMm: 165 },
  kingfisher: { slug: 'kingfisher', name: 'Kingfisher', description: 'A kingfisher in jewel-bright plumage — electric blue and copper, in fine thread painting.', prompt: 'a highly detailed naturalistic illustration of a kingfisher bird perched, vivid electric blue back and bright orange belly' + PLAIN, frame: 'rect', widthMm: 230 },
  cottage: { slug: 'cottage', name: 'Thatched Cottage Garden', description: 'A thatched English cottage with a lush flower garden — a full stitched scene.', prompt: 'a highly detailed naturalistic illustration of a thatched english cottage with a lush cottage flower garden, path and trees under a soft blue sky' + PLAIN, frame: 'rect', widthMm: 320 },
  peony: { slug: 'peony', name: 'Peony Bloom', description: 'A single blush-pink peony in soft, layered long-and-short shading on a hoop.', prompt: 'a highly detailed naturalistic illustration of a single large blush-pink peony bloom with soft layered petals and green leaves' + PLAIN, frame: 'round', widthMm: 150 },
  jar: { slug: 'jar', name: 'Wildflower Jar', description: 'A little jar of mixed wildflowers — poppies, cornflowers and daisies — in delicate thread painting on bare linen.', prompt: 'a simple delicate botanical illustration of a small glass mason jar holding a little bunch of mixed wildflowers, poppies cornflowers daisies' + DELICATE, mode: 'line', frame: 'rect', widthMm: 200 },
  sprig: { slug: 'sprig', name: 'Lavender Sprig', description: 'A few lavender stems and small wildflowers tied with twine — a delicate line motif on bare linen.', prompt: 'a simple delicate botanical illustration of three lavender stems and two small wildflowers tied with twine' + DELICATE, mode: 'line', frame: 'round', widthMm: 150 },
  facecrown: { slug: 'facecrown', name: 'Flower Crown', description: 'A fine-art portrait crowned with roses and poppies, in soft thread painting.', prompt: "a beautiful fine-art portrait illustration of a young woman's face looking forward, adorned with a lush crown of colourful flowers - roses, poppies and blooms - woven into her hair, soft painterly naturalistic style, warm skin tones, delicate facial features, gentle even lighting" + PLAIN, frame: 'rect', widthMm: 210, tameWarm: true, detail: true },
  dogwine: { slug: 'dogwine', name: 'Rosé Dachshund', description: 'A chic dachshund in heart sunglasses with a glass of rosé — a full stitched scene.', prompt: 'a whimsical fashionable painterly illustration of a dachshund dog wearing pink heart-shaped sunglasses, sitting at a little table with a glass of rosé wine and a stack of colourful books, hot pink room, bold and stylish, highly detailed, full scene filling the whole frame, no text', frame: 'rect', widthMm: 230, tameWarm: true, detail: true, bleed: true },
  // ---- 2026-06-30 batch: fresh subjects, new themes (generate + gate + cull) ----
  bee: { slug: 'bee', name: 'Bumblebee & Lavender', description: 'A fuzzy bumblebee resting on a lavender sprig, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a single fuzzy bumblebee resting on a sprig of purple lavender, soft striped velvety body, delicate translucent wings' + PLAIN, frame: 'round', widthMm: 165, detail: true },
  mushroomscene: { slug: 'mushroomscene', name: 'Toadstool Glade', description: 'A cluster of red-capped toadstools among moss and ferns — a dense woodland thread-painting.', prompt: 'a highly detailed naturalistic illustration of a cluster of red toadstool mushrooms with white spots, growing among soft green moss, ferns and tiny woodland flowers on the forest floor, rich and lush' + PLAIN, frame: 'round', widthMm: 190, tameWarm: true, detail: true },
  seaturtle: { slug: 'seaturtle', name: 'Sea Turtle', description: 'A green sea turtle gliding through teal water, worked in flowing long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a green sea turtle swimming, intricately patterned shell, flippers spread, soft teal and aqua water tones' + PLAIN, frame: 'round', widthMm: 200, detail: true },
  hollywreath: { slug: 'hollywreath', name: 'Holly Wreath', description: 'A festive wreath of holly, red berries and pinecones — a rich circular composition.', prompt: 'a highly detailed naturalistic illustration of a round christmas wreath made of glossy green holly leaves, clusters of red berries, pinecones and sprigs of eucalyptus, lush and full, circular' + PLAIN, frame: 'round', widthMm: 200, tameWarm: true, detail: true },
  bluetit: { slug: 'bluetit', name: 'Blue Tit', description: 'A single blue tit perched on a twig — a simple, bright garden-bird motif.', prompt: 'a highly detailed naturalistic illustration of a single blue tit bird perched on a small twig, bright blue cap and wings, yellow breast, white cheeks' + PLAIN, frame: 'round', widthMm: 150 },
  // ---- 2026-06-30 batch 2: new themes across the full range ----
  highlandcow: { slug: 'highlandcow', name: 'Highland Cow', description: 'A shaggy Highland cow with a flower crown — a rich, characterful showpiece.', prompt: 'a highly detailed naturalistic illustration of a highland cow with a long shaggy ginger fringe over its eyes, big curved horns, wearing a small crown of wildflowers' + PLAIN, frame: 'round', widthMm: 240, detail: true },
  whale: { slug: 'whale', name: 'Humpback Whale', description: 'A humpback whale gliding through sunlit ocean — a full underwater scene.', prompt: 'a beautiful painterly illustration of a humpback whale gliding through deep blue-green ocean water with rays of sunlight from above, small fish, full underwater scene filling the frame, no text', frame: 'rect', widthMm: 260, detail: true, bleed: true },
  goldenretriever: { slug: 'goldenretriever', name: 'Golden Retriever', description: 'A golden retriever head portrait in soft golden long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a golden retriever dog head and shoulders portrait, soft golden fur, warm brown eyes, gentle happy expression' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  dragon: { slug: 'dragon', name: 'Baby Dragon', description: 'A cute baby dragon curled around a flower, in jewel-toned scales.', prompt: 'a cute friendly baby dragon curled up around a single flower, smooth jewel-toned green and teal scales, big friendly eyes, tiny wings, whimsical' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  fairymushroom: { slug: 'fairymushroom', name: 'Toadstool Fairy', description: 'A little fairy resting on a red toadstool in a glowing twilight woodland — a full scene.', prompt: 'a whimsical painterly illustration of a small fairy with glowing translucent wings sitting on a red toadstool with white spots in a magical woodland clearing at dusk, soft purple and deep blue twilight sky, golden fireflies, tiny flowers and ferns, full scene filling the whole frame, no text, no border', frame: 'rect', widthMm: 210, detail: true, tameWarm: true, bleed: true },
  lighthouse: { slug: 'lighthouse', name: 'Cliffside Lighthouse', description: 'A red-and-white lighthouse on a cliff at dusk — a full coastal scene.', prompt: 'a painterly illustration of a red and white striped lighthouse on a rocky cliff at golden dusk, calm sea and a dramatic warm sky, full scene filling the frame, no text', frame: 'rect', widthMm: 240, detail: true, bleed: true },
  monstera: { slug: 'monstera', name: 'Monstera in a Pot', description: 'A potted monstera with glossy split leaves — a fresh houseplant motif.', prompt: 'a highly detailed illustration of a single compact potted monstera deliciosa houseplant in a terracotta pot, a few large glossy split green leaves gathered together, the whole plant centred with a generous plain empty margin all around it, plain pale cream background, no scattered loose leaves, no text, no border', frame: 'round', widthMm: 200, detail: true },
  pumpkins: { slug: 'pumpkins', name: 'Autumn Pumpkins', description: 'A cluster of autumn pumpkins and gourds with leaves and berries.', prompt: 'a highly detailed naturalistic illustration of a cluster of autumn pumpkins and gourds in orange, cream and pale green, with autumn leaves, rosehips and berries' + PLAIN, frame: 'round', widthMm: 210, detail: true },
  cupcake: { slug: 'cupcake', name: 'Frosted Cupcake', description: 'A single frosted cupcake with sprinkles — a simple, sweet motif.', prompt: 'a cute illustration of a single cupcake with swirled pink frosting, colourful sprinkles and a cherry on top' + PLAIN, frame: 'round', widthMm: 150, tameWarm: true },
  fernstem: { slug: 'fernstem', name: 'Fern Frond', description: 'A single fern frond worked in delicate line stitching on bare linen.', prompt: 'a simple delicate botanical illustration of a single green fern frond with fine leaflets' + DELICATE, mode: 'line', frame: 'round', widthMm: 150 },
  // ---- 2026-07-01 batch 3: new themes; scenes via bleed; avoid white-ground single subjects ----
  ragdoll: { slug: 'ragdoll', name: 'Ragdoll Cat', description: 'A fluffy ragdoll cat portrait with blue eyes, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a fluffy ragdoll cat portrait, striking blue eyes, soft cream and grey colourpoint fur, head and shoulders' + PLAIN, frame: 'round', widthMm: 220, detail: true },
  owl: { slug: 'owl', name: 'Barn Owl', description: 'A barn owl with a heart-shaped face, in fine feather thread painting.', prompt: 'a highly detailed naturalistic illustration of a barn owl with a heart-shaped white face, soft golden and white feathers, dark eyes, perched' + PLAIN, frame: 'round', widthMm: 200, detail: true },
  hedgehog: { slug: 'hedgehog', name: 'Autumn Hedgehog', description: 'A cute hedgehog among autumn leaves and a little mushroom.', prompt: 'a highly detailed naturalistic illustration of a cute hedgehog among autumn leaves with a small red mushroom, soft spines, warm autumn colours' + PLAIN, frame: 'round', widthMm: 170, detail: true },
  springbunny: { slug: 'springbunny', name: 'Spring Bunny', description: 'A fluffy brown rabbit among spring flowers — a fresh, cheerful piece.', prompt: 'a highly detailed naturalistic illustration of a fluffy brown rabbit sitting among spring daffodils, tulips and bluebells' + PLAIN, frame: 'round', widthMm: 200, detail: true },
  halloweencat: { slug: 'halloweencat', name: 'Halloween Cat', description: 'A black cat beside a glowing carved pumpkin — a charming Halloween motif.', prompt: 'a charming illustration of a black cat sitting beside a glowing carved jack-o-lantern pumpkin among autumn leaves' + PLAIN, frame: 'round', widthMm: 185, detail: true },
  moon: { slug: 'moon', name: 'Crescent Moon & Stars', description: 'A glowing crescent moon and stars on a deep night sky — a celestial scene.', prompt: 'a celestial illustration of a glowing golden crescent moon with scattered stars and wispy clouds on a deep navy blue night sky, full scene filling the frame, no text', frame: 'round', widthMm: 180, detail: true, bleed: true },
  butterfly: { slug: 'butterfly', name: 'Monarch Butterfly', description: 'A monarch butterfly resting on a coneflower, in rich long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a monarch butterfly with open orange and black wings resting on a pink coneflower' + PLAIN, frame: 'round', widthMm: 175, detail: true },
  strawberries: { slug: 'strawberries', name: 'Strawberries', description: 'A cluster of ripe strawberries with blossom and leaves — a sweet botanical.', prompt: 'a highly detailed naturalistic illustration of a small compact bunch of three ripe red strawberries tied together with a white blossom and a few green leaves, a single centred cluster with a generous empty margin all around it, plain pale cream background, no text, no border', frame: 'round', widthMm: 175, tameWarm: true, detail: true },
  ladybird: { slug: 'ladybird', name: 'Ladybird', description: 'A single ladybird on a leaf — a simple, bright little motif.', prompt: 'a simple cute illustration of a single red ladybird with black spots resting on a green leaf' + PLAIN, frame: 'round', widthMm: 140, tameWarm: true },
  singletulip: { slug: 'singletulip', name: 'Single Tulip', description: 'A single tulip on a stem, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a single pink tulip flower in full bloom, solid layered petals, on a green stem with two leaves' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  mountainlake: { slug: 'mountainlake', name: 'Mountain Lake', description: 'A mountain lake at sunrise with mirrored peaks — a full landscape scene.', prompt: 'a serene painterly illustration of a mountain lake at sunrise, snow-capped peaks reflected in still water, pine trees along the shore, full scene filling the frame, no text', frame: 'rect', widthMm: 240, detail: true, bleed: true },
  // ---- 2026-07-01 batch 4: new themes (valentine/witchy/nursery) + deepened popular ----
  cockapoo: { slug: 'cockapoo', name: 'Cockapoo', description: 'A curly apricot cockapoo portrait, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a cockapoo dog head and shoulders portrait, curly soft apricot fur, dark shiny eyes, happy expression' + PLAIN, frame: 'round', widthMm: 210, detail: true, tameWarm: true },
  redsquirrel: { slug: 'redsquirrel', name: 'Red Squirrel', description: 'A red squirrel with an acorn among autumn colours.', prompt: 'a highly detailed naturalistic illustration of a red squirrel sitting holding an acorn, bushy tail, warm autumn colours' + PLAIN, frame: 'round', widthMm: 170, detail: true },
  peoniesbouquet: { slug: 'peoniesbouquet', name: 'Peony Bouquet', description: 'A lush bouquet of pink and white peonies — a dense floral showpiece.', prompt: 'a lush highly detailed naturalistic illustration of a full bouquet of pink and white peonies with green foliage, buds and layered petals' + PLAIN, frame: 'round', widthMm: 240, detail: true, tameWarm: true },
  seahorse: { slug: 'seahorse', name: 'Seahorse', description: 'A seahorse among coral and seagrass, in fine detail.', prompt: 'a highly detailed naturalistic illustration of a seahorse among colourful coral and seagrass, intricate patterned body' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  valentineheart: { slug: 'valentineheart', name: 'Rose Heart', description: 'A heart made of red roses and pink flowers — a romantic floral motif.', prompt: 'a highly detailed illustration of a heart shape made of red roses, pink peonies and small flowers with green leaves, romantic, symmetrical' + PLAIN, frame: 'round', widthMm: 190, detail: true, tameWarm: true },
  babyelephant: { slug: 'babyelephant', name: 'Baby Elephant', description: 'A cute baby elephant with a balloon — a sweet nursery motif.', prompt: 'a cute cartoon illustration of a baby elephant sitting and holding a red heart balloon with its trunk, saturated soft periwinkle-blue body clearly darker than the background, bold dark charcoal outlines all around the body, big friendly dark eyes, rosy pink cheeks, simple, no sewing needle' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  hummingbird: { slug: 'hummingbird', name: 'Hummingbird', description: 'A hummingbird at a trumpet flower, in iridescent thread painting.', prompt: 'a highly detailed naturalistic illustration of a hummingbird hovering at a red trumpet flower, iridescent green and blue feathers' + PLAIN, frame: 'round', widthMm: 175, detail: true },
  cherryblossom: { slug: 'cherryblossom', name: 'Cherry Blossom', description: 'A cherry blossom branch in soft pink — a delicate spring motif.', prompt: 'a delicate naturalistic illustration of a cherry blossom branch with soft pink blossoms and buds' + PLAIN, frame: 'round', widthMm: 190, detail: true, tameWarm: true },
  snowdrop: { slug: 'snowdrop', name: 'Snowdrop', description: 'A single snowdrop nodding on a stem, in soft shading.', prompt: 'a highly detailed naturalistic illustration of a single snowdrop flower nodding on a green stem with two leaves, white petals with distinct green-tipped markings, soft grey-green shading and a shadowed side so the white reads against a pale ground' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  witchymoon: { slug: 'witchymoon', name: 'Cat & Moon', description: 'A black cat beneath a crescent moon and stars — a mystical night scene.', prompt: 'a mystical painterly illustration of a black cat silhouette sitting beneath a glowing crescent moon, stars and wispy clouds, deep purple night sky, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 210, detail: true, bleed: true },
  lavenderfield: { slug: 'lavenderfield', name: 'Lavender Field', description: 'Rows of lavender at sunset — a full landscape scene.', prompt: 'a serene painterly illustration of a lavender field in provence at sunset, rows of purple lavender leading to a distant stone farmhouse, warm glowing sky, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 240, detail: true, bleed: true },
  // ---- Batch 5 (2026-07-01): closes themes 29/30/31 + range spread simple line -> dense showpiece ----
  eucalyptussprig: { slug: 'eucalyptussprig', name: 'Eucalyptus Sprig', description: 'A eucalyptus sprig with rounded silver-green leaves — a soft botanical motif.', prompt: 'a highly detailed naturalistic illustration of a single eucalyptus sprig with clearly rounded silver-green leaves arranged in neat pairs along one slender brown stem, soft sage and dusty blue-green tones, clean and simple' + PLAIN, frame: 'round', widthMm: 165, detail: true },
  dandelionclock: { slug: 'dandelionclock', name: 'Dandelion Clock', description: 'A dandelion seed head on a green stem — a soft botanical motif.', prompt: 'a highly detailed naturalistic illustration of a single dandelion seed head clock, a soft round pom-pom made ENTIRELY of fluffy pale grey-white translucent seeds radiating from a small pale brown centre, no red, no orange, no petals, on one clean slender green stem, a few seeds drifting off to one side' + PLAIN, frame: 'round', widthMm: 165, detail: true, tameWarm: true },
  toadstoolsingle: { slug: 'toadstoolsingle', name: 'Red Toadstool', description: 'A single red-capped toadstool with white spots — a simple woodland motif.', prompt: 'a simple cute naturalistic illustration of a single red toadstool mushroom with white spots and a cream stem, a little grass at the base' + PLAIN, frame: 'round', widthMm: 150, tameWarm: true },
  teddybear: { slug: 'teddybear', name: 'Teddy Bear', description: 'A soft honey-brown teddy bear holding a heart — a sweet nursery motif.', prompt: 'a cute cartoon illustration of a soft honey-brown teddy bear sitting and holding a small pink heart, stitched button eyes, clear bold clean outlines, simple' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  puffin: { slug: 'puffin', name: 'Puffin on the Cliffs', description: 'An Atlantic puffin on a grassy clifftop above the sea — a full coastal scene.', prompt: 'a naturalistic painterly illustration of a single atlantic puffin standing on a grassy clifftop dotted with pink sea-thrift flowers, black and white body, bright orange striped beak and orange feet, calm blue sea and soft sky behind, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 220, detail: true, bleed: true },
  dragonfly: { slug: 'dragonfly', name: 'Dragonfly', description: 'A dragonfly with iridescent wings on a reed — in fine thread painting.', prompt: 'a highly detailed naturalistic illustration of a single dragonfly resting on a reed, iridescent teal and blue body, delicate translucent lacework wings' + PLAIN, frame: 'round', widthMm: 175, detail: true },
  artnouveauiris: { slug: 'artnouveauiris', name: 'Art Nouveau Iris', description: 'A stylised purple iris in the Art Nouveau manner — a heritage-inspired motif.', prompt: 'a stylised art nouveau illustration of a single purple iris flower with flowing curved stem and leaves, elegant decorative lines, muted heritage colours' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  popartlady: { slug: 'popartlady', name: 'Pop-Art Lady', description: 'A bold stylised woman in a sunhat, in flat pop-art colour blocks — a graphic fashion portrait.', prompt: 'a bold graphic pop-art illustration of a stylised elegant woman wearing a wide red sunhat and cat-eye sunglasses, flat blocks of bright colour, strong clean outlines, teal background, full composition filling the frame, no text, no border', frame: 'square', widthMm: 200, detail: true, bleed: true },
  macaw: { slug: 'macaw', name: 'Scarlet Macaw', description: 'A scarlet macaw in vivid red, blue and gold plumage — a bright showpiece.', prompt: 'a stunning highly detailed naturalistic illustration of a scarlet macaw parrot perched on a branch, vivid scarlet red body, bright blue and gold wings, ornate feather detail' + PLAIN, frame: 'round', widthMm: 250, detail: true, tameWarm: true },
  stag: { slug: 'stag', name: 'Red Deer Stag', description: 'A majestic red deer stag with full antlers among autumn bracken — a rich showpiece.', prompt: 'a majestic highly detailed naturalistic illustration of a red deer stag head and shoulders with large branching antlers, rich russet-brown fur, standing among golden autumn bracken and heather' + PLAIN, frame: 'round', widthMm: 250, detail: true },
  hydrangea: { slug: 'hydrangea', name: 'Hydrangea Bloom', description: 'A full blue and lilac hydrangea head with leaves — a dense floral showpiece.', prompt: 'a lush highly detailed naturalistic illustration of one single round hydrangea flower head packed with tiny blue lilac and violet florets, with a few broad green leaves below it, the whole plant centered small with a generous clear margin of empty space all around it, nothing touching the edges, plain pale cream background, no text, no border', frame: 'round', widthMm: 210, detail: true },
  // ---- Batch 6 (2026-07-01): full range across new themes (simple pet -> XL floral/wreath showpieces) ----
  guineapig: { slug: 'guineapig', name: 'Guinea Pig', description: 'A little agouti guinea pig sitting — a simple, sweet pet motif.', prompt: 'a cute naturalistic illustration of a single small agouti brown guinea pig sitting facing forward, soft brown and tan fur, dark eyes, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  labrador: { slug: 'labrador', name: 'Golden Labrador', description: 'A yellow Labrador head portrait in soft golden long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a yellow labrador dog head and shoulders portrait, soft golden coat, warm brown eyes, gentle happy expression' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  mainecoon: { slug: 'mainecoon', name: 'Maine Coon', description: 'A majestic Maine Coon cat portrait with tufted ears and a full ruff — a rich showpiece.', prompt: 'a highly detailed photorealistic illustration of a classic brown tabby maine coon cat head and shoulders portrait, long flowing brown and cream fur with natural black tabby striping, tufted ears, full ruff, calm green eyes, a small dark brown-black nose, realistic domestic cat colouring, absolutely no red markings, no red or pink patches on the face, no face paint' + PLAIN, frame: 'round', widthMm: 220, detail: true, tameWarm: true },
  rooster: { slug: 'rooster', name: 'Rooster', description: 'A proud rooster in iridescent plumage — a rich, colourful farmyard portrait.', prompt: 'a highly detailed naturalistic illustration of a proud rooster standing, iridescent green and copper tail feathers, golden neck hackles, bright red comb and wattle, ornate plumage detail' + PLAIN, frame: 'round', widthMm: 210, detail: true },
  goldfinch: { slug: 'goldfinch', name: 'Goldfinch on a Thistle', description: 'A goldfinch perched on a purple thistle, in fine feather thread painting.', prompt: 'a highly detailed naturalistic illustration of a european goldfinch perched on a purple thistle, red face, gold wing bars, brown and cream body, delicate' + PLAIN, frame: 'round', widthMm: 165, detail: true, tameWarm: true },
  lunamoth: { slug: 'lunamoth', name: 'Luna Moth', description: 'A luna moth with full pale-green wings and eyespots — delicate specimen thread painting.', prompt: 'a highly detailed naturalistic illustration of a luna moth with full spread wings, soft sea-green wings with distinct pink-purple eyespots and dark maroon wing borders and veining, long tapering tails, resting on a small brown twig' + PLAIN, frame: 'round', widthMm: 185, detail: true },
  narwhal: { slug: 'narwhal', name: 'Narwhal', description: 'A friendly narwhal with a single spiralled tusk — a sweet, simple sea motif.', prompt: 'a cute simple naturalistic illustration of a single friendly narwhal in clean side profile, one smooth torpedo-shaped blue-grey body with a pale underside, ONE single long straight spiralled ivory tusk pointing forward from the tip of its snout, one small friendly eye, a gently curved tail fluke, clear bold clean outlines, no extra horns, no flowers' + PLAIN, frame: 'round', widthMm: 175, detail: true },
  phoenix: { slug: 'phoenix', name: 'Phoenix', description: 'A mythical phoenix with fiery plumage and a long flame tail — a vivid fantasy motif.', prompt: 'a striking illustration of a mythical phoenix bird with wings spread, vivid scarlet red, orange and gold flame-like feathers and a long trailing tail of fire, glowing, ornate feather detail' + PLAIN, frame: 'round', widthMm: 190, detail: true },
  sunflower: { slug: 'sunflower', name: 'Sunflower', description: 'A single sunflower with a textured seed head — a bright, cheerful bloom.', prompt: 'a highly detailed naturalistic illustration of a single large classic sunflower in full bloom facing forward, bright golden-yellow petals, one large round dark brown seed-head centre, green leaves and stem, pure yellow petals with no pink and no coral, a dark brown centre not a green centre' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  cottagegardenmix: { slug: 'cottagegardenmix', name: 'Cottage Garden Bouquet', description: 'A lush overflowing English cottage-garden bouquet — roses, delphiniums, foxgloves and sweet peas, a dense floral showpiece.', prompt: 'a lush highly detailed naturalistic illustration of an overflowing english cottage garden bouquet with pink and cream roses, tall blue delphiniums, pink foxgloves, sweet peas, nigella and green foliage, layered overlapping blooms, rich and full' + PLAIN, frame: 'round', widthMm: 260, detail: true, tameWarm: true },
  englishroseswreath: { slug: 'englishroseswreath', name: 'English Roses Wreath', description: 'A full circular wreath of English roses, buds and leaves — a dense romantic showpiece.', prompt: 'a lush highly detailed naturalistic illustration of a round wreath made of blush pink and cream english garden roses, rosebuds and green leaves, full and dense, circular, clean open centre' + PLAIN, frame: 'round', widthMm: 240, detail: true, tameWarm: true },
  // ---- Batch 7 (2026-07-02): full range across new themes (simple pet -> XL floral/scene showpieces) ----
  hamster: { slug: 'hamster', name: 'Hamster', description: 'A little golden hamster with full cheeks — a simple, sweet pet motif.', prompt: 'a cute naturalistic illustration of a single golden hamster sitting facing forward with full round cheek pouches, soft golden-tan and cream fur, tiny paws held up, bright dark bead eyes, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true, tameWarm: true },
  chick: { slug: 'chick', name: 'Baby Chick', description: 'A fluffy yellow baby chick — a simple, cheerful farmyard motif.', prompt: 'a cute naturalistic illustration of a single fluffy yellow baby chick standing, soft downy pale butter-yellow feathers, tiny orange beak and feet, bright dark eyes, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 145, detail: true, tameWarm: true },
  frenchbulldog: { slug: 'frenchbulldog', name: 'French Bulldog', description: 'A French bulldog head portrait with big bat ears, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a french bulldog head and shoulders portrait, large upright bat ears, short fawn coat with a soft dark mask, big round dark eyes, wrinkled brow, gentle friendly expression' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  siamese: { slug: 'siamese', name: 'Siamese Cat', description: 'A Siamese cat portrait with blue eyes and dark points, in fine thread painting.', prompt: 'a highly detailed naturalistic illustration of a classic seal-point siamese cat head and shoulders portrait, very pale cream body, sharply contrasting dark chocolate seal-brown almost-black points on the ears the face mask and the nose, striking almond-shaped blue eyes, short sleek fur, no orange, no ginger, no tabby stripes' + PLAIN, frame: 'round', widthMm: 210, detail: true, tameWarm: true },
  otter: { slug: 'otter', name: 'River Otter', description: 'A river otter sitting upright with sleek fur — a charming woodland motif.', prompt: 'a highly detailed naturalistic illustration of a single river otter sitting upright, sleek glossy warm chestnut-brown fur with a pale cream throat and cheeks, whiskered face, bright dark eyes, small front paws held together, natural brown and cream tones only, absolutely no purple, no magenta, no pink shadows, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 190, detail: true, tameWarm: true },
  swallowtail: { slug: 'swallowtail', name: 'Swallowtail Butterfly', description: 'A swallowtail butterfly with open wings, in rich long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a single swallowtail butterfly with open wings, pale creamy-yellow wings with bold black veins and borders and small blue and red eyespots near the tails, resting on a small flower' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  sweetpeas: { slug: 'sweetpeas', name: 'Sweet Peas', description: 'A little bunch of sweet peas in soft pastels — a delicate floral motif.', prompt: 'a highly detailed naturalistic illustration of a small bunch of sweet pea flowers in soft pink, lilac and cream with delicate ruffled petals, curling tendrils and green leaves, gathered in a little clear glass jar, a single centred arrangement with a generous clear margin around it' + PLAIN, frame: 'round', widthMm: 190, detail: true, tameWarm: true },
  pheasant: { slug: 'pheasant', name: 'Pheasant', description: 'A male pheasant in iridescent and coppery plumage among golden bracken — a rich portrait.', prompt: 'a highly detailed naturalistic illustration of a male common pheasant standing in profile, iridescent bottle-green head with a red face wattle, white neck ring, coppery-gold body with intricate dark barred plumage, long pointed barred tail, standing among golden autumn bracken' + PLAIN, frame: 'round', widthMm: 220, detail: true },
  dahliabouquet: { slug: 'dahliabouquet', name: 'Dahlia Bouquet', description: 'A lush bouquet of jewel-toned dahlias — a dense floral showpiece.', prompt: 'a lush highly detailed naturalistic illustration of a full bouquet of dahlias in rich jewel tones of deep burgundy, coral, peach, gold and plum, with layered geometric petals, buds and dark green foliage, dense overlapping blooms filling the composition' + PLAIN, frame: 'round', widthMm: 260, detail: true, tameWarm: true },
  autumnforest: { slug: 'autumnforest', name: 'Autumn Forest', description: 'An autumn forest panorama with a golden canopy, winding path and a little fox — a full scene.', prompt: 'a beautiful painterly illustration of an autumn forest panorama, oak beech and birch trees in a golden red and amber canopy, a winding path through fallen leaves, a small red fox on the path, soft misty morning light, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 260, detail: true, bleed: true },
  // ---- Batch 8 (2026-07-02): full range across new themes (simple bird -> XL scene/wreath showpieces) ----
  wren: { slug: 'wren', name: 'Wren', description: 'A tiny wren with a cocked tail on a twig — a simple, sweet garden-bird motif.', prompt: 'a highly detailed naturalistic illustration of a single tiny wren bird perched on a small twig, plump round body, upright cocked tail, warm brown finely-barred plumage, a pale eye-stripe, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 145, detail: true },
  penguin: { slug: 'penguin', name: 'Penguin in a Scarf', description: 'A penguin in a cosy red scarf — a cheerful winter motif.', prompt: 'a cute naturalistic illustration of a single penguin standing, black back and glossy white belly, orange-yellow ear patches, wearing a cosy red knitted winter scarf, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 165, detail: true, tameWarm: true },
  beagle: { slug: 'beagle', name: 'Beagle', description: 'A tricolour beagle head portrait, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a beagle dog head and shoulders portrait, classic tricolour coat of black tan and white, long soft drop ears, big brown eyes, a plain black nose, a clean white and tan muzzle with absolutely no red and no pink around the mouth or lips, closed mouth, gentle friendly expression' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  octopus: { slug: 'octopus', name: 'Octopus', description: 'An octopus with gracefully curled tentacles in soft coral and lilac tones.', prompt: 'a highly detailed naturalistic illustration of a single octopus with its curled tentacles gracefully arranged, soft coral-pink and lilac-purple mottled skin, large expressive eyes, rows of suckers along the arms, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  alpaca: { slug: 'alpaca', name: 'Alpaca', description: 'A fluffy cream alpaca portrait with a characterful expression.', prompt: 'a highly detailed naturalistic illustration of a fluffy alpaca head and shoulders portrait, soft cream and pale fawn fleece, long neck, gentle dark eyes, characterful expression, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  foxglove: { slug: 'foxglove', name: 'Foxglove', description: 'A tall foxglove spire of speckled pink bells — a dense botanical stem.', prompt: 'a highly detailed naturalistic illustration of a single tall foxglove flower spire with many pendant pink and magenta tubular bells speckled inside, buds gathered at the top, broad green leaves at the base, all on one upright stem, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 190, detail: true, tameWarm: true },
  wisteria: { slug: 'wisteria', name: 'Wisteria', description: 'A wisteria branch of cascading lilac racemes — a rich floral motif.', prompt: 'a highly detailed naturalistic illustration of a wisteria branch with several long cascading racemes of purple and lilac pea-flowers hanging down, soft green leaves, a single centred composition with a clear margin all around it' + PLAIN, frame: 'round', widthMm: 210, detail: true },
  autumnwreath: { slug: 'autumnwreath', name: 'Autumn Harvest Wreath', description: 'A full circular wreath of pumpkins, rosehips, acorns and autumn leaves — a dense seasonal showpiece.', prompt: 'a lush highly detailed naturalistic illustration of a round autumn harvest wreath made of small orange pumpkins, red rosehips, acorns, hazelnuts, clusters of berries, ears of wheat and golden red and amber oak and maple leaves, full and dense, circular, clean open centre' + PLAIN, frame: 'round', widthMm: 240, detail: true },
  bluebellwood: { slug: 'bluebellwood', name: 'Bluebell Wood', description: 'A path winding through a bluebell wood in spring — a full landscape scene.', prompt: 'a beautiful painterly illustration of an english bluebell wood in spring, a soft path winding through tall beech trees with fresh green leaves, a dense carpet of blue-violet bluebells across the forest floor, dappled sunlight, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 250, detail: true, bleed: true },
  oceanreef: { slug: 'oceanreef', name: 'Coral Reef', description: 'A vibrant coral reef with a gliding sea turtle — a full underwater showpiece scene.', prompt: 'a beautiful highly detailed painterly illustration of a vibrant underwater coral reef scene, a green sea turtle gliding, colourful branching coral, swaying kelp, small tropical fish, sea anemones, rays of sunlight from the surface through deep blue-green water, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 260, detail: true, bleed: true },
  // ---- Batch 9 (2026-07-02): full range across new themes (simple pet -> XL floral/scene showpieces) ----
  corgi: { slug: 'corgi', name: 'Corgi', description: 'A Pembroke Welsh corgi head portrait with big ears, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a pembroke welsh corgi dog head and shoulders portrait, large upright pointed ears, soft golden-orange and white fur, dark friendly eyes, gentle happy expression, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  bengal: { slug: 'bengal', name: 'Bengal Cat', description: 'A bengal cat portrait with leopard rosettes and green eyes — a rich, striking piece.', prompt: 'a highly detailed naturalistic illustration of a bengal cat head and shoulders portrait, golden-brown coat covered in bold dark leopard-like rosettes and spots, striking green eyes, short sleek fur, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 215, detail: true, tameWarm: true },
  badger: { slug: 'badger', name: 'Badger', description: 'A European badger with its striped black-and-white face — a simple woodland motif.', prompt: 'a highly detailed naturalistic illustration of a single european badger head portrait, distinctive black and white striped face, small dark eyes, soft silvery-grey body fur, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 165, detail: true },
  piglet: { slug: 'piglet', name: 'Piglet', description: 'A little pink piglet standing — a simple, sweet farmyard motif.', prompt: 'a cute naturalistic illustration of a single small pink piglet standing, soft rounded body, big floppy ears, snout, tiny trotters, curly tail, bright dark eyes, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true, tameWarm: true },
  koifish: { slug: 'koifish', name: 'Koi Fish', description: 'A koi fish gliding through water with flowing fins — a graceful sea motif.', prompt: 'a highly detailed naturalistic illustration of a single koi fish swimming gracefully in side profile, long flowing trailing fins and tail, bold orange red and white patterned scales, no lily pad, no water plants, no leaves, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 190, detail: true },
  nutcracker: { slug: 'nutcracker', name: 'Nutcracker', description: 'A traditional Christmas nutcracker soldier in red and gold — a festive motif.', prompt: 'a highly detailed naturalistic illustration of a traditional christmas nutcracker soldier figure standing upright, tall black hat, bright red military jacket with gold buttons and gold braid, white curly hair and beard, blue trousers, black boots, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 195, detail: true, tameWarm: true },
  macarons: { slug: 'macarons', name: 'Macaron Stack', description: 'A little stack of pastel French macarons — a sweet, delicate food motif.', prompt: 'a bold clean simple naturalistic illustration of a neat stack of three french macarons in pastel pink, mint green and cream, each one a smooth round crisp shell with a clear cream filling, clean rounded shapes with well-defined smooth edges, no loose crumbs, a single centred stack with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 185, detail: true, tameWarm: true },
  magnolia: { slug: 'magnolia', name: 'Magnolia Branch', description: 'A magnolia branch with two soft pink blooms and buds — a rich floral motif.', prompt: 'a highly detailed naturalistic illustration of two large compact magnolia blooms with full rounded solid petals in soft pink and white, a couple of furred buds, on a dark woody branch with a few glossy green leaves, solid full petals with clean smooth edges and no wispy or frayed threads, a single centred composition with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 215, detail: true, tameWarm: true },
  botanicalheart: { slug: 'botanicalheart', name: 'Botanical Heart', description: 'A heart shape formed entirely of densely packed flowers — a dense romantic showpiece.', prompt: 'a lush highly detailed naturalistic illustration of a heart shape formed entirely from densely packed flowers - roses, peonies, ranunculus, anemones, sweet peas and small blooms in soft pinks, reds, cream and blush with green foliage, a full romantic heart-shaped floral composition, the heart centred with a clear margin all around it' + PLAIN, frame: 'round', widthMm: 245, detail: true, tameWarm: true },
  highlandglen: { slug: 'highlandglen', name: 'Highland Glen', description: 'A red deer stag beside a still loch in an autumn highland glen — a full landscape scene.', prompt: 'a soft naturalistic painterly illustration of a scottish highland glen in autumn, a red deer stag standing beside a calm loch that mirrors misty grey-blue mountains, gently muted dusky-purple heather and soft golden-brown bracken on the hillsides, soft desaturated misty morning light, muted natural earthy colours, calm and atmospheric, absolutely not neon, not oversaturated, no bright magenta, no bright orange, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 260, detail: true, bleed: true, tameWarm: true },
  // ---- Batch 10 (2026-07-02): full range across new themes (simple duckling/mouse -> XL heritage tree + halloween scene) ----
  duckling: { slug: 'duckling', name: 'Duckling', description: 'A fluffy yellow duckling — a simple, cheerful farmyard motif.', prompt: 'a cute naturalistic illustration of a single fluffy yellow duckling standing, soft downy pale butter-yellow feathers, small orange beak and webbed feet, bright dark eyes, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 145, detail: true, tameWarm: true },
  fieldmouse: { slug: 'fieldmouse', name: 'Field Mouse', description: 'A tiny field mouse holding a seed — a sweet, simple woodland motif.', prompt: 'a highly detailed naturalistic illustration of a single tiny wood mouse sitting upright holding a seed in its front paws, soft warm brown fur with a pale cream belly, large round ears, bright dark eyes, long delicate tail, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true, tameWarm: true },
  bullfinch: { slug: 'bullfinch', name: 'Bullfinch', description: 'A bullfinch on a blossom branch with a rosy breast — a bright garden-bird motif.', prompt: 'a highly detailed naturalistic illustration of a single plump rounded bullfinch bird perched on a pink cherry blossom branch, a glossy jet-black cap and face, a bright rosy salmon-pink breast and cheeks, a soft blue-grey back, black wings and tail with a white rump, a short thick black bill, absolutely no orange, no teal, no turquoise, no blue on the body, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 165, detail: true, tameWarm: true },
  redpoppy: { slug: 'redpoppy', name: 'Red Poppy', description: 'A single red field poppy with ruffled petals — a bold botanical motif.', prompt: 'a highly detailed naturalistic illustration of a single large red field poppy in full bloom, softly ruffled crepe-textured scarlet-red petals, a dark centre with a ring of stamens, on a green stem with a bud and a few leaves, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 175, detail: true, tameWarm: true },
  sealpup: { slug: 'sealpup', name: 'Seal Pup', description: 'A dappled grey harbour seal pup with big dark eyes — a soft sea motif.', prompt: 'a highly detailed naturalistic illustration of a single harbour seal pup resting, soft dappled silver-grey and cream fur with darker grey mottled markings, big soulful dark eyes, whiskers, a rounded body, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 185, detail: true },
  springerspaniel: { slug: 'springerspaniel', name: 'Springer Spaniel', description: 'An English springer spaniel portrait with long feathered ears, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of an english springer spaniel dog head and shoulders portrait, a full rounded domed forehead and crown fully covered in fur connecting the two ears with no bare gap at the top of the head, long soft feathered liver-brown and white drop ears, a white blaze down the centre of the face, kind warm brown eyes, a completely plain solid dark brown-black nose leather, the top of the muzzle and the bridge of the nose covered in plain brown-and-white fur with absolutely no red, no orange, no pink and no scarlet anywhere on or above the nose or muzzle, closed mouth, gentle happy expression, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  britishshorthair: { slug: 'britishshorthair', name: 'British Shorthair', description: 'A plush blue-grey British Shorthair with copper eyes — a rich cat portrait.', prompt: 'a highly detailed naturalistic illustration of a british shorthair cat head and shoulders portrait, plush dense SHORT blue-grey fur (not long-haired, not fluffy), a broad round face with full chubby cheeks, small rounded ears with soft pale pink inner ears (absolutely no orange and no red in the ears), calm round amber-copper eyes, a small blue-grey nose (not red, not orange), short whiskers, natural cool grey tones only, absolutely no teal, no turquoise, no blue streaks in the fur, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 215, detail: true, tameWarm: true },
  gingerbreadhouse: { slug: 'gingerbreadhouse', name: 'Gingerbread House', description: 'A decorated gingerbread house with icing and candy — a festive winter motif.', prompt: 'a charming naturalistic illustration of a single decorated christmas gingerbread house, warm golden-brown biscuit walls with white piped royal icing, colourful candy buttons and gumdrops, a snowy white icing roof, a little icing door and windows, dusted with snow, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 190, detail: true, tameWarm: true },
  treeoflife: { slug: 'treeoflife', name: 'Tree of Life', description: 'A Jacobean crewelwork tree of life with stylised flowers and a bird — a dense heritage showpiece.', prompt: 'a lush highly detailed jacobean crewelwork tree of life illustration, one ornate curving tree trunk and branches rising from a small mound, bearing large stylised decorative flowers, curling leaves, acorns and paisley shapes in rich jewel tones of blue, green, coral, gold and terracotta, a small bird and a butterfly among the branches, dense ornate and symmetrical, a single centred composition with a clear margin all around it' + PLAIN, frame: 'round', widthMm: 250, detail: true, tameWarm: true },
  halloweenscene: { slug: 'halloweenscene', name: 'Cosy Halloween Night', description: 'A cosy haunted Halloween scene — crooked cottage, pumpkin path, moon, bats and a black cat — a full showpiece scene.', prompt: 'a charming painterly illustration of a cosy haunted halloween night scene, a little crooked cottage with warm glowing amber windows on a hill, a winding path lined with carved glowing jack-o-lantern pumpkins, a big full moon, bats flying across the sky, a black cat sitting on a fence, bare spooky autumn trees, a spider on a web, deep purple and warm orange twilight sky, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 280, detail: true, bleed: true },
  pug: { slug: 'pug', name: 'Pug', description: 'A fawn pug head portrait with a black mask and soulful eyes, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a fawn pug dog head and shoulders portrait, soft warm beige-fawn short coat, a distinctive dark black mask across the muzzle and face, deep wrinkled brow, big round soulful dark eyes, a plain solid black nose, small folded ears, closed mouth with no red or pink around it, gentle expression, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 160, detail: true, tameWarm: true },
  cactus: { slug: 'cactus', name: 'Potted Cactus', description: 'A cheerful little potted cactus with a single pink flower — a simple houseplant motif.', prompt: 'a simple cute illustration of a single small round green barrel cactus in a terracotta pot, a few white spines and one bright pink flower on top, the whole plant centred with a generous plain empty margin all around it, no other plants, no scattered leaves' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  dolphin: { slug: 'dolphin', name: 'Bottlenose Dolphin', description: 'A bottlenose dolphin leaping over teal water, in flowing long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a single bottlenose dolphin leaping in a graceful arc, smooth blue-grey back fading to a pale cool silvery-grey and white belly (no orange, no cream, no tan), a gentle smiling beak, above soft teal-blue water with a few droplets, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  jay: { slug: 'jay', name: 'Eurasian Jay', description: 'A Eurasian jay with its bright blue wing panel, in fine feather thread painting.', prompt: 'a highly detailed naturalistic illustration of a single eurasian jay bird (Garrulus glandarius, NOT an american blue jay) perched calmly on a plain bare brown twig, a smooth rounded head with NO crest, warm soft pinkish-brown body and warm pinkish-brown breast and underparts (no orange, no blue on the body), a small black-and-white streaked forehead, a bold black moustache stripe below the eye, a white throat, a black tail, and a single small patch of bright blue and black finely barred feathers on the wing only, a plain pale pinkish beak, clean simple feet gripping the twig with no red and no loose threads, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 185, detail: true },
  redadmiral: { slug: 'redadmiral', name: 'Painted Lady Butterfly', description: 'A painted lady butterfly with open wings on a cornflower, in rich long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a red admiral butterfly with open wings resting on a purple flower, deep velvety black-brown wings crossed by bold orange-red bands and edged with small white spots, delicate wing veining, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 175, detail: true, tameWarm: true },
  sheep: { slug: 'sheep', name: 'Sheep', description: 'A plump fluffy sheep with a dark face and soft creamy fleece, in soft textured shading.', prompt: 'a charming naturalistic illustration of a single plump well-fed sheep standing square in profile, a rounded cloud-like body of thick soft curly creamy-beige and pale grey wool with gentle rounded shading and depth (soft and fluffy, not spiky, not straw-like, no yellow), a neat dark charcoal-grey face and ears, four sturdy dark straight legs all clearly visible and evenly placed, gentle dark eyes, a calm friendly expression, well-proportioned and cute, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 190, detail: true },
  unicorn: { slug: 'unicorn', name: 'Unicorn', description: 'A pastel unicorn head with a flowing rainbow mane and flower crown — a whimsical piece.', prompt: 'a whimsical illustration of a unicorn head and neck in profile, a richly coloured saturated lavender-purple coat with clearly defined darker violet and grey shadows and a bold dark outline all around the head and muzzle (definitely NOT white, NOT pale cream, NOT pale — a strong solid lavender-purple colour so the whole face is filled in), a golden spiral horn, big kind dark eyes with clear detail, small ears, a flowing pastel rainbow mane in soft pink lavender mint and blue, and a little crown of flowers behind the horn, the entire head and face fully coloured and shaded with no empty or white areas, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 190, detail: true },
  irisbloom: { slug: 'irisbloom', name: 'Bearded Iris', description: 'A single purple bearded iris in full bloom, in layered long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a single bearded iris flower in full bloom, rich violet and deep purple ruffled petals with soft velvety falls, a golden-yellow beard, and delicate veining, on a green stem with a bud and two blade leaves, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 180, detail: true },
  springwreath: { slug: 'springwreath', name: 'Spring Wreath', description: 'A lush spring wreath of tulips, daffodils, blossom and catkins around an open linen centre — a dense showpiece.', prompt: 'a highly detailed naturalistic illustration of a lush round spring wreath with a clear open empty centre, made of pink and yellow tulips, golden daffodils, sprigs of pink cherry blossom, blue grape hyacinths, fresh green leaves and pussy-willow catkins, densely packed in a full circular ring, the centre of the ring completely empty and plain, no text, no border', frame: 'round', widthMm: 240, detail: true, tameWarm: true },
  coastalcove: { slug: 'coastalcove', name: 'Coastal Cove', description: 'A sunny hidden cove with turquoise sea, golden sand and wildflower cliffs — a full coastal showpiece scene.', prompt: 'a beautiful painterly illustration of a hidden coastal cove on a bright summer day, clear turquoise and deep blue sea, a curve of golden sandy beach, rugged green headland cliffs dotted with pink sea thrift and yellow wildflowers, a little white sailing boat on the water, soft blue sky with a few clouds, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 280, detail: true, bleed: true },
  // ---- Batch 12 (2026-07-03): full range across new themes (simple bird/sea/houseplant -> XL meadow scene + autumn harvest showpiece) ----
  budgie: { slug: 'budgie', name: 'Budgerigar', description: 'A bright green-and-yellow budgie on a perch — a simple, cheerful bird motif.', prompt: 'a cute naturalistic illustration of a single budgerigar parakeet perched on a small wooden perch, bright grass-green body, sunny yellow head and face, black-barred wings, a small orange beak and blue cheek spots, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  starfish: { slug: 'starfish', name: 'Starfish', description: 'A single warm-orange starfish with a pebbled surface — a simple, sunny sea motif.', prompt: 'a highly detailed naturalistic illustration of a single five-armed starfish seen from above, warm coral-orange with a gently pebbled bumpy textured surface and a paler underside at the arm tips, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  succulent: { slug: 'succulent', name: 'Potted Succulent', description: 'A plump echeveria succulent rosette in a little pot — a simple houseplant motif.', prompt: 'a simple cute illustration of a single plump echeveria succulent, a neat rosette of thick rounded blue-green leaves tipped with soft dusky pink, planted in a small pale terracotta pot, the whole plant centred with a generous plain empty margin all around it, no other plants, no scattered leaves' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  germanshepherd: { slug: 'germanshepherd', name: 'German Shepherd', description: 'An alert German shepherd head portrait in tan and black, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a german shepherd dog head and shoulders portrait, rich tan and black saddle-marked coat, large upright pointed ears, a long dark muzzle with a plain black nose, warm intelligent dark eyes, alert noble expression, closed mouth with no red or pink around it, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 205, detail: true, tameWarm: true },
  teapot: { slug: 'teapot', name: 'Floral Teapot', description: 'A vintage duck-egg-blue china teapot painted with roses and forget-me-nots — a charming cottagecore motif.', prompt: 'a charming naturalistic illustration of a single vintage floral china teapot in profile, a solid rounded duck-egg blue china body with soft rounded shading and a clear dark outline all around it so the whole teapot reads as one solid filled shape clearly darker than the pale background, the body painted with a spray of pink cabbage roses, blue forget-me-nots and small green leaves, a curved spout and a curled handle, a domed lid with a little round knob, a soft gold rim, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 180, detail: true, tameWarm: true },
  easterbasket: { slug: 'easterbasket', name: 'Easter Basket', description: 'A woven basket of pastel eggs and spring flowers with a little chick — a cheerful Easter motif.', prompt: 'a charming naturalistic illustration of a small woven wicker basket filled with pastel-painted easter eggs in soft pink, blue, yellow and mint, golden daffodils and pink tulips tucked among them, a fluffy yellow chick peeking over the rim, the whole arrangement centred with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 195, detail: true, tameWarm: true },
  flowerfairy: { slug: 'flowerfairy', name: 'Flower Fairy', description: 'A delicate flower fairy among oversized garden blooms in a sunlit magical garden — a full scene.', prompt: 'a whimsical painterly illustration of a delicate flower fairy with translucent iridescent wings sitting among oversized garden flowers, tall pink foxgloves, white oxeye daisies and blue bluebells, in a soft sunlit magical garden, dreamy golden light, tiny glowing sparkles drifting in the air, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 210, detail: true, tameWarm: true, bleed: true },
  catreading: { slug: 'catreading', name: 'Cat Reading by the Window', description: 'A bespectacled cat curled up reading in a cosy lamplit nook — a whimsical full scene.', prompt: 'a cosy whimsical painterly illustration of a content tabby cat wearing small round glasses, curled up in a soft armchair reading an open book, a steaming cup of tea and a little stack of books on a side table, a warm lamplit reading nook beside a window with soft evening light outside, houseplants and a rug, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 230, detail: true, tameWarm: true, bleed: true },
  wildflowermeadow: { slug: 'wildflowermeadow', name: 'Wildflower Meadow', description: 'A summer wildflower meadow panorama with poppies, cornflowers and daisies — a full showpiece scene.', prompt: 'a beautiful highly detailed painterly illustration of a summer wildflower meadow panorama, red poppies, blue cornflowers, white oxeye daisies and golden buttercups among tall waving grasses, a scattering of butterflies, soft rolling green hills in the distance under a gentle blue sky with a few clouds, warm sunlight, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 280, detail: true, tameWarm: true, bleed: true },
  autumnbounty: { slug: 'autumnbounty', name: 'Autumn Harvest', description: 'An abundant gathered autumn harvest of pumpkins, sunflowers, wheat and berries — a dense seasonal showpiece.', prompt: 'a lush highly detailed naturalistic illustration of a gathered autumn harvest still life arranged in an abundant cluster, small orange pumpkins and gourds, golden sunflowers, tied ears of wheat, red rosehips, acorns, hazelnuts, clusters of blackberries and richly coloured amber red and gold oak and maple leaves, dense layered and overlapping, a single centred composition with a clear margin all around it' + PLAIN, frame: 'round', widthMm: 250, detail: true },
  // ---- Batch 13 (2026-07-03): full range across new themes (simple tortoise/thistle -> XL spring bouquet + winter village scene) ----
  // russianblue + rose carry their REPAIRED prompts (first renders had a source-baked red nose / an orange colour blow-out; see master-list Batch 13).
  tortoise: { slug: 'tortoise', name: 'Tortoise', description: 'A little tortoise walking in profile with a patterned domed shell — a simple, sweet motif.', prompt: 'a cute naturalistic illustration of a single small tortoise walking in side profile, a domed brown and olive-green shell with clear patterned scute markings, wrinkled sturdy legs, a gentle wrinkled face and dark eye, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 150, detail: true },
  thistle: { slug: 'thistle', name: 'Scottish Thistle', description: 'A single spiky purple Scottish thistle on a stem — a bold botanical motif.', prompt: 'a highly detailed naturalistic illustration of a single scottish thistle, a spiky tufted rosy-purple flower head rising from a rounded spiny green bulb base, on one upright stem with jagged silvery-green spined leaves, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 165, detail: true, tameWarm: true },
  dachshund: { slug: 'dachshund', name: 'Dachshund', description: 'A smooth-haired dachshund head portrait in warm reddish-tan, in soft long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a smooth-haired dachshund dog head and shoulders portrait, a sleek short reddish-tan coat, long soft drop ears, a slender pointed muzzle with a plain solid black nose, warm dark eyes, a gentle friendly expression, closed mouth with no red or pink around it, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  russianblue: { slug: 'russianblue', name: 'Russian Blue Cat', description: 'A plush blue-grey Russian Blue cat with vivid green eyes — a cool-toned portrait.', prompt: 'a highly detailed naturalistic illustration of a russian blue cat head and shoulders portrait, plush dense short blue-grey fur with a soft silvery sheen, large rounded ears with soft dusky grey inner ears (absolutely no red, no pink, no scarlet inside the ears), striking calm vivid green eyes with plain grey eyelids and no red rims, a fine elegant face with a small solid slate-grey nose (absolutely not red, not pink, not orange), cool grey and silver tones only everywhere with no red, no pink, no orange and no warm patches anywhere, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 210, detail: true, tameWarm: true },
  flamingo: { slug: 'flamingo', name: 'Flamingo', description: 'A graceful flamingo standing in profile with rosy-pink plumage — a bright, elegant motif.', prompt: 'a highly detailed naturalistic illustration of a single flamingo standing in profile with an elegant curved S-shaped neck, soft rosy-pink and coral feathers deepening on the wings, a black-tipped down-curved pink beak, one long slender leg, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  jellyfish: { slug: 'jellyfish', name: 'Jellyfish', description: 'A glowing pink-and-violet jellyfish with trailing tentacles — a luminous sea motif.', prompt: 'a highly detailed naturalistic illustration of a single glowing jellyfish drifting, a translucent domed bell in deep saturated rose-pink and violet-purple with a bold darker outline all around it so it reads clearly against the pale background, long delicate frilled trailing tentacles hanging below, a soft bioluminescent glow, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 200, detail: true, tameWarm: true },
  peacockbutterfly: { slug: 'peacockbutterfly', name: 'Peacock Butterfly', description: 'A peacock butterfly with open wings and bold eyespots — rich specimen thread painting.', prompt: 'a highly detailed naturalistic illustration of a peacock butterfly with open wings resting on a flower, rich reddish-brown wings each marked with a large striking blue and pale-yellow eyespot, dark charcoal wing borders, delicate wing veining and a furred body, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 185, detail: true, tameWarm: true },
  rose: { slug: 'rose', name: 'Red Rose', description: 'A single deep-red garden rose in full bloom, in layered long-and-short shading.', prompt: 'a highly detailed naturalistic illustration of a single large deep-red garden rose in full bloom, softly layered velvety petals in a rich muted burgundy and dark crimson red with gentle darker shadows and soft rose highlights, a natural deep-red rose colour that is definitely not orange, not scarlet, not vermilion and with no purple, no blue and no teal streaks, a green stem with two leaves and a small bud, a single centred subject with a generous clear margin all around it' + PLAIN, frame: 'round', widthMm: 175, detail: true, tameWarm: true },
  springbouquet: { slug: 'springbouquet', name: 'Spring Bouquet', description: 'A lush overflowing spring bouquet of daffodils, tulips and narcissi — a dense floral showpiece.', prompt: 'a lush highly detailed naturalistic illustration of an abundant spring bouquet of golden daffodils, pink and white tulips, blue grape hyacinths, sprigs of white narcissi, soft pink ranunculus and fresh green leaves, gathered in a full overflowing arrangement, layered overlapping blooms, a single centred composition with a clear margin all around it' + PLAIN, frame: 'round', widthMm: 260, detail: true, tameWarm: true },
  wintervillage: { slug: 'wintervillage', name: 'Snowy Village at Dusk', description: 'A cosy snowy village at dusk with glowing windows and pine trees — a full winter scene.', prompt: 'a beautiful cosy painterly illustration of a snowy winter village at dusk, little stone cottages with deep snow-covered roofs and warm glowing golden windows, a small church with a steeple, a winding lane with an old lamppost, tall snow-dusted pine trees, gentle falling snow, distant soft hills, a deep blue and lilac twilight sky with a scatter of stars, full scene filling the frame, no text, no border', frame: 'rect', widthMm: 280, detail: true, bleed: true },
}

function flag(name: string): boolean { return process.argv.includes(`--${name}`) }
function titleCase(s: string): string { return s.replace(/(^|-)([a-z])/g, (_, p, c) => (p ? ' ' : '') + c.toUpperCase()) }

async function fluxCached(job: Job): Promise<Buffer> {
  mkdirSync(OUT, { recursive: true })
  const p = resolve(OUT, `${job.slug}.flux.png`)
  if (existsSync(p)) return readFileSync(p)
  const src = await fluxIllustration(job.prompt, { imageSize: 'square_hd' })
  writeFileSync(p, src.buffer)
  return src.buffer
}

async function run(job: Job): Promise<void> {
  const publish = flag('publish')
  const refreshDoc = flag('refresh-doc')
  const frameless = flag('none')
  const img = await fluxCached(job)
  const WORK = 460
  const { data, info } = await sharp(img).resize(WORK, WORK, { fit: 'inside' }).removeAlpha().raw().toBuffer({ resolveWithObject: true })

  const engineFrame = frameless ? 'none' : (job.frame === 'round' ? 'round' : job.frame ?? 'round')
  const { stitchedElements, frameType, finishedSizeMm, outline } = bitmapToStitches(data, info.width, info.height, {
    mode: job.mode, frame: engineFrame, bleed: job.bleed, detail: job.detail, widthMm: job.widthMm,
  })
  console.log(`[${job.slug}] ${job.mode ?? 'dense'} · ${frameType} · ${stitchedElements.length} stitches · ${outline.length} outline paths · ${Math.round(finishedSizeMm.width)}x${Math.round(finishedSizeMm.height)}mm`)

  // --refresh-doc: rebuild the document + outline + vectorData on the EXISTING
  // row and re-store, WITHOUT re-rendering the hero. The engine is deterministic
  // from the cached Flux image, so the stored hero still matches these elements.
  if (refreshDoc) {
    const { prisma } = await import('@homemade/db')
    const existing = await prisma.needleworkPattern.findUnique({ where: { slug: job.slug }, select: { id: true } })
    if (!existing) throw new Error(`no NeedleworkPattern row for slug "${job.slug}" — publish it first`)
    const name = job.name ?? titleCase(job.slug)
    const canonical: NeedleworkSurfacePattern = {
      stitchedElements, finishedSizeMm, fabricSpec: { material: 'linen', colourHex: FABRIC, count: null },
      defaultThread: { type: 'stranded-cotton', weight: '3-strand' }, frameType, outline,
    }
    const document = buildPatternDocument(stitchedElements, finishedSizeMm, { title: name, outline })
    const { vectorData, regionAnnotations } = toStoredVectorData(canonical, { document })
    await prisma.needleworkPattern.update({
      where: { id: existing.id },
      data: {
        vectorData: vectorData as unknown as object,
        regionAnnotations: regionAnnotations as unknown as object,
        colourCount: document.flossKey.length,
      },
    })
    console.log(`[${job.slug}] REFRESHED doc on NeedleworkPattern ${existing.id} — ${document.flossKey.length} colours, ${outline.length} outline paths (hero untouched)`)
    await prisma.$disconnect()
    return
  }

  const hero = await renderHero(
    { name: job.slug, stitchedElements, finishedSizeMm, fabricHex: FABRIC, frameType,
      defaultThread: { type: 'stranded-cotton', weight: '3-strand' }, strands: 3 },
    { persist: publish, tameWarm: job.tameWarm ?? false, r2Prefix: 'patterns/needlework' },
  )

  if (!publish) {
    const { publicUrl } = await r2UploadScript(readFileSync(hero.localHeroPath), 'image/png', { prefix: 'scratch-review' })
    console.log(`[${job.slug}] preview: ${publicUrl}`)
    return
  }

  // ---- publish: persist through the proven NeedleworkPattern pipeline ----
  const { prisma, Visibility } = await import('@homemade/db')
  if (!hero.r2) throw new Error('renderHero did not persist to R2')
  // File into the surface-embroidery shelf. The live needlework category grid
  // only shows rows with a sub-category in the needlework category
  // (pattern-layout.tsx needleworkWhere) — an unfiled row is invisible on-site.
  const nwCat = await prisma.category.findUnique({ where: { slug: 'needlework' }, select: { id: true } })
  const nwSub = nwCat ? await prisma.subCategory.findFirst({ where: { categoryId: nwCat.id, slug: 'surface-embroidery' }, select: { id: true } }) : null
  if (!nwSub) throw new Error('surface-embroidery sub-category not found for needlework')
  const name = job.name ?? titleCase(job.slug)
  const meta = await sharp(hero.localHeroPath).metadata()
  const media = await prisma.media.create({
    data: {
      type: 'PHOTO', mimeType: 'image/png', filename: `${job.slug}-hero.png`,
      alt: `${name} — finished embroidery`, width: meta.width ?? hero.width, height: meta.height ?? hero.height,
      bytes: readFileSync(hero.localHeroPath).length, status: 'READY', r2Key: hero.r2.key,
      source: 'loom-render', requiresAttribution: false,
    },
    select: { id: true },
  })
  const canonical: NeedleworkSurfacePattern = {
    stitchedElements, finishedSizeMm, fabricSpec: { material: 'linen', colourHex: FABRIC, count: null },
    defaultThread: { type: 'stranded-cotton', weight: '3-strand' }, frameType, outline,
  }
  const document = buildPatternDocument(stitchedElements, finishedSizeMm, { title: name, outline })
  const { vectorData, regionAnnotations } = toStoredVectorData(canonical, { document })
  const data2 = {
    slug: job.slug, name, description: job.description ?? null,
    discipline: 'SURFACE_EMBROIDERY' as never, patternFormat: 'SURFACE_VECTOR' as never,
    vectorData: vectorData as unknown as object, regionAnnotations: regionAnnotations as unknown as object,
    fabricSpec: canonical.fabricSpec as unknown as object,
    frameType: (frameType === 'NONE' ? null : frameType) as never,
    threadTypes: ['stranded-cotton'], colourCount: document.flossKey.length,
    difficulty: 'INTERMEDIATE' as never, heroMediaId: media.id, thumbnailMediaId: media.id,
    subCategoryId: nwSub.id,
    visibility: Visibility.UNLISTED, publishedAt: new Date(),
  }
  const pattern = await prisma.needleworkPattern.upsert({ where: { slug: job.slug }, create: data2, update: data2, select: { id: true } })
  console.log(`[${job.slug}] PUBLISHED NeedleworkPattern ${pattern.id} (UNLISTED) — ${document.flossKey.length} colours`)
  console.log(`[${job.slug}] live at /needlework/patterns/${job.slug}`)
  await prisma.$disconnect()
}

async function main(): Promise<void> {
  const want = process.argv.slice(2).filter((a) => !a.startsWith('--'))
  for (const slug of (want.length ? want : ['fox'])) { const j = JOBS[slug]; if (!j) { console.error('no job', slug); continue } await run(j) }
}
main().catch((e) => { console.error('FAILED:', e instanceof Error ? (e.stack ?? e.message) : String(e)); process.exit(1) })
