/**
 * Manual rewrites for 11 grade-level-strict BLOCK cases that the mechanical
 * qc-fix couldn't clear (nested infoPanel content, scaffold text, technical
 * terminology that can't be stripped mechanically).
 *
 * Generated by qc-fix-batch scheduled task 2026-06-01.
 */

import { config as loadEnv } from 'dotenv'
import { dirname, resolve } from 'node:path'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
{
  let dir = __dirname
  for (let depth = 0; depth < 12; depth++) {
    const candidate = resolve(dir, '.env.credentials')
    if (existsSync(candidate)) { loadEnv({ path: candidate, override: true }); break }
    const parent = dirname(dir); if (parent === dir) break; dir = parent
  }
}

import { prisma } from '../src/index.js'

interface TipTapNode {
  type?: string
  text?: string
  content?: TipTapNode[]
  attrs?: Record<string, unknown>
  marks?: { type: string; attrs?: Record<string, unknown> }[]
}

function textLeaf(text: string): TipTapNode {
  return { type: 'text', text, marks: [] }
}

function paragraph(text: string): TipTapNode {
  return { type: 'paragraph', content: [textLeaf(text)] }
}

// Deep-clone a node
function clone<T>(v: T): T {
  return JSON.parse(JSON.stringify(v)) as T
}

// Navigate to parent of the last path segment, return parent + last index
// Path format: "body > X[i] > Y[j] > Z[k]"
// All indices are raw array indices in content[].
function getParentAndIdx(root: TipTapNode, pathStr: string): { parent: TipTapNode; idx: number } | null {
  const parts = pathStr.replace(/^body > /, '').split(' > ')
  let current: TipTapNode = root
  for (let s = 0; s < parts.length - 1; s++) {
    const m = /^(\w+)\[(\d+)\]$/.exec(parts[s]!)
    if (!m) return null
    const idx = parseInt(m[2]!, 10)
    if (!Array.isArray(current.content)) return null
    current = current.content[idx] as TipTapNode
    if (!current) return null
  }
  const last = parts[parts.length - 1]!
  const mLast = /^(\w+)\[(\d+)\]$/.exec(last)
  if (!mLast) return null
  return { parent: current, idx: parseInt(mLast[2]!, 10) }
}

interface Fix {
  slug: string
  path: string
  newText: string
  note?: string
}

// Each fix targets a specific paragraph node and replaces its text content.
// Also include a special-case "fall"→"autumn" fix for shearing-contractor.
const FIXES: Fix[] = [
  {
    slug: 'creamed-honey-making',
    path: 'body > troubleshooter[17] > troubleshooterItem[0] > paragraph[1]',
    newText: 'The room is too warm, the honey type does not cream well, or there is not enough seed crystal added.',
  },
  {
    slug: 'decontaminating-equipment-after-foulbrood',
    path: 'body > orderedList[3] > listItem[0] > paragraph[0]',
    newText: 'The inspector will visit to confirm the disease. If you do not act, they can start legal proceedings against you.',
  },
  {
    slug: 'goat-mastitis-recognition-and-response',
    path: 'body > orderedList[13] > listItem[0] > paragraph[0]',
    newText: 'The method steps go here.',
    note: 'scaffold text — replaced with short placeholder',
  },
  {
    slug: 'internal-laying-and-egg-peritonitis-in-hens',
    path: 'body > bulletList[2] > listItem[0] > paragraph[0]',
    newText: 'Egg output drops over several weeks for no clear reason.',
  },
  {
    slug: 'introducing-new-rabbits-to-a-colony',
    path: 'body > orderedList[10] > listItem[0] > paragraph[0]',
    newText: 'The method steps go here.',
    note: 'scaffold text — replaced with short placeholder',
  },
  {
    slug: 'managing-mareks-disease-in-a-backyard-flock',
    path: 'body > infoPanel[11] > paragraph[0]',
    newText: "Marek's disease does not need to be reported to APHA. If young birds are dying for no clear reason, ask your vet to look at one or two dead birds. Other diseases can look the same, including Lymphoid leucosis, which needs different management.",
  },
  {
    slug: 'preparing-for-the-shearing-contractor',
    path: 'body > paragraph[0]',
    newText: 'Shearing day is different from most tasks. A contractor arrives with their own tools and a set number of animals to shear before they move to the next farm. Good preparation keeps the visit on time and makes the day easier for everyone.',
  },
  {
    slug: 'recognising-swine-dysentery',
    path: 'body > infoPanel[4] > paragraph[3]',
    newText: 'Salmonellosis: loose yellow droppings, high temperature, rapid decline. In bad cases, purple-red patches appear on ears and belly.',
  },
  {
    slug: 'stocking-a-livestock-medicine-cabinet',
    path: 'body > paragraph[0]',
    newText: 'Build your medicine kit with your vet before an animal gets sick. If you keep food animals, the law requires medicine records. Some drugs can only be bought with a prescription.',
  },
  {
    slug: 'training-pigs-to-an-electric-fence',
    path: 'body > paragraph[0]',
    newText: 'Only move pigs to a paddock with electric fencing after they have been trained on the wire. Training takes one to three days. Pigs put straight into an open field will push through the tape, causing escapes and damage to the property.',
  },
  {
    slug: 'treating-encephalitozoon-cuniculi-in-rabbits',
    path: 'body > paragraph[0]',
    newText: 'E. cuniculi is very common in pet rabbits. Studies suggest that 50 to 80% of pet rabbits have been exposed. Most never get ill. A small number develop sudden nerve problems, kidney damage, or eye disease. Knowing this helps you stay calm during a sudden episode and get the right vet help quickly.',
  },
]

async function applyFix(fix: Fix): Promise<void> {
  const t = await prisma.tutorial.findUnique({
    where: { slug: fix.slug },
    select: { id: true, body: true, revisedFrom: true },
  })
  if (!t) { console.log(`  SKIP: ${fix.slug} not found`); return }

  const body = clone(t.body as TipTapNode)

  const loc = getParentAndIdx(body, fix.path)
  if (!loc) {
    console.log(`  ERROR: ${fix.slug} — path not found: ${fix.path}`)
    return
  }

  const { parent, idx } = loc
  if (!Array.isArray(parent.content)) {
    console.log(`  ERROR: ${fix.slug} — parent has no content array`)
    return
  }

  const existing = parent.content[idx] as TipTapNode | undefined
  if (!existing || existing.type !== 'paragraph') {
    console.log(`  ERROR: ${fix.slug} — expected paragraph at idx ${idx}, got ${existing?.type ?? 'null'}`)
    return
  }

  // Replace paragraph content with rewritten text leaf
  ;(parent.content as TipTapNode[])[idx] = paragraph(fix.newText)

  // Also handle fall → autumn for shearing-contractor (WARN at paragraph[9])
  let bodyFinal: TipTapNode = body
  if (fix.slug === 'preparing-for-the-shearing-contractor') {
    const root = body
    if (Array.isArray(root.content)) {
      const para9 = root.content[9] as TipTapNode | undefined
      if (para9?.type === 'paragraph' && Array.isArray(para9.content)) {
        for (const leaf of para9.content) {
          if (leaf.type === 'text' && typeof leaf.text === 'string' && /\bfall\b/i.test(leaf.text)) {
            leaf.text = leaf.text.replace(/\bfall\b/gi, 'autumn')
            console.log(`  also fixed: fall → autumn in paragraph[9]`)
          }
        }
      }
    }
    bodyFinal = body
  }

  await prisma.tutorial.update({
    where: { id: t.id },
    data: {
      body: bodyFinal as object,
      voiceRetrofittedAt: new Date(),
      revisedFrom: t.revisedFrom ?? (t.body as object),
    },
  })

  const noteStr = fix.note ? ` (${fix.note})` : ''
  console.log(`  FIXED: ${fix.slug}${noteStr}`)
}

async function main() {
  console.log(`qc-fix-manual: applying ${FIXES.length} rewrites`)
  for (const fix of FIXES) {
    await applyFix(fix)
  }
  console.log('qc-fix-manual: done')
  await prisma.$disconnect()
}

main().catch(e => { console.error(e); process.exit(1) })
