/**
 * Generator: D-Lacework Batch 3 — Lace Shawls Part 3 (L21-L30)
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-lacework-batch3.ts
 * Writes JSON files to briefs-crochet-d-lacework/
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-lacework')
mkdirSync(OUT, { recursive: true })

// ── TipTap helpers ────────────────────────────────────────────────────────────
function p(...nodes: object[]) {
  return { type: 'paragraph', content: nodes }
}
function t(text: string) { return { type: 'text', text } }
function h2(text: string) {
  return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] }
}
function gt(termSlug: string, text: string) {
  return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text }
}
function li(...content: object[]) {
  return { type: 'listItem', content: [{ type: 'paragraph', content: content }] }
}
function ol(...items: object[]) { return { type: 'orderedList', content: items } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string; substitutions?: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}
function trouble(heading: string, intro: string, items: { symptom: string; cause: string; fix: string }[]) {
  return { type: 'troubleshooter', attrs: { heading, intro, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── L21 ── hexagon-lace-shawl-crochet ────────────────────────────────────────
{
  slug: 'hexagon-lace-shawl-crochet',
  title: 'Hexagon lace shawl',
  subtitle: 'Geometric hexagon motifs joined into a crescent shawl.',
  excerpt: 'Individual hexagon motifs in fingering weight are joined as you go into a crescent shape. The open mesh between motifs keeps the fabric airy and the geometric lines give it a modern edge.',
  difficulty: 'INTERMEDIATE',
  primaryYarnWeightSlug: 'fingering',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: 'One hexagon motif = 8 cm point to point with a 3.5 mm hook in fingering yarn, blocked.',
  finishedSizeText: 'Crescent shawl, 160 cm wingspan x 45 cm deep at centre back, blocked.',
  techniqueSlugs: ['crochet-join-as-you-go', 'crochet-motif-construction', 'crochet-blocking', 'crochet-chain-space-mesh'],
  criticalTechniques: ['crochet-join-as-you-go', 'crochet-motif-construction', 'crochet-blocking'],
  aliases: ['hexagon shawl crochet', 'hex motif shawl', 'geometric lace shawl crochet'],
  glossaryTerms: [
    { slug: 'hexagon-motif', term: 'Hexagon motif', definition: 'A six-sided flat crochet piece worked in the round, beginning from a centre ring and built up in rounds of clusters and chain spaces to form six equal points.' },
    { slug: 'join-as-you-go', term: 'Join as you go', definition: 'Attaching a new motif to completed neighbours during its final round by replacing chain arches with slip stitches into matching arches on adjacent motifs.' },
    { slug: 'chain-space', term: 'Chain space', definition: 'The gap formed by one or more chains that the next round works into rather than into individual stitches.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wetting or steaming finished crochet and pinning it to the stated dimensions so the lace opens up and the fabric holds its shape when dry.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Hexagon motif construction draws on traditional Continental European hexagon lace traditions documented in 19th-century pattern books (Weldon\'s Practical Crochet series, Internet Archive). Crescent shaping and JAYG method are modern interpretations.',
  body: {
    type: 'doc',
    content: [
      p(t('A hexagon lace shawl is built from individual '), gt('hexagon-motif', 'hexagon motifs'), t(' that are '), gt('join-as-you-go', 'joined as you go'), t(' into a crescent shape. Each motif is 8 cm point to point after '), gt('blocking', 'blocking'), t('. The finished shawl is 160 cm across the wingspan and 45 cm deep at the centre back.')),
      p(t('The motifs are arranged in rows that increase by one hexagon on each row until the widest point is reached. Flat-joining keeps the surface smooth on both sides. The gaps between the motifs become part of the design, creating a lattice of open '), gt('chain-space', 'chain spaces'), t(' across the whole piece.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Fingering weight yarn', qty: '400 g', substitutions: 'Any smooth lace or fingering yarn in natural or plant fibre blocks well.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('One hexagon motif = 8 cm point to point with a 3.5 mm hook in fingering yarn, blocked. Work one motif and block it before starting the full shawl. If your motif is wider than 8 cm, go down one hook size. If narrower, go up. The crescent shaping depends on accurate motif size to stay flat.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('dc (UK): double crochet, insert hook, pull through, two loops off together')),
        li(t('tr (UK): treble, one yarn-over before inserting, three loops worked off two at a time')),
      ),
      h2('Single hexagon motif'),
      p(t('Foundation ring: ch 6, sl st to first ch to form a ring.')),
      p(t('Round 1: Ch 3 (counts as 1 tr). Work 2 tr into ring, ch 2. *3 tr into ring, ch 2*. Repeat 5 more times. Sl st to top of ch-3 to close. (6 clusters, 6 ch-2 corner spaces.)')),
      p(t('Round 2: Sl st into first ch-2 corner space. Ch 3. Work (2 tr, ch 2, 3 tr) into same space. Ch 1. *(3 tr, ch 2, 3 tr) into next corner, ch 1*. Repeat around. Sl st to close. (12 clusters, 6 ch-2 points, 6 ch-1 sides.)')),
      p(t('Round 3: Sl st to corner. Ch 3. Work (2 tr, ch 2, 3 tr) into corner. *(Ch 1, 3 tr into ch-1 side space, ch 1, (3 tr, ch 2, 3 tr) into next corner)*. Repeat around. Sl st. Fasten off. (18 clusters, 6 points, 12 sides.)')),
      h2('Crescent arrangement'),
      p(t('The shawl is built in diagonal rows with the flat edge of the crescent at the top.')),
      p(t('Row 1: Work 1 motif. Fasten off.')),
      p(t('Row 2: Work 2 motifs side by side. On the second motif\'s Round 3, '), gt('join-as-you-go', 'join as you go'), t(' to the first along one shared side: replace the ch-2 point with ch 1, sl st into matching point of adjacent motif, ch 1. Fasten off.')),
      p(t('Continue adding one more motif per row. Each new row joins to the row above along the top points. Stagger the motifs so each one sits in the gap between two motifs in the row above, like a brick course. Work 9 rows total to reach the 160 cm wingspan.')),
      h2('Finishing'),
      p(t('Weave in all tails with the tapestry needle. Block the finished shawl by soaking in cool water for 20 minutes, pressing out excess water in a towel, and pinning each hexagon point to the blocking mat at the stated dimensions. Leave to dry fully before removing pins. '), gt('blocking', 'Blocking'), t(' opens the chain spaces and makes the points sharp.')),
      trouble('Common problems', 'Hexagon join shawls have a few predictable trouble spots.', [
        { symptom: 'Shawl curling at the edges', cause: 'Motifs not blocked before joining or tension too tight', fix: 'Block each completed row before adding the next. If you skip this, wet-block the finished piece firmly and pin out every hexagon point.' },
        { symptom: 'Gaps uneven between motifs', cause: 'Inconsistent tension on the joining round', fix: 'Work the joining sl sts loosely; hold the two motifs face to face and ease the hook through both loops.' },
        { symptom: 'Shawl not lying flat', cause: 'Crescent not increasing correctly', fix: 'Check that each new row has exactly one more motif than the row above and that the joins are staggered, not lined up in straight columns.' },
      ]),
    ],
  },
},

// ── L22 ── filet-crochet-shawl ───────────────────────────────────────────────
{
  slug: 'filet-crochet-shawl',
  title: 'Filet crochet shawl',
  subtitle: 'A triangular shawl worked in filet mesh with solid block details.',
  excerpt: 'Filet crochet alternates open mesh squares with solid block squares to build pictures or geometric patterns into the fabric. This triangular shawl uses a simple diamond grid as its centrepiece worked in lace weight on a 3.5 mm hook.',
  difficulty: 'INTERMEDIATE',
  primaryYarnWeightSlug: 'lace',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: '10 mesh squares x 10 rows = 10 x 10 cm in lace weight with a 3.5 mm hook, blocked.',
  finishedSizeText: 'Triangular shawl, 170 cm wingspan x 80 cm deep at centre back, blocked.',
  techniqueSlugs: ['crochet-filet-mesh', 'crochet-blocking', 'crochet-triangular-shaping', 'crochet-reading-charts'],
  criticalTechniques: ['crochet-filet-mesh', 'crochet-blocking'],
  aliases: ['filet shawl crochet', 'mesh grid shawl', 'filet lace shawl'],
  glossaryTerms: [
    { slug: 'filet-mesh', term: 'Filet mesh', definition: 'A grid of open squares (one treble, two chains, skip two stitches) and solid squares (three trebles) worked in rows. Charts show which squares are open and which are filled to create patterns.' },
    { slug: 'open-mesh', term: 'Open mesh', definition: 'A filet square left as a gap: one treble at each edge with a two-chain bridge in the middle.' },
    { slug: 'solid-block', term: 'Solid block', definition: 'A filet square filled in with trebles: three trebles worked close together with no chain gap.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wetting or steaming finished crochet and pinning it to the stated dimensions so lace opens up fully.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Filet crochet as a domestic craft is documented from the 1890s in Weldon\'s Practical Needlework series (Internet Archive). The open-mesh solid-block grid is the foundational technique of 20th-century filet pattern books. This shaping and chart are original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A filet crochet shawl is a triangular piece 170 cm across the wingspan and 80 cm deep at the centre back. The fabric is a grid of '), gt('filet-mesh', 'filet mesh'), t(' squares, each one either open or filled in. Open squares let light through; solid squares build up the pattern.')),
      p(t('The shawl is worked from the top back neck edge downward, increasing by two '), gt('open-mesh', 'open mesh'), t(' squares per row at each side edge. A diamond grid sits in the centre panel, with '), gt('solid-block', 'solid blocks'), t(' tracing the diamond outline against an open mesh background.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Lace weight yarn', qty: '350 g', substitutions: 'A smooth lace or cobweb weight in cotton or silk-cotton blend shows filet patterns sharply.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('10 mesh squares x 10 rows = 10 x 10 cm in lace weight with a 3.5 mm hook, blocked. Work a 20-square-wide swatch across 15 rows, block it, and measure. The gauge determines the finished width. At 10 squares per 10 cm, the shawl reaches 170 cm at 170 squares wide.')),
      h2('Stitches and notation'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK): treble')),
        li(gt('open-mesh', 'Open mesh (O)'), t(': 1 tr, ch 2, skip 2 sts, 1 tr at the far edge')),
        li(gt('solid-block', 'Solid block (X)'), t(': 3 tr worked consecutively, no gap')),
      ),
      h2('Foundation row'),
      p(t('Ch 7 (counts as 1 open mesh square: 1 tr, ch 2, 1 tr in turning chain). Turn.')),
      h2('Row 2 (right side)'),
      p(t('Ch 8 (counts as 1 increase open mesh at left edge). Work 1 tr into the ch-4 base of row 1 to close the new increase mesh. Ch 2, skip 2, 1 tr into the last ch. Ch 5. Work 1 tr into the same last ch (increase open mesh at right edge). Turn. (3 open mesh squares.)')),
      h2('Continuing the increase'),
      p(t('Each right-side row increases by one open mesh at each edge using the ch-8 turn-and-fill method. Each wrong-side row mirrors the right side. Work in pattern following the chart: read right-side rows from right to left, wrong-side rows from left to right. The centre diamond appears from Row 15. Work 80 rows total.')),
      h2('Diamond centre chart'),
      p(t('Rows 15 to 45: The centre 11 squares of each row trace a diamond outline. On Row 15, the centre square is a solid block. On Row 16, the two squares either side of centre are solid. Continue expanding by two solid squares per row until Row 30 (the widest row of the diamond), then mirror back in to Row 45. All surrounding squares remain open mesh.')),
      h2('Finishing'),
      p(t('Work one row of double crochet around all three edges of the triangle. '), gt('blocking', 'Block'), t(' by soaking and pinning each corner and several points along each edge. The mesh opens significantly: an unblocked 10 x 10 cm swatch can reach 13 x 13 cm blocked, so pin to the stated 170 x 80 cm rather than working to a smaller target.')),
      trouble('Common problems', 'Filet mesh shawls have specific issues around counting and edge shaping.', [
        { symptom: 'Row width not increasing', cause: 'Missing the ch-8 turning chain increase method', fix: 'The ch-8 at the start of a right-side row forms one new open mesh and the turning chain for the row. Count it as a mesh square before working across.' },
        { symptom: 'Pattern diamonds misaligned', cause: 'Reading the chart from the wrong direction on wrong-side rows', fix: 'Mark every wrong-side row on the chart before you start. Read these rows from left to right on the chart so solid blocks fall in the correct columns.' },
        { symptom: 'Mesh squares uneven in size', cause: 'Inconsistent ch-2 tension', fix: 'Work all ch-2 bridges over a pencil or crochet hook one size larger to keep them consistent, then remove before the next row.' },
      ]),
    ],
  },
},

// ── L23 ── waterfall-lace-shawl-crochet ─────────────────────────────────────
{
  slug: 'waterfall-lace-shawl-crochet',
  title: 'Waterfall lace shawl',
  subtitle: 'Cascading chevron lace rows worked top down in fingering weight.',
  excerpt: 'Chevron lace rows angle downward from the spine to create a cascading waterfall effect across a crescent shawl. The repeat is a four-row pattern that is straightforward to memorise after the first few repeats.',
  difficulty: 'INTERMEDIATE',
  primaryYarnWeightSlug: 'fingering',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: '16 dc (UK) x 10 rows = 10 x 10 cm in fingering weight with a 3.5 mm hook, blocked.',
  finishedSizeText: 'Crescent shawl, 155 cm wingspan x 50 cm deep at centre back, blocked.',
  techniqueSlugs: ['crochet-chevron-lace', 'crochet-top-down-shaping', 'crochet-blocking', 'crochet-chain-space-mesh'],
  criticalTechniques: ['crochet-chevron-lace', 'crochet-top-down-shaping', 'crochet-blocking'],
  aliases: ['waterfall shawl crochet', 'chevron lace shawl', 'cascading lace shawl crochet'],
  glossaryTerms: [
    { slug: 'chevron-lace', term: 'Chevron lace', definition: 'A lace pattern where yarn-over decreases and chain arches are arranged in a diagonal or zigzag line, giving the impression of a V-shape or angular cascade.' },
    { slug: 'spine', term: 'Spine', definition: 'The central column of increases running down the back of a top-down shawl, from which stitches grow outward in each row.' },
    { slug: 'dc2tog', term: 'dc2tog', definition: 'Double crochet two together: a decrease that joins two stitches into one by working partway through each and then pulling the yarn through all three loops at once.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wetting the finished piece and pinning it to open the lace fully before drying.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Chevron lace construction synthesised from traditional zigzag lace principles present in 19th-century Shetland and Irish crochet sources. Top-down crescent shaping is a modern adaptation. Original pattern by Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A waterfall lace shawl is a crescent worked top down from the back neck edge. A central '), gt('spine', 'spine'), t(' of double increases grows the width as you go; chevron lace rows angle outward from it to create a cascading diagonal effect. The finished shawl is 155 cm across and 50 cm deep at centre back, blocked.')),
      p(t('The four-row '), gt('chevron-lace', 'chevron lace'), t(' repeat uses chains and '), gt('dc2tog', 'dc2tog'), t(' decreases to shift the columns of holes diagonally. After two pattern repeats (eight rows) the diagonal rhythm becomes easy to follow without counting every stitch.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Fingering weight yarn', qty: '400 g', substitutions: 'A wool or wool-silk fingering weight blocks well and holds the chevron angles sharply.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
        { name: 'Stitch markers', qty: '2' },
      ]),
      h2('Gauge'),
      p(t('16 dc (UK) x 10 rows = 10 x 10 cm in fingering weight with a 3.5 mm hook, blocked. The chevron lace fabric tends to be looser than plain double crochet; use a tighter tension gauge swatch in the actual pattern stitch if your yarn relaxes significantly.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('dc (UK): double crochet')),
        li(t('tr (UK): treble')),
        li(gt('dc2tog', 'dc2tog'), t(': double crochet two together (decrease)')),
      ),
      h2('Setup rows'),
      p(t('Ch 5. Work (1 tr, ch 2, 1 tr) into the 5th ch from hook (one corner made). Turn. Row 1 (increase row): Ch 4 (counts as 1 tr, ch 1). 1 tr into same base stitch. Ch 2. (1 tr, ch 2, 1 tr) into the ch-2 '), gt('spine', 'spine'), t(' space. Ch 2. (1 tr, ch 1, 1 tr) into the last tr. Turn. You now have 3 sections either side of the centre spine.')),
      h2('Chevron lace repeat (4 rows)'),
      p(t('Row A (right side): Ch 3, 1 tr into first ch-1 space. *Ch 2, skip, dc2tog over next 2 sts, ch 2, 1 tr into next space*. Work across to spine, work (2 tr, ch 2, 2 tr) into spine space (spine increase). Work back to match the other side. Turn.')),
      p(t('Row B (wrong side): Ch 3, 1 tr into ch-1 space. *Ch 2, 1 dc into ch-2 space, ch 2, 1 tr into next tr*. Repeat to spine, work (2 tr, ch 2, 2 tr) into spine. Mirror to end. Turn.')),
      p(t('Row C (right side): Ch 3, *ch 2, dc2tog, ch 2, 1 tr*. Repeat to spine, increase at spine. Mirror. Turn.')),
      p(t('Row D (wrong side): As Row B. Turn.')),
      p(t('Repeat rows A-D until the shawl is 50 cm deep from the neck edge when held flat and unblocked. Work a plain treble border row, then fasten off.')),
      h2('Blocking'),
      p(t('Soak the shawl, press out water in a towel, then pin. Pin the two tip ends of the crescent first to the wingspan markers at 155 cm apart on the blocking mats, then pin the centre back point downward to 50 cm. Fill in with pins along each curved edge every 5 cm. Leave until fully dry. '), gt('blocking', 'Blocking'), t(' makes the chevron diagonals sharp and the holes round.')),
      trouble('Common problems', 'Waterfall shawls have a few common tension and shaping errors.', [
        { symptom: 'Chevron diagonals not aligning between rows', cause: 'dc2tog worked in wrong position', fix: 'Mark the dc2tog positions on Row A with stitch markers and check they shift one stitch to the right on Row C. The diagonal angle comes from this one-stitch shift.' },
        { symptom: 'Shawl fanning too wide', cause: 'Too many increases at the spine', fix: 'The spine increase is always (2 tr, ch 2, 2 tr), not more. Count the spine stitches after each row and confirm the total stitch count grows by 4 per full repeat.' },
        { symptom: 'Edges pulling in', cause: 'Turning chain too short', fix: 'Work the ch-3 turning chain loosely. If the edge still pulls, add a ch-4 turning chain and count it as the first treble plus one chain space.' },
      ]),
    ],
  },
},

// ── L24 ── butterfly-lace-shawl-crochet ─────────────────────────────────────
{
  slug: 'butterfly-lace-shawl-crochet',
  title: 'Butterfly lace shawl',
  subtitle: 'A triangular shawl with a butterfly stitch repeat border in fingering weight.',
  excerpt: 'The butterfly stitch clusters open and close like wings across the border of this triangular shawl. The body is simple mesh; the border is where the stitch really shines, worked in rows of gathered loop clusters.',
  difficulty: 'INTERMEDIATE',
  primaryYarnWeightSlug: 'fingering',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: '18 sts x 12 rows = 10 x 10 cm in fingering weight mesh with a 3.5 mm hook, blocked.',
  finishedSizeText: 'Triangular shawl, 150 cm wingspan x 70 cm deep at centre back, blocked.',
  techniqueSlugs: ['crochet-butterfly-stitch', 'crochet-triangular-shaping', 'crochet-blocking', 'crochet-border-edging'],
  criticalTechniques: ['crochet-butterfly-stitch', 'crochet-triangular-shaping', 'crochet-blocking'],
  aliases: ['butterfly stitch shawl', 'butterfly crochet shawl', 'gathered loop shawl crochet'],
  glossaryTerms: [
    { slug: 'butterfly-stitch', term: 'Butterfly stitch', definition: 'A crochet stitch made by working multiple long loops across several rows and then gathering them with a slip stitch or chain, creating a shape that resembles butterfly wings.' },
    { slug: 'gathering-stitch', term: 'Gathering stitch', definition: 'A slip stitch or chain pulled through a set of long loops to cinch them together at their midpoint, forming the body of the butterfly cluster.' },
    { slug: 'lace-mesh', term: 'Lace mesh', definition: 'A simple open fabric of chain spaces and double crochet or treble stitches worked in a regular grid, forming the background of many lace shawl patterns.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wetting the finished shawl and pinning it to open the lace and set the butterfly shapes before drying.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Butterfly stitch construction draws on gathered-loop techniques present in mid-20th-century American crochet pattern booklets (public domain, pre-1928 editions held at Internet Archive). Triangular shaping and border placement are original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A butterfly lace shawl is a triangle worked from the top down. The body uses a simple '), gt('lace-mesh', 'lace mesh'), t(' ground of chains and trebles; the border is six rows of '), gt('butterfly-stitch', 'butterfly stitch'), t(' clusters that give the lower edge its character. The finished piece is 150 cm across and 70 cm deep at centre back, blocked.')),
      p(t('The butterfly stitch works by first making long loops across four mesh rows, then using a '), gt('gathering-stitch', 'gathering stitch'), t(' to pull them into the wing shape. The gathered point sits at the centre of what becomes the butterfly body. The technique looks complicated but has only two moves: long yarn-overs and one pull-through.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Fingering weight yarn', qty: '380 g', substitutions: 'A smooth fingering in wool or cotton shows the butterfly cluster shapes clearly.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('18 sts x 12 rows = 10 x 10 cm in fingering weight mesh with a 3.5 mm hook, blocked. The butterfly border is deeper than the mesh gauge suggests; work a 6-row butterfly swatch to check the border depth before committing to the full shawl.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('dc (UK): double crochet')),
        li(t('tr (UK): treble')),
        li(gt('butterfly-stitch', 'Butterfly stitch cluster'), t(': five long loops dropped across four rows, gathered at row 4 with one pulling sl st')),
      ),
      h2('Shawl body'),
      p(t('Foundation: ch 5. Work (2 tr, ch 2, 2 tr) into 5th ch from hook (centre spine set). Turn.')),
      p(t('Increase row: Ch 4 (counts as tr, ch 1). 1 tr into first tr. Work across in tr-ch-1 mesh to spine space. Work (2 tr, ch 2, 2 tr) into spine. Continue in mesh to end. Work (1 tr, ch 1, 1 tr) into turning chain. Turn.')),
      p(t('Repeat the increase row until the shawl is 60 cm deep from the spine, measured straight down. At this point there are approximately 200 stitches across the bottom edge.')),
      h2('Butterfly border: 6 rows'),
      p(t('Row 1 (right side): Work in tr-ch-1 mesh across, increasing at spine as usual. On every 8th stitch position, pull up a long loop (10 cm) instead of completing the tr. Leave the loop on the hook. Continue across. Turn. (The long loops sit loose on the hook; do not work them yet.)')),
      p(t('Rows 2 and 3: Work in plain mesh across, letting the long loops hang at the front of the fabric. Do not work into them.')),
      p(t('Row 4 (gathering row): Work in mesh to the first long-loop position. Insert hook through all five long loops from rows 1-3. Pull yarn through all loops in one movement ('), gt('gathering-stitch', 'gathering stitch'), t(' made, butterfly body formed). Continue in mesh to next long-loop position. Repeat across. Turn.')),
      p(t('Rows 5 and 6: Work two plain mesh rows to anchor the butterfly bases.')),
      h2('Border edge'),
      p(t('After Row 6, work one final row of dc (UK) along the bottom edge only, placing 1 dc into each stitch and 2 dc into each chain space. Fasten off.')),
      h2('Blocking'),
      p(t('Soak, pin wingspan corners to 150 cm apart and centre back to 70 cm deep. Ease the '), gt('blocking', 'blocking'), t(' pins between each butterfly cluster so the wings spread open. Leave to dry completely.')),
      trouble('Common problems', 'Butterfly stitch shawls have a few distinctive issues.', [
        { symptom: 'Long loops pulling out', cause: 'Not anchoring the loop base before rows 2-3', fix: 'Place a removable stitch marker through each long loop at the base to hold its position until the gathering row.' },
        { symptom: 'Butterfly bodies not centred', cause: 'Gathering stitch pulled off-centre', fix: 'Before gathering, fold the five loops so their midpoints align, then insert the hook and pull through all at once.' },
        { symptom: 'Border pulling the shawl forward', cause: 'Border worked too tightly', fix: 'Work the butterfly rows on a hook one size larger than the body rows and return to the smaller hook for the dc border.' },
      ]),
    ],
  },
},

// ── L25 ── square-lace-shawl-crochet ────────────────────────────────────────
{
  slug: 'square-lace-shawl-crochet',
  title: 'Square lace shawl',
  subtitle: 'A flat square worked from one corner in fingering weight open mesh.',
  excerpt: 'Starting from a single chain at one corner and increasing on every row builds a flat square shawl in fingering weight lace mesh. Simple but elegant, the geometry is self-evident from the first row and the shawl can stop at any size.',
  difficulty: 'BEGINNER',
  primaryYarnWeightSlug: 'fingering',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: '15 mesh squares x 15 rows = 10 x 10 cm in fingering weight mesh with a 3.5 mm hook, blocked.',
  finishedSizeText: 'Square shawl, 130 x 130 cm, blocked.',
  techniqueSlugs: ['crochet-corner-increase', 'crochet-chain-space-mesh', 'crochet-blocking', 'crochet-border-edging'],
  criticalTechniques: ['crochet-corner-increase', 'crochet-chain-space-mesh', 'crochet-blocking'],
  aliases: ['corner square shawl crochet', 'grandmother shawl crochet', 'flat square crochet shawl'],
  glossaryTerms: [
    { slug: 'corner-increase', term: 'Corner increase', definition: 'Working two stitches or a stitch-plus-chain into the tip stitch of a corner, turning one point into two diagonal edges that grow the fabric outward.' },
    { slug: 'lace-mesh', term: 'Lace mesh', definition: 'An open fabric of chains and single stitches forming a regular grid of holes through which light passes.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wetting and pinning crochet to its final dimensions so the fabric opens and sets in place.' },
    { slug: 'border-picot', term: 'Border picot', definition: 'A small decorative loop of three chains joined to the base with a slip stitch, used along border edges to add a scalloped finish.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Corner-to-corner square shawl construction is a classic format documented in early 20th-century American and British pattern booklets. Lace mesh ground and picot border are traditional finishing elements. This version is original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A square lace shawl starts at one corner with a single chain and is worked diagonally outward, increasing at the corner on every row, until the square reaches 130 x 130 cm. The fabric is plain '), gt('lace-mesh', 'lace mesh'), t(': one treble, two chains, skip two chains, repeated. Nothing more complex than that.')),
      p(t('The '), gt('corner-increase', 'corner increase'), t(' at the start and end of every row is the one technique that needs attention. Everything else is the same mesh repeat all the way to the final row. A '), gt('border-picot', 'border picot'), t(' edging along all four sides finishes the corners sharply.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Fingering weight yarn', qty: '350 g', substitutions: 'Any smooth fingering or light lace weight works. A mercerised cotton gives crisp mesh holes after blocking.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('15 mesh squares x 15 rows = 10 x 10 cm in fingering weight mesh with a 3.5 mm hook, blocked. Work a 20-mesh-square swatch across 20 rows. Block and measure. At 15 squares per 10 cm, the shawl needs 195 squares across the widest row to reach 130 cm. The shawl grows by 2 squares per row, so it takes 97 rows to reach full width.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('tr (UK): treble')),
        li(gt('corner-increase', 'Corner increase'), t(': (2 tr, ch 2, 2 tr) all into one stitch or chain space')),
      ),
      h2('Foundation'),
      p(t('Ch 6. Work (1 tr, ch 2, 1 tr) into 6th ch from hook. This is the first corner. Turn. (1 mesh square.)')),
      h2('Row 2'),
      p(t('Ch 5 (counts as 1 tr, ch 2). 1 tr into the same base ch (left corner increase made). Ch 2. Work (1 tr, ch 2, 1 tr) into the ch-2 corner space (centre mesh). Ch 2. Work (1 tr, ch 2, 1 tr) into the turning ch space (right corner increase). Turn. (4 mesh squares.)')),
      h2('Row 3 onwards'),
      p(t('Ch 5. 1 tr into same base (left corner increase). *Ch 2, skip 2 sts, 1 tr into next tr*. Repeat across to the ch-2 turning chain from the previous row. Work '), gt('corner-increase', 'corner increase'), t(' into that turning ch space (right corner increase). Turn. (Each row adds 2 mesh squares.)')),
      p(t('Work until the piece measures 65 cm diagonally from the starting corner to the current row edge. At this point the full 130 cm diagonal is halfway complete. Continue to 97 rows total.')),
      h2('Picot border'),
      p(t('Work one round of dc (UK) around all four sides of the square, placing 1 dc into each mesh stitch and 2 dc into each corner space. Then work a second border round: *1 dc into next dc, ch 3, sl st into the base of the ch-3 ('), gt('border-picot', 'picot'), t(' made), skip 1 dc*. Repeat around. Fasten off.')),
      h2('Blocking'),
      p(t('Soak the shawl, press out water without wringing, and lay flat on blocking mats. Pin each of the four corner points to form a true square at 130 x 130 cm. Pin along each edge every 5 cm. '), gt('blocking', 'Blocking'), t(' opens the mesh holes and makes the square geometry sharp and true.')),
      trouble('Common problems', 'Square shawls have straightforward problems with a clear fix for each.', [
        { symptom: 'Square pulling into a diamond shape', cause: 'Correct. The square sits on the diagonal.', fix: 'The piece looks like a diamond while on the hook. After blocking pinned to a square orientation, the corners become four equal points. Wear it as a triangle by folding in half.' },
        { symptom: 'Mesh holes closing up', cause: 'Tension too tight or yarn not blocked', fix: 'Block the swatch before adjusting hook size. Many fingering yarns need a full wet block to open properly.' },
        { symptom: 'Row count growing faster than width', cause: 'Increasing more than twice per row', fix: 'There should be exactly two corner increases per row, one at each end. If the piece is growing in all directions, count the corner-increase stitches and remove any extras.' },
      ]),
    ],
  },
},

// ── L26 ── tunisian-lace-shawl-crochet ─────────────────────────────────────
{
  slug: 'tunisian-lace-shawl-crochet',
  title: 'Tunisian lace shawl',
  subtitle: 'A rectangular shawl in Tunisian simple stitch with openwork panels.',
  excerpt: 'Tunisian crochet uses a long hook to hold all live stitches across the row like knitting, then works them off in a return pass. This shawl alternates solid Tunisian simple stitch columns with openwork chain panels for a woven-looking lace fabric.',
  difficulty: 'INTERMEDIATE',
  primaryYarnWeightSlug: 'sport',
  primaryHookSlug: 'crochet-hook-5-0mm',
  gaugeText: '18 Tss x 16 rows = 10 x 10 cm in sport weight with a 5 mm Tunisian hook, unblocked.',
  finishedSizeText: 'Rectangle shawl, 180 cm x 55 cm, blocked.',
  techniqueSlugs: ['crochet-tunisian-simple-stitch', 'crochet-tunisian-return-pass', 'crochet-openwork-panels', 'crochet-blocking'],
  criticalTechniques: ['crochet-tunisian-simple-stitch', 'crochet-tunisian-return-pass', 'crochet-blocking'],
  aliases: ['Tunisian shawl', 'Afghan stitch shawl', 'Tunisian lace rectangle shawl'],
  glossaryTerms: [
    { slug: 'tunisian-simple-stitch', term: 'Tunisian simple stitch', definition: 'The foundation stitch of Tunisian crochet: insert the hook behind the front vertical bar of each stitch and pull up a loop, keeping all loops on the hook across the forward pass, then work them off two at a time on the return pass.' },
    { slug: 'forward-pass', term: 'Forward pass', definition: 'The first half of a Tunisian row, where the hook picks up loops from left to right until all stitches are on the hook.' },
    { slug: 'return-pass', term: 'Return pass', definition: 'The second half of a Tunisian row, where the hook works from right to left, pulling yarn through two loops at a time until one loop remains.' },
    { slug: 'openwork-panel', term: 'Openwork panel', definition: 'A vertical strip of chain spaces and single stitches worked between solid Tunisian columns to create a ladder or eyelet effect.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Tunisian crochet (also called Afghan stitch) is documented from the 1860s in British needlework manuals. Openwork-panel variations appear in 20th-century pattern booklets. This shawl construction and panel repeat are original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A Tunisian lace shawl is a flat rectangle 180 cm long and 55 cm wide worked entirely in Tunisian crochet with a long-tail or interchangeable hook. The fabric alternates bands of solid '), gt('tunisian-simple-stitch', 'Tunisian simple stitch'), t(' with '), gt('openwork-panel', 'openwork panels'), t(' of chains and single stitches that run the full length of the shawl. Blocked, the panels open into wide lace ladders.')),
      p(t('Every row has two phases. The '), gt('forward-pass', 'forward pass'), t(' picks up loops across the row from right to left, leaving them all on the hook. The '), gt('return-pass', 'return pass'), t(' then works them off from left to right until one loop remains. This is the engine of all Tunisian work.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Sport weight yarn', qty: '400 g', substitutions: 'A smooth wool-cotton blend or bamboo blend drapes well in the long rectangle format.' },
        { name: '5 mm Tunisian crochet hook (long, at least 40 cm)', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('18 Tss x 16 rows = 10 x 10 cm in sport weight with a 5 mm Tunisian hook, unblocked. Tunisian fabric does not change dramatically with blocking, but does relax slightly. Work a 25-stitch swatch across 20 rows and measure unblocked.')),
      h2('Stitch notation'),
      ul(
        li(gt('tunisian-simple-stitch', 'Tss'), t(': Tunisian simple stitch, insert hook behind front vertical bar, pull up loop')),
        li(t('ch: chain')),
        li(t('dc (UK): double crochet')),
        li(gt('forward-pass', 'FP'), t(': forward pass')),
        li(gt('return-pass', 'RP'), t(': return pass, ch 1, *yo, pull through 2 loops* to end')),
      ),
      h2('Foundation row'),
      p(t('Ch 100. FP: insert hook into 2nd ch from hook, pull up loop. Continue pulling up 1 loop from each ch across. (100 loops on hook.) RP: ch 1, *yo, pull through 2 loops*. Repeat to end. (1 loop remains.)')),
      h2('Stitch pattern: 10-stitch repeat'),
      p(t('The pattern repeats across 10 stitches: 6 Tss, then 1 ch-2 openwork panel (skip 2, ch 2, pick up 1 Tss), then 1 Tss to anchor. Work this repeat across all 100 foundation stitches (10 repeats of 10). Follow with RP.')),
      p(t('On the next row, work 6 Tss over the Tss column. For the openwork section, insert the hook into the ch-2 space and pull up one loop as if it were a stitch. This is the '), gt('openwork-panel', 'openwork panel'), t(' repeat that keeps the ladders aligned on every row.')),
      h2('Working the length'),
      p(t('Continue working FP and RP with the 10-stitch pattern until the piece measures 180 cm. At 16 rows per 10 cm, this is approximately 288 rows. The fabric will bias slightly. This is normal for Tunisian and corrects on blocking.')),
      h2('Cast off'),
      p(t('On the final forward pass, instead of leaving loops on the hook, work sl st into each Tss and ch-2 space across. This is the Tunisian cast-off row. Fasten off.')),
      h2('Blocking'),
      p(t('Soak, press out water, and pin the rectangle to 180 x 55 cm on blocking mats. The Tunisian bias flattens on blocking. The openwork panels open into full-width lace ladders only after wet blocking.')),
      trouble('Common problems', 'Tunisian shawls have specific Tunisian-method issues.', [
        { symptom: 'Fabric biasing to one side', cause: 'Natural Tunisian bias from asymmetric stitch construction', fix: 'This is normal and corrects completely on blocking. Pin aggressively to the rectangular dimensions.' },
        { symptom: 'Loops falling off the hook', cause: 'Hook too short for the stitch count', fix: 'A 5 mm Tunisian hook must be at least 40 cm long for 100 stitches. Use an interchangeable Tunisian hook with an extension cable for long rows.' },
        { symptom: 'Openwork columns misaligned', cause: 'Inserting into the wrong position on the return pass', fix: 'The ch-2 space is a visible gap in the fabric. Insert the hook directly into the gap rather than into a vertical bar.' },
      ]),
    ],
  },
},

// ── L27 ── overlay-mesh-shawl-crochet ────────────────────────────────────────
{
  slug: 'overlay-mesh-shawl-crochet',
  title: 'Overlay mesh shawl',
  subtitle: 'Surface overlay stitches worked across a lace mesh ground in fingering weight.',
  excerpt: 'An overlay mesh shawl has two layers of crochet: a lace mesh ground worked first, then a second layer of surface stitches worked on top to create a raised geometric pattern. The result looks woven from a distance and lacework close up.',
  difficulty: 'ADVANCED',
  primaryYarnWeightSlug: 'fingering',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: '18 mesh sts x 12 rows = 10 x 10 cm in fingering weight with a 3.5 mm hook, blocked.',
  finishedSizeText: 'Triangular shawl, 160 cm wingspan x 75 cm deep at centre back, blocked.',
  techniqueSlugs: ['crochet-overlay-mesh', 'crochet-surface-crochet', 'crochet-triangular-shaping', 'crochet-blocking'],
  criticalTechniques: ['crochet-overlay-mesh', 'crochet-surface-crochet', 'crochet-blocking'],
  aliases: ['overlay crochet shawl', 'surface crochet shawl', 'overlay lace shawl'],
  glossaryTerms: [
    { slug: 'overlay-mesh', term: 'Overlay mesh', definition: 'A two-layer crochet technique where a foundation mesh ground is worked first, then a second set of stitches is worked on top by inserting the hook into specific mesh spaces to create a raised surface pattern.' },
    { slug: 'surface-stitch', term: 'Surface stitch', definition: 'A stitch worked on top of completed crochet by inserting the hook through the fabric from front to back and pulling up a loop, without using the foundation chain or stitches below.' },
    { slug: 'mesh-ground', term: 'Mesh ground', definition: 'The underlying open fabric of chains and single stitches that serves as the canvas for overlay crochet.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wetting the finished shawl and pinning to stated dimensions so both layers set together.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Overlay crochet technique developed in the late 20th century as an extension of traditional surface crochet, itself documented from the early 20th century. This shawl pattern is original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('An overlay mesh shawl is made in two passes. In the first pass you work a triangular '), gt('mesh-ground', 'mesh ground'), t(' of chains and trebles from the top down, increasing at each edge to build the triangle. In the second pass you work '), gt('surface-stitch', 'surface stitches'), t(' across the ground using a contrasting or matching yarn to create the '), gt('overlay-mesh', 'overlay mesh'), t(' pattern on top of the foundation.')),
      p(t('The overlay gives the fabric a raised geometric quality: diamonds, chevrons, or grid lines appear to float above the lace mesh below. The work is advanced because you must read both the mesh grid and the overlay chart simultaneously.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Fingering weight yarn, main colour (MC)', qty: '350 g', substitutions: 'A smooth single-ply or lightly plied fingering in wool or cotton works best for the ground.' },
        { name: 'Fingering weight yarn, contrast colour (CC)', qty: '100 g', substitutions: 'Can also use MC for a tone-on-tone effect.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('18 mesh sts x 12 rows = 10 x 10 cm in fingering weight with a 3.5 mm hook, blocked. Work the gauge swatch in the MC only. The overlay adds body but does not significantly change the dimensions.')),
      h2('Phase 1: mesh ground'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK): treble')),
        li(t('Mesh square: 1 tr, ch 2, skip 2, 1 tr')),
      ),
      p(t('Foundation: ch 7. Work (2 tr, ch 2, 2 tr) into 5th ch from hook. Turn. This is the centre spine.')),
      p(t('Increase row: Ch 5. 1 tr into first tr (left edge increase). Work mesh squares across to spine. Work (2 tr, ch 2, 2 tr) into spine ch-2 space. Continue mesh to end. Work (1 tr, ch 2, 1 tr) into turning ch space (right edge increase). Turn.')),
      p(t('Repeat increase row until '), gt('mesh-ground', 'mesh ground'), t(' is 75 cm deep. Block the ground lightly before working overlay.')),
      h2('Phase 2: overlay'),
      p(t('Attach CC at the top right corner of the blocked mesh ground. Insert hook from front to back through the first mesh square. Pull up a loop ('), gt('surface-stitch', 'surface stitch'), t(' start). Ch 1 to anchor.')),
      p(t('Diamond overlay repeat: *Cross diagonally up-right across 2 mesh squares (skip one, insert into the second). Cross diagonally down-right 2 squares. This makes one diamond half.* Continue across, building diamonds that are 4 squares wide and 4 rows tall. At each row of the ground, secure the overlay thread with a slip stitch before continuing the diagonal.')),
      p(t('Work the overlay across the full width of the ground. Fasten off CC at the left edge. Reattach at the top of the next overlay row and repeat.')),
      h2('Blocking'),
      p(t('After overlay is complete, soak the full shawl and block to 160 x 75 cm. '), gt('blocking', 'Blocking'), t(' melds both layers together. Pin the overlay threads gently so they sit flat against the ground without pulling.')),
      trouble('Common problems', 'Overlay shawls have unique two-layer challenges.', [
        { symptom: 'Overlay threads pulling the ground', cause: 'Surface stitches worked too tightly', fix: 'Work overlay stitches with a hook one size larger than the ground hook. The surface thread should lie on the fabric without gathering the mesh underneath.' },
        { symptom: 'Overlay pattern misaligned across rows', cause: 'Losing track of the mesh square count', fix: 'Count mesh squares in the ground before working and mark every 4th square with a removable marker. Overlay diamonds sit on multiples of 4.' },
        { symptom: 'CC yarn tangling during overlay', cause: 'Working in long runs without securing', fix: 'Work overlay in short segments of 10 diamonds at a time. Cut CC and rejoin rather than carrying it across long distances.' },
      ]),
    ],
  },
},

// ── L28 ── prayer-shawl-lace-crochet ────────────────────────────────────────
{
  slug: 'prayer-shawl-lace-crochet',
  title: 'Shell lace prayer shawl',
  subtitle: 'A wide, comforting shawl in dk weight shell lace, beginner-friendly.',
  excerpt: 'A prayer shawl in shell lace is wide, warm, and simple to make. This dk weight version uses a four-row shell repeat that is easy to memorise. The finished shawl wraps around the shoulders with plenty of fabric to spare.',
  difficulty: 'BEGINNER',
  primaryYarnWeightSlug: 'dk',
  primaryHookSlug: 'crochet-hook-4-0mm',
  gaugeText: '1 shell (5 tr) + 1 dc = 4.5 cm wide in dk weight with a 4 mm hook.',
  finishedSizeText: 'One size, 180 cm x 70 cm, unblocked.',
  techniqueSlugs: ['crochet-shell-stitch', 'crochet-border-edging', 'crochet-working-back-and-forth'],
  criticalTechniques: ['crochet-shell-stitch'],
  aliases: ['prayer shawl crochet', 'comfort shawl crochet', 'dk shell lace shawl'],
  glossaryTerms: [
    { slug: 'shell-stitch', term: 'Shell stitch', definition: 'Five (or more) trebles worked into the same stitch or chain space, fanning out to form a fan or shell shape.' },
    { slug: 'shell-repeat', term: 'Shell repeat', definition: 'The full unit of one shell and its surrounding stitches that tiles across the row to build the fabric.' },
    { slug: 'dc-anchor', term: 'dc anchor', definition: 'A single double crochet worked into the chain space between two shells to hold the fabric flat and set the position for the next row\'s shell.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Shell lace is one of the oldest crochet stitch families, documented in Weldon\'s Practical Crochet (1880s) and Priscilla Crochet publications (early 1900s, Internet Archive). Prayer shawl knitting and crochet became a popular charity and spiritual practice from the 1990s onward. This pattern is original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A shell lace prayer shawl is 180 cm long and 70 cm wide, worked flat in rows. The '), gt('shell-repeat', 'shell repeat'), t(' is four rows that are easy to remember after the first few: shell into chain space, '), gt('dc-anchor', 'dc anchor'), t(' into shell centre, and back again. DK weight on a 4 mm hook gives a warm, drapy fabric.')),
      p(t('The '), gt('shell-stitch', 'shell stitch'), t(' itself is five trebles into one space. It fans out from a narrow base to a wide top and the shells stack on top of each other row by row, anchored in between by single double crochets. The rhythm is satisfying and meditative once established.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK weight yarn', qty: '600 g', substitutions: 'Any soft DK in a wool-acrylic or bamboo blend works. Avoid very textured yarns as they hide the shell definition.' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('1 shell (5 tr) + 1 dc = 4.5 cm wide in dk weight with a 4 mm hook. The row height is about 4 cm per two-row repeat. Work one shell repeat and measure before starting. At 4.5 cm per repeat, the shawl needs 40 shell repeats to reach 180 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK): double crochet')),
        li(t('tr (UK): treble')),
        li(gt('shell-stitch', 'Shell'), t(': 5 tr into same ch space')),
        li(gt('dc-anchor', 'dc anchor'), t(': 1 dc into centre tr of shell below')),
      ),
      h2('Foundation chain'),
      p(t('Ch 183. Foundation row (wrong side): 1 dc into 4th ch from hook. *Skip 2 ch, 5 tr (shell) into next ch, skip 2 ch, 1 dc into next ch.* Repeat from * to * across. Turn. (40 shells.)')),
      h2('Row 1 (right side)'),
      p(t('Ch 3 (counts as 1 tr). 2 tr into first dc (half shell at edge). *1 dc into centre tr of next shell, 5 tr (shell) into next dc.* Repeat to last shell. 1 dc into centre tr of last shell. 3 tr into last dc (half shell at edge). Turn.')),
      h2('Row 2 (wrong side)'),
      p(t('Ch 1. 1 dc into first tr. *5 tr (shell) into next dc, 1 dc into centre tr of next shell.* Repeat across. End with 1 dc into top of turning ch. Turn.')),
      p(t('Repeat Rows 1 and 2 until the shawl measures 180 cm. Fasten off and weave in all ends.')),
      h2('Border'),
      p(t('Work one row of dc (UK) along each short end: pick up one dc per row end, working into the side of each row. Fasten off. This gives the short ends a firm, even edge.')),
      h2('Care'),
      p(t('Follow the yarn label. Most DK wool-acrylic blends are machine washable on a gentle 30-degree cycle. Lay flat to dry to preserve the shell shapes. Do not tumble dry.')),
      trouble('Common problems', 'Shell lace shawls have a few straightforward issues.', [
        { symptom: 'Shell count drifting across rows', cause: 'Not working into the correct anchor points', fix: 'The dc always goes into the centre (3rd) treble of the shell below. The shell always goes into the dc between two shells. Count 5 trebles per shell before moving to the next dc.' },
        { symptom: 'Edges flaring outward', cause: 'Half shells at the edges not counted correctly', fix: 'The half shells at each end (3 tr into the edge stitch) replace a full shell at the corner. If you see the fabric widening, remove the extra trebles from the edge half shells.' },
        { symptom: 'Row ends looking uneven', cause: 'Turning chain height not matching shell', fix: 'The ch-3 turning chain counts as the first treble. Work 2 tr more into the same base stitch to complete the edge half shell and match the height of the shells across the row.' },
      ]),
    ],
  },
},

// ── L29 ── beach-cover-shawl-crochet ────────────────────────────────────────
{
  slug: 'beach-cover-shawl-crochet',
  title: 'Beach cover shawl',
  subtitle: 'A large open-mesh rectangle in cotton sport weight for beach and poolside.',
  excerpt: 'A wide mesh rectangle in sport weight cotton doubles as a shawl, beach blanket, and pool cover-up. The open mesh dries fast and the generous 200 x 90 cm size wraps comfortably. One simple stitch repeat all the way through.',
  difficulty: 'BEGINNER',
  primaryYarnWeightSlug: 'sport',
  primaryHookSlug: 'crochet-hook-4-0mm',
  gaugeText: '12 mesh sts x 8 rows = 10 x 10 cm in cotton sport weight with a 4 mm hook.',
  finishedSizeText: 'Rectangle, 200 cm x 90 cm, unblocked.',
  techniqueSlugs: ['crochet-chain-space-mesh', 'crochet-working-back-and-forth', 'crochet-border-edging'],
  criticalTechniques: ['crochet-chain-space-mesh'],
  aliases: ['beach throw crochet', 'cotton mesh shawl', 'sarong crochet', 'pool cover-up crochet'],
  glossaryTerms: [
    { slug: 'open-mesh', term: 'Open mesh', definition: 'A repeating grid of chains and single stitches that creates an open fabric with large, regular holes.' },
    { slug: 'foundation-chain', term: 'Foundation chain', definition: 'The initial row of chains from which the rest of the piece is worked, setting the width of a flat crochet piece.' },
    { slug: 'border-dc', term: 'Border dc', definition: 'A final row of double crochet worked around the perimeter of a piece to give the edges a firm, even finish.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Open mesh crochet in cotton for beach and summer use has been a popular pattern category since the mid-20th century in both American and British pattern magazines. This version is original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('A beach cover shawl is a 200 x 90 cm rectangle of '), gt('open-mesh', 'open mesh'), t(' worked in cotton sport weight on a 4 mm hook. Cotton dries fast and the large holes in the mesh mean even less fabric to hold water. The piece is light enough to fold into a beach bag.')),
      p(t('The whole pattern is one stitch repeat: one treble, two chains, skip two stitches. That is the entire fabric, worked back and forth across 200 rows until the rectangle is 90 cm wide. A '), gt('border-dc', 'border dc'), t(' round at the end gives the perimeter a firm edge.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Sport weight cotton yarn', qty: '500 g', substitutions: 'Any smooth sport or DK cotton works. Mercerised cotton dries fastest.' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Measuring tape', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('12 mesh sts x 8 rows = 10 x 10 cm in cotton sport weight with a 4 mm hook. At 12 mesh stitches per 10 cm, the 200 cm length needs 240 stitches across the '), gt('foundation-chain', 'foundation chain'), t('. Each mesh square is (1 tr, ch 2, skip 2), so 80 mesh squares x 3 sts each = 240 sts, plus a 5-ch setup = ch 245 to start.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK): treble')),
        li(gt('open-mesh', 'Mesh square'), t(': 1 tr, ch 2, skip 2, repeat')),
      ),
      h2('Foundation chain'),
      p(t('Ch 245. Row 1 (wrong side): 1 tr into 6th ch from hook (first mesh square). *Ch 2, skip 2 ch, 1 tr into next ch.* Repeat to end. Turn. (80 mesh squares, 200 cm.)')),
      h2('Row 2 onwards'),
      p(t('Ch 5 (counts as 1 tr, ch 2). 1 tr into first tr of previous row. *Ch 2, 1 tr into next tr.* Repeat across, ending 1 tr into the 3rd ch of the turning ch. Turn.')),
      p(t('The row 2 pattern is the entire fabric. Work the same row until the piece measures 90 cm from the foundation row. At 8 rows per 10 cm, this is 72 rows.')),
      h2('Border'),
      p(t('Work one round of '), gt('border-dc', 'dc border'), t(' around all four sides: 1 dc into each tr and 2 dc into each ch-2 space along the long edges, and 1 dc into each row end along the short edges. Work 2 dc into each corner. Join with sl st and fasten off.')),
      h2('Care'),
      p(t('Rinse in fresh water after beach or pool use. Wring gently and hang to dry or lay flat. The open mesh dries in under an hour in sun and wind. Machine wash on a gentle cold cycle.')),
      trouble('Common problems', 'Mesh beach shawls have simple, practical fixes.', [
        { symptom: 'Stitch count drifting after several rows', cause: 'Skipping the turning chain as a stitch', fix: 'The ch-5 at the start of each row is 1 tr plus a ch-2 space. Count it as the first mesh square. The final tr of the row goes into the 3rd chain of the previous row\'s ch-5, not into the first tr.' },
        { symptom: 'Rectangle not rectangular', cause: 'Foundation chain too tight', fix: 'Work the foundation chain on a hook one size larger, then swap to the 4 mm for the mesh rows. A tight foundation causes the bottom edge to pull in.' },
        { symptom: 'Yarn running out before the width is reached', cause: 'Underestimating cotton yardage', fix: 'Cotton is heavier than wool at the same weight label. Weigh the yarn rather than relying on the label length. Each 100 g ball of sport cotton covers approximately 18 rows at 200 cm width.' },
      ]),
    ],
  },
},

// ── L30 ── heirloom-lace-shawl-crochet ──────────────────────────────────────
{
  slug: 'heirloom-lace-shawl-crochet',
  title: 'Heirloom lace shawl',
  subtitle: 'A fine lace weight shawl in shell and picot lace, advanced skill level.',
  excerpt: 'This heirloom shawl combines deep shell fans with picot arches and a six-row lace border to create a piece that can be passed down. Worked in lace weight on a 3.5 mm hook, the finished shawl is 180 cm wingspan and 85 cm deep at centre back.',
  difficulty: 'ADVANCED',
  primaryYarnWeightSlug: 'lace',
  primaryHookSlug: 'crochet-hook-3-5mm',
  gaugeText: '1 shell fan (7 tr) + picot arch = 5 cm wide in lace weight with a 3.5 mm hook, blocked.',
  finishedSizeText: 'Triangular shawl, 180 cm wingspan x 85 cm deep at centre back, blocked.',
  techniqueSlugs: ['crochet-shell-fan', 'crochet-picot-arch', 'crochet-heirloom-lace-border', 'crochet-triangular-shaping', 'crochet-blocking'],
  criticalTechniques: ['crochet-shell-fan', 'crochet-picot-arch', 'crochet-heirloom-lace-border', 'crochet-blocking'],
  aliases: ['heirloom shawl crochet', 'fine lace shawl crochet', 'shell picot shawl crochet', 'advanced lace shawl crochet'],
  glossaryTerms: [
    { slug: 'shell-fan', term: 'Shell fan', definition: 'A large shell of seven or more trebles worked into a single stitch or chain space, spreading into a wide arc that dominates the lace fabric design.' },
    { slug: 'picot-arch', term: 'Picot arch', definition: 'An arch of chains that includes a picot: a three-chain loop joined at its base with a slip stitch, adding a decorative point to the arch.' },
    { slug: 'lace-border', term: 'Lace border', definition: 'A separately worked or attached edging of several rows, usually more detailed than the body pattern, that finishes the outer edge of a lace shawl.' },
    { slug: 'blocking', term: 'Blocking', definition: 'Wet-blocking with pins to open fine lace to its full dimensions and set the fan and picot shapes permanently.' },
    { slug: 'spine', term: 'Spine', definition: 'The central increase column running down the centre back of a top-down triangular shawl.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Shell and picot lace is one of the most enduring crochet traditions, documented in Irish crochet sources from the 1890s and in Weldon\'s Practical Needlework. Heirloom-quality lace shawls with detailed borders are well represented in early 20th-century pattern booklets (Internet Archive). This construction and border are original to Homemade.',
  body: {
    type: 'doc',
    content: [
      p(t('An heirloom lace shawl is the most refined piece in the lacework collection. The body is a repeating column of seven-treble '), gt('shell-fan', 'shell fans'), t(' separated by '), gt('picot-arch', 'picot arches'), t('. The border is six additional rows of increasing complexity, finishing with a deep scalloped '), gt('lace-border', 'lace border'), t(' along the lower triangle edge. Worked in lace weight on a 3.5 mm hook and fully '), gt('blocking', 'blocked'), t(', the shawl reaches 180 cm wingspan and 85 cm deep at the '), gt('spine', 'spine'), t('.')),
      p(t('This is an advanced pattern. Each body row has multiple stitch types in a fixed sequence and the border chart requires reading a six-row repeat without losing position. Set aside uninterrupted time for the border rows.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Lace weight yarn', qty: '500 g', substitutions: 'A fine merino or merino-silk lace weight takes blocking beautifully. Avoid very springy yarns as the fans compress back after pinning.' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and T-pins', qty: '1 set' },
        { name: 'Measuring tape', qty: '1' },
        { name: 'Stitch markers', qty: '6' },
      ]),
      h2('Gauge'),
      p(t('1 shell fan (7 tr) + picot arch = 5 cm wide in lace weight with a 3.5 mm hook, blocked. Work one full body repeat swatch and block it before starting. The fan width determines the total wingspan at full stitch count. An unblocked fan is only 3.5 cm; blocking opens it to the full 5 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('dc (UK): double crochet')),
        li(t('tr (UK): treble')),
        li(t('dtr (UK): double treble, two yarn-overs before inserting hook')),
        li(gt('shell-fan', 'Shell fan'), t(': 7 tr into same space')),
        li(gt('picot-arch', 'Picot arch'), t(': ch 4, picot (ch 3, sl st into base ch), ch 4')),
      ),
      h2('Foundation'),
      p(t('Ch 7. Work (3 tr, ch 3, 4 tr) into 7th ch from hook (first shell fan half at spine). Turn.')),
      h2('Body row: spine increase'),
      p(t('Ch 6. Work 1 dc into the 4th tr of the previous fan half. Work a '), gt('picot-arch', 'picot arch'), t(' (ch 4, ch 3 sl st to base, ch 4). Work 1 dc into the turning ch space. Work (3 tr, ch 3, 4 tr) into the ch-3 '), gt('spine', 'spine'), t(' space (spine increase fan). Work dc into turning ch of far side. Picot arch. Dc into 4th tr of the far fan half. Ch 6. 1 tr into the foundation base. Turn.')),
      h2('Pattern rows'),
      p(t('Each row grows by one shell fan on each side. The sequence for every row is: ch-6 edge arch, dc into far fan tr, picot arch, dc into ch-3 space between fans, *7-tr shell fan into dc position, dc into ch-3 space, picot arch, dc, picot arch, dc*, repeat to spine, spine fan (7 tr, ch 3, 7 tr), mirror back to right edge, ch-6 arch at right. Turn.')),
      p(t('Continue working until the body measures 70 cm deep from the spine, measured straight down the centre back line. At this point work one plain dc row across the bottom edge to set the border start.')),
      h2('Six-row heirloom border'),
      p(t('Row B1: Dc across the full bottom edge, 1 dc per stitch and 2 dc into each chain space. Turn.')),
      p(t('Row B2: Ch 5. *Skip 2 dc, 1 tr into next, ch 2*. Repeat across. Turn. (Open mesh row.)')),
      p(t('Row B3: Sl st into first ch-2 space. *7 tr into next space (shell fan), ch 3, dc into next space, ch 3.* Repeat across. Turn. ('), gt('shell-fan', 'Shell fan'), t(' row.)')),
      p(t('Row B4: Dc into first tr. *Ch 3, picot (ch 3, sl st to base), ch 3, 1 dc into 4th tr of fan, ch 3, picot, ch 3, 1 dc into ch-3 arch.* Repeat across. Turn. ('), gt('picot-arch', 'Picot arch'), t(' row.)')),
      p(t('Row B5: Work one row of plain dc, placing 1 dc per stitch and 3 dc into each picot loop. Turn.')),
      p(t('Row B6 (final '), gt('lace-border', 'lace border'), t('): Ch 1. *1 dc into dc, ch 3, picot, ch 3, skip 2 dc.* Repeat across. Fasten off.')),
      h2('Blocking'),
      p(t('Soak the shawl for 30 minutes, press out excess water in a towel, and pin aggressively. Pin each border scallop point separately using T-pins. Pin the wingspan corners first to 180 cm apart, then the centre spine point to 85 cm. Fill all border scallops between. Leave 24 hours to dry. '), gt('blocking', 'Blocking'), t(' transforms the shawl: every shell fan opens, every picot stands clear, and the border scallops sharp.')),
      trouble('Common problems', 'Heirloom lace shawls have exacting standards and specific failure points.', [
        { symptom: 'Shell fans collapsing', cause: 'Not working into the correct dc between fans', fix: 'The 7-tr fan must go into a single dc stitch, not into a chain space. Mark every dc position with a removable marker before working the fan row.' },
        { symptom: 'Picot arches uneven in size', cause: 'Inconsistent chain tension on the ch-4 on either side of the picot', fix: 'Work all ch-4 arches over a size 4 knitting needle and remove it before the next stitch. Consistent chain size is critical to even scallops in the border.' },
        { symptom: 'Border pulling the shawl', cause: 'Border worked too tight against the body', fix: 'Work the dc pick-up row (B1) on a hook one size larger. A loose pick-up row is the foundation for the border and must not compress the body edge.' },
      ]),
    ],
  },
},

] // end PATTERNS

// ── Write JSON files ──────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle ?? '',
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'lacework',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.primaryYarnWeightSlug,
      primaryHookSlug: pat.primaryHookSlug,
      gaugeText: pat.gaugeText,
      finishedSizeText: pat.finishedSizeText,
      terminologyConvention: 'uk',
      craftStitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: [
      { slug: 'crochet-hook', isOptional: false },
      { slug: 'tapestry-needle', isOptional: false },
      { slug: 'craft-scissors', isOptional: false },
      { slug: 'measuring-tape-soft', isOptional: false },
    ],
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`wrote ${pat.slug}.json`)
}
console.log('Done.')
