/**
 * Generator: D-Garments Batch 19 -- Granny square garments G181-G190
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-garments-batch19.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-garments')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [
  {
    slug: 'granny-square-pullover-crochet',
    title: 'Granny square pullover',
    excerpt: 'A classic pullover assembled entirely from 15 cm granny squares. Each square is worked separately then joined with slip stitch seams. The square count determines the fit. Graded XS to 2XL.',
    difficulty: 'INTERMEDIATE',
    yarnWeight: 'aran',
    hook: 'crochet-hook-5-0mm',
    gaugeText: 'Each granny square measures 15 x 15 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
    aliases: ['granny square jumper crochet', 'granny square sweater', 'patchwork pullover crochet'],
    glossaryTerms: [
      { slug: 'granny-sq-g181', term: 'Granny square', definition: 'A classic motif worked in rounds from a centre ring. Each round adds a shell of dc or treble clusters at the corners and along each side, building a flat square.' },
      { slug: 'flat-join-g181', term: 'Flat join', definition: 'A method of joining finished motifs by placing them wrong sides together and working a slip stitch through both outer loops along the shared edge. The result is a flat visible seam on the right side.' },
      { slug: 'blocking-g181', term: 'Blocking', definition: 'Wetting or steaming a finished piece and pinning it to measurements while it dries. Granny squares block reliably and all four corners sharpen to 90 degrees.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Granny square garments are a long-established technique in crochet. Construction logic is standard.',
    body: {
      type: 'doc', content: [
        p(t('This pullover is built entirely from '), gt('granny-sq-g181', 'granny squares'), t('. Each square is worked separately, '), gt('blocking-g181', 'blocked'), t(' flat, then joined with a '), gt('flat-join-g181', 'flat join'), t('.')),
        p(t('The finished garment has a relaxed drop-shoulder fit. Size comes from how many squares you use in each panel, not from row-count adjustments.')),
        h2('Square count guide'),
        p(t('Each square is 15 cm. At size M, the front and back panels are each 4 squares wide and 4 squares tall (60 x 60 cm). Each sleeve is 3 squares wide and 4 squares tall (45 x 60 cm). Total squares needed at size M: 56.')),
        p(t('To go up or down a size, add or remove one square column from both front and back panels. XS: 3 wide x 4 tall per body panel. S: 3 wide x 4 tall. M: 4 wide x 4 tall. L: 4 wide x 4 tall with one border square added at each side. XL: 5 wide x 4 tall. 2XL: 5 wide x 4 tall with one border square added at each side.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'Aran yarn', qty: '900 yards' },
          { name: '5 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
          { name: 'Rust-proof pins for blocking', qty: '20 or more' },
        ]),
        h2('Making each square'),
        p(t('Round 1: Magic ring, ch 3 (counts as first tr), 2 tr into ring, ch 2, [3 tr, ch 2] three times. Join with sl st.')),
        p(t('Round 2: Sl st to corner ch-2 sp, ch 3, 2 tr in same sp, ch 1, [3 tr, ch 2, 3 tr] in next corner sp, ch 1. Repeat around. Join.')),
        p(t('Round 3: Sl st to corner sp, ch 3, 2 tr in same sp, ch 1, 3 tr in ch-1 sp, ch 1, [3 tr, ch 2, 3 tr] in corner sp. Repeat around. Join and fasten off.')),
        h2('Assembly'),
        p(t('Block every square before assembly. Lay out the front panel squares in a grid and join each pair of adjacent edges with a flat join, working row by row. Join the back panel the same way. Sew shoulder seams. Attach sleeve panels at the armhole edges, then seam sleeve and side edges from hem to cuff.')),
        h2('Neckline finish'),
        p(t('Work one round of dc around the neck opening to neaten the edge. Fasten off and weave in ends.')),
        h2('What to try next'),
        p(t('The granny square cardigan uses the same square and the same join. The only difference is the front panels are left open and finished with a dc border.')),
      ],
    },
  },
  {
    slug: 'granny-square-cardigan-crochet',
    title: 'Granny square cardigan',
    excerpt: 'An open-front cardigan built from 15 cm granny squares seamed together. The front edges are finished with a simple dc border. Graded XS to 2XL.',
    difficulty: 'INTERMEDIATE',
    yarnWeight: 'aran',
    hook: 'crochet-hook-5-0mm',
    gaugeText: 'Each granny square measures 15 x 15 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
    aliases: ['granny square jacket crochet', 'patchwork cardigan crochet', 'open front granny crochet'],
    glossaryTerms: [
      { slug: 'granny-sq-g182', term: 'Granny square', definition: 'A classic motif worked in rounds from a centre ring. Clusters of treble stitches sit at each corner and along each side, building a flat square.' },
      { slug: 'flat-join-g182', term: 'Flat join', definition: 'Placing two finished squares wrong sides together and working a slip stitch through both outer loops along the shared edge. Creates a visible raised seam on the right side.' },
      { slug: 'dc-border-g182', term: 'dc border', definition: 'One or more rounds of double crochet worked around the full outer edge of the finished cardigan to neaten and stabilise all open edges including the front bands.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Granny square cardigans are a popular project for using up yarn. Construction method is standard.',
    body: {
      type: 'doc', content: [
        p(t('This cardigan uses the same '), gt('granny-sq-g182', 'granny square'), t(' as the pullover, assembled with a '), gt('flat-join-g182', 'flat join'), t(' and finished with a '), gt('dc-border-g182', 'dc border'), t(' along the full front opening.')),
        p(t('The left and right front panels each run from shoulder to hem. There is no button band construction: the dc border provides all the edge finishing needed.')),
        h2('Square count guide'),
        p(t('At size M the back panel is 4 squares wide x 4 tall. Each front panel is 2 squares wide x 4 tall. Each sleeve is 3 squares wide x 4 tall. Total squares at size M: 52.')),
        p(t('Adjust width by adding or removing one square column per panel. Keep front and back column counts consistent so the shoulder seams align.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'Aran yarn', qty: '850 yards' },
          { name: '5 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
          { name: 'Rust-proof pins for blocking', qty: '20 or more' },
        ]),
        h2('Making the squares'),
        p(t('Work each granny square to 15 cm following the standard three-round construction: magic ring, four corner clusters with ch-2 spaces, two further rounds adding clusters along each side. Block every square flat before joining.')),
        h2('Assembly order'),
        p(t('Join back panel squares in a grid. Join each front panel separately. Seam back to fronts at shoulders. Attach sleeve panels at the armhole edges. Seam side and sleeve edges.')),
        h2('Border'),
        p(t('Starting at one lower front corner, work the dc border continuously around the lower hem, up the right front, around the neck, down the left front and along the hem. Work 3 dc into each outer corner to keep the corners flat. Fasten off.')),
        h2('What to try next'),
        p(t('The granny square vest drops the sleeves and shortens the body for a lighter layering piece.')),
      ],
    },
  },
  {
    slug: 'granny-square-vest-crochet',
    title: 'Granny square vest',
    excerpt: 'A sleeveless vest with front and back panels each made from a grid of 10 cm granny squares. Lightweight and adjustable by square count. Graded XS to 2XL.',
    difficulty: 'BEGINNER',
    yarnWeight: 'dk',
    hook: 'crochet-hook-4-0mm',
    gaugeText: 'Each granny square measures 10 x 10 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-double-uk'],
    aliases: ['granny square waistcoat crochet', 'patchwork vest crochet', 'crochet motif vest'],
    glossaryTerms: [
      { slug: 'granny-sq-g183', term: 'Granny square', definition: 'A motif worked in rounds from a centre ring. Treble clusters at the corners and along the sides build a flat square that measures consistently once blocked.' },
      { slug: 'join-as-you-go-g183', term: 'Join as you go', definition: 'A technique where the final round of each new square replaces the ch-2 corner space with a slip stitch into the corresponding corner of an already-finished square, attaching the two without a separate seaming step.' },
      { slug: 'armhole-edge-g183', term: 'Armhole edge', definition: 'The open side edges of a sleeveless vest left unjoined at the top of each panel to form the armhole. A round of dc is worked along this edge to stabilise it.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Granny square vests are a lightweight beginner-friendly project.',
    body: {
      type: 'doc', content: [
        p(t('Each panel of this vest is a grid of '), gt('granny-sq-g183', 'granny squares'), t('. Smaller 10 cm DK squares make a lighter fabric than aran squares. Squares can be joined after blocking or with '), gt('join-as-you-go-g183', 'join as you go'), t(' on the final round of each new square.')),
        h2('Square count guide'),
        p(t('At size M the front and back panels are each 6 squares wide x 5 squares tall (60 x 50 cm). Total squares at size M: 60.')),
        p(t('To adjust size, add or remove one column. XS: 5 wide x 5 tall per panel. S: 5 wide x 5 tall. M: 6 wide x 5 tall. L: 7 wide x 5 tall. XL: 8 wide x 5 tall. 2XL: 9 wide x 5 tall.')),
        p(t('Leave the top two squares of each outer column unjoined at the top edge to form the '), gt('armhole-edge-g183', 'armhole edges'), t('.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'DK yarn', qty: '550 yards' },
          { name: '4 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Assembly'),
        p(t('Join all squares into front and back grids. Seam the panels at both shoulder edges across the top two squares. Seam both side edges leaving the top 20 cm (two squares) open for armholes. Work one round of dc around each armhole edge and around the neckline.')),
        h2('What to try next'),
        p(t('The granny square top shortens the body further for a cropped style worn at hip length.')),
      ],
    },
  },
  {
    slug: 'granny-square-dress-crochet',
    title: 'Granny square dress',
    excerpt: 'A knee-length dress with a granny square bodice and a solid dc skirt worked in rounds from the hem of the bodice. Graded XS to 2XL.',
    difficulty: 'INTERMEDIATE',
    yarnWeight: 'dk',
    hook: 'crochet-hook-4-0mm',
    gaugeText: 'Each granny square measures 10 x 10 cm blocked. Skirt body: 18 dc x 20 rows = 10 x 10 cm.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
    aliases: ['granny square boho dress crochet', 'motif bodice dress crochet', 'patchwork dress crochet'],
    glossaryTerms: [
      { slug: 'granny-sq-g184', term: 'Granny square', definition: 'A motif worked in rounds from a centre ring. Each round adds treble clusters at the corners and along the sides.' },
      { slug: 'pickup-round-g184', term: 'Pick-up round', definition: 'A row or round of dc worked along the lower edge of a finished bodice section to establish a stitch count for the skirt. The number of stitches picked up determines the skirt width.' },
      { slug: 'skirt-flare-g184', term: 'Skirt flare', definition: 'Increases worked at regular intervals on the skirt rounds to add width toward the hem. A slight A-line flare is created by adding one dc every 10 stitches on every fifth round.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Granny square bodice with a worked skirt is a classic construction for crochet dresses.',
    body: {
      type: 'doc', content: [
        p(t('The bodice of this dress is a grid of '), gt('granny-sq-g184', 'granny squares'), t('. A '), gt('pickup-round-g184', 'pick-up round'), t(' of dc is worked along the lower edge of the assembled bodice, then the skirt is worked downward in rounds with optional '), gt('skirt-flare-g184', 'skirt flare'), t('.')),
        h2('Square count guide for bodice'),
        p(t('At size M the front and back bodice panels are each 6 squares wide x 3 squares tall (60 x 30 cm). Total squares for bodice at size M: 36.')),
        p(t('Adjust width by adding or removing one column per panel. Bodice depth is fixed at three squares (30 cm) for all sizes.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'DK yarn', qty: '700 yards' },
          { name: '4 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Bodice assembly'),
        p(t('Join squares into front and back grids. Seam shoulders and sides. Work one round of dc around the neckline and armhole edges.')),
        h2('Skirt'),
        p(t('Work a pick-up round along the lower bodice edge, placing one dc into each dc or ch space evenly around the full circumference. Join into a round and work dc downward for 45 cm, adding one dc every 10 sts on every fifth round for a gentle flare. Fasten off.')),
        h2('What to try next'),
        p(t('The granny square skirt uses the same pick-up-and-work-down method but attaches to an elasticated waistband instead of a bodice.')),
      ],
    },
  },
  {
    slug: 'granny-square-skirt-crochet',
    title: 'Granny square skirt',
    excerpt: 'A knee-length skirt made from a grid of granny squares joined edge to edge, finished with an elasticated waistband. Graded XS to 2XL.',
    difficulty: 'BEGINNER',
    yarnWeight: 'dk',
    hook: 'crochet-hook-4-0mm',
    gaugeText: 'Each granny square measures 10 x 10 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-treble'],
    aliases: ['granny square midi skirt crochet', 'patchwork skirt crochet', 'motif skirt crochet'],
    glossaryTerms: [
      { slug: 'granny-sq-g185', term: 'Granny square', definition: 'A motif worked in rounds from a centre ring. Treble clusters at the corners and along the sides build a flat square.' },
      { slug: 'elastic-waist-g185', term: 'Elasticated waistband', definition: 'A folded band of dc at the top edge of the skirt, sewn into a casing and threaded with elastic cut to waist measurement plus 5 cm overlap.' },
      { slug: 'square-grid-g185', term: 'Square grid', definition: 'The arrangement of joined granny squares into rows and columns that form the skirt body. Adjusting the number of columns changes the width; adjusting the number of rows changes the length.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Granny square skirts are a popular beginner granny square project.',
    body: {
      type: 'doc', content: [
        p(t('This skirt is a flat '), gt('square-grid-g185', 'square grid'), t(' of '), gt('granny-sq-g185', 'granny squares'), t(' joined edge to edge. The side seam closes the rectangle into a tube. An '), gt('elastic-waist-g185', 'elasticated waistband'), t(' finishes the top.')),
        h2('Square count guide'),
        p(t('Each square is 10 cm. At size M the skirt is 12 squares wide x 5 squares tall (120 x 50 cm, plus a 5 cm dc waistband). Total squares at size M: 60.')),
        p(t('To adjust hip size, add or remove squares from the width. XS: 9 wide x 5 tall. S: 10 wide x 5 tall. M: 12 wide x 5 tall. L: 13 wide x 5 tall. XL: 15 wide x 5 tall. 2XL: 16 wide x 5 tall. Adjust row count (tall number) to change length.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'DK yarn', qty: '500 yards' },
          { name: '4 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
          { name: 'Elastic, 2.5 cm wide', qty: 'waist + 5 cm' },
        ]),
        h2('Joining and seaming'),
        p(t('Join the square grid row by row. Seam the short side edges together to form the tube. Work five rows of dc along the top edge for the waistband. Fold in half and sew to form the elastic casing. Thread elastic and join.')),
        h2('What to try next'),
        p(t('The granny square top uses the same grid structure but at a shorter length for a crop top.')),
      ],
    },
  },
  {
    slug: 'granny-square-top-crochet',
    title: 'Granny square crop top',
    excerpt: 'A simple crop top made from four large granny squares: one for the front, one for the back, and one for each side panel. Graded XS to 2XL by square size.',
    difficulty: 'BEGINNER',
    yarnWeight: 'dk',
    hook: 'crochet-hook-4-0mm',
    gaugeText: 'Each large granny square measures approximately 30 x 30 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-treble'],
    aliases: ['four square top crochet', 'large granny square top crochet', 'motif crop top crochet'],
    glossaryTerms: [
      { slug: 'large-granny-g186', term: 'Large granny square', definition: 'A granny square worked to a large number of rounds. A seven-round granny square in DK on a 4 mm hook reaches approximately 30 cm square blocked.' },
      { slug: 'side-panel-g186', term: 'Side panel square', definition: 'The two squares that close the side edges of the top. Each side square is seamed to the adjacent edges of the front and back squares to form a closed tube at the body.' },
      { slug: 'shoulder-seam-g186', term: 'Shoulder seam', definition: 'The top edge of the front and back squares is joined for approximately 8 cm at each shoulder, leaving a central neck opening in between.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Four-square tops are a minimal-construction approach to granny square garments.',
    body: {
      type: 'doc', content: [
        p(t('This top uses four '), gt('large-granny-g186', 'large granny squares'), t(': one front, one back, and one '), gt('side-panel-g186', 'side panel square'), t(' on each side. There is almost no shaping involved, just four seams.')),
        p(t('Work each square to seven rounds in DK on a 4 mm hook. Blocked size is approximately 30 cm square. For a smaller top work fewer rounds; for a larger top work more rounds or use a heavier yarn.')),
        h2('Square count guide'),
        p(t('All sizes use exactly four squares. Size is controlled by the number of rounds per square. XS: 5-round squares (approx 22 cm). S: 6-round squares (approx 26 cm). M: 7-round squares (approx 30 cm). L: 8-round squares (approx 34 cm). XL: 9-round squares (approx 38 cm). 2XL: 10-round squares (approx 42 cm).')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'DK yarn', qty: '400 yards' },
          { name: '4 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Assembly'),
        p(t('Block all four squares. Join the front and back squares at each shoulder edge for 8 cm, leaving the centre open as the neck. Seam each side square between the front and back squares at the side edges. Work one round of dc around the armhole openings and neckline.')),
        h2('What to try next'),
        p(t('The granny square vest adds more squares and leaves larger armhole openings for a fuller sleeveless layer.')),
      ],
    },
  },
  {
    slug: 'granny-square-shrug-crochet',
    title: 'Granny square shrug',
    excerpt: 'A minimal shrug made from two large granny squares seamed at the side edges. The open back and wide armholes give a relaxed wrap-style fit. Graded XS to 2XL by square size.',
    difficulty: 'BEGINNER',
    yarnWeight: 'aran',
    hook: 'crochet-hook-5-0mm',
    gaugeText: 'Each large granny square measures approximately 35 x 35 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-treble'],
    aliases: ['two square shrug crochet', 'large motif shrug crochet', 'open back shrug crochet'],
    glossaryTerms: [
      { slug: 'large-sq-g187', term: 'Large granny square', definition: 'A granny square worked through many rounds. In aran on a 5 mm hook, an eight-round granny square reaches approximately 35 cm square.' },
      { slug: 'side-seam-g187', term: 'Side seam', definition: 'The seam joining the two squares along one pair of matching edges. The seam length determines the sleeve length. Leaving the remaining edge open forms the armhole.' },
      { slug: 'dc-cuff-g187', term: 'dc cuff', definition: 'One or two rounds of dc worked around the lower sleeve opening after the side seams are closed. The cuff stabilises the sleeve edge and gives a neater finish.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Two-square shrugs are a well-known minimal construction in granny square garments.',
    body: {
      type: 'doc', content: [
        p(t('Two '), gt('large-sq-g187', 'large granny squares'), t(' are all that is needed for this shrug. Lay the two squares side by side. Join each pair of adjacent edges along the '), gt('side-seam-g187', 'side seam'), t(' for approximately 15 cm from each outer corner, leaving the central section open as a wide back and armholes.')),
        p(t('Work a '), gt('dc-cuff-g187', 'dc cuff'), t(' along each sleeve opening and a round of dc around the full centre back edge to finish.')),
        h2('Square count guide'),
        p(t('All sizes use two squares. Size is controlled by the number of rounds per square. XS: 7-round squares (approx 30 cm). S: 7 rounds. M: 8-round squares (approx 35 cm). L: 9 rounds (approx 39 cm). XL: 10 rounds (approx 43 cm). 2XL: 11 rounds (approx 47 cm). Side seam length is always one third of the square edge length.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'Aran yarn', qty: '400 yards' },
          { name: '5 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Assembly'),
        p(t('Block both squares. Lay them with right sides facing up and one long edge of each touching. Work a slip stitch seam from each outer corner inward for the side seam length. Leave the remaining central section open. Repeat on the other long edge. Work dc around sleeve openings and the back edge.')),
        h2('What to try next'),
        p(t('The granny square poncho uses two larger rectangular panels seamed at the shoulder for a fuller wrap.')),
      ],
    },
  },
  {
    slug: 'granny-square-coat-crochet',
    title: 'Granny square coat',
    excerpt: 'A long statement coat worked in chunky yarn from large 20 cm granny squares. Front, back, and sleeves are all assembled from square panels. Graded XS to 2XL.',
    difficulty: 'ADVANCED',
    yarnWeight: 'chunky',
    hook: 'crochet-hook-6-0mm',
    gaugeText: 'Each granny square measures 20 x 20 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
    aliases: ['granny square long coat crochet', 'chunky patchwork coat crochet', 'statement granny coat crochet'],
    glossaryTerms: [
      { slug: 'chunky-granny-g188', term: 'Chunky granny square', definition: 'A granny square worked in chunky weight yarn on a 6 mm hook. The thicker yarn produces a denser, warmer fabric with a bold visible stitch texture.' },
      { slug: 'coat-front-panel-g188', term: 'Coat front panel', definition: 'Two separate panels, one for each side of the coat front. Each panel is two squares wide and five squares tall, leaving the centre front open for the coat opening.' },
      { slug: 'collar-g188', term: 'Collar', definition: 'A wide band of dc or a single rectangle of granny squares attached along the upper back and front neck edges to frame the face.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Granny square coats are a statement project using chunky yarn for warmth and impact.',
    body: {
      type: 'doc', content: [
        p(t('This coat uses '), gt('chunky-granny-g188', 'chunky granny squares'), t(' at 20 cm each. The garment is long enough to reach mid-thigh. Each '), gt('coat-front-panel-g188', 'coat front panel'), t(' and the back panel are assembled from square grids. A simple '), gt('collar-g188', 'collar'), t(' finishes the neckline.')),
        h2('Square count guide'),
        p(t('Each square is 20 cm. At size M the back panel is 3 squares wide x 5 squares tall (60 x 100 cm). Each front panel is 2 squares wide x 5 squares tall (40 x 100 cm). Each sleeve is 2 squares wide x 3 squares tall (40 x 60 cm). Total squares at size M: 49.')),
        p(t('Adjust width by adding one square column per panel for each size step. XS: back 2 wide, fronts 1 wide each. S: back 3 wide, fronts 2 wide each. M: as above. L: back 4 wide, fronts 2 wide each. XL: back 4 wide, fronts 3 wide each. 2XL: back 5 wide, fronts 3 wide each.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'Chunky yarn', qty: '1,800 yards' },
          { name: '6 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Assembly'),
        p(t('Block all squares. Join back panel, left front panel, and right front panel each as separate grids. Seam fronts to back at shoulders. Attach sleeve panels at the armhole edges. Seam sleeve and side edges. Work a dc border along the full front opening, hem, and collar.')),
        h2('What to try next'),
        p(t('The granny square pullover uses smaller squares and a closed front for a lighter everyday garment.')),
      ],
    },
  },
  {
    slug: 'granny-hex-pullover-crochet',
    title: 'Hexagon motif pullover',
    excerpt: 'A pullover assembled from hexagonal motifs joined as you go in DK yarn. The hex grid fills the body and sleeves with no half-motif filler pieces at the seams. Graded XS to 2XL.',
    difficulty: 'ADVANCED',
    yarnWeight: 'dk',
    hook: 'crochet-hook-4-0mm',
    gaugeText: 'Each hexagon motif measures 8 cm point to point blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
    aliases: ['hex motif pullover crochet', 'hexagon sweater crochet', 'join as you go hex sweater'],
    glossaryTerms: [
      { slug: 'hex-motif-g189', term: 'Hexagon motif', definition: 'A six-sided crochet motif worked in rounds from a centre ring. Each round extends the shape outward and ends with six equal sides.' },
      { slug: 'jayg-g189', term: 'Join as you go', definition: 'On the final round of each new hexagon, slip stitch into the corresponding edge of an already-finished neighbour instead of working a ch-2 space. This joins the two motifs in the same pass as completing the new one.' },
      { slug: 'half-hex-g189', term: 'Half hexagon', definition: 'A hexagon worked to the midpoint then folded in half to fill the stepped edge of a hex grid at the hem and cuff lines. Half hexagons create a straight lower edge.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Hexagon motif pullovers are a classic advanced crochet construction.',
    body: {
      type: 'doc', content: [
        p(t('This pullover uses '), gt('hex-motif-g189', 'hexagon motifs'), t(' joined with '), gt('jayg-g189', 'join as you go'), t(' on the final round of each new hex. A row of '), gt('half-hex-g189', 'half hexagons'), t(' fills the stepped lower edge of each panel to create a straight hem and cuff.')),
        p(t('Each hex is 8 cm point to point. The hex grid is planned on paper before starting so the column and row counts sit correctly for each size.')),
        h2('Motif count guide'),
        p(t('At size M the front and back panels each use approximately 56 full hexagons (8 columns x 7 rows) plus 8 half hexagons along the hem. Each sleeve uses approximately 28 full hexagons plus 4 half hexagons. Total motifs at size M: approximately 160 full and 20 half hexagons.')),
        p(t('Increase or decrease the number of columns per panel to adjust width. Add or remove rows to adjust length.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'DK yarn (main colour)', qty: '700 yards' },
          { name: 'DK yarn (contrast)', qty: '200 yards' },
          { name: '4 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Working the hex grid'),
        p(t('Work the first row of hexagons separately. On each subsequent row, join each new hexagon to its neighbours on the final round using join as you go. Work back-to-front panels separately then seam at shoulder and sides. Attach sleeve panels at the armholes and seam sleeve edges.')),
        h2('Finishing'),
        p(t('Work one round of dc around the neckline, picking up one dc per edge segment of each hex at the neck opening. Fasten off and weave in all ends.')),
        h2('What to try next'),
        p(t('The granny square pullover uses square motifs with the same join-as-you-go logic for a simpler motif shape.')),
      ],
    },
  },
  {
    slug: 'granny-square-poncho-with-fringe',
    title: 'Granny square poncho with fringe',
    excerpt: 'A two-panel poncho assembled from classic granny squares and finished with a yarn fringe along the hem. Two rectangular panels are seamed at the shoulder. Graded XS to 2XL.',
    difficulty: 'BEGINNER',
    yarnWeight: 'aran',
    hook: 'crochet-hook-5-0mm',
    gaugeText: 'Each granny square measures 15 x 15 cm blocked.',
    finishedSizeText: 'XS to 2XL. Size M: adjust square count as noted in pattern.',
    stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch'],
    techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
    criticalTechniques: ['crochet-treble'],
    aliases: ['granny square poncho crochet', 'fringed poncho crochet', 'two panel poncho crochet'],
    glossaryTerms: [
      { slug: 'granny-sq-g190', term: 'Granny square', definition: 'A classic motif worked in rounds from a centre ring. Treble clusters at the corners and along the sides build a flat square, consistent across all rounds.' },
      { slug: 'shoulder-seam-g190', term: 'Shoulder seam', definition: 'The short seam joining each panel at the centre top edge. For a poncho, each panel is laid flat and the two panels are seamed at the top edge, leaving a neck opening in the centre.' },
      { slug: 'fringe-g190', term: 'Fringe', definition: 'Lengths of yarn folded in half, looped through the edge stitch of the hem, and pulled tight to form a hanging tassel. Each fringe group uses two to four strands cut to double the desired fringe length.' },
    ],
    sourceType: 'SYNTHESISED',
    sourceNotes: 'Poncho construction from two panels is a beginner-friendly granny square project.',
    body: {
      type: 'doc', content: [
        p(t('This poncho is two rectangular panels of '), gt('granny-sq-g190', 'granny squares'), t(' seamed at the '), gt('shoulder-seam-g190', 'shoulder seam'), t('. A '), gt('fringe-g190', 'fringe'), t(' of cut yarn is knotted along the lower hem edge of each panel.')),
        h2('Panel and square count guide'),
        p(t('Each panel is a rectangle 4 squares wide x 6 squares tall (60 x 90 cm). At size M, the two panels together give a total of 48 squares.')),
        p(t('To adjust width, add or remove one square from the width of both panels. XS: 3 wide x 6 tall per panel. S: 3 wide x 6 tall. M: 4 wide x 6 tall. L: 5 wide x 6 tall. XL: 5 wide x 6 tall. 2XL: 6 wide x 6 tall.')),
        h2('What you need'),
        supplies('Materials (size M)', [
          { name: 'Aran yarn', qty: '900 yards (includes fringe)' },
          { name: '5 mm crochet hook', qty: '1' },
          { name: 'Tapestry needle', qty: '1' },
          { name: 'Scissors', qty: '1 pair' },
        ]),
        h2('Assembly'),
        p(t('Join squares into two rectangular panels. Place both panels right sides together with the long edges aligned. Seam the top 20 cm at each end of the top edge, leaving a 20 cm neck opening in the centre. Turn right sides out.')),
        h2('Adding the fringe'),
        p(t('Cut yarn into 40 cm lengths. Working along both short hem edges, fold two strands in half, insert the loop through an edge stitch, draw the tails through the loop and pull snug. Space fringes every second stitch across each hem edge. Trim the fringe tails to an even length.')),
        h2('What to try next'),
        p(t('The granny square shrug uses a similar two-square construction but seams along the long side edges to close the sleeves.')),
      ],
    },
  },
]

for (const pat of PATTERNS) {
  const {
    slug, excerpt, difficulty, yarnWeight, hook, gaugeText, finishedSizeText,
    stitchSlugs, techniqueSlugs, criticalTechniques, aliases, glossaryTerms,
    sourceType, sourceNotes, body,
  } = pat

  const title = pat.title

  const out = {
    slug,
    title,
    subtitle: '',
    excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'garments',
    difficulty,
    sourceType,
    sourceNotes,
    techniqueSlugs,
    criticalTechniques,
    aliases,
    glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: yarnWeight,
      primaryHookSlug: hook,
      gaugeText,
      finishedSizeText,
      terminologyConvention: 'uk',
      craftStitchSlugs: stitchSlugs,
      craftTechniqueTags: techniqueSlugs,
    },
    recipeTools: TOOLS,
    body,
  }

  writeFileSync(join(OUT, `${slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${slug}.json`)
}

console.log('Done.')
