/**
 * Generator: D-Homewares Batch 9 -- Cushions and pillows 1-15
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch9.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── C1 ── granny square cushion ───────────────────────────────────────────────
{
  slug: 'granny-square-cushion-cover',
  title: 'Granny square cushion cover',
  subtitle: 'A 40 cm square cushion cover made from a single large granny square on each side.',
  excerpt: 'Two large granny squares seamed together form this classic 40 cm cushion cover. Use two contrasting DK colours for a bold geometric look.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 large granny square = 40 x 40 cm using DK yarn on a 4 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-slip-stitch', 'crochet-double-uk', 'crochet-granny-cluster', 'crochet-whipstitch-join'],
  techniqueSlugs: ['crochet-granny-cluster', 'crochet-double-uk', 'crochet-whipstitch-join'],
  criticalTechniques: ['crochet-granny-cluster'],
  aliases: ['granny square cushion', 'granny cushion cover', 'crochet cushion cover'],
  glossaryTerms: [
    { slug: 'granny-cluster-cushion', term: 'Granny cluster', definition: 'Three trebles worked into the same space with a chain gap between groups. The repeating unit of a granny square.' },
    { slug: 'whipstitch-cushion', term: 'Whipstitch join', definition: 'A seaming method that passes yarn through edge stitches at the front, creating a visible ridge. Neat and fast for joining cushion panels.' },
    { slug: 'colour-change-cushion', term: 'Colour change', definition: 'Switching yarn at the end of a round by drawing the new colour through the final slip stitch.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Granny square cushion covers are a well-established modern crochet project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('This cushion cover uses two large '), gt('granny-cluster-cushion', 'granny cluster'), t(' squares, each grown to 40 cm. Work one square per side, then join them with a '), gt('whipstitch-cushion', 'whipstitch join'), t(' on three edges. Insert a 40 cm pad and seam the last edge.')),
      p(t('DK yarn gives a lightweight, washable cover suitable for sofas or bedrooms. Plan around 200 m of main colour and 50 m of contrast per side.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, main colour', qty: '400 m' },
        { name: 'DK yarn, contrast colour', qty: '100 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Square (make 2)'),
      p(t('Round 1: chain 4, slip stitch to join, work 3 '), gt('granny-cluster-cushion', 'granny clusters'), t(' with ch-2 corner spaces. Continue working rounds, adding one cluster per side per round. At '), gt('colour-change-cushion', 'colour change'), t(' rounds, fasten off and join new colour at any corner.')),
      p(t('Continue until the square measures 40 cm. Each side should have the same number of cluster groups. Fasten off.')),
      h2('Assembly'),
      p(t('Place squares wrong sides together. Use '), gt('whipstitch-cushion', 'whipstitch join'), t(' along three sides. Insert cushion pad. Whipstitch the remaining side closed.')),
      h2('Finishing'),
      p(t('Weave in all ends securely. The cover can be removed for washing by undoing the last seam stitches.')),
      h2('What to try next'),
      p(t('The bobble textured cushion cover uses the same 40 cm square format. Or try the ripple pattern cushion for a striped design.')),
    ],
  },
},

// ── C2 ── bobble textured cushion ─────────────────────────────────────────────
{
  slug: 'bobble-textured-cushion-cover',
  title: 'Bobble textured cushion cover',
  subtitle: 'A 45 cm square cushion cover worked in rows of raised bobble stitches.',
  excerpt: 'Dense bobble rows give this 45 cm cushion cover a tactile, sculptural surface. Worked in one colour in aran weight for maximum texture.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 st x 16 rows = 10 x 10 cm in bobble pattern on a 5 mm hook.',
  finishedSize: '45 x 45 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-bobble'],
  techniqueSlugs: ['crochet-bobble', 'crochet-double-uk'],
  criticalTechniques: ['crochet-bobble'],
  aliases: ['bobble cushion cover', 'textured cushion crochet', 'bobble pillow cover'],
  glossaryTerms: [
    { slug: 'bobble-cushion', term: 'Bobble', definition: 'Five trebles worked into the same stitch and closed together at the top. Creates a rounded bump on the right side of the fabric.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'A chain worked at the end of a row before turning the work. Sets the height for the next row of stitches.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Bobble stitch cushion covers are a contemporary crochet project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Rows of '), gt('bobble-cushion', 'bobbles'), t(' alternate with plain double crochet rows across a 45 cm rectangle. Make two panels and seam them together, or work the front in bobble pattern and the back in plain double crochet to reduce yarn use.')),
      p(t('Aran weight yarn on a 5 mm hook gives a firm, structured fabric. Total yarn around 550 m. The '), gt('turning-chain', 'turning chain'), t(' counts as the first stitch on every row.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '550 m' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '45 cm cushion pad', qty: '1' },
      ]),
      h2('Front panel'),
      p(t('Chain 65. Row 1 (RS): dc across. Row 2 (WS): ch 3 (', ), gt('turning-chain', 'turning chain'), t('), '), gt('bobble-cushion', 'bobble'), t(' in first st, * dc, bobble; rep from * to last st, dc. Row 3: dc across. Repeat rows 2 and 3 until piece measures 45 cm. Fasten off.')),
      h2('Back panel'),
      p(t('Chain 65. Work dc rows until 45 cm. Fasten off.')),
      h2('Assembly'),
      p(t('Place panels wrong sides together. Whipstitch along three edges. Insert cushion pad. Whipstitch the remaining edge.')),
      h2('What to try next'),
      p(t('The puff stitch cushion gives a softer, rounder texture. Or try the cable effect cushion cover for a different raised pattern.')),
    ],
  },
},

// ── C3 ── striped floor cushion ───────────────────────────────────────────────
{
  slug: 'striped-floor-cushion',
  title: 'Striped floor cushion',
  subtitle: 'A large 60 cm round floor cushion crocheted in bold stripes.',
  excerpt: 'Two circular panels striped in three colours join to make a 60 cm round floor cushion. Worked in chunky yarn for a fast, weighty result.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '11 dc x 13 rounds = 10 x 10 cm in chunky on a 6 mm hook.',
  finishedSize: '60 cm diameter round floor cushion.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-colour-change'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-colour-change'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['floor cushion crochet', 'round floor pillow', 'crochet pouf cover'],
  glossaryTerms: [
    { slug: 'magic-ring-floor', term: 'Magic ring', definition: 'An adjustable loop start that closes to a small, neat centre. Used at the start of each circular panel.' },
    { slug: 'colour-change-floor', term: 'Colour change', definition: 'Drawing the new yarn colour through at the last step of the final stitch of a round.' },
    { slug: 'increase-round', term: 'Increase round', definition: 'A round in which two stitches are worked into each existing stitch or at regular intervals, expanding the circle diameter.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round floor cushions are a modern crochet project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Two flat circles grow from a '), gt('magic-ring-floor', 'magic ring'), t(' to 60 cm using standard dc '), gt('increase-round', 'increase rounds'), t('. Swap colours every 4 rounds for bold stripes using '), gt('colour-change-floor', 'colour change'), t('. Seam together and stuff firmly.')),
      p(t('Chunky yarn makes this a quick project. Allow around 800 m total across three colours. A firm cushion insert or loose stuffing both work.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky yarn, colour A', qty: '300 m' },
        { name: 'Chunky yarn, colour B', qty: '280 m' },
        { name: 'Chunky yarn, colour C', qty: '220 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '60 cm round cushion pad or stuffing', qty: '1' },
      ]),
      h2('Circle (make 2)'),
      p(t('Round 1: magic ring, 6 dc. Round 2: 2 dc in each st (12 dc). Round 3: * 2 dc, 1 dc; rep (18 dc). Continue standard 6-increase rounds until the circle is 60 cm across. Change colour every 4 rounds.')),
      h2('Assembly'),
      p(t('Place circles wrong sides together. Whipstitch around the edge, leaving a 20 cm gap. Insert pad or stuffing. Whipstitch the gap closed.')),
      h2('What to try next'),
      p(t('The granny square cushion cover uses the same basic assembly approach on a square format.')),
    ],
  },
},

// ── C4 ── puff stitch cushion ─────────────────────────────────────────────────
{
  slug: 'puff-stitch-cushion-cover',
  title: 'Puff stitch cushion cover',
  subtitle: 'A 40 cm square cushion cover worked in rows of soft puff stitches.',
  excerpt: 'Alternating rows of puff stitches and chain gaps create a dimpled, squishy surface on this 40 cm cushion cover. Worked in DK yarn.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '12 puffs x 14 rows = 10 x 10 cm in puff pattern on a 4 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-puff'],
  techniqueSlugs: ['crochet-puff', 'crochet-double-uk'],
  criticalTechniques: ['crochet-puff'],
  aliases: ['puff stitch cushion', 'puff pillow cover', 'textured cushion DK'],
  glossaryTerms: [
    { slug: 'puff-cushion', term: 'Puff stitch', definition: 'Four to six yarn-overs drawn up into loops in the same stitch, all closed together. Forms a soft rounded mound on the fabric surface.' },
    { slug: 'chain-gap-cushion', term: 'Chain gap', definition: 'A single chain between puffs that keeps the row even and stops the fabric from pulling in.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Puff stitch cushion covers are a modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Rows of '), gt('puff-cushion', 'puff stitches'), t(' sit in the '), gt('chain-gap-cushion', 'chain gaps'), t(' of the row below, building a grid of raised mounds. The fabric is thicker and softer than plain double crochet, making it ideal for a cushion cover.')),
      p(t('Each panel measures 40 x 40 cm in DK yarn. Make two panels and seam three sides, insert a 40 cm pad, and close the final seam.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn', qty: '450 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Panel (make 2)'),
      p(t('Chain 53. Row 1 (WS): dc in 2nd ch from hook and each ch across. Row 2 (RS): ch 1, * '), gt('puff-cushion', 'puff'), t(' in next st, ch 1, skip 1; rep to last st, dc. Row 3: ch 1, dc across placing a dc in each puff and each ch-1 sp. Repeat rows 2 and 3 until panel is 40 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side.')),
      h2('What to try next'),
      p(t('The bobble textured cushion uses the same rectangular panel format with bolder raised stitches.')),
    ],
  },
},

// ── C5 ── cable effect cushion ────────────────────────────────────────────────
{
  slug: 'cable-effect-cushion-cover',
  title: 'Cable effect cushion cover',
  subtitle: 'A 40 cm cushion cover with a central panel of front post treble cables.',
  excerpt: 'Front post treble stitches form bold vertical cables down this 40 cm cushion cover, flanked by plain double crochet side panels.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '16 st x 18 rows = 10 x 10 cm in aran on a 5 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-fptr', 'crochet-bptr'],
  techniqueSlugs: ['crochet-fptr', 'crochet-bptr', 'crochet-double-uk'],
  criticalTechniques: ['crochet-fptr'],
  aliases: ['cable crochet cushion', 'front post treble cushion', 'cable pillow cover'],
  glossaryTerms: [
    { slug: 'fptr-cushion', term: 'Front post treble', definition: 'A treble worked by inserting the hook around the post of the stitch in the row below from front to back. Creates a raised ridge that mimics knitting cables.' },
    { slug: 'bptr-cushion', term: 'Back post treble', definition: 'A treble worked around the post from back to front. Used on wrong-side rows to maintain the cable texture consistently.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Cable effect crochet cushion covers are a modern technique application. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The cable panel alternates '), gt('fptr-cushion', 'front post trebles'), t(' on right-side rows and '), gt('bptr-cushion', 'back post trebles'), t(' on wrong-side rows across a 16-stitch cable section, flanked by 12 dc stitches on each side. This creates five vertical ridges that look like knit cables.')),
      p(t('Aran weight on a 5 mm hook gives the cables good definition. Total yarn around 480 m for both panels.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '480 m' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Front panel'),
      p(t('Chain 65. Establish pattern: 12 dc, 16 sts cable section (alternating fptr and bptr per row), 12 dc. Continue until panel measures 40 cm.')),
      p(t('RS rows: work '), gt('fptr-cushion', 'fptr'), t(' across cable sts. WS rows: work '), gt('bptr-cushion', 'bptr'), t(' across cable sts. Dc sections work plain on every row.')),
      h2('Back panel'),
      p(t('Chain 65. Work plain dc rows until 40 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side.')),
      h2('What to try next'),
      p(t('The bobble textured cushion cover adds a different kind of raised surface. Or try the linen stitch square cushion for a woven appearance.')),
    ],
  },
},

// ── C6 ── linen stitch square cushion ─────────────────────────────────────────
{
  slug: 'linen-stitch-square-cushion',
  title: 'Linen stitch square cushion',
  subtitle: 'A 40 cm cushion cover worked in linen stitch for a woven, fabric-like surface.',
  excerpt: 'Linen stitch produces a tight, flat fabric that closely resembles woven cloth. This 40 cm cushion cover uses the stitch for a smart, tailored look.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-3-5mm',
  gauge: '20 st x 22 rows = 10 x 10 cm in linen stitch on a 3.5 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-waistcoat-stitch'],
  techniqueSlugs: ['crochet-waistcoat-stitch', 'crochet-double-uk'],
  criticalTechniques: ['crochet-waistcoat-stitch'],
  aliases: ['linen stitch cushion', 'waistcoat stitch cushion', 'woven look cushion'],
  glossaryTerms: [
    { slug: 'waistcoat-cushion', term: 'Linen stitch', definition: 'A dc worked into the centre of the V of the stitch below, rather than under the top loops. Produces a dense, flat fabric with a woven texture.' },
    { slug: 'dc-cushion-plain', term: 'Double crochet', definition: 'The basic UK crochet stitch. Insert hook, draw up a loop, yarn over and pull through both loops. Used here for the back panel.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Linen stitch cushion covers are a modern crochet application. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The front panel is worked entirely in '), gt('waistcoat-cushion', 'linen stitch'), t(', inserting the hook into the centre V of each stitch below. The resulting fabric is firm and flat with very little stretch.')),
      p(t('Use a slightly smaller hook than for standard dc at this yarn weight; the extra tightness helps the cover hold its shape. Around 500 m total for both panels.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn', qty: '500 m' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Front panel'),
      p(t('Chain 82. Row 1: '), gt('dc-cushion-plain', 'double crochet'), t(' across (foundation row). Row 2 onwards: '), gt('waistcoat-cushion', 'linen stitch'), t(' every row. Insert hook between the two legs of the V below rather than under the top loops. Continue until panel is 40 cm.')),
      h2('Back panel'),
      p(t('Chain 82. Work plain double crochet rows until 40 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side.')),
      h2('What to try next'),
      p(t('The cable effect cushion cover uses a similar flat panel format with raised vertical ridges.')),
    ],
  },
},

// ── C7 ── ripple pattern cushion ──────────────────────────────────────────────
{
  slug: 'ripple-pattern-cushion-cover',
  title: 'Ripple pattern cushion cover',
  subtitle: 'A 40 cm square cushion cover worked in a classic chevron ripple stripe.',
  excerpt: 'A six-colour chevron ripple stripe pattern covers both sides of this 40 cm cushion. Worked flat in rows using standard decreases and increases.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 st x 16 rows = 10 x 10 cm in ripple pattern on a 5 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-dc2tog', 'crochet-colour-change'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-dc2tog', 'crochet-colour-change'],
  criticalTechniques: ['crochet-dc2tog'],
  aliases: ['ripple cushion', 'chevron cushion cover', 'zigzag cushion crochet'],
  glossaryTerms: [
    { slug: 'dc2tog-ripple', term: 'Dc2tog', definition: 'Double crochet two together: a decrease that joins two stitches into one. Used at each valley of the chevron repeat.' },
    { slug: 'colour-change-ripple', term: 'Colour change', definition: 'Pulling the new yarn through at the end of the last stitch of a row before turning.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Ripple crochet cushion covers are a modern application of the classic ripple pattern. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The ripple pattern repeats over 16 stitches: 3 dc increase at each peak, '), gt('dc2tog-ripple', 'dc2tog'), t(' at each valley. Two decreases at each valley keep the total stitch count constant across every row.')),
      p(t('Change colour every two rows using '), gt('colour-change-ripple', 'colour change'), t(' at the end of each colour block. Six colours cycling every 2 rows produces 12-row colour stripes across 40 cm.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, 6 colours', qty: '80 m each' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Panel (make 2)'),
      p(t('Chain 65 (multiple of 16, plus 1). Set up ripple on row 1. Repeat ripple rows, changing colour every 2 rows until panel measures 40 cm.')),
      h2('Assembly'),
      p(t('Align chevrons or offset them for a different effect. Whipstitch three sides. Insert pad. Whipstitch remaining side.')),
      h2('What to try next'),
      p(t('The striped floor cushion uses colour stripes in a circular format.')),
    ],
  },
},

// ── C8 ── popcorn stitch cushion ──────────────────────────────────────────────
{
  slug: 'popcorn-stitch-cushion-cover',
  title: 'Popcorn stitch cushion cover',
  subtitle: 'A 40 cm cushion cover worked with raised popcorn stitches in a grid pattern.',
  excerpt: 'Popcorn stitches arranged in a regular grid produce a three-dimensional diamond surface on this 40 cm cushion cover.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '13 st x 15 rows = 10 x 10 cm in popcorn pattern on a 5 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-popcorn'],
  techniqueSlugs: ['crochet-popcorn', 'crochet-double-uk'],
  criticalTechniques: ['crochet-popcorn'],
  aliases: ['popcorn stitch cushion', 'popcorn pillow', 'raised stitch cushion'],
  glossaryTerms: [
    { slug: 'popcorn-cushion', term: 'Popcorn stitch', definition: 'Five trebles worked into one stitch, the hook removed from the loop, re-inserted through the first treble, and the loop pulled through. Pops forward on the right side.' },
    { slug: 'dc-plain-cushion', term: 'Double crochet', definition: 'The base fabric stitch between popcorns. One yarn over, pull through, yarn over, pull through both loops.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Popcorn stitch cushion covers are a modern crochet project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Each '), gt('popcorn-cushion', 'popcorn'), t(' sits every 4 stitches and every 4 rows, creating a uniform raised grid. The base fabric between popcorns is '), gt('dc-plain-cushion', 'double crochet'), t('. Both the front and back panels use the popcorn grid.')),
      p(t('Aran weight yarn holds the popcorns upright without blocking. Allow around 500 m for both panels.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '500 m' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Panel (make 2)'),
      p(t('Chain 55. Row 1: dc across. Row 2 (RS, set-up): ch 1, dc 2, * '), gt('popcorn-cushion', 'popcorn'), t(' in next st, dc 3; rep from * to last st, dc. Rows 3 to 5: dc across. Row 6: shift popcorns by 2 sts to offset grid. Repeat 6-row repeat until 40 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side. Popcorns should face outward on both sides.')),
      h2('What to try next'),
      p(t('The bobble textured cushion uses a similar raised stitch with a different scale and density.')),
    ],
  },
},

// ── C9 ── corner-to-corner cushion ────────────────────────────────────────────
{
  slug: 'corner-to-corner-cushion-cover',
  title: 'Corner-to-corner cushion cover',
  subtitle: 'A 40 cm cushion cover worked in the corner-to-corner technique with diagonal stripes.',
  excerpt: 'Corner-to-corner blocks grow diagonally across this 40 cm cushion cover, creating natural diagonal stripe opportunities with two contrasting yarns.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '4 C2C blocks x 4 blocks = 10 x 10 cm on a 4 mm hook with DK.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-colour-change'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-colour-change'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['C2C cushion', 'corner to corner cushion', 'diagonal crochet cushion'],
  glossaryTerms: [
    { slug: 'c2c-block', term: 'C2C block', definition: 'A cluster of one chain-3 and three double crochets worked as a unit. Rows of increasing then decreasing blocks build a diagonal square.' },
    { slug: 'colour-change-c2c', term: 'Colour change', definition: 'Switching yarn mid-row at a block boundary. Required for diagonal stripe effects in C2C work.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Corner-to-corner is a popular modern crochet technique. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Corner-to-corner grows by adding one '), gt('c2c-block', 'C2C block'), t(' per row from a single starting block. At 16 blocks wide, decrease one block per row back to one. The resulting square is 40 cm. Add '), gt('colour-change-c2c', 'colour changes'), t(' at block boundaries to create diagonal stripes.')),
      p(t('Use two DK colours. The diagonal growth means your colour changes move across the work naturally. Total yarn around 450 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, colour A', qty: '230 m' },
        { name: 'DK yarn, colour B', qty: '220 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Front panel'),
      p(t('Start with 1 '), gt('c2c-block', 'C2C block'), t('. Increase phase: each row adds 1 block, alternating colours every 2 rows. At 16 blocks, begin decrease phase: each row removes 1 block from one end. Fasten off at 1 block.')),
      h2('Back panel'),
      p(t('Work a plain 40 x 40 cm panel in dc, or repeat the C2C panel in a single colour.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side.')),
      h2('What to try next'),
      p(t('The granny square cushion cover uses a similarly geometric motif approach.')),
    ],
  },
},

// ── C10 ── chunky knot cushion ────────────────────────────────────────────────
{
  slug: 'chunky-knot-cushion-cover',
  title: 'Chunky knot cushion cover',
  subtitle: 'A 40 cm cushion cover worked in super-chunky yarn with large mock cable knots.',
  excerpt: 'Large mock cable knots worked in super-chunky yarn give this 40 cm cushion cover a dramatic, oversized texture reminiscent of knotted rope.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '7 st x 8 rows = 10 x 10 cm in super-chunky on a 10 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-fpdc', 'crochet-bpdc'],
  techniqueSlugs: ['crochet-fpdc', 'crochet-bpdc', 'crochet-double-uk'],
  criticalTechniques: ['crochet-fpdc'],
  aliases: ['chunky cable cushion', 'super chunky cushion', 'knotted cushion crochet'],
  glossaryTerms: [
    { slug: 'fpdc-knot', term: 'Front post double crochet', definition: 'A dc worked around the post of the stitch below from the front. Creates a raised ridge when repeated across a row.' },
    { slug: 'bpdc-knot', term: 'Back post double crochet', definition: 'A dc worked around the post from the back. Used on alternate rows to keep the raised rib consistent.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Chunky post-stitch cushion covers are a modern crochet project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Alternating '), gt('fpdc-knot', 'front post double crochet'), t(' and '), gt('bpdc-knot', 'back post double crochet'), t(' columns produce bold vertical ribs across a 40 cm panel. In super-chunky yarn, each rib appears as a large raised knot.')),
      p(t('The fabric works up very fast. Allow around 200 m total for the front panel and a plain dc back.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky yarn', qty: '200 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Front panel'),
      p(t('Chain 30. Row 1: dc across. Row 2 (RS): ch 1, * '), gt('fpdc-knot', 'fpdc'), t(', dc; rep to end. Row 3 (WS): ch 1, * '), gt('bpdc-knot', 'bpdc'), t(', dc; rep to end. Repeat rows 2 and 3 until panel is 40 cm.')),
      h2('Back panel'),
      p(t('Chain 30. Work plain dc rows until 40 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert 40 cm pad. Whipstitch remaining side.')),
      h2('What to try next'),
      p(t('The cable effect cushion uses post stitches in a similar way but adds defined cable crossings.')),
    ],
  },
},

// ── C11 ── mini granny hexagon cushion ────────────────────────────────────────
{
  slug: 'mini-granny-hexagon-cushion',
  title: 'Mini granny hexagon cushion',
  subtitle: 'A 40 cm round cushion cover assembled from 19 small granny hexagons.',
  excerpt: 'Nineteen small six-sided granny motifs join edge-to-edge to form two 40 cm hexagon panels. Fill gaps at the outer edge with partial hexagons.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 granny hexagon = 9 cm side to side, DK on a 4 mm hook.',
  finishedSize: '40 cm across hexagon cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-slip-stitch', 'crochet-double-uk', 'crochet-granny-cluster', 'crochet-join-as-you-go'],
  techniqueSlugs: ['crochet-granny-cluster', 'crochet-join-as-you-go', 'crochet-double-uk'],
  criticalTechniques: ['crochet-granny-cluster', 'crochet-join-as-you-go'],
  aliases: ['hexagon cushion', 'hexagon motif cushion', 'granny hex pillow'],
  glossaryTerms: [
    { slug: 'granny-cluster-hex', term: 'Granny cluster', definition: 'Three trebles worked into the same space. The repeating unit of each hexagonal motif.' },
    { slug: 'jayg-cushion', term: 'Join-as-you-go', definition: 'Joining a new motif to adjacent finished motifs during the final round, rather than seaming after. Saves time and reduces bulk.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Hexagonal motif cushions are a modern crochet application. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Each hexagon uses six '), gt('granny-cluster-hex', 'granny clusters'), t(' per round, one at each side. After round 3 the hexagon is 9 cm across. Use '), gt('jayg-cushion', 'join-as-you-go'), t(' to attach each motif to its neighbours on the final round.')),
      p(t('Make 38 full hexagons (19 per panel) in a mix of 4 to 6 colours. Partial hexagons at the edge fill any gaps before the final border round.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn in 4 to 6 colours', qty: '500 m total' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm round or hexagon cushion pad', qty: '1' },
      ]),
      h2('Hexagon (make 38)'),
      p(t('Round 1: ch 4, sl st to join, 2 dc in ring. * ch 2, 3 dc in ring; rep 4 more times. Ch 2, sl st. (6 clusters.) Round 2: sl st to ch-2 sp, '), gt('granny-cluster-hex', '3 dc'), t(', ch 2, 3 dc in same sp (corner), * ch 1, corner in next sp; rep. Round 3: extend as before, joining to adjacent motifs if using JAYG.')),
      h2('Assembly'),
      p(t('Lay out 19 hexagons in a flower arrangement for each panel. '), gt('jayg-cushion', 'Join-as-you-go'), t(' into a panel. Repeat for the second panel. Place wrong sides together and dc or whipstitch around the edge, inserting the pad before closing.')),
      h2('What to try next'),
      p(t('The granny square cushion cover uses the same motif assembly method in a square format.')),
    ],
  },
},

// ── C12 ── textured shell stitch cushion ──────────────────────────────────────
{
  slug: 'shell-stitch-cushion-cover',
  title: 'Shell stitch cushion cover',
  subtitle: 'A 40 cm cushion cover worked in a classic fan shell pattern.',
  excerpt: 'Overlapping shell fans create a scalloped, textured surface across both panels of this 40 cm cushion cover. Worked in DK yarn in a single colour.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '4 shells x 12 rows = 10 x 10 cm in shell pattern on a 4 mm hook.',
  finishedSize: '40 x 40 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-shell', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-shell', 'crochet-double-uk'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['shell stitch cushion', 'fan stitch cushion', 'shell pattern pillow'],
  glossaryTerms: [
    { slug: 'shell-cushion', term: 'Shell', definition: 'Five trebles worked into the same stitch or space, fanning out into a rounded shape. The repeating unit of the shell stitch pattern.' },
    { slug: 'dc-anchor', term: 'Anchor double crochet', definition: 'A single dc worked in the gap between two shells. Holds the shells in place and creates the valley of the pattern.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Shell stitch patterns appear in Weldon\'s Practical Crochet (1880s) and are also a popular modern project.',
  body: {
    type: 'doc', content: [
      p(t('The shell pattern repeats over 6 stitches: 5 trebles into a single stitch, skip 2, '), gt('dc-anchor', 'anchor dc'), t(', skip 2. Shells in alternate rows sit in the '), gt('dc-anchor', 'anchor dc'), t(' of the row below, building a staggered scallop pattern.')),
      p(t('Five trebles per '), gt('shell-cushion', 'shell'), t(' at DK weight gives defined fans without pulling the fabric. Total yarn around 450 m for both panels.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn', qty: '450 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Panel (make 2)'),
      p(t('Chain 61 (multiple of 6, plus 1). Row 1 (foundation): dc across. Row 2 (shell row): ch 3, '), gt('shell-cushion', '5 tr in 4th st'), t(', * skip 2, '), gt('dc-anchor', 'dc'), t(', skip 2, 5 tr in next st; rep. Row 3 (shift row): ch 1, dc in first tr, * 5 tr in anchor dc below, dc in centre tr of shell; rep. Alternate rows 2 and 3 until 40 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side. Align shell ridges across front and back if using the same panel for both.')),
      h2('What to try next'),
      p(t('The puff stitch cushion cover builds a similar soft texture with a different stitch.')),
    ],
  },
},

// ── C13 ── seed stitch lumbar cushion ─────────────────────────────────────────
{
  slug: 'seed-stitch-lumbar-cushion',
  title: 'Seed stitch lumbar cushion',
  subtitle: 'A 50 x 30 cm rectangular lumbar cushion in a moss seed stitch pattern.',
  excerpt: 'Alternating dc and ch-1 spaces in every row produce a fine seed stitch texture on this 50 x 30 cm lumbar cushion cover.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 st x 20 rows = 10 x 10 cm in seed stitch on a 4 mm hook.',
  finishedSize: '50 x 30 cm lumbar cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['lumbar cushion crochet', 'seed stitch cushion', 'moss stitch lumbar pillow'],
  glossaryTerms: [
    { slug: 'seed-stitch-lumbar', term: 'Seed stitch', definition: 'A pattern of alternating single stitches and chain spaces, each worked into the chain spaces of the row below. Gives a fine, even all-over texture.' },
    { slug: 'dc-in-sp', term: 'Dc in chain space', definition: 'Working a double crochet into a chain-1 space from the row below, rather than under the top loops of a stitch.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Seed or moss stitch crochet cushions are a widely used modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The '), gt('seed-stitch-lumbar', 'seed stitch'), t(' pattern alternates dc and ch-1 across every row, then works each '), gt('dc-in-sp', 'dc into the chain space'), t(' of the row below. This staggers the texture without needing a different row for right and wrong side.')),
      p(t('A lumbar cushion is wider than it is tall: 50 cm across, 30 cm high. Two panels seamed together fit a standard 50 x 30 cm lumbar insert. Around 380 m total.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn', qty: '380 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '50 x 30 cm lumbar cushion pad', qty: '1' },
      ]),
      h2('Panel (make 2)'),
      p(t('Chain 91 (odd number). Row 1: dc in 2nd ch from hook, * ch 1, skip 1, dc; rep to end. Row 2 onwards: ch 1, dc in first ch-1 sp, * ch 1, '), gt('dc-in-sp', 'dc in next ch-1 sp'), t('; rep. Each row offsets one space. Repeat until 30 cm.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert lumbar pad. Close remaining side.')),
      h2('What to try next'),
      p(t('The linen stitch square cushion uses a similar fine flat texture at a larger scale.')),
    ],
  },
},

// ── C14 ── boho tassel cushion ────────────────────────────────────────────────
{
  slug: 'boho-tassel-cushion-cover',
  title: 'Boho tassel cushion cover',
  subtitle: 'A 40 cm square cushion cover in plain double crochet with knotted fringe tassels.',
  excerpt: 'A plain double crochet 40 cm cushion cover finished with rows of knotted tassel fringe across one or all four edges for a boho look.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 st x 16 rows = 10 x 10 cm in aran on a 5 mm hook.',
  finishedSize: '40 x 40 cm cushion cover, plus 10 cm tassel fringe.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-double-uk'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['tassel cushion crochet', 'fringe cushion', 'boho pillow cover'],
  glossaryTerms: [
    { slug: 'tassel-fringe', term: 'Tassel fringe', definition: 'Lengths of yarn folded through edge stitches and knotted at the base to create hanging tassels. Attached after the panel is complete.' },
    { slug: 'dc-cushion-boho', term: 'Double crochet', definition: 'The base stitch used throughout the cushion panels. Insert hook, draw up a loop, yarn over and pull through both loops.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Tassel fringe cushion covers are a modern crochet application. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Both panels are worked in rows of '), gt('dc-cushion-boho', 'double crochet'), t('. The '), gt('tassel-fringe', 'tassel fringe'), t(' is added after assembly by folding 20 cm yarn lengths through every other edge stitch and knotting them close to the panel surface.')),
      p(t('Choose a natural aran wool or cotton for tassels that hang well. Around 480 m for both panels plus 80 m for fringe on one edge.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, main colour', qty: '480 m' },
        { name: 'Aran yarn, fringe colour (can match)', qty: '80 m' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '40 cm cushion pad', qty: '1' },
      ]),
      h2('Panel (make 2)'),
      p(t('Chain 57. Work dc rows until 40 cm. Fasten off.')),
      h2('Assembly'),
      p(t('Whipstitch three sides. Insert pad. Close remaining side.')),
      h2('Adding fringe'),
      p(t('Cut yarn in 22 cm lengths (pairs). Fold each pair in half. Insert the folded loop through an edge stitch, pass tails through loop, and pull firm. Trim to 10 cm. Repeat every other stitch along the bottom edge.')),
      h2('What to try next'),
      p(t('The seed stitch lumbar cushion uses the same basic panel format with added surface texture.')),
    ],
  },
},

// ── C15 ── square motif sampler cushion ───────────────────────────────────────
{
  slug: 'square-motif-sampler-cushion',
  title: 'Square motif sampler cushion',
  subtitle: 'A 45 cm cushion cover assembled from nine different 15 cm square motifs.',
  excerpt: 'Nine individually designed 15 cm square motifs join in a 3 by 3 grid to create a patchwork sampler cushion front panel. Each motif uses a different stitch.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 motif = 15 x 15 cm using DK on a 4 mm hook.',
  finishedSize: '45 x 45 cm cushion cover.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-shell', 'crochet-bobble', 'crochet-granny-cluster', 'crochet-puff', 'crochet-v-stitch', 'crochet-whipstitch-join'],
  techniqueSlugs: ['crochet-granny-cluster', 'crochet-shell', 'crochet-bobble', 'crochet-puff', 'crochet-v-stitch', 'crochet-whipstitch-join'],
  criticalTechniques: ['crochet-granny-cluster', 'crochet-whipstitch-join'],
  aliases: ['sampler cushion crochet', 'patchwork cushion cover', 'motif cushion'],
  glossaryTerms: [
    { slug: 'sampler-motif', term: 'Sampler motif', definition: 'A 15 cm square worked to a specific stitch pattern. Each of the nine motifs uses a different texture or construction method.' },
    { slug: 'whipstitch-sampler', term: 'Whipstitch join', definition: 'A visible ridge seam used to join motifs edge-to-edge. Creates a decorative line between each square.' },
    { slug: 'v-stitch-sampler', term: 'V-stitch', definition: 'A double crochet and a treble worked into the same stitch, creating a V shape. Used for one of the nine sampler panels.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Sampler motif cushions are a modern crochet project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Each '), gt('sampler-motif', 'sampler motif'), t(' is a 15 cm square worked individually. The nine motifs cover: plain dc, shell rows, '), gt('v-stitch-sampler', 'v-stitch'), t(', granny cluster, bobble row, puff row, cross-stitch crochet, waistcoat stitch, and fan stitch. Join with a '), gt('whipstitch-sampler', 'whipstitch join'), t(' in a 3 by 3 grid.')),
      p(t('Use a single yarn colour for a tonal look, or each motif in a different colour for a true patchwork effect. Allow around 500 m for the front panel and 250 m for a plain dc back.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, main or assorted colours', qty: '750 m total' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '45 cm cushion pad', qty: '1' },
      ]),
      h2('Make 9 motifs'),
      p(t('For each '), gt('sampler-motif', 'motif'), t(': cast on the appropriate foundation, work the featured stitch pattern, and end when the square is 15 cm across. Fasten off, leaving a long tail for seaming.')),
      h2('Joining'),
      p(t('Lay out 9 motifs in 3 rows of 3. '), gt('whipstitch-sampler', 'Whipstitch join'), t(' motifs in each row first, then join the rows together.')),
      h2('Back panel'),
      p(t('Work a plain dc 45 x 45 cm panel. Whipstitch to the front on three sides. Insert pad. Close remaining side.')),
      h2('What to try next'),
      p(t('The mini granny hexagon cushion uses a similar motif-assembly method with a different shape.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
