/**
 * Generator: D-Homewares Batch 7 — Dishcloths 26-30 + Baskets 1-10
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch7.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ══════════════════════════════════════════════════════════════════════════════
// DISHCLOTHS 26-30 (final 5 to complete the 30-dishcloth quota)
// ══════════════════════════════════════════════════════════════════════════════

// ── D26 ── bamboo stitch dishcloth ────────────────────────────────────────────
{
  slug: 'bamboo-stitch-dishcloth',
  title: 'Bamboo stitch dishcloth',
  subtitle: 'Vertical raised bars cross a dc background to make a bamboo-like pattern.',
  excerpt: 'Bamboo stitch works a yarn-over dc (also called a spike dc) into the row below to pull a raised bar to the surface. The vertical bars look like bamboo segments across the fabric.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts x 18 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-flo-dc'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-flo-dc'],
  criticalTechniques: ['crochet-flo-dc'],
  aliases: ['bamboo stitch cloth', 'spike dc dishcloth', 'vertical bar dishcloth'],
  glossaryTerms: [
    { slug: 'bamboo-bar', term: 'Bamboo bar', definition: 'A dc worked into the row below (into the front loop of the stitch two rows down), pulling the loop up to the current row height. This creates a raised vertical bar on the fabric surface.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Bamboo stitch is a modern derivative of the front-loop and long-dc family. No direct Weldon source; contemporary technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('bamboo-bar', 'bamboo stitch'), t(' dishcloth is 20 x 20 cm. Every other stitch on bamboo rows is a dc worked into the front loop of the stitch two rows below, pulling a raised bar to the surface. The vertical bars give the fabric its bamboo look.')),
      p(t('DK cotton on a 4 mm hook. The raised bars add texture for scrubbing. Total yarn needed is around 35 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 33 (32 dc).')),
      h2('Rows 1 and 2 (plain dc)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Work 32 dc. Turn. Work a second plain row. Turn.')),
      h2('Row 3 (bamboo row)'),
      p(t('Ch 1. Dc into first stitch. *Work 1 dc into the front loop of the stitch 2 rows below the next stitch (bamboo bar). Dc into next stitch on current row*. Repeat. Turn.')),
      h2('Row 4 (plain dc)'),
      p(t('Ch 1. Work 32 dc. Turn.')),
      h2('Rows 5 onward'),
      p(t('Alternate Row 3 (bamboo) and Row 4 (plain dc) for 36 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The moss stitch dishcloth uses a similar dot pattern. Or try the bobble stitch dishcloth for a firmer raised element.')),
    ],
  },
},

// ── D27 ── double treble mesh dishcloth ───────────────────────────────────────
{
  slug: 'dtr-mesh-dishcloth',
  title: 'Double treble mesh dishcloth',
  subtitle: 'Taller double trebles with ch-2 gaps make a wider, more open mesh cloth.',
  excerpt: 'Using double trebles instead of trebles and ch-2 gaps instead of ch-1 makes an open mesh that drains even faster than a treble mesh. A light cloth for rinsing.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '10 sts x 6 rows = 10 x 10 cm in DK cotton with a 4 mm hook, dtr mesh.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-treble'],
  techniqueSlugs: ['crochet-double-treble'],
  criticalTechniques: ['crochet-double-treble'],
  aliases: ['dtr mesh cloth', 'open mesh dishcloth', 'wide mesh cloth'],
  glossaryTerms: [
    { slug: 'dtr-stitch', term: 'Double treble', definition: 'UK: dtr. Two yarn-overs before inserting the hook. Four draw-throughs to complete. Taller than a treble.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Five chains at the start of each dtr mesh row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Double treble mesh from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('dtr-stitch', 'double treble'), t(' mesh dishcloth is 20 x 20 cm. The taller dtr with ch-2 gaps makes a very open mesh that lets water drain through quickly. This cloth is best for rinsing rather than scrubbing.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 15 m because the very open grid uses minimal yarn.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '15 m (about 12 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 31 (multiple of 3 + 1).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 5. *Dtr into next ch, ch 2, skip 2*. Repeat. Dtr into last ch. Turn.')),
      h2('Row 2 and onward'),
      p(t('Ch 5. *Dtr into each ch-2 space, ch 2*. Repeat. Dtr into top of turning chain. Turn.')),
      p(t('Repeat Row 2 for 12 rows (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Hang to dry.')),
      h2('What to try next'),
      p(t('The treble mesh dishcloth is a denser mesh with ch-1 gaps. Or try the v-stitch dishcloth for an open mesh with more structure.')),
    ],
  },
},

// ── D28 ── crossed dc dishcloth ───────────────────────────────────────────────
{
  slug: 'crossed-dc-dishcloth',
  title: 'Crossed dc dishcloth',
  subtitle: 'Pairs of dc worked in reversed order make a simple X pattern on a cotton cloth.',
  excerpt: 'Crossed dc works the second stitch first, then comes back for the first stitch. The pairs of crossed stitches give a woven appearance on both sides of the cloth.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 sts x 22 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['crossed dc cloth', 'woven look dishcloth', 'x stitch dishcloth'],
  glossaryTerms: [
    { slug: 'crossed-dc', term: 'Crossed dc', definition: 'Skip 1 stitch, dc into the next stitch, then dc back into the skipped stitch. The two stitches cross to form an X. Both stitches together use the space of 2 stitches.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each crossed dc row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Crossed dc from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('crossed-dc', 'crossed dc'), t(' dishcloth is 20 x 20 cm. Skipping one stitch, working dc into the next, then coming back for the skipped stitch makes a row of small X shapes. The fabric looks woven on both sides.')),
      p(t('DK cotton on a 4 mm hook. Foundation chain must be an even number. Total yarn needed is around 30 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 33 (32 sts).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. *Skip 1, dc into next, dc into skipped (crossed pair)*. Repeat across. Turn. (16 crossed pairs.)')),
      h2('Row 2 and onward'),
      p(t('Ch 1. *Crossed pair over every 2 stitches*. Repeat. Turn.')),
      p(t('Repeat Row 2 for 44 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The cross stitch crochet throw uses crossed trebles for a larger X pattern. Or try the waistcoat stitch dishcloth for a different woven-look surface.')),
    ],
  },
},

// ── D29 ── star stitch face cloth ─────────────────────────────────────────────
{
  slug: 'star-stitch-face-cloth',
  title: 'Star stitch face cloth',
  subtitle: 'Star stitches form a layered pattern on a soft DK cotton face cloth.',
  excerpt: 'A star stitch pulls up five loops from five positions and locks them through a common chain eye. The layered star shapes make a face cloth with good texture and softness.',
  difficulty: 'ADVANCED',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '8 star sts x 10 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square face cloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-star-stitch'],
  techniqueSlugs: ['crochet-star-stitch', 'crochet-double-uk'],
  criticalTechniques: ['crochet-star-stitch'],
  aliases: ['star stitch cloth', 'star face cloth', 'layered loop face cloth'],
  glossaryTerms: [
    { slug: 'star-st', term: 'Star stitch', definition: 'Pull up 5 loops: from the previous eye, the next 3 stitches, and one chain ahead. Draw yarn through all 5 loops plus ch 1 (the new eye). The five gathered loops form a star shape.' },
    { slug: 'star-eye', term: 'Star eye', definition: 'The chain stitch at the centre of each completed star, used as the starting point for the next star\'s first loop.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Star stitch from Weldon\'s Practical Crochet (series 5, 1886). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('star-st', 'star stitch'), t(' face cloth is 20 x 20 cm. Each star pulls five loops together through a central '), gt('star-eye', 'eye'), t(' chain. The layered loops produce a plush surface that is good for face washing.')),
      p(t('Star stitch is advanced because the loop order is strict and the eye chain is easy to miss. DK cotton on a 4 mm hook. Total yarn needed is around 35 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work one star'),
      p(t('Pull up a loop from: (1) previous eye chain, (2) current stitch top, (3) next stitch, (4) stitch after that. (5 loops on hook.) Yarn over, draw through all 5 loops. Ch 1 (new eye). One star made.')),
      h2('Foundation chain'),
      p(t('Chain 33 (even number + 1).')),
      h2('Row 1'),
      p(t('Pull up loops from ch 2, ch 3, ch 4 (3 loops). Yarn over through all 3, ch 1 (half star at edge). *Pull up 5-loop star, ch 1*. Repeat. Dc into last ch. Turn. (15 stars + 1 half star.)')),
      h2('Row 2 and onward'),
      p(t('Ch 2. Work stars across pulling loops from each eye chain. End with dc into turning chain. Turn.')),
      p(t('Repeat Row 2 for 20 rows (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block flat to open the star centres.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang flat.')),
      h2('What to try next'),
      p(t('The spider stitch baby blanket uses a related loop-gathering technique. Or try the puff stitch dishcloth for a simpler loop-gathering texture.')),
    ],
  },
},

// ── D30 ── shell stitch dishcloth ─────────────────────────────────────────────
{
  slug: 'shell-stitch-dishcloth',
  title: 'Shell stitch dishcloth',
  subtitle: 'Five-treble shells in an offset pattern on a 25 cm square cotton cloth.',
  excerpt: 'Rows of five-treble shells offset into the dc gaps between previous shells. The scalloped pattern makes a dishcloth with decorative edges on all four sides.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '6 shells x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 25 x 25 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-shell'],
  techniqueSlugs: ['crochet-shell', 'crochet-double-uk'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['shell stitch cloth', 'scallop dishcloth', 'fan dishcloth'],
  glossaryTerms: [
    { slug: 'shell-st-dc', term: 'Shell stitch', definition: 'Five trebles worked into the same base stitch or space, fanning out into a shell or scallop shape.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each shell row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Shell stitch from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('shell-st-dc', 'shell stitch'), t(' dishcloth is 25 x 25 cm. Five-treble shells sit in the dc spaces between each previous row\'s shells. The scalloped edges appear on all four sides when the edging is worked in the round.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 45 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '45 m (about 36 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 61 (12 shell repeats of 5 ch + 1).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Skip 2, 5 tr into next ch (shell), skip 2, dc into next ch*. Repeat. Turn. (12 shells.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Shell into the dc between shells below, dc into 3rd tr (centre) of shell below*. Repeat. Turn.')),
      p(t('Repeat Row 2 for 20 rows (approximately 25 cm). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The shell edged face cloth uses shells as a border only. Or try the fan stitch baby blanket for larger seven-treble fans in the same shell family.')),
    ],
  },
},

// ══════════════════════════════════════════════════════════════════════════════
// BASKETS 1-10
// ══════════════════════════════════════════════════════════════════════════════

// ── B1 ── basic round basket ──────────────────────────────────────────────────
{
  slug: 'basic-round-basket',
  title: 'Basic round basket',
  subtitle: 'A flat circle base growing into straight sides makes a simple storage basket.',
  excerpt: 'A magic ring base worked in dc spiral rounds builds a flat circle, then the sides grow straight up. The basic basket shape holds yarn, fruit, or small household items.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket, 20 cm diameter, 12 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['crochet basket', 'round storage basket', 'yarn basket crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-basket', term: 'Magic ring', definition: 'An adjustable loop start for working in the round. Pull the tail to close the centre hole completely. Gives a neat flat base with no central hole.' },
    { slug: 'dc-spiral', term: 'Spiral rounds', definition: 'Working in a continuous spiral without joining rounds with a slip stitch. Mark the first stitch of each round with a stitch marker to track progress.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Circular dc base from Weldon\'s Practical Crochet (series 2, 1880s). Magic ring and spiral construction are modern applications. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A basic round basket is 20 cm across and 12 cm tall. It starts with a '), gt('magic-ring-basket', 'magic ring'), t(' and grows in '), gt('dc-spiral', 'spiral rounds'), t(' until the base reaches 20 cm, then the sides work straight up.')),
      p(t('Super-chunky cotton rope or t-shirt yarn on a 10 mm hook gives a rigid basket. Thinner rope is softer and more flexible. Total yardage is around 150 m of super-chunky rope.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope or t-shirt yarn', qty: '150 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 7)'),
      p(t('Round 1: Magic ring, 8 dc. Pull ring closed. Place marker. (8 dc.)')),
      p(t('Round 2: 2 dc into every stitch. (16 dc.)')),
      p(t('Round 3: *1 dc, 2 dc into next*. Repeat. (24 dc.)')),
      p(t('Round 4: *1 dc, 1 dc, 2 dc into next*. Repeat. (32 dc.)')),
      p(t('Round 5: *1 dc x 3, 2 dc into next*. Repeat. (40 dc.)')),
      p(t('Round 6: *1 dc x 4, 2 dc into next*. Repeat. (48 dc.)')),
      p(t('Round 7: *1 dc x 5, 2 dc into next*. Repeat. (56 dc.) Check: base should measure about 20 cm across.')),
      h2('Sides (rounds 8 onward)'),
      p(t('Round 8: Work 1 dc into the back loop only of every stitch around. This creates a sharp fold line between base and sides. (56 dc.)')),
      p(t('Rounds 9 to 18: Work 1 dc into every stitch around in spiral (both loops). Continue until sides measure 12 cm. Sl st to next stitch to close final round. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Place a flat heavy book inside while the basket is damp to even the base.')),
      h2('Care'),
      p(t('Spot clean cotton rope. Machine wash only if the label allows. Shape while damp.')),
      h2('What to try next'),
      p(t('The oval basket uses the same technique from an oval base. Or try the tall round basket for a deeper version of this shape.')),
    ],
  },
},

// ── B2 ── oval basket ─────────────────────────────────────────────────────────
{
  slug: 'oval-basket',
  title: 'Oval basket',
  subtitle: 'An oval base in dc rounds makes a basket that fits inside a shelf or under a bed.',
  excerpt: 'An oval base starts from a chain foundation and adds stitches around both ends and along both sides. The resulting oval basket fits in rectangular spaces better than a round basket.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Oval basket, 30 x 20 cm, 10 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['oval crochet basket', 'oblong basket', 'rectangular base basket'],
  glossaryTerms: [
    { slug: 'oval-base', term: 'Oval base', definition: 'A foundation chain with stitches worked along both long edges and curved increases at each short end. The curve adds 4-6 stitches at each end over several rounds to build a flat oval.' },
    { slug: 'dc-spiral-oval', term: 'Spiral rounds', definition: 'Continuous rounds worked without a joining slip stitch. Use a stitch marker on the first stitch of each round.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Oval base construction from Weldon\'s Practical Crochet (series 3, 1880s). Spiral dc application is modern. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('An '), gt('oval-base', 'oval basket'), t(' is 30 x 20 cm and 10 cm tall. The base starts from a 10 cm foundation chain and grows in '), gt('dc-spiral-oval', 'spiral rounds'), t(' by adding stitches at both short ends until the oval reaches the stated size.')),
      p(t('Super-chunky cotton rope on a 10 mm hook. Total yardage is around 130 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope or t-shirt yarn', qty: '130 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 5)'),
      p(t('Foundation chain: chain 12. Round 1: dc into 2nd ch from hook and each of next 9 ch. Work 3 dc into end chain. Continue along underside of chain (10 dc). Work 3 dc into the first end ch. Place marker. (26 dc.)')),
      p(t('Round 2: 2 dc into first dc, dc x 10, 2 dc into each of 3 end stitches, dc x 10, 2 dc into each of 2 remaining end stitches. (32 dc.)')),
      p(t('Rounds 3 to 5: Continue adding 2 dc at each end curve, dc along straight edges. By round 5 the oval measures approximately 30 x 20 cm.')),
      h2('Sides (rounds 6 to 15)'),
      p(t('Round 6: Work 1 dc into the back loop only around (fold line). Rounds 7 to 15: Work 1 dc into every stitch around in spiral. Continue until sides measure 10 cm. Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Shape while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The basic round basket uses the same side technique from a magic ring base. Or try the square basket for a flat-sided version.')),
    ],
  },
},

// ── B3 ── square basket ───────────────────────────────────────────────────────
{
  slug: 'square-basket',
  title: 'Square basket',
  subtitle: 'A flat square base with corner increases gives a basket with straight sides.',
  excerpt: 'A square basket starts from a chain and increases at four corners to build a flat square base. The sides go straight up from the base fold round. Corners stay sharp if worked with back-loop increases.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Square basket, 20 x 20 cm base, 12 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['square crochet basket', 'box basket', 'corner basket'],
  glossaryTerms: [
    { slug: 'corner-increase', term: 'Corner increase', definition: 'Three dc worked into one corner stitch: 1 dc, then 2 dc into the same stitch, then 1 dc. The extra stitch turns the fabric at 90 degrees without curling.' },
    { slug: 'fold-round', term: 'Fold round', definition: 'A round worked into the back loop only at the junction of base and sides. The unused front loops form a visible ridge that holds the sides upright.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Square basket construction from Weldon\'s Practical Crochet (series 4, 1880s). Corner increase method is modern. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A square basket is 20 x 20 cm across and 12 cm tall. The base starts from a 4-stitch magic ring and adds '), gt('corner-increase', 'corner increases'), t(' at four points on every round. After the base, a '), gt('fold-round', 'fold round'), t(' in the back loop only creates the sharp base edge.')),
      p(t('Super-chunky rope on a 10 mm hook. For sharp corners, keep tension firm on the corner stitches. Total yardage is around 150 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '150 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch markers (4)', qty: '4' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 8)'),
      p(t('Round 1: Magic ring, ch 1, 3 dc, ch 1, 3 dc, ch 1, 3 dc, ch 1, 3 dc. Sl st. Pull ring closed. Mark 4 ch-1 corner spaces. (12 dc.)')),
      p(t('Round 2: *3 dc into corner ch-1 space, dc along side*. Repeat 4 times. (8 more dc per corner round.)')),
      p(t('Rounds 3 to 8: Continue the corner increase pattern until the base measures 20 x 20 cm (approximately 8 rounds).')),
      h2('Sides (rounds 9 onward)'),
      p(t('Round 9 (fold round): Work 1 dc into the back loop only around all stitches. Rounds 10 to 20: Work 1 dc into every stitch around in spiral. Continue until sides measure 12 cm. Sl st, fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Place a square piece of cardboard in the base while it sets for a crisp flat bottom.')),
      h2('Care'),
      p(t('Spot clean cotton rope. Reshape flat while damp.')),
      h2('What to try next'),
      p(t('The basic round basket uses the same side technique with a circular base. Or try the small storage basket for a shorter, tighter version.')),
    ],
  },
},

// ── B4 ── tall round basket ───────────────────────────────────────────────────
{
  slug: 'tall-round-basket',
  title: 'Tall round basket',
  subtitle: 'A deeper version of the basic round basket for storing yarn, laundry, or toys.',
  excerpt: 'The same magic ring base as the basic round basket, but the sides continue to 30 cm for a deep storage container. Good for yarn stash, toys, or laundry in a small space.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket, 25 cm diameter, 30 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['deep crochet basket', 'storage basket crochet', 'tall yarn basket'],
  glossaryTerms: [
    { slug: 'magic-ring-tall', term: 'Magic ring', definition: 'An adjustable loop start for working in the round. Pull the tail to close the centre hole. The base of the basket.' },
    { slug: 'blo-fold', term: 'BLO fold round', definition: 'A round worked into the back loop only to create a clean right-angle fold line between base and sides.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Circular dc base from Weldon\'s Practical Crochet (series 2, 1880s). Tall basket construction is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A tall round basket is 25 cm across and 30 cm tall. The base is a '), gt('magic-ring-tall', 'magic ring'), t(' dc spiral expanding to 25 cm, then a '), gt('blo-fold', 'BLO fold round'), t(' marks the transition and the sides grow straight up for 30 cm.')),
      p(t('Super-chunky rope on a 10 mm hook. A basket this tall needs around 300 m of rope. The extra yardage means a thicker rope (8-9 mm) makes this project more manageable.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope (8-9 mm)', qty: '300 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 8)'),
      p(t('Round 1: Magic ring, 8 dc. Rounds 2 to 8: same increase pattern as the basic round basket, adding 8 dc per round. By round 8 the base should measure 25 cm across. (72 dc after round 8.)')),
      h2('Sides (rounds 9 onward)'),
      p(t('Round 9 (fold round): Work 1 dc into the back loop only around. Rounds 10 onward: Work 1 dc into every stitch in spiral. Continue for approximately 27 rounds (30 cm). Sl st to close last round. Fasten off.')),
      h2('Handles (optional)'),
      p(t('Work a ch-10 bridge at each side, anchoring both ends with a sl st into the basket wall. Reinforce by working dc back across the chain. Cut and weave ends.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Stiffen the base with a cut circle of cardboard or a thin cutting board inside if needed.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand upright while damp to set the shape.')),
      h2('What to try next'),
      p(t('The basic round basket is the shorter version of this project. Or try the oval basket for a shape that fits a shelf better.')),
    ],
  },
},

// ── B5 ── small coiled rope basket ────────────────────────────────────────────
{
  slug: 'small-coiled-rope-basket',
  title: 'Small coiled rope basket',
  subtitle: 'A flat-bottomed basket made by coiling rope and joining with dc stitches.',
  excerpt: 'The coiled rope basket wraps rope in a spiral and joins the rounds with dc worked over the rope as a core. The dc anchors the rope coils together and adds colour.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '8 dc-over-rope rows = 10 cm height; 1 round = approx 3 cm diameter added.',
  finishedSize: 'Round basket, 18 cm diameter, 8 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['coiled basket', 'rope coil basket', 'dc over rope basket'],
  glossaryTerms: [
    { slug: 'dc-over-rope', term: 'DC over rope core', definition: 'Hold the rope core along the top of the previous round, insert hook over and around the rope, and complete a dc. The stitch encases the rope while simultaneously joining the new round to the previous one.' },
    { slug: 'coil-join', term: 'Coil join', definition: 'A slip stitch worked through both the current round of rope and the stitch of the previous round, holding the coil together at the base of each dc.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Coiled rope construction is a traditional basketry method adapted for crochet. No direct Weldon source. Contemporary documentation.',
  body: {
    type: 'doc', content: [
      p(t('A small coiled rope basket is 18 cm across and 8 cm tall. '), gt('dc-over-rope', 'DC stitches worked over a rope core'), t(' join each new coil to the previous round while wrapping the rope in a contrasting colour of DK cotton. The result looks like traditional coiled basketry.')),
      p(t('Use approximately 10 m of thick cotton washing line or similar rope (5-6 mm diameter) and 50 m of DK cotton for the joining yarn. A 4 mm hook works the dc over the rope.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Cotton rope, 5-6 mm diameter', qty: '10 m' },
        { name: 'DK cotton yarn (joining colour)', qty: '50 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Starting the base'),
      p(t('Coil the rope into a tight circle about 3 cm across. Work dc stitches all around the coil to lock the centre tight. Approximately 12 dc for the first coil.')),
      h2('Building rounds'),
      p(t('For each new round: hold the rope coil next to the previous round. Work 1 dc over the rope and into the stitch of the previous round ('), gt('coil-join', 'coil join'), t('). Space the stitches so the rope curves naturally without gaps or bunching. Add extra dc over the rope between the join stitches on wider rounds to keep it flat.')),
      h2('Sides'),
      p(t('After round 6 (approximately 18 cm diameter), stop adding extra dc between joins. Work dc over rope and into previous round only. The sides will naturally begin to rise. Continue for 6 more rounds (approximately 8 cm tall). Cut rope, tuck end inside last dc, secure with sl st.')),
      h2('Finishing'),
      p(t('Secure yarn tail with '), gt('weaving-in-ends', 'weaving in ends'), t('. Trim rope end closely inside the basket.')),
      h2('Care'),
      p(t('Spot clean. Do not machine wash rope baskets. Reshape while damp.')),
      h2('What to try next'),
      p(t('The basic round basket uses the same dc-in-spiral technique without the rope core. Or try the oval basket for a larger coiled version.')),
    ],
  },
},

// ── B6 ── handled market basket ───────────────────────────────────────────────
{
  slug: 'handled-market-basket',
  title: 'Handled market basket',
  subtitle: 'A round basket with two thick rope handles for carrying produce or craft supplies.',
  excerpt: 'A standard magic ring dc basket with two chain-loop handles reinforced with double dc rows. The handles are long enough to slip over a wrist.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket with handles, 22 cm diameter, 15 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['market basket crochet', 'carry basket', 'handled round basket'],
  glossaryTerms: [
    { slug: 'magic-ring-market', term: 'Magic ring', definition: 'Adjustable loop start for working in the round. Gives a tight closed centre for the basket base.' },
    { slug: 'handle-loop', term: 'Handle loop', definition: 'A chain loop of 18 stitches anchored to the basket wall at two points. Reinforced with a row of dc back across the chain to add strength.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Handle construction is a modern technique. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A handled market basket is 22 cm across and 15 cm tall. The base is a standard '), gt('magic-ring-market', 'magic ring'), t(' dc spiral. After the sides reach 15 cm, two '), gt('handle-loop', 'handle loops'), t(' are added at opposite sides.')),
      p(t('Super-chunky rope on a 10 mm hook. Total yardage is around 200 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '200 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base and sides'),
      p(t('Follow the basic round basket base to 22 cm diameter (approximately 8 rounds). Work BLO fold round, then work sides straight up for 15 cm (approximately 12 rounds). Sl st to close the last round.')),
      h2('Handles (make 2)'),
      p(t('Mark two points on opposite sides of the basket top (180 degrees apart). At the first mark: join yarn, ch 18, sl st into a point 10 stitches to the right on the same basket round. Work dc back across the ch 18 (reinforced handle). Cut and secure ends.')),
      p(t('Repeat for the second handle.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Shape the basket while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand to dry.')),
      h2('What to try next'),
      p(t('The basic round basket is the same shape without handles. Or try the tall round basket for a deeper version.')),
    ],
  },
},

// ── B7 ── mini trinket basket ─────────────────────────────────────────────────
{
  slug: 'mini-trinket-basket',
  title: 'Mini trinket basket',
  subtitle: 'A small dc basket for jewellery, keys, or small items on a bedside table.',
  excerpt: 'A 10 cm diameter mini basket in chunky cotton yarn on a 6 mm hook. The small size is quick to make and good for a first basket project before scaling up.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 dc x 14 rounds = 10 x 10 cm in chunky cotton on a 6 mm hook.',
  finishedSize: 'Round basket, 10 cm diameter, 7 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['trinket basket', 'small crochet bowl', 'mini basket crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-mini', term: 'Magic ring', definition: 'An adjustable loop start. Pull the tail to close the centre hole tight. Gives a neat base for a small basket.' },
    { slug: 'blo-round-mini', term: 'BLO round', definition: 'A round worked into the back loop only to create the fold line between base and sides of the basket.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Circular dc base from Weldon\'s Practical Crochet (series 2, 1880s). Mini basket sizing is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A mini trinket basket is 10 cm across and 7 cm tall. Starting with a '), gt('magic-ring-mini', 'magic ring'), t(', the base grows in dc spiral rounds to 10 cm, then a '), gt('blo-round-mini', 'BLO round'), t(' creates the base fold and the sides work straight up for 7 cm.')),
      p(t('Chunky cotton on a 6 mm hook makes a firm, small basket. Total yardage is around 40 m of chunky cotton.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky cotton yarn', qty: '40 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 4)'),
      p(t('Round 1: Magic ring, 6 dc. (6 dc.) Round 2: 2 dc into every stitch. (12 dc.) Round 3: *1 dc, 2 dc into next*. Repeat. (18 dc.) Round 4: *1 dc x 2, 2 dc into next*. Repeat. (24 dc.) Check: base should measure about 10 cm across.')),
      h2('Sides (rounds 5 to 14)'),
      p(t('Round 5: Work 1 dc into the back loop only around (fold line). Rounds 6 to 14: 1 dc into every stitch in spiral (approximately 7 cm). Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Spot clean or machine wash 30 degrees if yarn label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The basic round basket scales this shape to a 20 cm storage size. Or try the small coiled rope basket for a different construction method.')),
    ],
  },
},

// ── B8 ── two tone round basket ───────────────────────────────────────────────
{
  slug: 'two-tone-round-basket',
  title: 'Two tone round basket',
  subtitle: 'A contrasting colour at the fold line gives a basket with a different colour base and sides.',
  excerpt: 'The base is worked in Colour A, then at the BLO fold round the yarn changes to Colour B for the sides. The colour split at the fold makes a clean horizontal stripe at the basket waist.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket, 20 cm diameter, 15 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-colour-change'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-colour-change'],
  aliases: ['two colour basket', 'split colour basket', 'colour block basket'],
  glossaryTerms: [
    { slug: 'colour-change-basket', term: 'Colour change', definition: 'Pulling the new colour through the final loop of the last stitch of the previous round, so the next round begins cleanly in the new colour.' },
    { slug: 'blo-basket', term: 'BLO fold round', definition: 'The round at the base-to-side transition worked in back loop only. Used here as the colour-change point for a clean stripe at the basket waist.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Two-colour application is modern. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A two tone round basket is 20 cm across and 15 cm tall. The base is Colour A. At the '), gt('blo-basket', 'BLO fold round'), t(', a '), gt('colour-change-basket', 'colour change'), t(' to Colour B begins the sides. The colour split sits exactly at the basket waist for a clean stripe.')),
      p(t('Super-chunky rope in two contrasting colours on a 10 mm hook. Total yardage is around 100 m A (base) and 150 m B (sides).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky rope, Colour A (base)', qty: '100 m' },
        { name: 'Super-chunky rope, Colour B (sides)', qty: '150 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (Colour A)'),
      p(t('Follow the basic round basket base rounds 1 to 7 in Colour A to 20 cm diameter.')),
      h2('Fold round (colour change to Colour B)'),
      p(t('At the last pull-through of the final stitch of round 7, draw Colour B through to change colour. Work round 8 (fold round) in BLO in Colour B. (56 dc.)')),
      h2('Sides (Colour B)'),
      p(t('Continue in Colour B in spiral rounds, both loops, for 15 cm (approximately 12 rounds). Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Tuck Colour A tail inside the base folds.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand upright while damp.')),
      h2('What to try next'),
      p(t('The basic round basket is the single-colour version. Or try the striped basket for multiple colour bands up the sides.')),
    ],
  },
},

// ── B9 ── striped round basket ────────────────────────────────────────────────
{
  slug: 'striped-round-basket',
  title: 'Striped round basket',
  subtitle: 'Three alternating colour bands up the sides make a striped storage basket.',
  excerpt: 'Three colours alternate in 4-round bands up the sides of a round dc basket. The colour changes stack neatly on top of each other to form clean horizontal stripes.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket, 20 cm diameter, 20 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-colour-change'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-colour-change'],
  aliases: ['striped basket crochet', 'multi colour basket', 'three stripe basket'],
  glossaryTerms: [
    { slug: 'colour-change-stripe', term: 'Colour change', definition: 'Pulling the new colour through the final loop of the last stitch. In a spiral, the change appears one stitch offset from the start of the previous round.' },
    { slug: 'blo-fold-stripe', term: 'BLO fold round', definition: 'The transition round between base and sides worked in back loop only. Marks the base edge and sets up the stripe bands.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Stripe technique from Weldon\'s Practical Crochet (series 2, 1880s) adapted for rope baskets. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A striped round basket is 20 cm across and 20 cm tall with three '), gt('colour-change-stripe', 'colour'), t(' bands. The base is Colour A. After the '), gt('blo-fold-stripe', 'BLO fold round'), t(', the sides alternate 4 rounds each of Colours A, B, and C.')),
      p(t('Super-chunky rope in three colours on a 10 mm hook. Total yardage is around 80 m each colour (240 m total).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky rope, Colour A', qty: '80 m' },
        { name: 'Super-chunky rope, Colour B', qty: '80 m' },
        { name: 'Super-chunky rope, Colour C', qty: '80 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (Colour A, rounds 1 to 7)'),
      p(t('Follow basic round basket base to 20 cm in Colour A.')),
      h2('Fold round (round 8, Colour A)'),
      p(t('Work BLO around (fold line).')),
      h2('Sides'),
      p(t('Rounds 9 to 12: Colour A (4 rounds). Change to Colour B.')),
      p(t('Rounds 13 to 16: Colour B (4 rounds). Change to Colour C.')),
      p(t('Rounds 17 to 20: Colour C (4 rounds). If taller basket is wanted, continue in the 3-colour sequence. Sl st to close last round. Fasten off.')),
      h2('Finishing'),
      p(t('Secure all colour-change tails with '), gt('weaving-in-ends', 'weaving in ends'), t(' on the inside of the basket.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand upright while damp.')),
      h2('What to try next'),
      p(t('The two tone round basket uses a single colour split. Or try the basic round basket for a single-colour version of the same shape.')),
    ],
  },
},

// ── B10 ── bathroom storage basket ────────────────────────────────────────────
{
  slug: 'bathroom-storage-basket',
  title: 'Bathroom storage basket',
  subtitle: 'A wide, low round basket for toiletries or towels in a bathroom.',
  excerpt: 'A shallow round basket with a wide 30 cm base and only 10 cm sides. Proportioned for bathroom shelves holding cotton wool, soap bars, or small bottles.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket, 30 cm diameter, 10 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['bathroom basket crochet', 'shelf basket', 'wide shallow basket'],
  glossaryTerms: [
    { slug: 'magic-ring-bath', term: 'Magic ring', definition: 'An adjustable loop start for working in the round. Pull the tail to close the centre hole of the base.' },
    { slug: 'blo-fold-bath', term: 'BLO fold round', definition: 'One round worked in back loop only at the base-to-side transition to create a clean right-angle edge.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Bathroom proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A bathroom storage basket is 30 cm across and 10 cm tall. A wide, flat base in a '), gt('magic-ring-bath', 'magic ring'), t(' dc spiral reaches 30 cm before the '), gt('blo-fold-bath', 'BLO fold round'), t('. The sides are only 10 cm tall, making the basket proportioned for a shelf.')),
      p(t('Super-chunky rope on a 10 mm hook. Total yardage is around 180 m for this wide but shallow shape.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '180 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 10)'),
      p(t('Round 1: Magic ring, 8 dc. Rounds 2 to 10: standard circle increases (+8 dc per round). By round 10 the base should measure approximately 30 cm across. (88 dc.)')),
      h2('Fold round'),
      p(t('Work 1 dc into the back loop only around. (88 dc.)')),
      h2('Sides (rounds 12 to 19)'),
      p(t('Work 1 dc into every stitch in spiral for 8 rounds (approximately 10 cm). Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Press flat from inside to level the base.')),
      h2('Care'),
      p(t('Spot clean or machine wash if the rope label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The tall round basket uses the same technique with a much taller side height. Or try the oval basket for a shape that fits a narrow shelf.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
