/**
 * Generator: D-Homewares Batch 11 -- Decorative/seasonal 4-18
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch11.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── D4 ── crochet bunting ─────────────────────────────────────────────────────
{
  slug: 'triangle-pennant-bunting',
  title: 'Triangle pennant bunting',
  subtitle: 'A 3 m string of twelve crocheted triangular pennants for parties or year-round display.',
  excerpt: 'Twelve small dc triangles in four colours join onto a 3 m twisted cord. Works for birthday parties, seasonal displays, or as a permanent bedroom decoration.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 triangle pennant = 12 cm base x 10 cm tall on a 4 mm hook with DK.',
  finishedSize: '12 triangles on a 3 m cord.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-dc2tog'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-dc2tog'],
  criticalTechniques: ['crochet-dc2tog'],
  aliases: ['crochet bunting', 'crochet pennant garland', 'party bunting crochet'],
  glossaryTerms: [
    { slug: 'dc2tog-bunting', term: 'Dc2tog', definition: 'Double crochet two together. A decrease that reduces the row by one stitch. Used at both ends of each row to taper the triangle.' },
    { slug: 'pennant-edge', term: 'Pennant edge', definition: 'A round of slip stitch or dc worked around the two slanted sides of each triangle before attaching to the cord.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet bunting is a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Each triangle starts at the wide top edge and tapers to a point. A '), gt('dc2tog-bunting', 'dc2tog'), t(' decrease at each end of every row narrows the triangle over ten rows. A '), gt('pennant-edge', 'pennant edge'), t(' round neatens the sides before the triangle hangs from the cord.')),
      p(t('Use four DK colours and make three triangles per colour for an even repeat. Total yarn around 120 m across all four colours.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, 4 colours', qty: '30 m each' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '3 m twisted cotton cord', qty: '1' },
      ]),
      h2('Triangle (make 12)'),
      p(t('Chain 25. Row 1: dc across (24 sts). Row 2: ch 1, '), gt('dc2tog-bunting', 'dc2tog'), t(', dc to last 2, dc2tog (22 sts). Repeat row 2 every row until 2 sts remain. Dc2tog. Fasten off. Work '), gt('pennant-edge', 'pennant edge'), t(' around side edges.')),
      h2('Assembly'),
      p(t('Fold the top edge of each triangle over the cord and sl st or whipstitch into place. Space triangles 20 cm apart. Tie cord ends to loops for hanging.')),
      h2('What to try next'),
      p(t('The snowflake bunting uses a different motif style on the same cord format.')),
    ],
  },
},

// ── D5 ── crochet leaf garland ────────────────────────────────────────────────
{
  slug: 'leaf-garland',
  title: 'Leaf garland',
  subtitle: 'A 2 m garland of twenty crocheted leaves in two shades of green for autumn display.',
  excerpt: 'Twenty pointed oval leaves in two greens hang from a jute twine garland. Works for autumn mantels, doorways, or table runners.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 leaf = 8 cm long x 4 cm wide on a 4 mm hook with DK.',
  finishedSize: '20 leaves on a 2 m jute twine.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-half-treble', 'crochet-treble', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-half-treble', 'crochet-treble'],
  criticalTechniques: ['crochet-treble'],
  aliases: ['crochet leaf garland', 'autumn leaf garland', 'fall garland crochet'],
  glossaryTerms: [
    { slug: 'leaf-spine', term: 'Leaf spine', definition: 'A central chain line along each leaf from base to tip. Stitches work along both sides of this spine to form the leaf shape.' },
    { slug: 'leaf-shaping', term: 'Leaf shaping', definition: 'Working increasing stitch heights (dc, htr, tr) from the base and decreasing back to dc at the tip. Creates the oval point of each leaf.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet leaf garlands are a popular modern seasonal project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Each leaf is worked along a central '), gt('leaf-spine', 'leaf spine'), t(' chain. Stitch heights increase from dc to htr to tr at the widest point, then decrease back to the tip using '), gt('leaf-shaping', 'leaf shaping'), t('. The result is a pointed oval that lies flat.')),
      p(t('Make ten leaves in each of two greens. Thread onto jute twine through the base loop. Total yarn around 100 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, light green', qty: '50 m' },
        { name: 'DK yarn, dark green', qty: '50 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '2 m jute twine', qty: '1' },
      ]),
      h2('Leaf (make 20)'),
      p(t('Chain 9 (', ), gt('leaf-spine', 'spine'), t('). Work along one side: sl st, dc, htr, 3 tr in tip ch, then work back along the other side: htr, dc, sl st to base. The double-ended chain gives the two sides of each leaf. Fasten off.')),
      h2('Assembly'),
      p(t('Thread each leaf onto the jute twine through the slip stitch at its base. Alternate colours. Space leaves 10 cm apart. Knot cord ends for hanging.')),
      h2('What to try next'),
      p(t('The triangle pennant bunting uses a similar cord-and-motif format in a bolder geometric style.')),
    ],
  },
},

// ── D6 ── table centrepiece bowl ─────────────────────────────────────────────
{
  slug: 'decorative-bowl-centrepiece',
  title: 'Decorative bowl centrepiece',
  subtitle: 'A stiffened 20 cm crochet bowl for use as a table centrepiece or fruit display.',
  excerpt: 'A round double crochet bowl stiffened with fabric stiffener holds its shape for use as a fruit bowl, centrepiece, or display piece.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 dc x 20 rounds = 10 x 10 cm in DK on a 4 mm hook.',
  finishedSize: '20 cm diameter, 8 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-blo-dc'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-blo-dc'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['crochet bowl centrepiece', 'stiffened crochet bowl', 'crochet fruit bowl'],
  glossaryTerms: [
    { slug: 'magic-ring-bowl', term: 'Magic ring', definition: 'An adjustable loop start for circular work. Pulled closed, it leaves no visible hole at the bowl centre.' },
    { slug: 'blo-bowl', term: 'BLO fold round', definition: 'Working one round into the back loops only at the transition from base to sides. This creates the sharp right-angle fold at the base of the bowl.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Stiffened crochet bowls are a popular modern craft project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The base grows from a '), gt('magic-ring-bowl', 'magic ring'), t(' to 20 cm using standard dc increase rounds. A '), gt('blo-bowl', 'BLO fold round'), t(' at the base edge turns the work upward for 8 cm of sides. Stiffen with spray or soaking stiffener while shaping over a bowl mould.')),
      p(t('Cotton DK takes stiffener well. The bowl is not waterproof but works for dry fruit, potpourri, or display. Total yarn around 150 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '150 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Fabric stiffener', qty: 'as needed' },
      ]),
      h2('Base (rounds 1 to 10)'),
      p(t('Round 1: magic ring, 6 dc. Increase 6 dc per round until base is 20 cm. Work '), gt('blo-bowl', 'BLO fold round'), t('.')),
      h2('Sides'),
      p(t('Work 10 rounds plain dc (8 cm). Sl st to close last round. Fasten off.')),
      h2('Finishing'),
      p(t('Apply stiffener and shape over a 20 cm bowl or plate. Leave to dry completely (4 to 6 hours). The bowl will hold its shape when dry.')),
      h2('What to try next'),
      p(t('The market shopper tote uses the same base-up circular construction at a much larger scale.')),
    ],
  },
},

// ── D7 ── door wreath ─────────────────────────────────────────────────────────
{
  slug: 'spring-door-wreath',
  title: 'Spring door wreath',
  subtitle: 'A 30 cm crochet-covered wreath base decorated with small flower and leaf motifs.',
  excerpt: 'Small crochet flowers and leaves attached to a covered 30 cm wreath base make a lightweight door wreath for spring or year-round display.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: 'Not critical for decorative motifs.',
  finishedSize: '30 cm diameter door wreath.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-slip-stitch', 'crochet-shell'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-shell', 'crochet-treble'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['crochet door wreath', 'spring wreath crochet', 'floral wreath crochet'],
  glossaryTerms: [
    { slug: 'flower-motif-wr', term: 'Flower motif', definition: 'A small six-petal flower worked in the round from a central ring. Each petal is a 5-treble shell worked into a chain space.' },
    { slug: 'leaf-motif-wr', term: 'Leaf motif', definition: 'A simple oval leaf worked along a central spine chain. Two or three worked per stem cluster.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet door wreaths are a popular modern seasonal project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Cover a 30 cm foam or wire wreath base with a plain green dc tube. Then attach '), gt('flower-motif-wr', 'flower motifs'), t(' and '), gt('leaf-motif-wr', 'leaf motifs'), t(' in clusters around the front.')),
      p(t('Make around 12 flowers in pink, white, and yellow, and 20 leaves in two greens. Attach with the tapestry needle. Total yarn around 180 m across all colours.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, green (base cover)', qty: '80 m' },
        { name: 'DK yarn, flower colours (3 colours)', qty: '20 m each' },
        { name: 'DK yarn, leaf greens (2 colours)', qty: '20 m each' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '30 cm wreath base', qty: '1' },
      ]),
      h2('Base cover'),
      p(t('Crochet a dc rectangle long enough to cover the wreath circumference. Seam into a tube. Slide over wreath base and join ends.')),
      h2('Flower motif (make 12)'),
      p(t('Round 1: ch 4, sl st to ring, 12 dc in ring. Round 2: * ch 2, 5 tr in ring sp, ch 2, sl st in next dc; rep 5 more times. 6 petals. Fasten off.')),
      h2('Leaf motif (make 20)'),
      p(t('Ch 8. Work along spine: sl st, dc, htr, 3 tr in tip, htr, dc, sl st. Fasten off.')),
      h2('Assembly'),
      p(t('Arrange flowers and leaves in 3 to 4 clusters around the base. Sew each motif securely with the tapestry needle. Add a ribbon loop at the top for hanging.')),
      h2('What to try next'),
      p(t('The advent wreath cover uses the same wreath-covering method for a seasonal variant.')),
    ],
  },
},

// ── D8 ── crochet lantern cover ───────────────────────────────────────────────
{
  slug: 'crochet-lantern-cover',
  title: 'Crochet lantern cover',
  subtitle: 'An open-stitch crochet sleeve that slips over a glass jar to diffuse candlelight.',
  excerpt: 'A cylindrical open-mesh crochet sleeve fits over a standard large jam jar. The open stitches cast patterned shadows when a candle or tea light is placed inside.',
  difficulty: 'BEGINNER',
  yarnWeight: 'fingering',
  hook: 'crochet-hook-2-5mm',
  gauge: '24 st x 28 rounds = 10 x 10 cm in fingering on a 2.5 mm hook.',
  finishedSize: 'Fits a jar 8 cm diameter x 11 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-v-stitch'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-v-stitch'],
  criticalTechniques: ['crochet-v-stitch'],
  aliases: ['crochet jar cover', 'crochet candle holder', 'crochet lantern sleeve'],
  glossaryTerms: [
    { slug: 'v-stitch-lantern', term: 'V-stitch', definition: 'A dc and treble worked into the same stitch, forming a V. Repeated around the cylinder it creates an open, lacy fabric that lets light through.' },
    { slug: 'jar-gauge', term: 'Working in the round', definition: 'Crocheting in a continuous spiral around the inside of the sleeve, so no seam is needed. A stitch marker tracks the round start.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet jar covers are a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Work the sleeve as a tube in '), gt('v-stitch-lantern', 'V-stitch'), t(' rounds. V-stitches create a net-like fabric that glows when lit from within. Work '), gt('jar-gauge', 'in the round'), t(' from the base edge up.')),
      p(t('Measure your jar first and adjust the foundation chain to fit snugly. Fingering yarn gives the finest shadow pattern. Total yarn around 60 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Fingering yarn, natural or white', qty: '60 m' },
        { name: '2.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Large glass jam jar, 8 cm diameter', qty: '1' },
      ]),
      h2('Sleeve'),
      p(t('Foundation: chain to fit jar diameter (approx. 56 sts), sl st to join ring. Rounds 1 to 2: dc around. Round 3 onwards: '), gt('v-stitch-lantern', 'V-stitch'), t(' around: * dc and tr in same st, skip 1; rep. Continue for 11 cm (jar height). Final 2 rounds: dc. Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Slide sleeve over jar. Use an LED tea light inside (never a real flame with yarn near it).')),
      h2('What to try next'),
      p(t('The decorative bowl centrepiece uses the same circular base approach for a solid fabric vessel.')),
    ],
  },
},

// ── D9 ── pumpkin decoration ──────────────────────────────────────────────────
{
  slug: 'crochet-pumpkin-decoration',
  title: 'Crochet pumpkin decoration',
  subtitle: 'A small 12 cm stuffed crochet pumpkin for autumn and Halloween display.',
  excerpt: 'A round stuffed pumpkin with surface ridges crocheted in orange aran yarn. A short green stalk and optional leaf complete the decoration.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 dc x 16 rounds = 10 x 10 cm in aran on a 5 mm hook.',
  finishedSize: '12 cm diameter stuffed pumpkin.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-dc2tog', 'crochet-blo-dc'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-dc2tog'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['crochet pumpkin', 'halloween pumpkin crochet', 'autumn pumpkin decoration'],
  glossaryTerms: [
    { slug: 'magic-ring-pumpkin', term: 'Magic ring', definition: 'An adjustable loop that closes to a neat point. Used at both the top and bottom of the pumpkin.' },
    { slug: 'ridge-stitch', term: 'Surface ridge', definition: 'A yarn strand drawn tightly through the centre of the stuffed ball from top to bottom, dividing it into pumpkin-like segments.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet pumpkin decorations are a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The pumpkin body is a round ball worked from top to bottom. Once stuffed, a yarn strand is threaded through the centre and pulled tight, then repeated six times around to create '), gt('ridge-stitch', 'surface ridges'), t('.')),
      p(t('A small green stalk worked in a tight tube adds the finishing detail. Total yarn around 100 m in orange and 10 m in green.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, orange', qty: '100 m' },
        { name: 'Aran yarn, green', qty: '10 m' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Toy stuffing', qty: 'handful' },
      ]),
      h2('Body'),
      p(t('Round 1: '), gt('magic-ring-pumpkin', 'magic ring'), t(', 6 dc. Rounds 2 to 8: increase to 42 dc. Rounds 9 to 12: dc even. Rounds 13 to 18: decrease back to 6. Stuff firmly. Thread through last 6 sts and pull to close.')),
      h2('Ridges'),
      p(t('Thread a length of orange yarn on the tapestry needle. Push through the centre from bottom to top. Pull snug. Repeat 5 more times at even intervals to make 6 '), gt('ridge-stitch', 'ridges'), t('.')),
      h2('Stalk'),
      p(t('Ch 5 in green, sl st in 2nd ch and each ch back. Sew to the top centre.')),
      h2('What to try next'),
      p(t('The hanging wall star uses a similar two-panel stuffed approach for a flat decoration.')),
    ],
  },
},

// ── D10 ── heart bunting ──────────────────────────────────────────────────────
{
  slug: 'heart-bunting',
  title: 'Heart bunting',
  subtitle: 'A 2 m string of ten crocheted hearts in pink and red for Valentine or bedroom display.',
  excerpt: 'Ten small crocheted hearts in two shades thread onto a narrow ribbon to make 2 m of bunting. Each heart is worked in two panels and joined at the edges.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 heart = 7 cm wide x 6 cm tall on a 4 mm hook with DK.',
  finishedSize: '10 hearts on a 2 m ribbon.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-half-treble', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-half-treble'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['crochet heart bunting', 'heart garland crochet', 'valentine bunting'],
  glossaryTerms: [
    { slug: 'heart-lobe', term: 'Heart lobe', definition: 'One of the two rounded upper sections of the heart. Each is worked as a small circle, then the two lobes are joined and shaped into the V at the top.' },
    { slug: 'heart-join', term: 'Heart join round', definition: 'A dc round worked around both heart panels simultaneously to close the edges and lightly stuff each heart.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet heart decorations are a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Each heart is made of two flat panels. Work two '), gt('heart-lobe', 'heart lobes'), t(' per panel, join at the top, and work down to the bottom point. A '), gt('heart-join', 'heart join round'), t(' closes both panels, stuffing lightly as you go.')),
      p(t('Make five hearts in pink and five in red. Thread onto ribbon through the top loop. Total yarn around 100 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, pink', qty: '50 m' },
        { name: 'DK yarn, red', qty: '50 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '2 m narrow ribbon', qty: '1' },
        { name: 'Small amount of toy stuffing', qty: 'optional' },
      ]),
      h2('Heart panel (make 20)'),
      p(t('Work 2 small circles (', ), gt('heart-lobe', 'lobes'), t(') of 6 dc each. Join with sl st. Work down the outer edge, decreasing to a point. Fasten off.')),
      h2('Assembly'),
      p(t('Place 2 panels wrong sides together. Work '), gt('heart-join', 'heart join round'), t(' through both. Leave a small gap at the top to insert stuffing if desired. Close gap. Thread onto ribbon.')),
      h2('What to try next'),
      p(t('The snowflake bunting uses the same cord format with a different seasonal motif.')),
    ],
  },
},

// ── D11 ── house door stop ────────────────────────────────────────────────────
{
  slug: 'house-door-stop-cover',
  title: 'House door stop cover',
  subtitle: 'A crochet house-shaped cover for a standard door stop weight.',
  excerpt: 'A simple house-shaped crochet cover for a standard door stop. Worked in double crochet with a contrasting colour for the roof section.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '11 dc x 13 rows = 10 x 10 cm in chunky on a 6 mm hook.',
  finishedSize: 'Fits a standard brick door stop (approx. 19 x 9 x 6 cm).',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-double-uk'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['crochet door stop', 'house door stop', 'door stopper cover crochet'],
  glossaryTerms: [
    { slug: 'dc-flat-doorstop', term: 'Double crochet', definition: 'The main stitch throughout the cover. Insert hook under both top loops, draw up a loop, yarn over and pull through both loops.' },
    { slug: 'peaked-roof', term: 'Peaked roof', definition: 'A triangular panel worked by decreasing one stitch at each end of every row until one stitch remains. Forms the gable end of the house shape.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet door stop covers are a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The cover is worked flat in two main panels (front and back) plus two side panels. The front and back panels have a '), gt('peaked-roof', 'peaked roof'), t(' section worked in a contrasting colour above the main rectangle.')),
      p(t('Seam the four panels together and slip over the door stop brick. Total yarn around 200 m in the main colour plus 50 m for the roof.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky yarn, main colour', qty: '200 m' },
        { name: 'Chunky yarn, roof colour', qty: '50 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Brick door stop', qty: '1' },
      ]),
      h2('Front and back panels (make 2)'),
      p(t('Chain 22. Work '), gt('dc-flat-doorstop', 'double crochet'), t(' rows for 6 cm (wall section). Change to roof colour. Work '), gt('peaked-roof', 'peaked roof'), t(': decrease 1 st each end every row until 1 st remains.')),
      h2('Side panels (make 2)'),
      p(t('Chain 11. Work dc rows for 6 cm only (no peaked roof). Fasten off.')),
      h2('Assembly'),
      p(t('Seam front to sides, sides to back. Slip cover over door stop brick from the bottom. The roof peaks should meet and can be seamed or left open.')),
      h2('What to try next'),
      p(t('The table centrepiece bowl uses a similar open-top fabric vessel approach.')),
    ],
  },
},

// ── D12 ── mini cactus pot cover ──────────────────────────────────────────────
{
  slug: 'mini-cactus-pot-cover',
  title: 'Mini cactus pot cover',
  subtitle: 'A small crochet sleeve that fits over a standard 8 cm terracotta cactus pot.',
  excerpt: 'A simple cylindrical sleeve in green dk yarn fits snugly over an 8 cm terracotta pot. Small bump stitches represent cactus spines along the outside.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 dc x 20 rounds = 10 x 10 cm in DK on a 4 mm hook.',
  finishedSize: 'Fits an 8 cm diameter pot.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-bobble'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-bobble'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['crochet pot cover', 'cactus pot cover', 'plant pot crochet'],
  glossaryTerms: [
    { slug: 'bobble-spine', term: 'Spine bobble', definition: 'A small 3-treble bobble worked into the fabric to represent a cactus spine or bump.' },
    { slug: 'dc-tube-cactus', term: 'Dc tube', definition: 'A cylindrical sleeve worked in dc in the round. Sized to slip over a standard pot with a firm fit.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet pot covers are a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The sleeve is a '), gt('dc-tube-cactus', 'dc tube'), t(' worked in the round. '), gt('bobble-spine', 'Spine bobbles'), t(' are placed in a vertical line pattern every 8 stitches to suggest cactus ribs.')),
      p(t('Size the cast-on to your pot by measuring the circumference. Total yarn around 50 m. Works equally well for any small round pot.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, green', qty: '50 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '8 cm diameter pot', qty: '1' },
      ]),
      h2('Sleeve'),
      p(t('Foundation: chain to fit pot circumference (approx. 48 sts), sl st to join. Work '), gt('dc-tube-cactus', 'dc tube'), t(' for 3 rounds. Round 4: place '), gt('bobble-spine', 'bobbles'), t(' in vertical columns every 8 sts. Rounds 5 to 7: dc. Repeat bobble round every 4th round until sleeve matches pot height. Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Slip sleeve over pot from the top. Weave in ends.')),
      h2('What to try next'),
      p(t('The spring door wreath uses similar small motifs assembled on a larger display piece.')),
    ],
  },
},

// ── D13 ── photo frame cover ──────────────────────────────────────────────────
{
  slug: 'crochet-photo-frame-surround',
  title: 'Crochet photo frame surround',
  subtitle: 'A crocheted border that wraps around a standard 13 x 18 cm photo frame.',
  excerpt: 'A flat crochet border in shell stitch wraps around a standard 13 x 18 cm photo frame. Worked flat then seamed at the corners and slipped over the frame.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 st x 20 rows = 10 x 10 cm in DK on a 4 mm hook.',
  finishedSize: 'Fits a 13 x 18 cm photo frame.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-shell'],
  techniqueSlugs: ['crochet-shell', 'crochet-double-uk'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['crochet photo frame', 'picture frame crochet', 'crochet frame cover'],
  glossaryTerms: [
    { slug: 'shell-frame', term: 'Shell stitch', definition: 'Five trebles worked into the same stitch or space. The repeating unit of the frame border pattern.' },
    { slug: 'mitred-corner', term: 'Corner turn', definition: 'Working extra stitches into the corner space to keep the border flat when turning 90 degrees.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet photo frame borders are a popular modern craft project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The border is a rectangular strip of '), gt('shell-frame', 'shell stitch'), t(' worked to the frame\'s perimeter length. '), gt('mitred-corner', 'Corner turns'), t(' at each 90-degree turn add extra shells to keep the strip flat.')),
      p(t('Seam the strip into a rectangle and slip over the frame. Choose a yarn colour that complements the print inside. Total yarn around 80 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn', qty: '80 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '13 x 18 cm photo frame', qty: '1' },
      ]),
      h2('Border strip'),
      p(t('Work a strip of '), gt('shell-frame', 'shell stitch'), t(' long enough to encircle the frame (about 62 cm total perimeter). Work '), gt('mitred-corner', 'corner turns'), t(' at each angle. Seam short ends.')),
      h2('Fitting'),
      p(t('Slip border over the frame. Adjust to sit flat on the front surface. The border can be glued down if needed.')),
      h2('What to try next'),
      p(t('The house door stop cover uses a similar flat panel and assembly approach for a different decorative piece.')),
    ],
  },
},

// ── D14 ── coaster set ────────────────────────────────────────────────────────
{
  slug: 'round-coaster-set',
  title: 'Round coaster set',
  subtitle: 'A set of four 10 cm round coasters in double crochet, each in a different colour.',
  excerpt: 'Four flat 10 cm round coasters worked in cotton DK yarn from a magic ring. Each in a different colour from the same palette.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 dc x 20 rounds = 10 x 10 cm in cotton DK on a 4 mm hook.',
  finishedSize: '10 cm diameter each, set of 4.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['crochet coaster set', 'round crochet coasters', 'cotton crochet coasters'],
  glossaryTerms: [
    { slug: 'magic-ring-coaster', term: 'Magic ring', definition: 'An adjustable loop start for circular work. Gives a clean, closed centre point to the coaster.' },
    { slug: 'invisible-join', term: 'Invisible join', definition: 'A method of closing the final round that mimics a normal stitch, leaving no visible seam on the coaster edge.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet coasters are a classic project. No direct public-domain source needed.',
  body: {
    type: 'doc', content: [
      p(t('Each coaster starts with a '), gt('magic-ring-coaster', 'magic ring'), t(' and grows by 6 dc per round to 10 cm. Close the final round with an '), gt('invisible-join', 'invisible join'), t(' for a neat edge.')),
      p(t('Cotton yarn is essential for coasters as it is absorbent and machine-washable. Four colours from the same family gives a coordinated set. Total yarn around 80 m across four colours.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Cotton DK yarn, 4 colours', qty: '20 m each' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Coaster (make 4)'),
      p(t('Round 1: '), gt('magic-ring-coaster', 'magic ring'), t(', 6 dc. Round 2: 2 dc in each st (12 dc). Round 3: * 2 dc, 1 dc; rep (18 dc). Round 4: * 2 dc, 2 dc; rep (24 dc). Continue adding 6 dc per round until coaster is 10 cm. Sl st. '), gt('invisible-join', 'Invisible join'), t('. Fasten off.')),
      h2('Finishing'),
      p(t('Block each coaster flat by dampening and pinning to shape. Allow to dry.')),
      h2('What to try next'),
      p(t('The decorative bowl centrepiece uses the same circular base method at a larger scale.')),
    ],
  },
},

// ── D15 ── table runner ───────────────────────────────────────────────────────
{
  slug: 'shell-stitch-table-runner',
  title: 'Shell stitch table runner',
  subtitle: 'A 120 x 30 cm table runner in a shell stitch pattern worked in natural cotton.',
  excerpt: 'A long 120 x 30 cm table runner worked in alternating shell stitch rows. Natural cotton in an off-white or neutral tone suits any table setting.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '4 shells x 12 rows = 10 x 10 cm in shell pattern on a 4 mm hook.',
  finishedSize: '120 x 30 cm table runner.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-shell'],
  techniqueSlugs: ['crochet-shell', 'crochet-double-uk'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['crochet table runner', 'shell stitch table runner', 'cotton table runner'],
  glossaryTerms: [
    { slug: 'shell-runner', term: 'Shell stitch', definition: 'Five trebles worked into the same point, fanning into a rounded shell. Shells in alternate rows sit in the gap between the shells of the row below.' },
    { slug: 'picot-edge-runner', term: 'Picot border', definition: 'A decorative row of small chain loops along the long edges of the runner. Each picot is a ch-3 loop slip-stitched to the edge.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Shell stitch table runners are a modern project with Victorian-era stitch roots. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The runner is worked lengthways in alternating '), gt('shell-runner', 'shell stitch'), t(' rows to 30 cm wide. The natural dc rows between shell rows keep the fabric stable. A '), gt('picot-edge-runner', 'picot border'), t(' finishes both long edges.')),
      p(t('Cotton DK is the best choice for a table runner: it is washable and lies flat without needing blocking. Total yarn around 600 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Cotton DK yarn, natural or white', qty: '600 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Runner'),
      p(t('Chain 241 (multiple of 6 plus 1, to reach 120 cm). Row 1: dc across. Row 2: ch 3, '), gt('shell-runner', '5 tr in 4th st'), t(', * skip 2, dc, skip 2, 5 tr; rep. Row 3: ch 1, dc in first shell centre, * 5 tr in dc below, dc in shell centre; rep. Repeat rows 2 and 3 to 30 cm.')),
      h2('Edging'),
      p(t('Work a '), gt('picot-edge-runner', 'picot border'), t(' along both long edges: sl st, * ch 3, sl st in same sp, sl st in next sp; rep.')),
      h2('What to try next'),
      p(t('The round coaster set uses the same shell stitch in a much smaller circular format.')),
    ],
  },
},

// ── D16 ── mobile hanging ─────────────────────────────────────────────────────
{
  slug: 'crochet-mobile-hanging',
  title: 'Crochet mobile hanging',
  subtitle: 'A three-tier hanging mobile with crocheted circles, stars, and leaf shapes.',
  excerpt: 'Eight small crocheted motifs at three levels hang from a 30 cm dowel on twisted cotton cords for a bedroom or nursery mobile.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: 'Not critical for small decorative motifs.',
  finishedSize: '30 cm wide, approximately 50 cm tall with cords.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['crochet mobile', 'nursery mobile crochet', 'hanging mobile crochet'],
  glossaryTerms: [
    { slug: 'motif-circle', term: 'Circle motif', definition: 'A small flat circle made by working dc in the round from a magic ring to 5 cm diameter. Used at the bottom tier of the mobile.' },
    { slug: 'mobile-cord', term: 'Hanging cord', definition: 'A twisted or braided cotton cord that supports each motif. Shorter cords at the top tier, longer at the bottom.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet mobiles are a popular modern craft project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('Make 4 small '), gt('motif-circle', 'circle motifs'), t(' for the bottom tier, 2 leaf shapes for the middle, and 2 small stars for the top tier. Thread each on a '), gt('mobile-cord', 'hanging cord'), t(' and tie to a painted wooden dowel.')),
      p(t('Use pastel colours for a nursery or bold primaries for a playroom. Total yarn around 100 m across four colours.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn, 4 colours', qty: '25 m each' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '30 cm wooden dowel', qty: '1' },
        { name: 'Twisted cotton cord, various lengths', qty: '2 m total' },
      ]),
      h2('Bottom tier: circles (make 4)'),
      p(t('Round 1: magic ring, 6 dc. Round 2 to 4: increase to 18 dc. Sl st. Fasten off. '), gt('motif-circle', 'Circle motif'), t(' is 5 cm across.')),
      h2('Middle tier: leaves (make 2)'),
      p(t('Ch 8. Work along both sides of spine (sl st, dc, htr, 3 tr in tip, htr, dc, sl st). Fasten off.')),
      h2('Top tier: stars (make 2)'),
      p(t('Work 5 triangular points from a central ring, each ending in a ch-2 tip. Fasten off.')),
      h2('Assembly'),
      p(t('Tie each motif to a cord of the right length. Knot cords to the dowel: circles at the outer ends and centre, leaves mid-way, stars near centre. Balance by adjusting knot positions.')),
      h2('What to try next'),
      p(t('The snowflake bunting uses similar small motifs on a cord in a linear garland format.')),
    ],
  },
},

// ── D17 ── storage pot cover ──────────────────────────────────────────────────
{
  slug: 'storage-pot-cover',
  title: 'Storage pot cover',
  subtitle: 'A 12 cm cylindrical crochet sleeve that fits over a standard storage pot or tin.',
  excerpt: 'A ribbed dc cylinder slips over a standard 12 cm storage pot or metal tin. Front post and back post double crochet give it a stretchy ribbed fit.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 st x 18 rounds = 10 x 10 cm in rib pattern on a 4 mm hook.',
  finishedSize: 'Fits a 12 cm diameter pot or tin.',
  stitchSlugs: ['crochet-chain', 'crochet-fpdc', 'crochet-bpdc', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-fpdc', 'crochet-bpdc'],
  criticalTechniques: ['crochet-fpdc'],
  aliases: ['crochet tin cover', 'pot cover crochet', 'storage jar cover'],
  glossaryTerms: [
    { slug: 'fpdc-pot', term: 'Front post double crochet', definition: 'A dc worked around the post of the stitch below from the front. Creates raised vertical ribs on the right side.' },
    { slug: 'bpdc-pot', term: 'Back post double crochet', definition: 'A dc worked around the post from the back. The recessed counterpart to FPDC in a 1x1 rib.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crochet storage pot covers are a modern craft project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('A 1x1 rib of alternating '), gt('fpdc-pot', 'front post double crochet'), t(' and '), gt('bpdc-pot', 'back post double crochet'), t(' gives the sleeve good stretch to fit different pot sizes snugly.')),
      p(t('Foundation chain length: measure pot circumference plus 2 cm ease. Rib height equals pot height. Total yarn around 80 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK yarn', qty: '80 m' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Storage pot or tin, 12 cm diameter', qty: '1' },
      ]),
      h2('Sleeve'),
      p(t('Foundation: chain to fit pot circumference, sl st to join. Round 1: dc around. Round 2 onwards: * '), gt('fpdc-pot', 'fpdc'), t(', '), gt('bpdc-pot', 'bpdc'), t('; rep. Continue rib until height matches pot. Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Slip sleeve over pot from the top. The rib stretches to grip the pot without falling off.')),
      h2('What to try next'),
      p(t('The mini cactus pot cover uses the same sleeve format with a different surface stitch detail.')),
    ],
  },
},

// ── D18 ── crochet picture hanging ────────────────────────────────────────────
{
  slug: 'crochet-wall-hanging',
  title: 'Crochet wall hanging',
  subtitle: 'A 30 x 25 cm textured wall hanging worked in chunky yarn on a wooden dowel.',
  excerpt: 'A rectangular wall hanging in a mixed stitch sampler: double crochet, shell rows, and fringe edging. Hung from a 35 cm wooden dowel with a loop.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '11 st x 13 rows = 10 x 10 cm in chunky on a 6 mm hook.',
  finishedSize: '30 x 25 cm, plus 8 cm fringe.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-shell', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-shell'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['crochet wall hanging', 'chunky wall hanging', 'boho wall hanging crochet'],
  glossaryTerms: [
    { slug: 'shell-wall', term: 'Shell row', definition: 'A row of 5-treble shells separated by anchor double crochets. Alternates with plain dc rows to give a wave texture.' },
    { slug: 'knotted-fringe-wall', term: 'Knotted fringe', definition: 'Pairs of yarn lengths folded through edge stitches and knotted at the base. Cut to 8 cm after knotting.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Boho crochet wall hangings are a popular modern project. No direct public-domain source.',
  body: {
    type: 'doc', content: [
      p(t('The hanging is worked flat: 8 rows of plain dc, then 4 rows of '), gt('shell-wall', 'shell rows'), t(', then 4 rows of dc. A '), gt('knotted-fringe-wall', 'knotted fringe'), t(' added along the bottom edge gives the boho finish.')),
      p(t('Chunky yarn on a 6 mm hook works up fast. Loop the top edge over a 35 cm dowel and knot a hanging cord. Total yarn around 180 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky yarn, natural or white', qty: '180 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: '35 cm wooden dowel', qty: '1' },
      ]),
      h2('Panel'),
      p(t('Chain 35. Work 8 rows dc. Work 4 '), gt('shell-wall', 'shell rows'), t(': row 1 shell, row 2 dc, row 3 shell, row 4 dc. Work 4 more rows dc. Fasten off. Panel is 25 cm tall.')),
      h2('Mounting'),
      p(t('Fold top 2 cm over the dowel and whipstitch in place. Tie a 40 cm cord to each end of the dowel for hanging.')),
      h2('Fringe'),
      p(t('Cut 20 cm yarn lengths. Fold in pairs and attach '), gt('knotted-fringe-wall', 'knotted fringe'), t(' to every other stitch along the bottom edge. Trim even to 8 cm.')),
      h2('What to try next'),
      p(t('The boho tassel cushion cover uses the same fringe technique on a different project.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
