/**
 * Generator: D-Homewares Batch 8 — Baskets 11-25
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch8.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── B11 ── nesting basket set ─────────────────────────────────────────────────
{
  slug: 'nesting-basket-set',
  title: 'Nesting basket set',
  subtitle: 'Three round baskets in small, medium, and large that stack inside each other.',
  excerpt: 'Three round dc baskets at diameters of 12, 18, and 24 cm. Each uses the same magic ring increase pattern, stopped at a different round. They stack inside each other when not in use.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Set of 3: 12 cm / 18 cm / 24 cm diameter, each 10 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['nesting baskets', 'graduated basket set', 'stackable baskets crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-nest', term: 'Magic ring', definition: 'An adjustable loop start for working in the round. Pull the tail to close the centre hole. Gives a neat base for each basket.' },
    { slug: 'blo-nest', term: 'BLO fold round', definition: 'A round worked into the back loop only at the junction of base and sides. Creates the right-angle fold that gives each basket a defined waist.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Graduated sizing is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A nesting basket set is three round baskets in super-chunky rope on a 10 mm hook. Each starts with a '), gt('magic-ring-nest', 'magic ring'), t(' and uses the same increase pattern, stopped at a different round for each size. A '), gt('blo-nest', 'BLO fold round'), t(' marks the base edge before the sides go straight up.')),
      p(t('The three sizes nest inside each other when not in use. Total yardage is around 60 m (small), 100 m (medium), and 160 m (large).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope, Colour A (small)', qty: '60 m' },
        { name: 'Super-chunky cotton rope, Colour B (medium)', qty: '100 m' },
        { name: 'Super-chunky cotton rope, Colour C (large)', qty: '160 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Small basket (12 cm diameter)'),
      p(t('Rounds 1 to 4: magic ring increase pattern (+8 dc per round). Stop at round 4 (32 dc, approximately 12 cm). BLO fold round. Work sides straight for 10 cm (approximately 8 rounds). Fasten off.')),
      h2('Medium basket (18 cm diameter)'),
      p(t('Rounds 1 to 6: increase pattern. Stop at round 6 (48 dc, approximately 18 cm). BLO fold round. Work sides 10 cm. Fasten off.')),
      h2('Large basket (24 cm diameter)'),
      p(t('Rounds 1 to 8: increase pattern. Stop at round 8 (64 dc, approximately 24 cm). BLO fold round. Work sides 10 cm. Fasten off.')),
      h2('Finishing all three'),
      p(t('Secure tails on all three baskets with '), gt('weaving-in-ends', 'weaving in ends'), t('. Shape while damp. Stack small inside medium inside large.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The basic round basket pattern is the single-size version. Or try the two tone round basket for a colour variant of any of these sizes.')),
    ],
  },
},

// ── B12 ── wall hanging planter basket ────────────────────────────────────────
{
  slug: 'wall-hanging-planter-basket',
  title: 'Wall hanging planter basket',
  subtitle: 'A small round basket with a looped back for hanging on a wall hook.',
  excerpt: 'A 15 cm diameter round basket worked flat on the back to hang against a wall. A loop at the top back allows hanging on a hook or nail. For a small pot plant or dried flowers.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 dc x 14 rounds = 10 x 10 cm in chunky cotton on a 6 mm hook.',
  finishedSize: 'Wall basket, 15 cm diameter, 10 cm deep, flat back.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring', 'crochet-slip-stitch'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['wall basket crochet', 'hanging planter basket', 'flat back basket'],
  glossaryTerms: [
    { slug: 'flat-back', term: 'Flat back', definition: 'Working only across the front half of the round, then turning at each end instead of spiralling. Creates a half-round basket shape that lies flat against a wall.' },
    { slug: 'hanging-loop', term: 'Hanging loop', definition: 'A chain bridge of 15 stitches attached at both ends to the top back of the basket. Reinforced with a row of dc.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Wall basket construction is a modern crochet application. No direct Weldon source.',
  body: {
    type: 'doc', content: [
      p(t('A wall hanging planter basket is 15 cm across with a '), gt('flat-back', 'flat back'), t(' that sits flush against a wall. The base is a standard magic ring dc circle, but the sides are worked in rows rather than rounds so one side stays flat.')),
      p(t('Chunky cotton on a 6 mm hook. A '), gt('hanging-loop', 'hanging loop'), t(' added at the top allows the basket to hang on a wall hook. Total yardage is around 80 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky cotton yarn', qty: '80 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base'),
      p(t('Work rounds 1 to 5 of the basic round basket (magic ring, +8 dc per round) to reach approximately 15 cm. (40 dc.)')),
      h2('Sides (rows, not rounds)'),
      p(t('Work in rows across the front 20 stitches only. Work dc rows back and forth, turning at each end, for 10 cm (approximately 14 rows). This creates a pocket front while the back stays flat.')),
      h2('Joining the sides to the flat back'),
      p(t('Work a row of dc along the side edge of the pocket rows and sl st into the edge of the base to join. Repeat on the other side.')),
      h2('Hanging loop'),
      p(t('Join yarn at the top centre back. Ch 15, sl st to the same stitch. Work dc back along the ch 15 for reinforcement. Fasten off.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Spot clean or machine wash 30 degrees if yarn allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The mini trinket basket uses the same base in a free-standing version. Or try the handled market basket for a carrying version.')),
    ],
  },
},

// ── B13 ── toy storage basket ─────────────────────────────────────────────────
{
  slug: 'toy-storage-basket',
  title: 'Toy storage basket',
  subtitle: 'A large round basket with reinforced handles for holding children\'s toys.',
  excerpt: 'A 30 cm diameter round basket with two thick chain handles reinforced with dc rows. Sized to hold soft toys, building blocks, or craft supplies in a nursery or living room.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket with handles, 30 cm diameter, 25 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['toy basket crochet', 'nursery basket', 'large storage basket with handles'],
  glossaryTerms: [
    { slug: 'magic-ring-toy', term: 'Magic ring', definition: 'An adjustable loop start for the basket base. Pull the tail to close the centre hole tightly.' },
    { slug: 'reinforced-handle', term: 'Reinforced handle', definition: 'A chain loop of 20 stitches worked twice: first the chain bridge, then dc back along the chain. Both passes are worked into the basket wall at the same anchor points.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Handle and sizing are modern applications. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A toy storage basket is 30 cm across and 25 cm tall with two '), gt('reinforced-handle', 'reinforced handles'), t('. The base is a '), gt('magic-ring-toy', 'magic ring'), t(' dc spiral. Super-chunky rope on a 10 mm hook holds its shape under the weight of toys.')),
      p(t('Total yardage is around 400 m of super-chunky cotton rope. This is the largest basket in the homewares set.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '400 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 10)'),
      p(t('Follow the basic round basket increase pattern (+8 dc per round) for 10 rounds to reach 30 cm diameter. (88 dc.)')),
      h2('Fold round'),
      p(t('Work 1 dc into the back loop only around. (88 dc.)')),
      h2('Sides'),
      p(t('Work 1 dc into every stitch in spiral for approximately 20 rounds (25 cm). Sl st to close. Fasten off.')),
      h2('Handles (make 2)'),
      p(t('Mark two points 180 degrees apart on the top edge. At first mark: join rope, ch 20, sl st into a point 8 stitches along. Work dc back across the ch-20 bridge. Fasten off. Repeat at opposite side.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Stand upright and press the base flat while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand upright while damp to hold shape.')),
      h2('What to try next'),
      p(t('The handled market basket is a smaller carrying version. Or try the tall round basket for a deeper, handleless version of a similar size.')),
    ],
  },
},

// ── B14 ── hexagon basket ─────────────────────────────────────────────────────
{
  slug: 'hexagon-basket',
  title: 'Hexagon basket',
  subtitle: 'Six-sided increases make a flat hexagon base that gives the basket angular sides.',
  excerpt: 'A hexagon basket increases at six equally spaced points instead of evenly around. The six corners give the base a faceted shape and the sides slight angular panels.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Hexagon basket, approx 22 cm across, 12 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['hexagon basket crochet', 'six sided basket', 'hex basket'],
  glossaryTerms: [
    { slug: 'hex-increase', term: 'Hexagon increase', definition: 'On each round, work 2 dc into one stitch at each of 6 evenly spaced corner points. Adds 6 dc per round and builds a flat hexagon base.' },
    { slug: 'blo-hex', term: 'BLO fold round', definition: 'A round worked into the back loop only at the base-to-side transition. Creates the clean hexagonal fold edge.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Hexagon base construction is a modern crochet technique. No direct Weldon source.',
  body: {
    type: 'doc', content: [
      p(t('A hexagon basket is approximately 22 cm across flat-to-flat and 12 cm tall. The base uses '), gt('hex-increase', 'hexagon increases'), t(' at 6 fixed corner points on every round. The six corners create angular panels on the sides that give the basket a faceted appearance.')),
      p(t('Super-chunky rope on a 10 mm hook. Total yardage is around 170 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '170 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch markers (6)', qty: '6' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 8)'),
      p(t('Round 1: Magic ring, 12 dc. Mark every 2nd dc as a corner (6 corners). Round 2: 2 dc into each corner stitch, 1 dc into all others. (18 dc.) Repeat increase pattern: each round adds 6 dc by doubling the corner stitches. Work 8 rounds to approximately 22 cm across. (60 dc.)')),
      h2('Fold round'),
      p(gt('blo-hex', 'BLO fold round'), t(': work 1 dc into the back loop only around. (60 dc.)')),
      h2('Sides'),
      p(t('Work 1 dc into every stitch in spiral for 12 cm (approximately 9 rounds). Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Place the basket on a flat surface to set the hexagonal base shape while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Reshape on a flat surface while damp.')),
      h2('What to try next'),
      p(t('The square basket uses four corner increases for a rectangular shape. Or try the basic round basket for a circular version using the same side technique.')),
    ],
  },
},

// ── B15 ── laundry basket ─────────────────────────────────────────────────────
{
  slug: 'laundry-basket',
  title: 'Laundry basket',
  subtitle: 'An extra-tall round basket for laundry, worked in thick rope on a large hook.',
  excerpt: 'A round dc basket at 35 cm diameter and 45 cm tall, proportioned to hold a full wash load. Worked in thick rope on a 12 mm hook for speed and rigidity.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-12-0mm',
  gauge: '6 dc x 7 rounds = 10 x 10 cm in extra-thick rope on a 12 mm hook.',
  finishedSize: 'Round basket, 35 cm diameter, 45 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['laundry basket crochet', 'large crochet basket', 'hamper crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-laundry', term: 'Magic ring', definition: 'Adjustable loop start for the basket base. Pull the tail to close the centre hole.' },
    { slug: 'blo-laundry', term: 'BLO fold round', definition: 'One round in back loop only at the base-to-side transition. Defines the basket waist.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Laundry proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A laundry basket is 35 cm across and 45 cm tall. Worked in very thick rope (10-12 mm diameter) on a 12 mm hook, it is large enough for a full wash load and rigid enough to stand unaided. The base is a '), gt('magic-ring-laundry', 'magic ring'), t(' dc spiral to 35 cm.')),
      p(t('Total yardage is around 600 m of thick cotton rope. This is a large project; in super-chunky rope the sides grow at about 7 cm per 5 rounds.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Extra-thick cotton rope (10-12 mm)', qty: '600 m' },
        { name: '12 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle (large eye)', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 11)'),
      p(t('Follow the standard circle increase pattern (+8 dc per round) for 11 rounds to reach 35 cm diameter. (96 dc.)')),
      h2('Fold round'),
      p(gt('blo-laundry', 'BLO fold round'), t(': work 1 dc into the back loop only around. (96 dc.)')),
      h2('Sides'),
      p(t('Work 1 dc into every stitch in spiral for approximately 32 rounds (45 cm). Sl st to close last round. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Place the basket upright while damp so the sides dry straight.')),
      h2('Care'),
      p(t('Spot clean. Machine wash only if the rope label allows for a basket of this size. Stand upright to dry.')),
      h2('What to try next'),
      p(t('The tall round basket is a smaller version at 25 cm x 30 cm. Or try the toy storage basket for a handled version at a similar large scale.')),
    ],
  },
},

// ── B16 ── plant pot cover basket ─────────────────────────────────────────────
{
  slug: 'plant-pot-cover-basket',
  title: 'Plant pot cover basket',
  subtitle: 'A round basket sized to slip over a standard 14 cm nursery pot.',
  excerpt: 'A dc round basket at 16 cm diameter and 15 cm tall drops over a standard nursery plant pot. It hides the plastic pot without lifting the plant out.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 dc x 14 rounds = 10 x 10 cm in chunky cotton on a 6 mm hook.',
  finishedSize: 'Round cover basket, 16 cm diameter, 15 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['plant pot crochet cover', 'planter basket crochet', 'pot cover crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-pot', term: 'Magic ring', definition: 'Adjustable loop start for the basket base. Pull the tail closed for a neat centre.' },
    { slug: 'blo-pot', term: 'BLO fold round', definition: 'One round in back loop only at the fold line between base and sides.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Plant pot sizing is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A plant pot cover basket is 16 cm across and 15 cm tall. Chunky cotton on a 6 mm hook gives a slightly flexible cover that fits snugly over a 14 cm plastic nursery pot. The base is a '), gt('magic-ring-pot', 'magic ring'), t(' dc spiral and the '), gt('blo-pot', 'BLO fold round'), t(' creates the sharp waist.')),
      p(t('Total yardage is around 70 m of chunky cotton. For a larger pot (17 cm), work one more increase round and add 2-3 more side rounds.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky cotton yarn', qty: '70 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 5)'),
      p(t('Round 1: Magic ring, 8 dc. Rounds 2 to 5: standard increase (+8 dc per round). By round 5 the base is approximately 16 cm across. (40 dc.)')),
      h2('Fold and sides'),
      p(t('Round 6 (BLO fold round): dc into back loop only around. Rounds 7 to 26: work 1 dc into every stitch in spiral for approximately 21 rounds (15 cm). Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Drop over the plant pot; the fold round should sit at the base of the pot.')),
      h2('Care'),
      p(t('Remove the pot before washing. Machine wash 30 degrees. Reshape while damp.')),
      h2('What to try next'),
      p(t('The mini trinket basket uses the same technique in a smaller size. Or try the bathroom storage basket for a wider, lower version of the same shape.')),
    ],
  },
},

// ── B17 ── market tote bag basket ──────────────────────────────────────────────
{
  slug: 'market-tote-basket',
  title: 'Market tote basket',
  subtitle: 'A rigid-sided tote shaped like a basket with long strap handles for carrying.',
  excerpt: 'A round dc basket base grows into a tall, straight-sided tote with two long strap handles. Sits upright like a basket but is carried by the long straps. Good for farmers markets or craft fairs.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Tote basket, 22 cm diameter, 25 cm tall, with 45 cm straps.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['basket tote bag', 'market bag basket', 'crochet tote basket'],
  glossaryTerms: [
    { slug: 'magic-ring-tote', term: 'Magic ring', definition: 'Adjustable loop start for the basket base.' },
    { slug: 'strap-chain', term: 'Strap chain', definition: 'A chain of 60 stitches anchored at both ends to the basket rim, forming a long carry strap. Reinforced with dc back along the chain.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Tote strap construction is modern. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A market tote basket is 22 cm across and 25 cm tall with two 45 cm '), gt('strap-chain', 'strap handles'), t('. The base is a '), gt('magic-ring-tote', 'magic ring'), t(' dc spiral. Super-chunky rope on a 10 mm hook gives a rigid base and sides.')),
      p(t('Total yardage is around 250 m for the body and 50 m for both straps.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '300 m total' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base and sides'),
      p(t('Follow the basic round basket base to 22 cm diameter (rounds 1 to 8, 64 dc). BLO fold round. Work sides straight for 25 cm (approximately 20 rounds). Sl st to close. Fasten off.')),
      h2('Straps (make 2)'),
      p(t('Mark four points on the basket rim: two on one side 6 cm apart, and two opposite. For each strap: join rope at one mark. Ch 60. Sl st into the second mark. Work dc back across the ch-60. Fasten off. Repeat for the second strap.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The two long straps allow the tote to be carried over one shoulder.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand upright while damp.')),
      h2('What to try next'),
      p(t('The handled market basket uses short loop handles instead. Or try the tall round basket for a deeper version without handles.')),
    ],
  },
},

// ── B18 ── lidded trinket box ─────────────────────────────────────────────────
{
  slug: 'lidded-trinket-box',
  title: 'Lidded trinket box',
  subtitle: 'A small round basket with a flat dc lid for storing jewellery or small items.',
  excerpt: 'A 12 cm round basket with a matching flat circle lid. The lid sits inside the rim and stays in place without fastening. Good for jewellery, keys, or charging cables.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 dc x 14 rounds = 10 x 10 cm in chunky cotton on a 6 mm hook.',
  finishedSize: 'Round box, 12 cm diameter, 8 cm tall, with lid.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['lidded basket crochet', 'trinket box crochet', 'crochet box with lid'],
  glossaryTerms: [
    { slug: 'magic-ring-lid', term: 'Magic ring', definition: 'Adjustable loop start used for both the basket base and the flat lid circle.' },
    { slug: 'lid-circle', term: 'Lid circle', definition: 'A flat dc circle worked to the same diameter as the inside of the basket rim, plus one round of dc worked in back loop only to give the lid a slight rim that grips the basket top.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Lid construction is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A lidded trinket box is 12 cm across and 8 cm tall. The basket is a standard magic ring dc basket. The '), gt('lid-circle', 'lid'), t(' is a flat dc circle worked to the same diameter, then one BLO round gives it a small inner rim that grips the basket top.')),
      p(t('Chunky cotton on a 6 mm hook for both pieces. Total yardage is around 50 m for the basket and 20 m for the lid.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky cotton yarn', qty: '70 m total' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Basket'),
      p(t('Rounds 1 to 4: '), gt('magic-ring-lid', 'magic ring'), t(' increase pattern to 12 cm. BLO fold round. Work sides straight for 8 cm. Sl st to close. Fasten off.')),
      h2('Lid'),
      p(t('Rounds 1 to 4: separate magic ring increase pattern to 12 cm (same as basket base). Round 5: work 1 dc into the front loop only of every stitch. Round 6: work 1 dc into every stitch (the FLO round from round 5 creates a slight downward rim). Sl st. Fasten off.')),
      h2('Fitting the lid'),
      p(t('Drop the lid onto the basket. The FLO rim should sit just inside the basket rim and hold the lid in place. If the lid is loose, work an extra round of dc around the rim edge.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Spot clean or machine wash 30 degrees. Reshape both pieces separately while damp.')),
      h2('What to try next'),
      p(t('The mini trinket basket is the same base without a lid. Or try the small coiled rope basket for a different base construction.')),
    ],
  },
},

// ── B19 ── kitchen utensil pot ────────────────────────────────────────────────
{
  slug: 'kitchen-utensil-pot',
  title: 'Kitchen utensil pot',
  subtitle: 'A tall narrow basket for storing wooden spoons, spatulas, and cooking utensils.',
  excerpt: 'A round basket at 12 cm diameter and 20 cm tall, proportioned to hold kitchen utensils upright on a worktop. The narrow base stops tipping.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round pot, 12 cm diameter, 20 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['utensil holder crochet', 'kitchen pot crochet', 'spoon holder basket'],
  glossaryTerms: [
    { slug: 'magic-ring-pot2', term: 'Magic ring', definition: 'Adjustable loop start for the pot base. Pull the tail closed to prevent a centre gap.' },
    { slug: 'blo-pot2', term: 'BLO fold round', definition: 'One round in back loop only to create the fold line between base and sides.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Utensil pot proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A kitchen utensil pot is 12 cm across and 20 cm tall. The narrow width holds utensils upright without tipping. The base is a '), gt('magic-ring-pot2', 'magic ring'), t(' dc spiral to 12 cm. A '), gt('blo-pot2', 'BLO fold round'), t(' creates the waist, then the sides work straight up for 20 cm.')),
      p(t('Super-chunky rope on a 10 mm hook. Total yardage is around 120 m. The tall narrow shape uses proportionally more yardage than a wide shallow basket.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '120 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 4)'),
      p(t('Follow the magic ring increase pattern for 4 rounds to reach 12 cm diameter. (32 dc.)')),
      h2('Fold and sides'),
      p(t('BLO fold round. Work 1 dc into every stitch in spiral for approximately 18 rounds (20 cm). Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Stand upright while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Stand upright to dry.')),
      h2('What to try next'),
      p(t('The mini trinket basket is a shorter, wider version of the same narrow shape. Or try the plant pot cover basket for a similar proportioned project.')),
    ],
  },
},

// ── B20 ── catch-all entry basket ─────────────────────────────────────────────
{
  slug: 'catch-all-entry-basket',
  title: 'Catch-all entry basket',
  subtitle: 'A wide shallow oval basket for keys, post, and small items near a front door.',
  excerpt: 'A wide, low oval basket proportioned for an entryway shelf or console table. Holds keys, post, sunglasses, and loose change without cluttering the surface.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Oval basket, 35 x 20 cm, 8 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['entry basket crochet', 'key basket', 'entryway tray basket'],
  glossaryTerms: [
    { slug: 'oval-base2', term: 'Oval base', definition: 'A foundation chain worked along both long edges with curved increases at each short end. Builds a flat oval by adding dc at the two ends over several rounds.' },
    { slug: 'blo-entry', term: 'BLO fold round', definition: 'One round worked into the back loop only at the base-to-side transition. Creates the fold line for the sides.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Oval basket base from Weldon\'s Practical Crochet (series 3, 1880s). Entry proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A catch-all entry basket is 35 x 20 cm and only 8 cm tall. The '), gt('oval-base2', 'oval base'), t(' starts from a 15 cm foundation chain and expands to 35 cm across. A '), gt('blo-entry', 'BLO fold round'), t(' marks the waist, then the sides are just 8 cm to keep the basket low and easy to reach into.')),
      p(t('Super-chunky rope on a 10 mm hook. Total yardage is around 130 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '130 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 5)'),
      p(t('Foundation chain 16. Round 1: dc along both sides with 3 dc at each short end curve. (30 dc.) Rounds 2 to 5: add 6 dc per round at the two curve ends. By round 5 the oval is approximately 35 x 20 cm. (54 dc.)')),
      h2('Fold and sides'),
      p(t('BLO fold round. Work 1 dc into every stitch in spiral for 8 rounds (approximately 8 cm). Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Press the base flat while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The oval basket is a taller version of the same oval base. Or try the bathroom storage basket for a round wide-low proportioned version.')),
    ],
  },
},

// ── B21 ── desk tidy basket set ───────────────────────────────────────────────
{
  slug: 'desk-tidy-basket-set',
  title: 'Desk tidy basket set',
  subtitle: 'Three small baskets in different heights for organising a desk or dressing table.',
  excerpt: 'Three small round baskets at 8, 10, and 14 cm diameter in chunky cotton. Sized for pens, scissors, and small office supplies standing upright on a desk.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 dc x 14 rounds = 10 x 10 cm in chunky cotton on a 6 mm hook.',
  finishedSize: 'Set of 3: 8 cm / 10 cm / 14 cm diameter, each 12 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring'],
  aliases: ['desk organiser crochet', 'pen pot set', 'desk basket set'],
  glossaryTerms: [
    { slug: 'magic-ring-desk', term: 'Magic ring', definition: 'Adjustable loop start for each basket base. Pull the tail closed for a neat centre.' },
    { slug: 'blo-desk', term: 'BLO fold round', definition: 'One round worked in back loop only to create the right-angle fold between base and sides on each basket.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Desk tidy sizing is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A desk tidy basket set is three round baskets in chunky cotton on a 6 mm hook. Each starts with a '), gt('magic-ring-desk', 'magic ring'), t(' and uses the standard increase pattern stopped at different rounds. A '), gt('blo-desk', 'BLO fold round'), t(' on each gives a clean waist.')),
      p(t('All three are 12 cm tall. The width difference means the narrowest holds pens, the middle holds scissors, and the widest holds small notebooks or cards. Total yardage is around 30 m (small), 45 m (medium), and 70 m (large).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky cotton yarn (one or three colours)', qty: '145 m total' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Small basket (8 cm diameter)'),
      p(t('Rounds 1 to 3: magic ring increase pattern to 8 cm. (24 dc.) BLO fold round. Work sides 12 cm. Fasten off.')),
      h2('Medium basket (10 cm diameter)'),
      p(t('Rounds 1 to 4: increase pattern to 10 cm. (32 dc.) BLO fold round. Work sides 12 cm. Fasten off.')),
      h2('Large basket (14 cm diameter)'),
      p(t('Rounds 1 to 5: increase pattern to 14 cm. (40 dc.) BLO fold round. Work sides 12 cm. Fasten off.')),
      h2('Finishing all three'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Group on a desk surface.')),
      h2('Care'),
      p(t('Machine wash 30 degrees. Reshape upright while damp.')),
      h2('What to try next'),
      p(t('The nesting basket set uses the same graduated approach in a larger super-chunky version. Or try the kitchen utensil pot for a taller narrow version.')),
    ],
  },
},

// ── B22 ── picnic storage basket ──────────────────────────────────────────────
{
  slug: 'picnic-storage-basket',
  title: 'Picnic storage basket',
  subtitle: 'A wide oval basket with rigid sides for storing picnic napkins, cutlery, or condiments.',
  excerpt: 'A 30 x 20 cm oval basket with 15 cm sides made in super-chunky cotton rope. Proportioned for a kitchen shelf holding picnic or outdoor dining supplies.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Oval basket, 30 x 20 cm, 15 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['picnic basket crochet', 'kitchen storage oval basket', 'rectangular storage basket'],
  glossaryTerms: [
    { slug: 'oval-base3', term: 'Oval base', definition: 'A foundation chain worked around both long edges with end curves built by adding extra dc at each short end over several rounds.' },
    { slug: 'blo-picnic', term: 'BLO fold round', definition: 'One round worked in back loop only at the base-to-side transition.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Oval basket from Weldon\'s Practical Crochet (series 3, 1880s). Proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A picnic storage basket is 30 x 20 cm and 15 cm tall. The '), gt('oval-base3', 'oval base'), t(' starts from a 10 cm foundation chain and expands over 5 rounds. A '), gt('blo-picnic', 'BLO fold round'), t(' marks the base edge, then the sides work straight up for 15 cm.')),
      p(t('Super-chunky rope on a 10 mm hook. Total yardage is around 160 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Super-chunky cotton rope', qty: '160 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 5)'),
      p(t('Foundation chain 11. Round 1: dc along both edges, 3 dc at each short end. (26 dc.) Rounds 2 to 5: add 6 dc per round at the curves. By round 5: approximately 50 dc, 30 x 20 cm.')),
      h2('Fold and sides'),
      p(t('BLO fold round. Work 1 dc into every stitch in spiral for 15 cm (approximately 12 rounds). Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Press the base flat while damp.')),
      h2('Care'),
      p(t('Spot clean. Machine wash if the rope label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The oval basket is a shorter version of the same shape. Or try the catch-all entry basket for a lower proportioned oval.')),
    ],
  },
},

// ── B23 ── bedroom catch-all tray ──────────────────────────────────────────────
{
  slug: 'bedroom-catch-all-tray',
  title: 'Bedroom catch-all tray',
  subtitle: 'A very shallow round basket for bedside items: watch, earrings, phone.',
  excerpt: 'A flat round tray only 5 cm tall and 20 cm across for a bedside table or dressing table. The low sides keep items visible and easy to pick up.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 dc x 14 rounds = 10 x 10 cm in chunky cotton on a 6 mm hook.',
  finishedSize: 'Round tray, 20 cm diameter, 5 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['bedside tray basket', 'flat crochet bowl', 'valet tray crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-tray', term: 'Magic ring', definition: 'Adjustable loop start for the flat base. Pull the tail closed for a neat centre.' },
    { slug: 'blo-tray', term: 'BLO fold round', definition: 'One round worked in back loop only to create the sharp fold between base and the low sides.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket base from Weldon\'s Practical Crochet (series 2, 1880s). Tray proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A bedroom catch-all tray is 20 cm across and only 5 cm tall. Starting with a '), gt('magic-ring-tray', 'magic ring'), t(', the base grows to 20 cm in dc spiral rounds, then a '), gt('blo-tray', 'BLO fold round'), t(' creates the fold and the sides work up just 5 cm.')),
      p(t('Chunky cotton on a 6 mm hook. Total yardage is around 60 m. The very short sides make this a fast project.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky cotton yarn', qty: '60 m' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 7)'),
      p(t('Rounds 1 to 7: magic ring increase pattern (+8 dc per round) to reach 20 cm. (56 dc.)')),
      h2('Fold and sides'),
      p(t('BLO fold round. Work 1 dc into every stitch in spiral for 7 rounds (approximately 5 cm). Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 30 degrees. Reshape flat while damp.')),
      h2('What to try next'),
      p(t('The bathroom storage basket is a wider, round version. Or try the mini trinket basket for a taller narrow container.')),
    ],
  },
},

// ── B24 ── fruit bowl basket ──────────────────────────────────────────────────
{
  slug: 'fruit-bowl-basket',
  title: 'Fruit bowl basket',
  subtitle: 'A wide open round basket for holding fruit on a kitchen table.',
  excerpt: 'A 28 cm diameter round basket with just 8 cm sides and an open rim. Proportioned to hold a few pieces of fruit without piling them too high. Worked in cotton rope for food safety.',
  difficulty: 'BEGINNER',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-10-0mm',
  gauge: '8 dc x 9 rounds = 10 x 10 cm in super-chunky rope on a 10 mm hook.',
  finishedSize: 'Round basket, 28 cm diameter, 8 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-double-uk'],
  aliases: ['fruit bowl crochet', 'kitchen table basket', 'produce basket crochet'],
  glossaryTerms: [
    { slug: 'magic-ring-fruit', term: 'Magic ring', definition: 'Adjustable loop start for the wide fruit bowl base. Pull the tail closed.' },
    { slug: 'blo-fruit', term: 'BLO fold round', definition: 'One round in back loop only to form the base-to-side fold line.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Round basket from Weldon\'s Practical Crochet (series 2, 1880s). Fruit bowl proportions are a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A fruit bowl basket is 28 cm across and 8 cm tall. A wide '), gt('magic-ring-fruit', 'magic ring'), t(' dc spiral base reaches 28 cm before a '), gt('blo-fruit', 'BLO fold round'), t(' creates the waist. The sides are only 8 cm to keep the fruit visible and easy to reach.')),
      p(t('100% cotton rope is food-safe and machine washable. Total yardage is around 150 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: '100% cotton rope (super-chunky)', qty: '150 m' },
        { name: '10 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 9)'),
      p(t('Rounds 1 to 9: magic ring increase pattern to reach 28 cm. (80 dc.)')),
      h2('Fold and sides'),
      p(t('BLO fold round. Work 1 dc in spiral for 8 rounds (approximately 8 cm). Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The basket should sit flat without rocking. If the base bows up, place a heavy book inside while it dries flat.')),
      h2('Care'),
      p(t('Machine wash 40 degrees. Dry flat. Cotton rope tolerates regular washing well.')),
      h2('What to try next'),
      p(t('The bathroom storage basket uses the same wide-low proportions. Or try the handled market basket for a similar size with handles.')),
    ],
  },
},

// ── B25 ── log holder basket ──────────────────────────────────────────────────
{
  slug: 'log-holder-basket',
  title: 'Log holder basket',
  subtitle: 'An extra-large oval basket for storing a small stack of firewood or logs.',
  excerpt: 'A 50 x 30 cm oval basket at 40 cm tall in very thick rope. Proportioned to hold a small stack of fireplace logs beside a hearth.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'super-chunky',
  hook: 'crochet-hook-12-0mm',
  gauge: '6 dc x 7 rounds = 10 x 10 cm in extra-thick rope on a 12 mm hook.',
  finishedSize: 'Oval basket, 50 x 30 cm, 40 cm tall.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['log basket crochet', 'firewood basket', 'hearth basket crochet'],
  glossaryTerms: [
    { slug: 'oval-base4', term: 'Oval base', definition: 'A foundation chain worked along both edges with dc end curves. For this large basket the foundation chain is 30 cm and the oval grows to 50 x 30 cm over 5 rounds.' },
    { slug: 'blo-log', term: 'BLO fold round', definition: 'One round in back loop only at the base-to-side transition. Creates a clean fold line at the base edge.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Large oval basket construction is a modern crochet application. No direct Weldon source.',
  body: {
    type: 'doc', content: [
      p(t('A log holder basket is 50 x 30 cm and 40 cm tall, worked in thick rope on a 12 mm hook. The '), gt('oval-base4', 'oval base'), t(' starts from a 30 cm foundation chain and expands to 50 x 30 cm. A '), gt('blo-log', 'BLO fold round'), t(' marks the base edge, then the sides rise 40 cm.')),
      p(t('Use 10-12 mm cotton or jute rope for a basket that holds its shape under the weight of logs. Total yardage is around 800 m. This is the largest project in the basket range.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Thick cotton or jute rope (10-12 mm)', qty: '800 m' },
        { name: '12 mm crochet hook', qty: '1' },
        { name: 'Stitch marker', qty: '1' },
        { name: 'Tapestry needle (large eye)', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Base (rounds 1 to 5)'),
      p(t('Foundation chain 31 cm. Round 1: dc along both edges, 3 dc at each short end curve. (About 50 dc.) Rounds 2 to 5: add 6 dc per round at both curves. By round 5: approximately 74 dc, 50 x 30 cm.')),
      h2('Fold and sides'),
      p(t('BLO fold round. Work 1 dc in spiral for approximately 28 rounds (40 cm). Sl st. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The basket is heavy when full of logs; place on a non-scratch mat to protect the floor.')),
      h2('Care'),
      p(t('Spot clean jute. Machine wash cotton rope if the label allows. Reshape while damp.')),
      h2('What to try next'),
      p(t('The laundry basket uses a round base at a similar large scale. Or try the picnic storage basket for a smaller oval of the same construction.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
