/**
 * Generator: D-Homewares Batch 3 — Blankets 26-40
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch3.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...content: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: content }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string; substitutions?: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── 26 ── back loop only throw ────────────────────────────────────────────────
{
  slug: 'back-loop-only-throw',
  title: 'Back loop only throw',
  subtitle: 'Working into the back loop every row builds a ribbed, stretchy fabric.',
  excerpt: 'Inserting the hook into the back loop only of each double crochet creates a horizontal rib across every row. The throw is stretchier and softer-feeling than regular dc.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 dc × 18 rows = 10 × 10 cm in aran yarn with a 5 mm hook, blo.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-back-loop-only'],
  techniqueSlugs: ['crochet-back-loop-only', 'crochet-double-uk'],
  criticalTechniques: ['crochet-back-loop-only'],
  aliases: ['blo throw', 'back loop only blanket', 'ribbed crochet throw'],
  glossaryTerms: [
    { slug: 'blo', term: 'Back loop only', definition: 'Working into only the back loop of the stitch below, leaving the front loop as a visible ridge on the right side. Abbreviated BLO.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each double crochet row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Back-loop-only stitch from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('blo', 'back loop only'), t(' throw is 90 x 100 cm. Every row inserts the hook into the back loop of each dc, leaving the front loop exposed as a horizontal ridge. The fabric stretches more than regular dc.')),
      p(t('Aran weight gives the right balance of warmth and drape for a lap throw. The rib is subtle in smooth yarn and more pronounced in a slightly textured or tweedy aran. Total yardage is around 650 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '650 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 dc x 18 rows = 10 x 10 cm in aran with a 5 mm hook, working BLO throughout. BLO fabric is slightly tighter than regular dc; check a swatch rather than relying on a plain dc gauge.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc-blo: double crochet into the back loop only')),
      ),
      h2('Foundation chain'),
      p(t('Chain 127.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into every chain. Turn. (126 dc, both loops on this first row.)')),
      h2('Row 2 and onward'),
      p(t('Ch 1. Insert hook into the back loop only of every dc across. Turn. (126 dc-blo.)')),
      p(t('Repeat Row 2 until piece measures 100 cm (approximately 180 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The selvedge edges show a chain of front loops; no separate edging is needed. Block lightly with steam.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Tumble dry low. The BLO fabric holds its shape well.')),
      h2('What to try next'),
      p(t('The front loop only baby blanket makes the same rib but the exposed loop sits on the other side. Or try the third-loop htr blanket for a similar flat-fabric effect in a taller stitch.')),
    ],
  },
},

// ── 27 ── front loop only baby blanket ───────────────────────────────────────
{
  slug: 'front-loop-only-baby-blanket',
  title: 'Front loop only baby blanket',
  subtitle: 'Working the front loop leaves a ridge on the wrong side and a smooth face.',
  excerpt: 'Front loop only double crochet leaves the back loop exposed on the wrong side as a ridge, giving the right side a smoother, flatter look than BLO. Good for baby blankets.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc × 20 rows = 10 × 10 cm in DK cotton with a 4 mm hook, flo.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-front-loop-only'],
  techniqueSlugs: ['crochet-front-loop-only', 'crochet-double-uk'],
  criticalTechniques: ['crochet-front-loop-only'],
  aliases: ['flo baby blanket', 'front loop only blanket', 'smooth face crochet blanket'],
  glossaryTerms: [
    { slug: 'flo', term: 'Front loop only', definition: 'Working into only the front loop of the stitch below. The back loop stays exposed on the wrong side as a ridge. Abbreviated FLO.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each double crochet row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Front-loop-only stitch from the loop-variation family in Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('flo', 'front loop only'), t(' baby blanket is 75 x 90 cm. The hook goes into the front loop only of each dc, leaving the back loops exposed as a ridge on the wrong side. The right side is smoother and flatter than BLO fabric.')),
      p(t('DK cotton is ideal for baby blankets because both sides are clean and soft. FLO fabric is slightly looser than regular dc in the same yarn. Total yardage is around 380 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '380 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook, working FLO throughout.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc-flo: double crochet into the front loop only')),
      ),
      h2('Foundation chain'),
      p(t('Chain 121.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into every chain (both loops on this row). Turn. (120 dc.)')),
      h2('Row 2 and onward'),
      p(t('Ch 1. Insert hook into the front loop only of every dc across. Turn. (120 dc-flo.)')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 180 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Work one round of dc (UK) around the perimeter if needed to square the edges.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. The FLO fabric holds its dimensions well.')),
      h2('What to try next'),
      p(t('The back loop only throw makes the ridge on the right side instead. Or try the third-loop htr blanket for a fabric-like texture using a different loop technique.')),
    ],
  },
},

// ── 28 ── herringbone htr throw ───────────────────────────────────────────────
{
  slug: 'herringbone-htr-throw',
  title: 'Herringbone half treble throw',
  subtitle: 'A modified htr that drops one step to create a dense diagonal look.',
  excerpt: 'Herringbone htr routes the yarn-over loop through the back loop of the previous stitch before completing, creating a denser, more diagonal fabric than regular htr.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 htr × 10 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-herringbone-htr'],
  techniqueSlugs: ['crochet-herringbone-htr', 'crochet-half-treble'],
  criticalTechniques: ['crochet-herringbone-htr'],
  aliases: ['herringbone htr blanket', 'hhtr throw', 'diagonal htr blanket'],
  glossaryTerms: [
    { slug: 'hhtr', term: 'Herringbone htr', definition: 'A half treble variation. After the yarn-over, insert the hook, pull up a loop, then pull this loop through the first loop on the hook before completing the stitch. The stitch leans diagonally.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each herringbone htr row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Herringbone htr is a modern stitch variation. No direct Weldon source; synthetic from contemporary technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('hhtr', 'herringbone htr'), t(' throw is 90 x 100 cm. The modified half treble routes the first pull-through the back loop of the stitch below, creating a dense, slightly diagonal surface that is firmer than regular htr.')),
      p(t('The stitch looks similar to woven fabric when worked in a solid aran. It is slightly tighter than regular htr, so the same hook size gives a narrower gauge. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work herringbone htr'),
      p(t('Yarn over. Insert hook into stitch. Pull up a loop (3 loops on hook). Pull this new loop through the first loop on the hook (2 loops remain). Yarn over and pull through both remaining loops. One hhtr made.')),
      h2('Gauge'),
      p(t('14 hhtr x 10 rows = 10 x 10 cm in aran with a 5 mm hook. Swatch before starting the full foundation; the herringbone routing tightens the stitch noticeably.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('hhtr: herringbone half treble')),
      ),
      h2('Foundation chain'),
      p(t('Chain 128.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2. Work 1 hhtr into every chain. Turn. (126 hhtr.)')),
      h2('Row 2 and onward'),
      p(t('Ch 2. Work 1 hhtr into every stitch across. Work 1 hhtr into the top of the turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 100 cm (approximately 100 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Work one round of dc (UK) around the perimeter if the selvedge edges look untidy. Block lightly with steam.')),
      h2('Care'),
      p(t('Handwash wool cool. Dry flat. Acrylic: machine wash 40 degrees, tumble dry low.')),
      h2('What to try next'),
      p(t('The waistcoat stitch throw uses a different unusual stitch that also gives a woven-look surface. Or try the basketweave throw for a more pronounced woven texture.')),
    ],
  },
},

// ── 29 ── waistcoat stitch throw ──────────────────────────────────────────────
{
  slug: 'waistcoat-stitch-throw',
  title: 'Waistcoat stitch throw',
  subtitle: 'A knit-stitch look in crochet, worked into the V of each dc below.',
  excerpt: 'Waistcoat stitch inserts the hook into the two vertical legs of the V of each stitch below instead of the top loops. The fabric surface looks like stocking stitch knitting.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-6-0mm',
  gauge: '12 ws × 14 rows = 10 × 10 cm in aran yarn with a 6 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-waistcoat-stitch'],
  techniqueSlugs: ['crochet-waistcoat-stitch', 'crochet-double-uk'],
  criticalTechniques: ['crochet-waistcoat-stitch'],
  aliases: ['waistcoat stitch blanket', 'knit-look crochet throw', 'jersey stitch blanket'],
  glossaryTerms: [
    { slug: 'waistcoat-stitch', term: 'Waistcoat stitch', definition: 'Insert the hook into both legs of the V of each stitch below (not the top loops). Complete a dc in the usual way. The surface resembles stocking stitch.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each waistcoat stitch row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Waistcoat stitch is a modern crochet technique. No direct Weldon source; synthetic from contemporary technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('waistcoat-stitch', 'waistcoat stitch'), t(' throw is 90 x 100 cm. The hook enters both vertical legs of the V-shape of each stitch below rather than the normal top loops. Completed as a dc, the stitch produces a surface that resembles stocking stitch knitting.')),
      p(t('A slightly larger hook than usual for aran is needed because the insertion into the V tightens the stitch. The fabric is denser and warmer than regular dc. Total yardage is around 720 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '720 g' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to find the V'),
      p(t('After completing a row, look at each dc from the front. You will see a horizontal pair of loops at the top (the normal insertion point) and below them a V-shape made by the two slanted legs of the stitch. Insert the hook through both legs of this V.')),
      h2('Gauge'),
      p(t('12 ws x 14 rows = 10 x 10 cm in aran with a 6 mm hook. The V insertion is tighter than a normal dc, so gauge is tighter despite the larger hook.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('ws: waistcoat stitch (dc into the V of the stitch below)')),
      ),
      h2('Foundation chain'),
      p(t('Chain 108.')),
      h2('Row 1 (set-up row in regular dc)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into every chain (both loops). Turn. (107 dc.)')),
      h2('Row 2 and onward'),
      p(t('Ch 1. Insert hook into the V of each dc below. Complete as dc. Turn. (107 ws.)')),
      p(t('Repeat Row 2 until piece measures 100 cm (approximately 140 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Work one border round of dc around the perimeter if needed. Steam block lightly.')),
      h2('Care'),
      p(t('Handwash wool cool. Dry flat. The V-stitch structure is robust and holds well through gentle washing.')),
      h2('What to try next'),
      p(t('The herringbone htr throw is another stitch that mimics a knit surface. Or try the back loop only throw for a simpler ribbed texture.')),
    ],
  },
},

// ── 30 ── diamond mesh throw ──────────────────────────────────────────────────
{
  slug: 'diamond-mesh-throw',
  title: 'Diamond mesh throw',
  subtitle: 'A diagonal chain-and-treble grid forms open diamond shapes.',
  excerpt: 'Trebles separated by chain spaces at alternating offsets build a diamond-grid mesh across an aran throw. The open structure gives drape without weight.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '6 diamonds × 5 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-mesh-structure'],
  criticalTechniques: ['crochet-treble'],
  aliases: ['diamond mesh blanket', 'open mesh throw', 'trellis crochet blanket'],
  glossaryTerms: [
    { slug: 'diamond-mesh', term: 'Diamond mesh', definition: 'A two-row repeat where a treble, ch-2 space, treble creates open squares that offset between rows to form a diamond or trellis pattern.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Five chains at the start of a diamond mesh row, counting as a tr and ch-2 space.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Trellis mesh from Weldon\'s Practical Crochet (series 1, 1880s). Diamond mesh is the standard trellis variation. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('diamond-mesh', 'diamond mesh'), t(' throw is 90 x 100 cm. Each row places trebles with two-chain spaces between them. The position of each treble offsets between rows to form a diagonal diamond grid.')),
      p(t('Aran weight in a smooth yarn shows the diamond grid most clearly. Mohair or fluffy yarn fills the gaps and loses the mesh structure. Total yardage is around 500 g because the open mesh uses less yarn than solid fabric.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, smooth', qty: '500 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('6 diamonds x 5 rows = 10 x 10 cm in smooth aran with a 5 mm hook. One diamond = one tr + one ch-2 space unit. Measure 6 units across.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('diamond mesh unit: tr, ch 2, skip 2')),
      ),
      h2('Foundation chain'),
      p(t('Chain 136 (45 diamond repeats of 3 ch + 1 starting ch).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 5 (counts as tr + ch 2). Skip 2 ch. *Tr into next ch, ch 2, skip 2 ch*. Repeat. Tr into last ch. Turn. (45 units.)')),
      h2('Row 2 (offset)'),
      p(t('Ch 5. *Tr into the tr of each unit, ch 2*. Repeat. Tr into top of starting ch-5. Turn. (Trebles land in the spaces of Row 1, creating the diamond offset.)')),
      h2('Continuing'),
      p(t('Repeat Row 2 until piece measures 100 cm (approximately 50 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work 2 rounds of dc (UK) around the perimeter: 1 dc into each tr, 2 dc into each ch-2 space. Work 3 dc into each corner. The edging closes the open mesh at the borders.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Wet-block by pinning to the stated dimensions while damp. Blocking is essential for the diamond shape to read clearly.')),
      h2('Care'),
      p(t('Handwash wool cool. Pin flat while damp and allow to dry completely. Acrylic: machine wash 40 degrees, pin flat while damp.')),
      h2('What to try next'),
      p(t('The filet mesh baby blanket uses a similar open grid with optional filled squares for a picture. Or try the v-stitch blanket for a simpler open structure.')),
    ],
  },
},

// ── 31 ── cluster and chain baby blanket ──────────────────────────────────────
{
  slug: 'cluster-chain-baby-blanket',
  title: 'Cluster and chain baby blanket',
  subtitle: 'Three-treble clusters separated by single chains form an open texture.',
  excerpt: 'Groups of three trebles worked together into a single closing stitch alternate with single chain spaces. The cluster-chain pattern gives an open, textured baby blanket.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '8 clusters × 8 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble-cluster'],
  techniqueSlugs: ['crochet-treble-cluster', 'crochet-treble'],
  criticalTechniques: ['crochet-treble-cluster'],
  aliases: ['cluster stitch blanket', 'cluster chain baby blanket', 'treble cluster blanket'],
  glossaryTerms: [
    { slug: 'treble-cluster', term: 'Treble cluster', definition: 'Three trebles worked into the same stitch or space, each left with one loop on the hook, then joined by a final yarn-over through all four loops.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of a treble-height row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Three-treble cluster stitch from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A cluster and chain baby blanket is 75 x 90 cm. Rows of three-treble '), gt('treble-cluster', 'clusters'), t(' alternate with single chains across the width. Each cluster sits in the chain space from the row below, building a textured open grid.')),
      p(t('DK cotton gives a clean cluster shape and washes well. The open gaps between clusters make the blanket lighter and more breathable than a solid fabric, which suits warm weather or layered use. Total yardage is around 320 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '320 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('8 clusters x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Measure 8 clusters across a test strip.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('cl: three-treble cluster into one space')),
      ),
      h2('Foundation chain'),
      p(t('Chain 151 (75 cluster spaces x 2 ch + 1 edge).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Work cl into next stitch. Ch 1. Skip 1*. Repeat. Tr into last ch. Turn. (75 clusters.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Work cl into each ch-1 space. Ch 1*. Repeat. Tr into top of turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 72 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter. Work 1 dc into each cluster top and each ch-1 space along top and bottom. Work 1 dc into each row end on the sides. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to open the cluster spaces.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The shell stitch blanket replaces each cluster with a five-treble fan. Or try the granny square join blanket for a motif-based approach using the same cluster structure.')),
    ],
  },
},

// ── 32 ── fan stitch baby blanket ─────────────────────────────────────────────
{
  slug: 'fan-stitch-baby-blanket',
  title: 'Fan stitch baby blanket',
  subtitle: 'Seven-treble fans separated by dc stitches in a repeating wave.',
  excerpt: 'Seven trebles spread into a wide fan, separated by a double crochet between each fan. The fans alternate with the dc to make a gentle wave pattern across the baby blanket.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '4 fans × 6 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-fan-stitch', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-fan-stitch', 'crochet-treble', 'crochet-double-uk'],
  criticalTechniques: ['crochet-fan-stitch', 'crochet-treble'],
  aliases: ['fan stitch blanket', 'seven treble fan baby blanket', 'wide fan blanket'],
  glossaryTerms: [
    { slug: 'fan-stitch', term: 'Fan stitch', definition: 'Seven trebles worked into the same stitch, spreading out like an open fan. Wider than a five-treble shell.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of a treble-height row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Fan stitch (wide shell) from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('fan-stitch', 'fan stitch'), t(' baby blanket is 75 x 90 cm. Seven trebles spread into one stitch make a wide fan, then a dc sits between each fan. The fans stack vertically on each other across every row.')),
      p(t('DK cotton in a pale colour shows the fan spread clearly. The fans are wider than a standard shell, making them easier to see and count. Total yardage is around 310 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '310 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('4 fans x 6 rows = 10 x 10 cm in DK cotton with a 4 mm hook. One fan takes 7 trebles at the base. At this gauge 30 fans across gives approximately 75 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet (between fans)')),
        li(t('fan: 7 tr into the same stitch or centre dc')),
      ),
      h2('Foundation chain'),
      p(t('Chain 163 (20 fan repeats of 8 ch + 3 edge ch).')),
      h2('Row 1 (right side)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Skip 3 ch. Work 7 tr into next ch (fan made). Skip 3 ch. Dc into next ch*. Repeat. Work last fan, dc into last ch. Turn. (20 fans, 20 dc.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Work 7 tr into each dc (the centre point of each fan below). Work 1 dc into the 4th (centre) tr of each fan*. Repeat. Turn. (20 fans.)')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 54 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter. Work 1 dc into each tr and each dc, 3 dc into corners.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly with steam to open the fan spread.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The shell stitch blanket uses a five-treble fan for a narrower repeat. Or try the v-stitch blanket for a two-treble fan with more open gaps.')),
    ],
  },
},

// ── 33 ── double treble baby blanket ──────────────────────────────────────────
{
  slug: 'double-treble-baby-blanket',
  title: 'Double treble baby blanket',
  subtitle: 'Tall double treble stitches make a very open, lacy DK cotton blanket.',
  excerpt: 'Double trebles are twice the height of a treble. Worked in rows in DK cotton they make a very open, drapey fabric that is almost lacy. A fast blanket for the height gained per row.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '12 dtr × 5 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-treble'],
  techniqueSlugs: ['crochet-double-treble', 'crochet-treble'],
  criticalTechniques: ['crochet-double-treble'],
  aliases: ['double treble blanket', 'dtr baby blanket', 'tall stitch baby blanket'],
  glossaryTerms: [
    { slug: 'double-treble', term: 'Double treble', definition: 'UK: dtr. Two yarn-overs before inserting the hook. Four pairs of loops worked off two at a time. Twice the height of a regular treble.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Four chains at the start of each double treble row, counting as the first dtr.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Double treble stitch from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('double-treble', 'double treble'), t(' baby blanket is 75 x 90 cm. Each row of dtr is tall enough that the blanket needs only about 45 rows to reach 90 cm. The tall stitches leave open gaps that give the fabric an almost lacy quality.')),
      p(t('DK cotton on a 4 mm hook keeps the stitch firm enough that the blanket holds its shape. A thicker hook would make the fabric too open and unstable for a baby blanket. Total yardage is around 280 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '280 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('12 dtr x 5 rows = 10 x 10 cm in DK cotton with a 4 mm hook. The tall stitch means fewer rows; 45 rows reaches 90 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dtr (UK) / tr (US): double treble, two yarn-overs before inserting')),
      ),
      h2('Foundation chain'),
      p(t('Chain 92 (90 dtr + 2 turning chain).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 4 (counts as 1 dtr). Work 1 dtr into every chain from the 5th chain. Turn. (90 dtr.)')),
      h2('Row 2 and onward'),
      p(t('Ch 4. Skip the first stitch. Work 1 dtr into every stitch across. Work 1 dtr into the top of the ch-4 turning chain at the end. Turn. (90 dtr.)')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 45 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter: 1 dc into each dtr along top and bottom, 2 dc into each row-end space on sides, 3 dc into corners. The edging fills the tall open edges.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to even the stitch height.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The v-stitch blanket combines dtr with chain spaces for a more structured open pattern. Or try the filet mesh blanket for a controlled grid using trebles.')),
    ],
  },
},

// ── 34 ── granny stripe throw (adult) ─────────────────────────────────────────
{
  slug: 'granny-stripe-throw',
  title: 'Granny stripe throw',
  subtitle: 'Adult-size granny stripe in aran weight with a self-striping yarn option.',
  excerpt: 'The same granny stripe construction as the baby blanket, scaled up to a 120 x 150 cm adult throw in aran weight. Each row is one colour of treble clusters. Quick to work up.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tr × 7 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Adult throw, 120 x 150 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-granny-cluster'],
  techniqueSlugs: ['crochet-treble', 'crochet-colour-change', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-treble', 'crochet-colour-change'],
  aliases: ['granny stripe throw', 'adult granny stripe blanket', 'treble cluster stripe throw'],
  glossaryTerms: [
    { slug: 'colour-change-crochet', term: 'Colour change', definition: 'Pulling the new colour through the final 2 loops of the last stitch, so the new colour begins the next row cleanly.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row, counting as the first treble.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Granny stripe construction from the Victorian striped afghan family. Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A granny stripe throw is 120 x 150 cm. Each row is a strip of treble clusters in one colour. A '), gt('colour-change-crochet', 'colour change'), t(' at the end of every row swaps to the next colour in the sequence.')),
      p(t('Aran weight on a 5 mm hook works up fast: the throw needs 105 rows and takes around a week of daily sessions. Three colours in a tight palette give the cleanest stripe result. Total yardage is around 900 g (300 g per colour).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, Colour A', qty: '300 g' },
        { name: 'Aran yarn, Colour B', qty: '300 g' },
        { name: 'Aran yarn, Colour C', qty: '300 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 tr x 7 rows = 10 x 10 cm in aran with a 5 mm hook. At this gauge a foundation chain of 169 gives 120 cm width.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('gr-cl: granny cluster, 3 tr into the same ch space')),
      ),
      h2('Foundation chain'),
      p(t('Using Colour A, chain 169. This sets up 56 clusters across.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Skip 3 ch. *Work gr-cl into next ch space, ch 1, skip 1 ch*. Repeat. End with gr-cl, 1 tr into last ch. Turn.')),
      h2('Row 2 onward'),
      p(t('At end of each row, complete the last stitch with the new colour. Work each colour for one row in the sequence A, B, C. Carry unused colours up the side edge.')),
      p(t('Work 105 rows (120 colour repeats of 3 rows gives 45 full stripe repeats of A, B, C). Fasten off.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t(' along the row edges. Block lightly if the edges curl.')),
      h2('Care'),
      p(t('Machine wash 40 degrees, normal cycle. Dry flat. Carried yarns at the edges are protected inside the selvedge.')),
      h2('What to try next'),
      p(t('The chevron throw adds a zigzag shape to the same stripe. Or try the simple treble throw for the same yarn in a plain one-colour version.')),
    ],
  },
},

// ── 35 ── picot edged baby blanket ────────────────────────────────────────────
{
  slug: 'picot-edged-baby-blanket',
  title: 'Picot edged baby blanket',
  subtitle: 'A plain treble blanket with a three-chain picot border.',
  excerpt: 'A simple treble blanket with a three-chain picot border worked on the final edging round. The picot edge adds a decorative finish without changing the main fabric construction.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 tr × 8 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-picot'],
  techniqueSlugs: ['crochet-treble', 'crochet-picot', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-treble', 'crochet-picot'],
  aliases: ['picot blanket', 'picot edge crochet', 'decorative edged baby blanket'],
  glossaryTerms: [
    { slug: 'picot', term: 'Picot', definition: 'A small decorative loop made by chaining 3, then slip stitching back into the base stitch. Creates a tiny raised bump along the edge.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row, counting as the first treble.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Picot stitch from Weldon\'s Practical Crochet (series 1, 1880s). Picot border decoration. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('picot', 'picot'), t(' edged baby blanket is 75 x 90 cm. The main fabric is plain treble rows. The final border round adds a picot every four stitches around the perimeter for a decorative edge.')),
      p(t('DK cotton shows the picot loops clearly without them becoming too floppy. The blanket body is straightforward; the picot edge is the single technique that needs practising. Total yardage is around 360 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '360 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a picot'),
      p(t('After working a dc, ch 3, then sl st back into the dc just made. A small loop (picot) stands up from the edge.')),
      h2('Gauge'),
      p(t('16 tr x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Work the main blanket body first, then add the picot border.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble (main body)')),
        li(t('dc (UK) / sc (US): double crochet (edging base)')),
        li(t('picot: ch 3, sl st into base dc')),
      ),
      h2('Foundation chain'),
      p(t('Chain 121.')),
      h2('Main body (rows 1 to 72)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch across. Tr into turning chain. Turn. Repeat until piece measures 90 cm. Fasten off.')),
      h2('Edging round 1 (plain dc border)'),
      p(t('Join yarn at any corner. Work dc around the full perimeter: 1 dc into each stitch along top and bottom, 1 dc into each row end on sides, 3 dc into each corner. Sl st to close.')),
      h2('Edging round 2 (picot)'),
      p(t('*Work 3 dc, then work 1 picot*. Repeat around the full perimeter. At corners, work 2 dc then a picot at the corner dc. Sl st to close. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly with steam to open the picot loops.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. The picot loops may need a gentle press with a steam iron to stand up again after washing.')),
      h2('What to try next'),
      p(t('The shell stitch blanket replaces the plain body with a fan pattern. Or add a picot edge to any of the other blanket patterns in this collection.')),
    ],
  },
},

// ── 36 ── offset ripple throw ─────────────────────────────────────────────────
{
  slug: 'offset-ripple-throw',
  title: 'Offset ripple throw',
  subtitle: 'A wide ripple in aran weight with a deeper peak and valley than the baby version.',
  excerpt: 'The same ripple construction as the baby blanket but scaled up to an adult throw in aran weight. A wider repeat and deeper increases and decreases give a more pronounced wave.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 dc × 8 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Adult throw, 120 x 150 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-dc2tog'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-dc2tog', 'crochet-treble', 'crochet-colour-change'],
  criticalTechniques: ['crochet-double-uk', 'crochet-dc2tog'],
  aliases: ['adult ripple blanket', 'aran ripple throw', 'large chevron throw'],
  glossaryTerms: [
    { slug: 'dc2tog', term: 'Dc2tog', definition: 'UK: double crochet two together. Insert hook into first stitch, pull up loop; insert into next, pull up loop; yarn over and through all three. One stitch removed.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each ripple row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Ripple (wave stitch) from Weldon\'s Practical Crochet (series 5, 1890s). Adult-size adaptation. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('An offset ripple throw is 120 x 150 cm. The ripple uses the same peak-and-valley construction as the baby blanket but with a wider 16-stitch repeat and '), gt('dc2tog', 'dc2tog'), t(' twice at each valley for a deeper wave.')),
      p(t('Aran weight in a two-colour stripe is the fastest option: two rows per colour, alternating throughout. Total yardage is around 900 g (450 g per colour).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, Colour A', qty: '450 g' },
        { name: 'Aran yarn, Colour B', qty: '450 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 dc x 8 rows = 10 x 10 cm in aran with a 5 mm hook. At this gauge a foundation chain of 163 gives approximately 120 cm (10 full ripple repeats of 16 stitches + edge stitches).')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet (flat sections)')),
        li(t('tr (UK) / dc (US): treble (peak increases)')),
        li(t('dc2tog: valley decrease, worked twice at each valley')),
      ),
      h2('Foundation chain'),
      p(t('Chain 163.')),
      h2('Row 1 (right side)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into 2nd ch from hook. *Skip 2 ch. Work 5 tr into next ch (peak). Skip 2 ch. Dc into each of next 3 ch. Dc2tog twice (valley). Dc into each of next 3 ch*. Repeat. End with peak, dc into last ch. Turn. (10 peaks, 9 valleys.)')),
      h2('Row 2 onward'),
      p(t('Work as Row 1, reading each peak and valley from the row below. Change colour every 2 rows. Work 120 rows total for 150 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t(' along the row edge of the matching colour stripe. Block by pinning to the stated dimensions while damp.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal cycle. Dry flat and pin if needed.')),
      h2('What to try next'),
      p(t('The chevron throw uses the same wave shape with sharper edges. Or try the granny stripe throw for the same two-colour approach in a cluster stitch.')),
    ],
  },
},

// ── 37 ── granny square sampler throw ─────────────────────────────────────────
{
  slug: 'granny-square-sampler-throw',
  title: 'Granny square sampler throw',
  subtitle: 'Mixed granny square designs in the same size joined for a sampler look.',
  excerpt: 'A throw made from six different granny square designs, each 15 cm, in the same yarn. Stitching them together after completion gives a patchwork sampler. A good project for learning motif variations.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '1 four-round granny square = 15 x 15 cm with a 5 mm hook in aran yarn.',
  finishedSize: 'Throw, 90 x 105 cm (6 x 7 squares).',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-slip-stitch', 'crochet-granny-cluster', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-treble', 'crochet-join-as-you-go', 'crochet-whipstitch-join'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-treble'],
  aliases: ['granny square sampler', 'mixed granny throw', 'sampler blanket'],
  glossaryTerms: [
    { slug: 'magic-ring', term: 'Magic ring', definition: 'An adjustable starting loop for working in the round. Tighten to close the centre hole after the first round.' },
    { slug: 'whipstitch-join', term: 'Whipstitch join', definition: 'Sewing two crochet edges together by passing the needle over and over both edges, creating a visible ridge seam on the wrong side.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Granny square sampler from the Victorian motif-blanket tradition. Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A granny square sampler throw is 90 x 105 cm made from 42 squares, each 15 cm, in six different designs. All squares use the same '), gt('magic-ring', 'magic ring'), t(' start and four rounds. They are joined with a '), gt('whipstitch-join', 'whipstitch join'), t(' on the wrong side after blocking.')),
      p(t('The six designs include the classic granny, a solid granny (no chain corners), a flower centre, a sunburst, a cross stitch granny, and a cluster granny. Use one yarn colour or several; a single colour shows the stitch differences most clearly. Total yardage is around 800 g in aran.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn (one or more colours)', qty: '800 g total' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
      ]),
      h2('Gauge'),
      p(t('One four-round granny square = 15 x 15 cm with a 5 mm hook in aran yarn. Make one test square of each design to confirm consistent sizing before making all 42.')),
      h2('Design list (7 squares each)'),
      ul(
        li(t('Classic granny: tr clusters with ch-2 corners, open sides')),
        li(t('Solid granny: same as classic but ch-1 corners only, no open chain spaces')),
        li(t('Flower centre: magic ring with dc petals in round 1, clusters in rounds 2 to 4')),
        li(t('Sunburst: extended tr spokes radiating from centre before the cluster rounds')),
        li(t('Cross granny: cross-shaped cluster pairs in alternating positions')),
        li(t('Cluster granny: two-treble clusters replacing the three-treble standard clusters')),
      ),
      h2('Joining'),
      p(t('Block all 42 squares before joining. Arrange in a 6 x 7 grid, mixing the designs. Join with whipstitch on the wrong side, working through the back loops of each matching edge.')),
      h2('Edging'),
      p(t('Work 2 rounds of dc (UK) around the full perimeter. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The seam ridges are hidden on the wrong side.')),
      h2('Care'),
      p(t('Machine wash 40 degrees, normal. Dry flat. Re-block if the squares pull apart at the joins.')),
      h2('What to try next'),
      p(t('The granny hexagon blanket uses a different geometry in the same motif-join approach. Or try the granny square join baby blanket for a single-design version in DK.')),
    ],
  },
},

// ── 38 ── linked treble throw ─────────────────────────────────────────────────
{
  slug: 'linked-treble-throw',
  title: 'Linked treble throw',
  subtitle: 'Linked trebles connect horizontally as they are worked for a denser, flatter fabric.',
  excerpt: 'Linked trebles insert the hook into the side loop of the previous stitch before completing, creating a connected horizontal join between stitches. The fabric is denser than regular treble.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '13 ltr × 8 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-linked-dc'],
  techniqueSlugs: ['crochet-linked-dc', 'crochet-treble'],
  criticalTechniques: ['crochet-linked-dc'],
  aliases: ['linked treble blanket', 'linked stitch throw', 'dense treble throw'],
  glossaryTerms: [
    { slug: 'linked-dc', term: 'Linked dc', definition: 'A double crochet worked by first inserting the hook into the side loop of the previous stitch, then into the base stitch. The horizontal link closes the gap between stitches.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each linked treble row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Linked stitch technique from the joined-stitch family in Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('linked-dc', 'linked dc'), t(' throw is 90 x 100 cm. Each stitch inserts the hook into the side loop of the previous stitch before inserting into the base, creating a horizontal link that closes the gap between stitches. The fabric is denser than regular dc with no visible holes.')),
      p(t('The linked dc works identically in all yarn weights; aran on a 5 mm hook gives a lap-throw weight. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a linked dc'),
      p(t('Insert hook into the right-hand side loop of the previous stitch, pull up a loop. Now insert hook into the next stitch, pull up a loop (3 loops on hook). Yarn over and draw through all 3. One linked dc made.')),
      h2('Gauge'),
      p(t('13 ldc x 8 rows = 10 x 10 cm in aran with a 5 mm hook. The linking tightens the stitch; gauge is closer to dc than to treble in the same yarn.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('ldc: linked double crochet')),
      ),
      h2('Foundation chain'),
      p(t('Chain 117.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 ldc into every chain. Turn. (115 ldc.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. Work 1 ldc into every stitch across. Work 1 ldc into the top of the turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 100 cm (approximately 80 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The selvedge is clean. Block lightly with steam.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Tumble dry low. The dense linked fabric holds shape well through washing.')),
      h2('What to try next'),
      p(t('The herringbone htr throw uses a different mid-stitch technique that also gives a denser surface. Or try the waistcoat stitch throw for a knit-look texture.')),
    ],
  },
},

// ── 39 ── crocodile stitch blanket ────────────────────────────────────────────
{
  slug: 'crocodile-stitch-accent-blanket',
  title: 'Crocodile stitch accent blanket',
  subtitle: 'Scale-like crocodile stitch panels on a treble background.',
  excerpt: 'Crocodile stitch wraps trebles around a base stitch pair to make overlapping scale shapes. Worked in panels across an accent blanket in chunky yarn on a 6 mm hook.',
  difficulty: 'ADVANCED',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-6-0mm',
  gauge: '4 scales × 3 rows = 10 × 10 cm in chunky yarn with a 6 mm hook.',
  finishedSize: 'Accent blanket, 60 x 80 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-crocodile-stitch'],
  techniqueSlugs: ['crochet-crocodile-stitch', 'crochet-treble'],
  criticalTechniques: ['crochet-crocodile-stitch'],
  aliases: ['crocodile stitch blanket', 'scale stitch blanket', 'dragon scale crochet'],
  glossaryTerms: [
    { slug: 'crocodile-stitch', term: 'Crocodile stitch', definition: 'Five trebles worked down one leg of a base stitch pair, then five more up the other leg, creating a scale or petal shape that overlaps the neighbouring scales.' },
    { slug: 'base-v', term: 'Base V', definition: 'The pair of trebles in the foundation row that each crocodile scale wraps around. Each V supports one scale.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crocodile stitch is a modern technique. No direct Weldon source; synthetic from contemporary technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('crocodile-stitch', 'crocodile stitch'), t(' accent blanket is 60 x 80 cm. Each scale wraps five trebles down one leg of a '), gt('base-v', 'base V'), t(' and five more up the other, forming an overlapping tile. The scales sit on a plain treble background.')),
      p(t('Chunky yarn on a 6 mm hook makes scales large enough to see clearly. The scale structure means the blanket is heavier than its size suggests. Total yardage is around 400 g chunky. This is a slow pattern to work; it takes longer per row than a plain treble blanket.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky yarn', qty: '400 g' },
        { name: '6 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('4 scales x 3 rows = 10 x 10 cm in chunky with a 6 mm hook. Work a test swatch of two full scale rows before starting the blanket.')),
      h2('Foundation row (base V row)'),
      p(t('Chain 61. Work *tr, ch 2, tr* into every 4th chain. This creates the base V pairs for the first scale row. (15 Vs.)')),
      h2('Scale row'),
      p(t('Work 5 tr down the right leg of the first V (counting from the top). Rotate work. Work 5 tr up the left leg of the same V (back upward). One scale made. Sl st to the ch-2 space of the next V. Repeat for every V across the row.')),
      h2('Second base row'),
      p(t('After the scale row, work a new base V row offset by half a repeat, placing each new V over the sl st join between two scales below. This offsets the scale rows for a true tile pattern.')),
      h2('Continuing'),
      p(t('Alternate scale rows and offset base rows. Work until piece measures 80 cm (approximately 8 scale rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The crocodile stitch forms a self-finished edge; no additional edging is needed.')),
      h2('Care'),
      p(t('Handwash chunky wool cool. Dry flat. Machine wash acrylic 40 degrees; the scale structure holds.')),
      h2('What to try next'),
      p(t('The bobble blanket is a more accessible raised-texture pattern at the same advanced level. Or try the puff stitch throw for a softer three-dimensional texture.')),
    ],
  },
},

// ── 40 ── mixed stitch sampler baby blanket ───────────────────────────────────
{
  slug: 'mixed-stitch-sampler-baby-blanket',
  title: 'Mixed stitch sampler baby blanket',
  subtitle: 'Six stitch sections, each 15 rows, give a horizontal sampler of techniques.',
  excerpt: 'Six bands of different stitches, each 15 rows tall, combine into one baby blanket. Treble, shell, v-stitch, bobble, moss, and half treble each fill one band. A good practice piece.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts × 10 rows = 10 × 10 cm average across bands in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm approximately.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-shell', 'crochet-v-stitch', 'crochet-bobble', 'crochet-double-uk', 'crochet-half-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-shell', 'crochet-v-stitch', 'crochet-bobble', 'crochet-double-uk', 'crochet-half-treble'],
  criticalTechniques: ['crochet-treble', 'crochet-bobble'],
  aliases: ['sampler crochet blanket', 'stitch sampler baby blanket', 'mixed technique blanket'],
  glossaryTerms: [
    { slug: 'sampler-band', term: 'Sampler band', definition: 'A horizontal section of a blanket worked in a single stitch pattern. Each band is a self-contained practice strip.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'The number of chains at the start of each row varies by stitch: 1 for dc/moss, 2 for htr, 3 for tr/v-stitch/shell/bobble.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Sampler blanket from the pattern-band tradition. No direct Weldon source; a modern teaching format.',
  body: {
    type: 'doc', content: [
      p(t('A mixed stitch '), gt('sampler-band', 'sampler'), t(' baby blanket is approximately 75 x 90 cm. Six 15-row bands in different stitches stack vertically. Each band is a separate technique practice: treble, shell, v-stitch, bobble, moss, and half treble.')),
      p(t('DK cotton in a single colour lets the stitch textures read clearly. The slight variation in row height between stitches means the blanket may not be exactly 90 cm; 15 rows per band gives a good approximation of equal sections. Total yardage is around 360 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '360 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 121. All bands are worked on the same 120-stitch base.')),
      h2('Band 1 (rows 1 to 15): plain treble'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch. Tr into turning chain. Turn. Repeat for 15 rows.')),
      h2('Band 2 (rows 16 to 30): shell stitch'),
      p(t('Ch 3. *Skip 2, work 5 tr into next stitch (shell), skip 2, dc*. Repeat. Work each shell over the dc from the row below. 15 rows.')),
      h2('Band 3 (rows 31 to 45): v-stitch'),
      p(t('Ch 3. *Work (tr, ch 1, tr) into next ch-1 space from below (v-stitch)*. Tr into turning chain. 15 rows.')),
      h2('Band 4 (rows 46 to 60): bobble'),
      p(t('Plain treble rows with a bobble (3-tr cluster) every 4th stitch on every other row, offset by 2 stitches between bobble rows. 15 rows.')),
      h2('Band 5 (rows 61 to 75): moss stitch'),
      p(t('Ch 1. *Dc, ch 1, skip 1*. Repeat. Each dc sits in the ch-1 space of the row below. 15 rows.')),
      h2('Band 6 (rows 76 to 90): half treble'),
      p(t('Ch 2. Work 1 htr into every stitch. Htr into turning chain. 15 rows. Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter: 1 dc into each stitch and space, 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to even the bands.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('Take any band you enjoyed and work it as a full blanket. The shell stitch, bobble, and moss stitch all have dedicated blanket patterns in this collection.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
