/**
 * Generator: D-Homewares Batch 4 — Blankets 41-55
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch4.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── 41 ── solomon's knot throw ────────────────────────────────────────────────
{
  slug: 'solomons-knot-throw',
  title: "Solomon's knot throw",
  subtitle: 'Extended loop knots form an open lace-like mesh across an aran throw.',
  excerpt: "Solomon's knot pulls a long loop and locks it with a dc, then repeats to build an open knotted mesh. The result is a lightweight lace-like throw in aran weight.",
  difficulty: 'ADVANCED',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '5 knots x 6 rows = 10 x 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-solomons-knot'],
  techniqueSlugs: ['crochet-solomons-knot', 'crochet-double-uk'],
  criticalTechniques: ['crochet-solomons-knot'],
  aliases: ["solomon's knot blanket", 'lovers knot throw', 'knotted mesh blanket'],
  glossaryTerms: [
    { slug: 'solomons-knot', term: "Solomon's knot", definition: 'Pull up a long loop (2-3 cm), yarn over and lock it with a single dc. Repeating makes an open knotted mesh. Also called a lover\'s knot.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two Solomon\'s knots worked at the end of each row to bring the hook to the correct height for the next row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: "Solomon's knot from Weldon's Practical Crochet (series 4, 1880s). Open knot mesh. Internet Archive.",
  body: {
    type: 'doc', content: [
      p(t('A '), gt('solomons-knot', "Solomon's knot"), t(" throw is 90 x 100 cm. Each knot is one long pulled loop locked with a dc. Rows of knots connect at their lock stitches to build an open mesh that looks like lace.")),
      p(t("Aran weight makes the knots large enough to work comfortably. The mesh uses much less yarn than solid fabric. Total yardage is around 450 g. Solomon's knot is considered advanced because the open mesh has no defined base row and the lock points can shift if the long loops are not pulled to a consistent height.")),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '450 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work one knot'),
      p(t('Pull the working loop up to about 2 cm (the knot height). Yarn over and draw through (chain made). Insert hook under the back loop of this long chain. Yarn over and draw up a loop (2 loops on hook). Yarn over and draw through both loops. One knot made.')),
      h2('Gauge'),
      p(t('5 knots x 6 rows = 10 x 10 cm in aran with a 5 mm hook. Pull every knot to exactly the same 2 cm height for an even mesh. Practice on a test swatch until the knot height is consistent.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain (inside the knot)')),
        li(t('dc (UK) / sc (US): double crochet (lock stitch of each knot)')),
        li(t('SK: Solomon\'s knot')),
      ),
      h2('Foundation row'),
      p(t('Make a slip knot and work 46 SK in a chain. This forms the base of the mesh (one row of knots).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of 2 SK at end of foundation. *Work 1 dc into the lock dc of every 2nd knot, then 2 SK*. Repeat across. Turn. (22 mesh pairs.)')),
      h2('Row 2 and onward'),
      p(t('Work 2 SK, *1 dc into the lock dc between two knots from below, 2 SK*. Repeat. Turn.')),
      p(t('Continue until piece measures 100 cm. Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter: 1 dc into each lock stitch and 2 dc across each knot gap. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block firmly by wet-blocking and pinning to the stated dimensions.')),
      h2('Care'),
      p(t('Handwash cool. Pin flat while damp. The mesh structure opens when wet and must be pinned back to size.')),
      h2('What to try next'),
      p(t('The diamond mesh throw uses a structured treble-and-chain grid for a similar open look that is easier to keep even. Or try the v-stitch blanket for an open mesh within a counted-row structure.')),
    ],
  },
},

// ── 42 ── cross stitch crochet throw ──────────────────────────────────────────
{
  slug: 'cross-stitch-crochet-throw',
  title: 'Cross stitch crochet throw',
  subtitle: 'Pairs of trebles worked in X formation make a woven-looking surface.',
  excerpt: 'Cross stitch crochet works the second of each stitch pair into a position behind the first, forming an X. Rows of X-stitches produce a dense woven-looking surface on an aran throw.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '12 cross pairs x 7 rows = 10 x 10 cm in aran with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-cross-stitch-crochet'],
  techniqueSlugs: ['crochet-cross-stitch-crochet', 'crochet-treble'],
  criticalTechniques: ['crochet-cross-stitch-crochet'],
  aliases: ['cross stitch crochet blanket', 'x-stitch throw', 'crossed treble blanket'],
  glossaryTerms: [
    { slug: 'cross-st', term: 'Cross stitch crochet', definition: 'Work a treble into the second stitch, then a treble back into the first stitch (in front of the previous one). The two stitches cross to form an X.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Crossed treble from Weldon\'s Practical Crochet (series 3, 1880s). Cross stitch crochet is a modern name for the same technique. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('cross-st', 'cross stitch crochet'), t(' throw is 90 x 100 cm. Each pair of trebles is worked out of order: the second stitch first, then the first stitch in front of it. The crossing produces an X on the surface.')),
      p(t('In aran weight the X shapes are prominent and make the fabric look woven. The cross pairs draw in slightly, making the fabric narrower than a regular treble row of the same stitch count. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a cross pair'),
      p(t('Skip 1 stitch. Work 1 tr into the next stitch (2nd stitch). Work 1 tr into the skipped stitch, bringing the hook in front of the first treble. One cross pair made (2 stitches used).')),
      h2('Gauge'),
      p(t('12 cross pairs x 7 rows = 10 x 10 cm in aran with a 5 mm hook. One cross pair uses 2 stitches. Foundation chain must be an even number.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('cross pair: 2 tr worked in reversed order')),
      ),
      h2('Foundation chain'),
      p(t('Chain 129 (128 stitches = 64 cross pairs).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Skip 1, tr into next, tr into skipped (cross pair made)*. Repeat to last stitch. Tr into last stitch. Turn. (64 cross pairs.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Work cross pair across every 2 stitches*. Tr into top of turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 100 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Steam block to settle the cross pairs.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Dry flat.')),
      h2('What to try next'),
      p(t('The basketweave throw uses front and back post stitches for a different woven texture. Or try the linked treble throw for a dense flat-surface effect.')),
    ],
  },
},

// ── 43 ── triple treble lap blanket ───────────────────────────────────────────
{
  slug: 'triple-treble-lap-blanket',
  title: 'Triple treble lap blanket',
  subtitle: 'Very tall stitches make a dramatic open lattice in chunky yarn.',
  excerpt: 'Triple trebles need three yarn-overs and are nearly twice the height of a double treble. Worked in chunky yarn they form a dramatic open lattice that makes a quick lap blanket.',
  difficulty: 'BEGINNER',
  yarnWeight: 'chunky',
  hook: 'crochet-hook-8-0mm',
  gauge: '7 trtr x 3 rows = 10 x 10 cm in chunky yarn with an 8 mm hook.',
  finishedSize: 'Lap blanket, 80 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-triple-treble'],
  techniqueSlugs: ['crochet-triple-treble', 'crochet-double-treble'],
  criticalTechniques: ['crochet-triple-treble'],
  aliases: ['triple treble blanket', 'ttr lap blanket', 'tall stitch throw'],
  glossaryTerms: [
    { slug: 'triple-treble', term: 'Triple treble', definition: 'UK: trtr. Three yarn-overs before inserting the hook. Five draw-throughs to complete. One of the tallest standard crochet stitches.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Five chains at the start of each triple treble row, counting as the first trtr.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Triple treble stitch from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('triple-treble', 'triple treble'), t(' lap blanket is 80 x 90 cm. The very tall stitches mean the blanket needs only about 27 rows to reach 90 cm in chunky yarn. The gaps between stitches are large and give the fabric a dramatic open look.')),
      p(t('Chunky yarn keeps the open stitch from becoming too flimsy. A fine yarn would produce a lacework-like fabric; chunky gives enough body for a lap blanket. Total yardage is around 350 g because the tall open stitch uses less yarn than a dense fabric.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Chunky yarn', qty: '350 g' },
        { name: '8 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a triple treble'),
      p(t('Yarn over 3 times. Insert hook into stitch. Pull up loop (5 loops on hook). *Yarn over, draw through 2 loops*. Repeat 4 times. One trtr made.')),
      h2('Gauge'),
      p(t('7 trtr x 3 rows = 10 x 10 cm in chunky with an 8 mm hook. Each row gains a lot of height; check after 5 rows to confirm the pace.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('trtr (UK) / tr (US): triple treble')),
      ),
      h2('Foundation chain'),
      p(t('Chain 57 (56 trtr + 1 edge).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 5. Work 1 trtr into every chain from the 6th. Turn. (56 trtr.)')),
      h2('Row 2 and onward'),
      p(t('Ch 5. Skip the first stitch. Work 1 trtr into every stitch. Work 1 trtr into the top of the turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 27 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work 2 rounds of dc (UK) around the perimeter. Work 1 dc into each trtr along top and bottom. Work 3 dc into each row-end gap on the sides. Work 3 dc into each corner. The edging closes the very open side edges.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to open the lattice.')),
      h2('Care'),
      p(t('Handwash wool cool. Dry flat. Acrylic: machine wash 40 degrees, tumble dry low.')),
      h2('What to try next'),
      p(t('The double treble baby blanket uses a slightly shorter stitch in DK for a more controlled open fabric. Or try the chunky throw for a dense dc version in the same yarn weight.')),
    ],
  },
},

// ── 44 ── overlay mosaic throw ────────────────────────────────────────────────
{
  slug: 'overlay-mosaic-throw',
  title: 'Overlay mosaic throw',
  subtitle: 'Surface slip stitches overlay a base fabric to add a second colour pattern.',
  excerpt: 'Overlay crochet adds surface slip stitches on top of a plain treble background. Working rows of surface stitches in a second colour creates a simple geometric pattern without changing yarns mid-row.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tr x 8 rows = 10 x 10 cm in aran with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-surface-slip-stitch'],
  techniqueSlugs: ['crochet-surface-slip-stitch', 'crochet-treble'],
  criticalTechniques: ['crochet-surface-slip-stitch', 'crochet-treble'],
  aliases: ['overlay crochet throw', 'surface crochet blanket', 'mosaic throw'],
  glossaryTerms: [
    { slug: 'surface-sl-st', term: 'Surface slip stitch', definition: 'A slip stitch worked on the surface of a completed fabric by inserting the hook through the fabric from front to back, looping yarn, and pulling through. Used to add colour and texture on top of a base.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row in the base fabric.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Surface slip stitch documented in Weldon\'s Practical Crochet (series 3, 1880s). Overlay pattern application is modern. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('An overlay mosaic throw is 90 x 100 cm. The base is a plain treble fabric in Colour A. After completing the base, '), gt('surface-sl-st', 'surface slip stitches'), t(' in Colour B are worked along the rows of the base to add a geometric pattern.')),
      p(t('The two-step method avoids mid-row colour changes: the base is one solid colour and the overlay is applied separately. A simple diamond or stripe pattern is easiest for a first overlay project. Total yardage is around 600 g A and 150 g B.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, Colour A (base)', qty: '600 g' },
        { name: 'Aran yarn, Colour B (overlay)', qty: '150 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 tr x 8 rows = 10 x 10 cm in aran with a 5 mm hook for the base fabric.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble (base fabric)')),
        li(t('surface sl st: slip stitch worked on the surface of the base')),
      ),
      h2('Step 1: base fabric'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch across. Tr into turning chain. Turn. Repeat until piece measures 100 cm (approximately 80 rows). Fasten off. Block the base fabric flat.')),
      h2('Step 2: surface overlay'),
      p(t('Using Colour B and holding yarn behind the work, insert the hook from front to back between the posts of two stitches on Row 1. Pull a loop through to the front. *Insert hook into the next space, pull a loop through and through the loop on the hook (surface sl st made)*.')),
      p(t('Work horizontal lines of surface stitches every 4 rows across the base. Add diagonal lines crossing the horizontal at every 4th stitch for a diamond grid pattern. Cut Colour B between each line, leaving 10 cm tails.')),
      h2('Finishing'),
      p(t('Secure all Colour B tails with '), gt('weaving-in-ends', 'weaving in ends'), t(' on the wrong side. Work one round of dc (UK) around the perimeter in Colour A. Work 3 dc into each corner.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Dry flat. The surface stitches are secured through the base and hold through washing.')),
      h2('What to try next'),
      p(t('The staggered stripe throw adds colour mid-row using a different method. Or try the c2c blanket for a diagonal colour-block approach that needs no surface work.')),
    ],
  },
},

// ── 45 ── petal stitch throw ──────────────────────────────────────────────────
{
  slug: 'petal-stitch-throw',
  title: 'Petal stitch throw',
  subtitle: 'Pairs of shells stagger to make overlapping petal shapes across an aran throw.',
  excerpt: 'A petal stitch places two five-treble shells sharing a base stitch, then offsets the next pair by three stitches. The overlapping shells look like flower petals across the surface.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '5 petals x 5 rows = 10 x 10 cm in aran with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-shell'],
  techniqueSlugs: ['crochet-shell', 'crochet-treble'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['petal stitch crochet', 'flower petal throw', 'overlapping shell blanket'],
  glossaryTerms: [
    { slug: 'shell-stitch', term: 'Shell stitch', definition: 'Five trebles worked into the same stitch, spreading into a fan shape. Two shells sharing a base make a double petal.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble-height row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Petal stitch from the double-shell family in Weldon\'s Practical Crochet (series 4, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A petal stitch throw is 90 x 100 cm. Two five-treble '), gt('shell-stitch', 'shells'), t(' share one base stitch, and the next pair starts 3 stitches later. The result is a row of overlapping petal shapes across the fabric.')),
      p(t('Aran weight gives petals that are large enough to see clearly. A two-colour version in alternating rows shows the petal overlap best. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('5 petals (petal = 2 shells sharing 1 base) x 5 rows = 10 x 10 cm in aran with a 5 mm hook.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('shell: 5 tr into one stitch')),
        li(t('petal: 2 shells into the same base stitch, worked in the same stitch then 3 stitches earlier')),
      ),
      h2('Foundation chain'),
      p(t('Chain 127 (42 petal repeats of 3 ch + 1 edge).')),
      h2('Row 1 (set-up treble row)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every chain. Turn. (125 tr.)')),
      h2('Row 2 (petal row)'),
      p(t('Ch 1. Dc into first stitch. *Skip 2, work 5 tr into next stitch (first half-petal), skip 2, dc. Skip 2, work 5 tr into same stitch as last shell (second half-petal, petal complete), skip 2, dc*. Repeat. Turn.')),
      h2('Row 3 (offset petal row)'),
      p(t('Ch 1. Dc into first stitch. Skip 1. Work petal starting 3 stitches from previous petal pair. Continue offset petals across. Turn.')),
      h2('Continuing'),
      p(t('Alternate Row 2 and Row 3 until piece measures 100 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to open the petal fans.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Dry flat.')),
      h2('What to try next'),
      p(t('The fan stitch blanket uses a single seven-treble fan without the overlap. Or try the shell stitch baby blanket for a simpler non-overlapping shell pattern.')),
    ],
  },
},

// ── 46 ── colour block throw ──────────────────────────────────────────────────
{
  slug: 'colour-block-throw',
  title: 'Colour block throw',
  subtitle: 'Four solid rectangles of treble in different colours, sewn together flat.',
  excerpt: 'Four large rectangles in different colours, each 45 x 75 cm, joined side by side. Each piece is plain treble in one colour. Joining at the end makes a 90 x 150 cm throw.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tr x 7 rows = 10 x 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Throw, 90 x 150 cm (4 panels joined).',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-slip-stitch-seam'],
  techniqueSlugs: ['crochet-treble', 'crochet-slip-stitch-seam'],
  criticalTechniques: ['crochet-treble', 'crochet-slip-stitch-seam'],
  aliases: ['colour block crochet', 'block throw', 'panel join blanket'],
  glossaryTerms: [
    { slug: 'slip-stitch-seam', term: 'Slip stitch seam', definition: 'Joining two crochet pieces by holding them with right sides together and working a row of slip stitches through both layers. Makes a neat seam on the wrong side.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row, counting as the first treble.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Colour block panel construction from the modular blanket tradition. Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A colour block throw is 90 x 150 cm made from four panels joined with a '), gt('slip-stitch-seam', 'slip stitch seam'), t('. Each panel is 45 x 75 cm of plain treble in one colour. Joining the four panels side by side makes the full throw.')),
      p(t('Four panels are easier to carry around than a full throw on the hook. Aran weight in four contrasting or complementary colours gives a bold geometric result. Total yardage is around 800 g (200 g per colour).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, Colour A', qty: '200 g' },
        { name: 'Aran yarn, Colour B', qty: '200 g' },
        { name: 'Aran yarn, Colour C', qty: '200 g' },
        { name: 'Aran yarn, Colour D', qty: '200 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 tr x 7 rows = 10 x 10 cm in aran with a 5 mm hook. At this gauge each panel needs a foundation chain of 64 and 52 rows to reach 45 x 75 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble (panel body)')),
        li(t('sl st: slip stitch (seam joining)')),
      ),
      h2('Each panel (make 4 in different colours)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch across. Tr into turning chain. Turn. Repeat until panel measures 75 cm (approximately 52 rows). Fasten off. Block all panels to the same dimensions before joining.')),
      h2('Joining panels'),
      p(t('Hold two panels with right sides together. Insert hook through both back loops of each matching edge stitch. Work a row of sl st through both layers from end to end. Repeat to join all 4 panels into one piece.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the full perimeter of the joined throw. Work 1 dc into each stitch along the top and bottom. Work 1 dc into each row end on the sides. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block the joined throw flat to align the panels.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Dry flat. The seams hold through machine washing.')),
      h2('What to try next'),
      p(t('The granny square sampler throw joins individual motifs using the same approach. Or try the staggered stripe throw for colour blocks within one continuous fabric.')),
    ],
  },
},

// ── 47 ── tunisian simple stitch blanket ──────────────────────────────────────
{
  slug: 'tunisian-simple-stitch-blanket',
  title: 'Tunisian simple stitch blanket',
  subtitle: 'The entry-level Tunisian stitch worked flat on a long hook or extension cable.',
  excerpt: 'Tunisian simple stitch is worked in two passes: a forward pass that loads loops onto a long hook, then a return pass that works them off. The fabric looks like a woven grid.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tss x 12 rows = 10 x 10 cm in aran with a 5 mm Tunisian hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-tunisian-simple'],
  techniqueSlugs: ['crochet-tunisian-simple', 'crochet-tunisian-extended'],
  criticalTechniques: ['crochet-tunisian-simple'],
  aliases: ['Tunisian crochet blanket', 'afghan stitch blanket', 'tss baby blanket'],
  glossaryTerms: [
    { slug: 'tunisian-simple-st', term: 'Tunisian simple stitch', definition: 'Forward pass: insert hook under each vertical bar and pull up a loop (all loops held on hook). Return pass: yarn over, draw through 2 loops at a time until 1 loop remains. Abbreviated tss.' },
    { slug: 'tunisian-cast-on', term: 'Tunisian cast-on', definition: 'The foundation chain for Tunisian crochet. Pull up a loop from each chain on the first forward pass to set up the initial row of loops.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Tunisian simple stitch (afghan stitch) from Weldon\'s Practical Needlework vol. 1, c.1885. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('tunisian-simple-st', 'Tunisian simple stitch'), t(' blanket is 75 x 90 cm. Each row has a forward pass loading loops and a return pass working them off. The fabric surface looks like a woven grid and lies flat without curling when blocked.')),
      p(t('A Tunisian hook or a standard hook with an extension cable is needed to hold all loops for a 75 cm wide piece. Aran weight on a 5 mm hook. Total yardage is around 700 g. Tunisian fabric uses more yarn than regular crochet because the stitch is denser.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm Tunisian hook with cable, or 40 cm Tunisian hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Blocking mats and pins', qty: '1 set' },
      ]),
      h2('Gauge'),
      p(t('14 tss x 12 rows = 10 x 10 cm in aran with a 5 mm Tunisian hook. Tunisian gauge is tighter than regular dc in the same yarn. Swatch before starting the full foundation.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain (foundation)')),
        li(t('tss: Tunisian simple stitch (forward pass: pick up vertical bars; return: work off 2 at a time)')),
      ),
      h2('Foundation'),
      p(gt('tunisian-cast-on', 'Tunisian cast-on'), t(': chain 105. Forward pass row 0: insert hook under the back bump of each chain, pull up a loop. (105 loops on hook.)')),
      p(t('Return pass row 0: yarn over, draw through 1 loop. *Yarn over, draw through 2 loops*. Repeat until 1 loop remains.')),
      h2('Rows 1 onward'),
      p(t('Forward pass: insert hook under each vertical bar from right to left, pull up a loop. (105 loops on hook.)')),
      p(t('Return pass: yarn over, draw through 1, *yarn over, draw through 2*. Repeat. (1 loop remains.)')),
      p(t('Repeat forward and return passes until piece measures 90 cm (approximately 108 rows). Work a final row of sl st across all vertical bars to cast off. Fasten off.')),
      h2('Finishing'),
      p(t('Tunisian fabric curls at the edges until blocked. Wet-block firmly: submerge in cool water, pin to the stated dimensions, and allow to dry completely. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Handwash cool. Pin flat while damp each time. Tunisian fabric can revert to curling if it dries in a heap.')),
      h2('What to try next'),
      p(t('The Tunisian knit stitch blanket produces a fabric that looks like stocking stitch knitting. Or try the waistcoat stitch throw for a knit-look in regular crochet without the long hook.')),
    ],
  },
},

// ── 48 ── striped half treble baby blanket ────────────────────────────────────
{
  slug: 'striped-htr-baby-blanket',
  title: 'Striped half treble baby blanket',
  subtitle: 'Half treble rows in a four-colour stripe sequence for a baby blanket.',
  excerpt: 'Half treble rows in four colours produce a compact, warm baby blanket with clean stripe edges. The stitch is between dc and treble in height and makes a denser fabric.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 htr x 12 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-half-treble'],
  techniqueSlugs: ['crochet-half-treble', 'crochet-colour-change'],
  criticalTechniques: ['crochet-half-treble', 'crochet-colour-change'],
  aliases: ['striped htr blanket', 'half treble stripe baby blanket', 'htr stripe blanket'],
  glossaryTerms: [
    { slug: 'colour-change-crochet', term: 'Colour change', definition: 'Pulling the new colour through the final loop of the last stitch, so the next row begins in the new colour cleanly.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each htr row, counting as the first htr.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Half treble stitch from Weldon\'s Practical Crochet (series 1, 1880s). Stripe sequence is a modern colour application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A striped htr baby blanket is 75 x 90 cm. Half treble rows in a four-colour rotation build clean horizontal stripes in DK cotton. The '), gt('colour-change-crochet', 'colour changes'), t(' happen at the end of each row.')),
      p(t('DK cotton in four colours at 2 rows per stripe gives a narrow candy-stripe look. At 6 rows per colour the stripes are bolder. Total yardage is around 380 g (95 g per colour at equal stripe width).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton, Colour A', qty: '95 g' },
        { name: 'DK cotton, Colour B', qty: '95 g' },
        { name: 'DK cotton, Colour C', qty: '95 g' },
        { name: 'DK cotton, Colour D', qty: '95 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 htr x 12 rows = 10 x 10 cm in DK cotton with a 4 mm hook. At this gauge a foundation chain of 121 gives 75 cm finished width.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('htr (UK) / hdc (US): half treble')),
      ),
      h2('Foundation chain (Colour A)'),
      p(t('Chain 121.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2. Work 1 htr into every chain. Turn. (120 htr.)')),
      h2('Stripe sequence'),
      p(t('Work 4 rows each in Colour A, B, C, D, then back to A. Carry each colour up the side edge when not in use (or cut and rejoin if the stripe gap is more than 8 rows). Work until piece measures 90 cm (approximately 108 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The striped dc throw uses the same four-colour sequence in a shorter stitch. Or try the granny stripe baby blanket for cluster-based stripes.')),
    ],
  },
},

// ── 49 ── single skein baby blanket ───────────────────────────────────────────
{
  slug: 'single-skein-baby-blanket',
  title: 'Single skein baby blanket',
  subtitle: 'A small baby blanket designed to use exactly one 100 g ball of DK cotton.',
  excerpt: 'Sized to use one 100 g ball of DK cotton (approximately 200 m), this baby blanket is 50 x 60 cm in plain treble. A great first blanket or a quick gift project.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 tr x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Small baby blanket, 50 x 60 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-treble'],
  aliases: ['one ball baby blanket', 'mini crochet blanket', 'quick baby blanket'],
  glossaryTerms: [
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row, counting as the first treble.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Plain treble blanket. Yardage-constrained sizing is a modern approach to reduce waste. Weldon\'s Practical Crochet (series 1, 1880s) documents the plain treble row. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(gt('turning-chain', 'Turning chain'), t(' pattern: a single skein baby blanket is 50 x 60 cm. One 100 g ball of DK cotton at 200 m gives just enough yarn for this size in plain treble on a 4 mm hook.')),
      p(t('Weigh or measure the yarn every 5 rows to check progress against the remaining amount. Stop when you have about 15 cm of yarn left for the finishing tail. Total yarn needed is around 190 m of DK cotton.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn, 100 g (approx 200 m)', qty: '1 ball' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Kitchen scales (optional)', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('16 tr x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook. At this gauge a foundation chain of 81 gives 50 cm width (80 tr). The blanket needs 48 rows for 60 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
      ),
      h2('Foundation chain'),
      p(t('Chain 83 (80 tr + 3 turning chain).')),
      h2('Rows 1 to 48'),
      p(t('Ch 3. Work 1 tr into every stitch across. Tr into turning chain. Turn. Repeat for 48 rows (approximately 60 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. No edging is needed for this project, but a round of dc can be added if yarn allows.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('Scale the foundation chain up to 121 stitches and add more yarn for a full 75 x 90 cm baby blanket. Or try the picot edged baby blanket for a decorative border version of the same plain treble body.')),
    ],
  },
},

// ── 50 ── cluster v-stitch baby blanket ───────────────────────────────────────
{
  slug: 'cluster-v-stitch-baby-blanket',
  title: 'Cluster V-stitch baby blanket',
  subtitle: 'A V-stitch made from a cluster instead of a single treble on each leg.',
  excerpt: 'Instead of one treble on each side of the V, this stitch uses a two-treble cluster on each side. The cluster-V is wider and more textured than a standard V-stitch.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '6 cluster-Vs x 7 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble-cluster', 'crochet-v-stitch'],
  techniqueSlugs: ['crochet-treble-cluster', 'crochet-v-stitch', 'crochet-treble'],
  criticalTechniques: ['crochet-treble-cluster', 'crochet-v-stitch'],
  aliases: ['cluster v stitch', 'big v stitch blanket', 'double shell v-stitch'],
  glossaryTerms: [
    { slug: 'cluster-v', term: 'Cluster V-stitch', definition: 'Two trebles joined at the top (a cluster) on each leg of the V, with a chain between. Wider and more textured than a single-treble V.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each cluster-V row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Cluster V-stitch from the shell-and-V family. Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('cluster-v', 'cluster V-stitch'), t(' baby blanket is 75 x 90 cm. Each V is built from a two-treble cluster on each side instead of a single treble. The result is wider and more pronounced than a standard V-stitch.')),
      p(t('DK cotton in a smooth pale colour shows the V structure clearly. Each cluster-V is about 2 cm wide. Total yardage is around 320 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '320 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work one cluster-V'),
      p(t('In the same stitch or space: work 2 tr joined at the top (cluster left leg). Ch 1. Work 2 tr joined at the top (cluster right leg). One cluster-V made.')),
      h2('Gauge'),
      p(t('6 cluster-Vs x 7 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Foundation chain must be a multiple of 5 plus 3 edge chains.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('cl: two-treble cluster')),
        li(t('cluster-V: two clusters with ch 1 between, worked into the same space')),
      ),
      h2('Foundation chain'),
      p(t('Chain 153 (30 V-st repeats of 5 ch + 3 edge ch).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Skip 2 ch. Work cluster-V into next ch. Skip 2 ch. Dc into next ch*. Repeat. End with cluster-V, dc into last ch. Turn. (30 cluster-Vs.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Work cluster-V into the ch-1 space of each cluster-V below. Dc between the next two cluster-Vs*. Repeat. Turn.')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 63 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The standard v-stitch blanket is a simpler version of the same structure. Or try the cluster-chain baby blanket for a similar cluster-based open pattern.')),
    ],
  },
},

// ── 51 ── extended foundation blanket ─────────────────────────────────────────
{
  slug: 'chainless-foundation-blanket',
  title: 'Chainless foundation blanket',
  subtitle: 'The foundation chain and first row worked in one step using chainless foundation trebles.',
  excerpt: 'The chainless foundation treble combines the foundation chain and first treble row into one step. The edge is stretchier and neater than a chain-based start.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 tr x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-chainless-foundation-treble'],
  techniqueSlugs: ['crochet-chainless-foundation-treble', 'crochet-treble'],
  criticalTechniques: ['crochet-chainless-foundation-treble', 'crochet-treble'],
  aliases: ['chainless foundation blanket', 'foundation treble blanket', 'no-chain start blanket'],
  glossaryTerms: [
    { slug: 'chainless-ftr', term: 'Chainless foundation treble', definition: 'Work a treble while simultaneously chaining the base stitch underneath it. Each stitch builds its own foundation chain, removing the need for a separate starting chain.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row after the foundation row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Chainless foundation stitch is a modern technique. No direct Weldon source; synthetic from contemporary technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('chainless-ftr', 'chainless foundation treble'), t(' blanket is 75 x 90 cm. The first row is worked as chainless foundation stitches, each one simultaneously creating a treble and its own foundation chain below. After the foundation row the blanket continues in plain treble.')),
      p(t('The chainless foundation gives a stretchier, neater bottom edge than a chain start. DK cotton shows the edge difference clearly. Total yardage is around 360 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '360 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work chainless foundation treble'),
      p(t('Ch 4 (counts as setup). Yarn over. Insert hook into the 4th ch from hook. Pull up loop. Yarn over, draw through 1 loop (this makes the foundation chain stitch below). Yarn over, draw through 2. Yarn over, draw through 2. One foundation treble made and one chain base created. For each subsequent ftr: yarn over, insert hook into the chain base of the last stitch (the bottom loop), pull up loop, and complete the treble.')),
      h2('Gauge'),
      p(t('16 tr x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook. The foundation row gauge matches the body row gauge when the foundation stitches are worked at the same tension.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain (setup only)')),
        li(t('ftr: chainless foundation treble (row 1 only)')),
        li(t('tr (UK) / dc (US): treble (all subsequent rows)')),
      ),
      h2('Foundation row (row 1)'),
      p(t('Work 120 chainless foundation trebles in a chain from the setup ch-4. The bottom edge should measure 75 cm.')),
      h2('Row 2 and onward'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch. Tr into top of turning chain. Turn. (120 tr.)')),
      p(t('Repeat Row 2 until piece measures 90 cm (approximately 72 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly with steam. The chainless foundation edge and the final row edge should look identical in weight and stretch.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('Any of the other blanket patterns can use a chainless foundation row instead of a chain start. Try the shell stitch blanket with a chainless foundation for a particularly neat shell edge.')),
    ],
  },
},

// ── 52 ── crossed treble throw ─────────────────────────────────────────────────
{
  slug: 'crossed-double-treble-throw',
  title: 'Crossed double treble throw',
  subtitle: 'Long crossed stitches make a bold cable-like pattern on an aran throw.',
  excerpt: 'Crossed double trebles skip two stitches and then cross back, creating large X shapes that look like cables. Aran weight makes the cross bold and the fabric warm.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '8 crossed pairs x 6 rows = 10 x 10 cm in aran with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-treble', 'crochet-crossed-double-treble'],
  techniqueSlugs: ['crochet-crossed-double-treble', 'crochet-double-treble'],
  criticalTechniques: ['crochet-crossed-double-treble'],
  aliases: ['crossed dtr throw', 'cable-look crochet throw', 'cross stitch aran throw'],
  glossaryTerms: [
    { slug: 'crossed-dtr', term: 'Crossed double treble', definition: 'Work a dtr 2 stitches ahead, skip back, and work a second dtr into the skipped stitch, crossing in front of the first. The result is a large X shape that reads like a cable.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Four chains at the start of each crossed dtr row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Crossed double treble from Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('crossed-dtr', 'crossed double treble'), t(' throw is 90 x 100 cm. Each pair of stitches works the second stitch first, then crosses back for the first, creating a large X that reads like a cable across aran-weight yarn.')),
      p(t('The long crossed dtr makes a bold geometric pattern. In a natural or cream aran it looks like a classic cable blanket but is worked flat without a cable needle. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a crossed dtr pair'),
      p(t('Skip 1 stitch. Work 1 dtr into the 2nd stitch. Without removing hook, work 1 dtr into the skipped stitch, passing the hook in front of the first dtr. Two stitches used, one X made.')),
      h2('Gauge'),
      p(t('8 crossed pairs x 6 rows = 10 x 10 cm in aran with a 5 mm hook. The crossed stitch draws in more than a plain dtr; swatch before starting the foundation.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dtr (UK) / tr (US): double treble')),
        li(t('crossed-dtr: pair of dtr worked in reversed order')),
      ),
      h2('Foundation chain'),
      p(t('Chain 145 (144 stitches = 72 crossed pairs + 1 turning chain).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 4. *Work crossed-dtr pair across every 2 stitches*. Work 1 dtr into last stitch. Turn. (72 pairs.)')),
      h2('Row 2 and onward'),
      p(t('Ch 4. *Work crossed-dtr pair across every 2 stitches*. Dtr into turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 100 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Steam block to open the X shapes.')),
      h2('Care'),
      p(t('Handwash wool cool. Dry flat. Acrylic: machine wash 40 degrees, tumble dry low.')),
      h2('What to try next'),
      p(t('The cross stitch crochet throw uses a similar crossing with trebles for a smaller X pattern. Or try the basketweave throw for a different cable-like effect using post stitches.')),
    ],
  },
},

// ── 53 ── fingering weight crib blanket ───────────────────────────────────────
{
  slug: 'fingering-weight-crib-blanket',
  title: 'Fingering weight crib blanket',
  subtitle: 'A fine cotton lace-weight blanket for a crib or pram in 4-ply cotton.',
  excerpt: 'Fingering weight cotton on a 3 mm hook gives a lightweight, finely detailed blanket for a crib. Plain treble rows at this gauge produce a fabric thin enough to see through in good light.',
  difficulty: 'BEGINNER',
  yarnWeight: 'fingering',
  hook: 'crochet-hook-3-0mm',
  gauge: '22 tr x 12 rows = 10 x 10 cm in 4-ply cotton with a 3 mm hook.',
  finishedSize: 'Crib blanket, 60 x 75 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-treble'],
  aliases: ['4-ply crochet blanket', 'crib blanket', 'fine cotton baby blanket'],
  glossaryTerms: [
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each treble row, counting as the first treble.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Plain treble row from Weldon\'s Practical Crochet (series 1, 1880s). 4-ply cotton application is a modern sizing. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A fingering weight crib blanket is 60 x 75 cm. Plain treble rows in 4-ply cotton on a 3 mm hook produce a lightweight fabric thin enough to fold into a pram bag. The small hook gives a tight enough gauge that the blanket holds its shape without gaps.')),
      p(t('4-ply cotton is cooler than wool and safer in a hot crib. The tighter gauge means more rows and stitches than a DK version, so this takes longer despite being a small blanket. Total yardage is around 280 m of 4-ply cotton (about 100 g).')),
      h2('What you need'),
      supplies('Materials', [
        { name: '4-ply or fingering weight cotton yarn', qty: '100 g (approx 280 m)' },
        { name: '3 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('22 tr x 12 rows = 10 x 10 cm in 4-ply cotton with a 3 mm hook. At this gauge a foundation chain of 133 gives 60 cm width (132 tr). The blanket needs 90 rows for 75 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
      ),
      h2('Foundation chain'),
      p(t('Chain 135.')),
      h2('Rows 1 to 90'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch across. Tr into turning chain. Turn. Repeat for 90 rows (75 cm). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter. Work 1 dc into each stitch along the top and bottom. Work 1 dc into each row end on the sides. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block the finished blanket by pinning to the stated dimensions while damp and allowing to dry fully.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. Fine cotton can shrink if washed hot.')),
      h2('What to try next'),
      p(t('Scale up the foundation chain to 165 stitches for a larger pram blanket. Or try the single skein baby blanket in DK cotton for a faster version of a similar sized piece.')),
    ],
  },
},

// ── 54 ── textured post stitch baby blanket ───────────────────────────────────
{
  slug: 'post-stitch-baby-blanket',
  title: 'Post stitch baby blanket',
  subtitle: 'Front and back post double crochets create a raised-rib pattern on a baby blanket.',
  excerpt: 'Front post and back post double crochets alternate in a 2x2 rib pattern on a DK cotton baby blanket. The raised ribs give the fabric a knit-like texture.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-fpdc', 'crochet-bpdc'],
  techniqueSlugs: ['crochet-fpdc', 'crochet-bpdc', 'crochet-double-uk'],
  criticalTechniques: ['crochet-fpdc', 'crochet-bpdc'],
  aliases: ['post stitch baby blanket', 'ribbed crochet baby blanket', '2x2 rib blanket'],
  glossaryTerms: [
    { slug: 'fpdc', term: 'FPdc', definition: 'Front post double crochet. Insert hook from front to back to front around the post of the stitch below. The stitch raises to the front.' },
    { slug: 'bpdc', term: 'BPdc', definition: 'Back post double crochet. Insert hook from back to front to back around the post below. The stitch pushes to the back, creating a recessed channel.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Post stitch rib from Weldon\'s Practical Crochet (series 4, 1880s). 2x2 rib pattern is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A post stitch baby blanket is 75 x 90 cm. Rows of 2 '), gt('fpdc', 'FPdc'), t(' followed by 2 '), gt('bpdc', 'BPdc'), t(' alternate to make a raised 2x2 rib. The fabric stretches sideways and has a knit-like texture on the right side.')),
      p(t('DK cotton gives a firm rib that holds its shape. The 2x2 rib draws in more than plain dc, so the foundation chain needs to be wider than a plain blanket to compensate. Total yardage is around 400 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '400 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook, working 2x2 post stitch rib. The rib draws in: at this gauge a foundation chain of 145 gives 75 cm stretched width.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet (foundation row only)')),
        li(t('FPdc: front post double crochet')),
        li(t('BPdc: back post double crochet')),
      ),
      h2('Foundation chain'),
      p(t('Chain 145. Work one row of plain dc. Turn. (144 dc.)')),
      h2('Row 2 (right side)'),
      p(t('Ch 1. *Work 2 FPdc, 2 BPdc*. Repeat across. Turn.')),
      h2('Row 3 and onward'),
      p(t('Ch 1. Work FPdc over FPdc and BPdc over BPdc from the row below (ribs stack on each other). Turn.')),
      p(t('Repeat Row 3 until piece measures 90 cm (approximately 126 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. Stretch gently sideways while damp to restore the rib width.')),
      h2('What to try next'),
      p(t('The basketweave throw uses the same post stitches in longer trebles for a woven pattern. Or try the waistcoat stitch throw for a different knit-like surface.')),
    ],
  },
},

// ── 55 ── blo treble blanket ──────────────────────────────────────────────────
{
  slug: 'blo-treble-blanket',
  title: 'BLO treble blanket',
  subtitle: 'Working trebles into the back loop only creates a ridged stripe texture.',
  excerpt: 'Working every treble into the back loop only leaves horizontal ridges across the fabric. Each row adds a ridge, giving the blanket a corduroy-like striped surface.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tr x 8 rows = 10 x 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-blo-tr'],
  techniqueSlugs: ['crochet-blo-tr', 'crochet-treble'],
  criticalTechniques: ['crochet-blo-tr'],
  aliases: ['blo treble blanket', 'ridged treble throw', 'corduroy crochet blanket'],
  glossaryTerms: [
    { slug: 'blo-tr', term: 'BLO treble', definition: 'A treble worked into the back loop only of the stitch below. The front loop is left as a visible raised ridge on the right side.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each BLO treble row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'BLO treble from the back-loop stitch family in Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('blo-tr', 'BLO treble'), t(' blanket is 90 x 100 cm. Every treble is worked into the back loop only, leaving the front loop as a raised horizontal ridge on the right side. Each row adds one ridge, building a corduroy-like stripe across the full width.')),
      p(t('Aran weight gives prominent ridges that are easy to see and feel. The BLO treble draws in slightly less than BLO dc in the same yarn. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 tr x 8 rows = 10 x 10 cm in aran with a 5 mm hook, BLO. Check a swatch in BLO specifically: the hook angle shifts slightly and affects gauge.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr-blo (UK) / dc-blo (US): treble into the back loop only')),
      ),
      h2('Foundation chain'),
      p(t('Chain 127 (126 stitches).')),
      h2('Row 1 (both loops)'),
      p(t('Work 1 tr into every chain from the 4th. Turn. (124 tr, both loops.)')),
      h2('Row 2 and onward'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into the back loop only of every stitch across. Tr into the top of the turning chain (both loops on turning chain). Turn.')),
      p(t('Repeat Row 2 until piece measures 100 cm (approximately 80 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Work one round of dc (UK) around the perimeter if the edges look uneven. Steam block lightly.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Dry flat. The BLO ridges hold their shape well through washing.')),
      h2('What to try next'),
      p(t('The back loop only throw uses the same technique with dc for a shorter stitch and finer rib. Or try the third loop htr blanket for a flat fabric-like texture with no visible ridge.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
