/**
 * Generator: D-Homewares Batch 2 — Blankets 11-25
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch2.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...content: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: content }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string; substitutions?: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}
function trouble(heading: string, intro: string, items: { symptom: string; cause: string; fix: string }[]) {
  return { type: 'troubleshooter', attrs: { heading, intro, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── 11 ── basketweave throw ───────────────────────────────────────────────────
{
  slug: 'basketweave-throw',
  title: 'Basketweave throw',
  subtitle: 'Raised front and back post trebles weave a woven-looking surface.',
  excerpt: 'Alternating panels of front post and back post trebles build a basketweave texture on an aran-weight throw. The raised surface looks woven but is worked flat on a 5 mm hook.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tr × 9 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-fptr', 'crochet-bptr'],
  techniqueSlugs: ['crochet-fptr', 'crochet-bptr', 'crochet-treble'],
  criticalTechniques: ['crochet-fptr', 'crochet-bptr'],
  aliases: ['basketweave crochet', 'post stitch blanket', 'woven crochet throw'],
  glossaryTerms: [
    { slug: 'fptr', term: 'FPtr', definition: 'Front post treble. Work the treble around the post of the stitch below by inserting the hook from front to back to front around the post. The stitch stands forward.' },
    { slug: 'bptr', term: 'BPtr', definition: 'Back post treble. Insert the hook from back to front to back around the post below. The stitch pushes to the back, creating a recessed panel.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Post-stitch basketweave derives from the raised-stitch family in Weldon\'s Practical Crochet (series 4, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A basketweave throw is 90 x 100 cm. Panels of '), gt('fptr', 'FPtr'), t(' and '), gt('bptr', 'BPtr'), t(' alternate across the width to build a surface that looks woven. The fabric is worked flat in aran yarn on a 5 mm hook.')),
      p(t('Each panel is four stitches wide and four rows tall. When the panels swap position every four rows, the raised ridges cross like a woven basket. Aran wool gives the best stitch definition; acrylic also works but the post stitches look slightly flatter. Total yardage is around 700 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran wool or blend', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 tr x 9 rows = 10 x 10 cm in aran with a 5 mm hook. Post stitches draw in slightly; check your swatch measures 10 cm across 14 stitches.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble (foundation row)')),
        li(t('FPtr: front post treble, raises the stitch to the front')),
        li(t('BPtr: back post treble, pushes the stitch to the back')),
      ),
      h2('Foundation chain'),
      p(t('Chain 129 (128 tr + 1 turning chain). Work one row of plain treble. (128 tr.)')),
      h2('Rows 2 to 5 (basket panel A)'),
      p(t('Ch 3. *Work 4 FPtr, 4 BPtr*. Repeat across. Tr into turning chain. Turn. Repeat this row 3 more times (4 rows total).')),
      h2('Rows 6 to 9 (basket panel B)'),
      p(t('Ch 3. *Work 4 BPtr, 4 FPtr*. Repeat across. Tr into turning chain. Turn. Repeat 3 more times. The panels swap, creating the weave.')),
      h2('Continuing'),
      p(t('Alternate 4-row A panels and 4-row B panels. Work until piece measures 100 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Steam block wool lightly to even the post stitches. Do not press flat; the raised texture is the point.')),
      h2('Care'),
      p(t('Handwash wool in cool water. Squeeze dry, reshape, dry flat. Post stitches can mat if machine washed on a warm cycle.')),
      h2('What to try next'),
      p(t('Try the cable-look crochet throw for a similar raised texture with crossing panels. Or the waffle stitch blanket for a more uniform dimpled surface.')),
    ],
  },
},

// ── 12 ── shell stitch baby blanket ──────────────────────────────────────────
{
  slug: 'shell-stitch-baby-blanket',
  title: 'Shell stitch baby blanket',
  subtitle: 'Five-treble fans spaced across a DK cotton baby blanket.',
  excerpt: 'Five trebles worked into a single stitch make a fan shell across a baby blanket. Shells alternate with single chain spaces to build a light, open fabric in DK cotton.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '5 shells × 8 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-shell', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-shell', 'crochet-treble', 'crochet-double-uk'],
  criticalTechniques: ['crochet-shell', 'crochet-treble'],
  aliases: ['shell stitch blanket', 'fan stitch baby blanket', 'crochet shell blanket'],
  glossaryTerms: [
    { slug: 'shell-stitch', term: 'Shell stitch', definition: 'Five trebles worked into the same stitch or space, spreading out like a fan or shell. The classic shell occupies one base point.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of a treble-height row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Shell (fan) stitch from Weldon\'s Practical Crochet (1st series, 1880s). Five-treble fan. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A shell stitch baby blanket is 75 x 90 cm. Rows of five-treble '), gt('shell-stitch', 'shells'), t(' sit over the spaces from the previous row. The result is a light, open fabric in DK cotton on a 4 mm hook.')),
      p(t('Each shell repeat is 6 stitches wide plus one chain. At this gauge a 75 cm blanket needs 12 shell repeats across. The pattern is one row to learn and then repeats to the end. Total yardage is around 300 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '300 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('5 shells x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Work one row of shells and measure 5 across. A half-shell difference per 10 cm shifts the finished width by 3 cm over 75 cm.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet (edge stitch)')),
        li(t('shell: 5 tr into the same stitch or space')),
      ),
      h2('Foundation chain'),
      p(t('Chain 148 (12 repeats of 12 ch + 4 edge ch).')),
      h2('Row 1 (right side)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Skip 2 ch. Work 5 tr into next ch (shell made). Skip 2 ch. Work 1 dc into next ch. Ch 1*. Repeat to end, ending with 5 tr into last repeat, dc into last ch. Turn. (12 shells.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Work 1 shell into the centre tr of each shell. Work 1 dc into each ch-1 space*. Repeat. Turn. (12 shells.)')),
      p(t('Repeat Row 2 until piece measures 90 cm (about 72 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter. Work 1 dc into each stitch on top and bottom. Work 1 dc into each row end on the sides. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly with steam to open the shells.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The v-stitch blanket uses a two-treble fan for a more open look. Or try the bobble blanket for raised texture in the same DK cotton.')),
    ],
  },
},

// ── 13 ── moss stitch baby blanket ────────────────────────────────────────────
{
  slug: 'moss-stitch-baby-blanket',
  title: 'Moss stitch baby blanket',
  subtitle: 'Alternating double crochet and chain spaces make a textured mesh.',
  excerpt: 'Moss stitch alternates a double crochet with a chain-1 space across every row. The offset creates a small dimpled grid that is firm, breathable, and good for baby blankets.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts × 16 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-moss-stitch'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['moss stitch crochet', 'linen stitch blanket', 'granite stitch blanket'],
  glossaryTerms: [
    { slug: 'moss-stitch', term: 'Moss stitch', definition: 'A crochet stitch pattern of dc, ch 1, skip 1, repeated across rows, with the dc of each row sitting in the ch-1 space of the row below. Also called linen stitch or granite stitch.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of a double crochet row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Alternating dc-chain mesh from the grid-stitch family in Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('moss-stitch', 'moss stitch'), t(' baby blanket is 75 x 90 cm. Each row works a double crochet into the chain space below and a chain over the dc below. The offset builds a small dimpled grid that is firm but breathable.')),
      p(t('DK cotton is ideal: the tight stitch shows the grid clearly and the fabric washes well. The pattern is one row that repeats all the way to the end. Total yardage is around 360 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '360 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 sts x 16 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Count both the dc and ch-1 spaces together as one stitch unit each for gauge.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet')),
      ),
      h2('Foundation chain'),
      p(t('Chain 151 (an odd number to set up the staggered repeat).')),
      h2('Row 1'),
      p(t('Work a '), gt('turning-chain', 'turning chain'), t(' of ch 1. Dc into 2nd ch from hook. *Ch 1, skip 1 ch, dc into next ch*. Repeat to end. Turn. (75 dc, 75 ch-1 spaces.)')),
      h2('Row 2 and onward'),
      p(t('Ch 1. Dc into first ch-1 space. *Ch 1, skip 1 dc, dc into next ch-1 space*. Repeat. End with ch 1, dc into last stitch. Turn.')),
      p(t('Repeat Row 2 until piece measures 90 cm (about 144 rows). Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter: 1 dc into each dc and each ch-1 space along top and bottom, 1 dc into each row end on sides, 3 dc into corners.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block to open the grid: pin the damp blanket to the stated dimensions and allow to dry fully.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. The grid opens slightly with washing, which is normal.')),
      h2('What to try next'),
      p(t('The waffle stitch throw uses a post-stitch variation of the same grid idea for a deeper texture. Or the linen stitch blanket is the same pattern in a finer weight.')),
    ],
  },
},

// ── 14 ── waffle stitch throw ─────────────────────────────────────────────────
{
  slug: 'waffle-stitch-throw',
  title: 'Waffle stitch throw',
  subtitle: 'Post stitches and chain spaces make a deep dimpled surface.',
  excerpt: 'Front post double crochets alternate with chain spaces to form a grid of raised ridges on an aran throw. The waffle texture is firmer and deeper than moss stitch.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '13 sts × 12 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 110 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-fpdc'],
  techniqueSlugs: ['crochet-fpdc', 'crochet-double-uk', 'crochet-waffle-stitch'],
  criticalTechniques: ['crochet-fpdc', 'crochet-double-uk'],
  aliases: ['waffle crochet', 'waffle stitch blanket', 'raised grid throw'],
  glossaryTerms: [
    { slug: 'fpdc', term: 'FPdc', definition: 'Front post double crochet. Insert the hook from front to back to front around the post of the stitch below. The stitch raises forward, creating a ridge.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of a double crochet row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Waffle stitch from the raised-post stitch family. Post stitches documented in Weldon\'s Practical Crochet (series 4, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A waffle stitch throw is 90 x 110 cm. Rows of '), gt('fpdc', 'FPdc'), t(' placed over dc from the previous row build a grid of raised ridges with recessed squares between them. The result looks like a waffle iron surface.')),
      p(t('Aran weight gives the right depth: the ridges stand up clearly but the fabric stays soft. Total yardage is around 700 g. The stitch repeat is 3 stitches: dc, FPdc, ch 1.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '700 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('13 sts x 12 rows = 10 x 10 cm in aran with a 5 mm hook. The waffle draws in: check a swatch before starting the full foundation.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet (recessed squares)')),
        li(t('FPdc: front post double crochet (raised ridges)')),
      ),
      h2('Foundation chain'),
      p(t('Chain 118 (39 repeats of 3 stitches + 1 edge stitch).')),
      h2('Row 1 (set-up, right side)'),
      p(t('Work a '), gt('turning-chain', 'turning chain'), t(' of ch 1. *Dc, dc, ch 1, skip 1*. Repeat across. Dc into last stitch. Turn. (78 dc, 39 ch-1 spaces.)')),
      h2('Row 2 (waffle row)'),
      p(t('Ch 1. *Dc into dc, FPdc around next dc below, dc into ch-1 space*. Repeat across. Dc into last stitch. Turn.')),
      h2('Row 3'),
      p(t('Ch 1. *Dc into dc, FPdc around FPdc below, ch 1 over dc, skip 1*. Repeat. Dc into last stitch. Turn.')),
      h2('Continuing'),
      p(t('Alternate Row 2 and Row 3 until piece measures 110 cm. Fasten off.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Steam block to settle the waffle grid.')),
      h2('Care'),
      p(t('Handwash aran wool cool. Dry flat. Acrylic: machine wash 40 degrees, tumble dry low.')),
      h2('What to try next'),
      p(t('The basketweave throw uses front and back post trebles for a deeper woven texture. Or try the moss stitch baby blanket for a lighter version of the same dimpled grid.')),
    ],
  },
},

// ── 15 ── popcorn stitch baby blanket ─────────────────────────────────────────
{
  slug: 'popcorn-baby-blanket',
  title: 'Popcorn stitch baby blanket',
  subtitle: 'Rounded popcorns in a staggered grid on a DK cotton background.',
  excerpt: 'A popcorn is five trebles into one stitch with the first and last loops joined and the cluster pushed to the right side. Spaced in a staggered grid on a DK cotton baby blanket.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 tr × 9 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-popcorn'],
  techniqueSlugs: ['crochet-popcorn', 'crochet-treble'],
  criticalTechniques: ['crochet-popcorn', 'crochet-treble'],
  aliases: ['popcorn blanket', 'popcorn stitch baby blanket', 'bubble crochet blanket'],
  glossaryTerms: [
    { slug: 'popcorn-stitch', term: 'Popcorn', definition: 'Five trebles into the same stitch. Remove the hook, insert it into the first of the five, then pull the working loop through. The cluster pops to the front.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of a treble row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Popcorn stitch (puff cluster) from Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('popcorn-stitch', 'popcorn'), t(' baby blanket is 75 x 90 cm. Raised popcorn clusters sit in a staggered grid against a plain treble background. The popcorn pops forward on the right side of the fabric.')),
      p(t('DK cotton keeps the fabric soft and machine-washable. Popcorns use more yarn than bobbles because all five trebles are full height before joining. Total yardage is around 400 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '400 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 tr x 9 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Popcorn rows pull in; check the swatch width against a plain treble swatch and adjust hook size if needed.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble (background)')),
        li(t('pop: popcorn, five trebles into one stitch joined by pulling the working loop through the first')),
      ),
      h2('Foundation chain'),
      p(t('Chain 121.')),
      h2('Rows 1 and 2 (plain treble)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every stitch. Turn. Repeat. (119 tr.)')),
      h2('Row 3 (popcorn row, right side)'),
      p(t('Ch 3. Tr into next 3 stitches. *Work pop into next stitch. Tr into next 5 stitches*. Repeat. End with pop, tr into remaining stitches and turning chain. Turn. (About 20 popcorns.)')),
      h2('Rows 4 and 5 (plain treble)'),
      p(t('Work 2 rows of plain treble. Turn.')),
      h2('Row 6 (offset popcorn row)'),
      p(t('Ch 3. Tr into next 6 stitches. *Pop. Tr into next 5*. Repeat. Turn. (Popcorns offset by 3 from Row 3.)')),
      h2('Continuing'),
      p(t('Repeat the 6-row sequence (2 plain, popcorn, 2 plain, offset popcorn) until piece measures 90 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Push any popcorns that landed on the wrong side forward through the fabric. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Push popcorns forward again while damp if they flattened. Dry flat.')),
      h2('What to try next'),
      p(t('The bobble blanket uses a smaller cluster that stays flatter. Or try the puff stitch throw for a softer, rounded texture between popcorn and bobble.')),
    ],
  },
},

// ── 16 ── puff stitch throw ───────────────────────────────────────────────────
{
  slug: 'puff-stitch-throw',
  title: 'Puff stitch throw',
  subtitle: 'Soft rounded puffs in a row on an aran-weight throw.',
  excerpt: 'A puff stitch is made by pulling up several long loops into the same stitch and joining them. The result is a soft rounded lump between two trebles on an aran throw.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '10 puffs × 7 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-puff'],
  techniqueSlugs: ['crochet-puff-stitch', 'crochet-treble'],
  criticalTechniques: ['crochet-puff-stitch', 'crochet-treble'],
  aliases: ['puff stitch crochet', 'puff blanket', 'bead stitch throw'],
  glossaryTerms: [
    { slug: 'puff-stitch', term: 'Puff stitch', definition: 'Insert hook, pull up a long loop (x3 or more into the same stitch), then yarn over and draw through all loops at once. Makes a soft rounded bump.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of a treble-height row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Puff stitch (elongated-loop cluster) from the cluster family in Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('puff-stitch', 'puff stitch'), t(' throw is 90 x 100 cm. Rows of puffs sit between single trebles on every other row, making a surface of soft rounded bumps in aran yarn on a 5 mm hook.')),
      p(t('The puff is softer than a bobble and rounder than a popcorn. Aran wool gives the most tactile puff; acrylic gives a firmer, more uniform result. Total yardage is around 650 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '650 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('10 puffs x 7 rows = 10 x 10 cm in aran with a 5 mm hook. Pull the long loops to a consistent height (about 1.5 cm) for even puffs across the row.')),
      h2('How to make a puff'),
      p(t('*Insert hook, yarn over, pull up a 1.5 cm loop*: repeat 3 times into the same stitch (7 loops on hook). Yarn over and draw through all 7 loops at once. Ch 1 to close. One puff made.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble (dividers between puffs)')),
        li(t('puff: three-loop puff stitch, closed with ch 1')),
      ),
      h2('Foundation chain'),
      p(t('Chain 127 (63 puff spaces + 64 treble dividers + edge stitches).')),
      h2('Row 1 (set-up treble row)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. Work 1 tr into every chain. Turn. (125 tr.)')),
      h2('Row 2 (puff row)'),
      p(t('Ch 3. *Work 1 puff into next stitch. Work 1 tr into next stitch*. Repeat across. Tr into turning chain. Turn. (63 puffs, 63 trebles.)')),
      h2('Row 3 (plain treble)'),
      p(t('Ch 3. Work 1 tr into every stitch and ch-1 close space. Tr into turning chain. Turn. (125 tr.)')),
      h2('Continuing'),
      p(t('Alternate puff rows and plain rows until piece measures 100 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Steam block to settle the puffs.')),
      h2('Care'),
      p(t('Handwash aran wool cool. Puffs flatten in a machine wash. Dry flat and reshape puffs while damp.')),
      h2('What to try next'),
      p(t('The bobble blanket uses a similar concept with a tighter cluster. Or try the popcorn baby blanket for a more defined, round bump.')),
    ],
  },
},

// ── 17 ── spike stitch blanket ────────────────────────────────────────────────
{
  slug: 'spike-stitch-blanket',
  title: 'Spike stitch blanket',
  subtitle: 'Long stitches dip into rows below to create a woven diagonal stripe.',
  excerpt: 'Spike stitches insert the hook one or more rows below the current row, pulling a long loop up. In a two-colour pattern they create a woven diagonal stripe effect.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc × 12 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-spike-stitch', 'crochet-double-uk', 'crochet-colour-change'],
  criticalTechniques: ['crochet-spike-stitch', 'crochet-double-uk'],
  aliases: ['spike stitch crochet', 'spiked dc blanket', 'two-colour spike blanket'],
  glossaryTerms: [
    { slug: 'spike-stitch', term: 'Spike stitch', definition: 'A double crochet worked by inserting the hook one or more rows below the current row, pulling a long loop up to the working row height before completing the stitch.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of a double crochet row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Long stitch (spike) documented in Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('spike-stitch', 'spike stitch'), t(' blanket is 75 x 90 cm. In a two-colour version, Colour A rows of plain dc alternate with Colour B rows of spike stitches inserted one row down. The long stitches of B pull across the A rows to make a woven diagonal pattern.')),
      p(t('DK cotton shows the spike pattern cleanly. Two colours with good contrast give the clearest diagonal. Total yardage is around 360 g (180 g each colour).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton, Colour A', qty: '180 g' },
        { name: 'DK cotton, Colour B', qty: '180 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 dc x 12 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Count the spike stitches at the same height as regular dc when measuring gauge.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet')),
        li(t('sp: spike stitch, dc inserted one row below the current row')),
      ),
      h2('Foundation chain (Colour A)'),
      p(t('Chain 121.')),
      h2('Row 1 (Colour A, right side)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into every chain. Turn. (120 dc.)')),
      h2('Row 2 (Colour B, spike row)'),
      p(t('Join Colour B. Ch 1. *Work 3 sp (insert hook one row below into the next stitch, pull up loop to row height, complete dc). Work 3 plain dc*. Repeat across. Turn. Cut Colour A tail.')),
      h2('Row 3 (Colour A, plain)'),
      p(t('Join Colour A. Ch 1. Dc into every stitch. Turn.')),
      h2('Continuing'),
      p(t('Alternate one spike row (Colour B) and one plain row (Colour A) until piece measures 90 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to even the spike heights.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. The spike loops should hold their shape without special care.')),
      h2('What to try next'),
      p(t('The planned pooling blanket is a more complex two-colour effect. Or try the moss stitch baby blanket for a single-colour texture with open spaces.')),
    ],
  },
},

// ── 18 ── lemon peel stitch throw ─────────────────────────────────────────────
{
  slug: 'lemon-peel-throw',
  title: 'Lemon peel stitch throw',
  subtitle: 'Alternating double and treble stitches make a subtle bumped surface.',
  excerpt: 'Lemon peel stitch alternates one double crochet and one treble across every row. The height difference between the two stitches creates a raised bump pattern on the surface.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 sts × 10 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-treble', 'crochet-lemon-peel'],
  criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
  aliases: ['lemon peel crochet', 'bumped throw', 'alternating stitch blanket'],
  glossaryTerms: [
    { slug: 'lemon-peel-stitch', term: 'Lemon peel stitch', definition: 'A two-stitch repeat of dc and tr worked across every row, with the position swapped each row so the taller tr always sits over the shorter dc from below. The height difference makes a raised bump.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One or two chains at the start of the row, depending on the first stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Alternating dc-tr pattern from the mixed-height stitch family in Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('lemon-peel-stitch', 'lemon peel stitch'), t(' throw is 90 x 100 cm. The dc-tr alternation creates a subtle raised bump across every row. With the position of the two stitches swapping each row, the taller stitch always lands over the shorter, producing a small ridge.')),
      p(t('This is a beginner-friendly stitch: two stitches, two heights, the same action across every row. It works in any weight. Aran acrylic is an easy starting point for a first textured throw. Total yardage is around 650 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran acrylic or wool blend', qty: '650 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 sts x 10 rows = 10 x 10 cm in aran with a 5 mm hook. Work a 20-stitch swatch of the dc-tr repeat to check.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet (shorter stitch)')),
        li(t('tr (UK) / dc (US): treble (taller stitch)')),
      ),
      h2('Foundation chain'),
      p(t('Chain 128 (even number for the two-stitch repeat).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. *Dc into next stitch, tr into next stitch*. Repeat across. Turn. (64 dc, 64 tr.)')),
      h2('Row 2'),
      p(t('Ch 1. *Tr into next dc, dc into next tr*. Repeat across. Turn. (Stitches swap position.)')),
      h2('Continuing'),
      p(t('Alternate Row 1 and Row 2 until piece measures 100 cm (approximately 100 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Lay flat and steam block lightly.')),
      h2('Care'),
      p(t('Machine wash 40 degrees, normal cycle. Tumble dry low. The stitch is stable and holds well through machine washing.')),
      h2('What to try next'),
      p(t('The waffle stitch throw builds a deeper version of the same raised-and-recessed idea. Or try the basketweave throw for a post-stitch woven texture.')),
    ],
  },
},

// ── 19 ── baby granny hexagon blanket ─────────────────────────────────────────
{
  slug: 'granny-hexagon-blanket',
  title: 'Granny hexagon baby blanket',
  subtitle: 'Six-sided granny motifs joined flat for a honeycomb layout.',
  excerpt: 'Six-sided granny motifs, each about 12 cm across, join edge to edge in a honeycomb grid. The joined hexagons make a 75 x 90 cm baby blanket with a distinctive geometric look.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 hexagon motif = 12 cm point-to-point in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm approximately.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-slip-stitch', 'crochet-granny-cluster', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-join-as-you-go', 'crochet-treble', 'crochet-hexagon-motif'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-join-as-you-go'],
  aliases: ['hexagon crochet blanket', 'honeycomb baby blanket', 'hex motif blanket'],
  glossaryTerms: [
    { slug: 'magic-ring', term: 'Magic ring', definition: 'An adjustable starting loop for in-the-round work. Pulls closed to leave no centre hole.' },
    { slug: 'jayg', term: 'Join-as-you-go', definition: 'Joining motifs on the final round by slip-stitching into the adjacent motif instead of sewing afterwards.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Hexagonal motif crochet from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A granny hexagon baby blanket is made from six-sided motifs joined in a honeycomb grid. Each hexagon is worked in the round from a '), gt('magic-ring', 'magic ring'), t('. The '), gt('jayg', 'join-as-you-go'), t(' method connects motifs on the final round so there is no sewing.')),
      p(t('Each hexagon takes about 5 minutes in DK cotton on a 4 mm hook. The blanket needs approximately 48 full hexagons and some half hexagons at the straight edges for a 75 x 90 cm finished size. Total yardage is around 450 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton (one or more colours)', qty: '450 g total' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Stitch markers', qty: '6' },
      ]),
      h2('Gauge'),
      p(t('One hexagon motif = 12 cm point-to-point in DK cotton with a 4 mm hook. Make one test hexagon and measure from point to point. The blanket layout needs even, consistent motifs.')),
      h2('Stitches used'),
      ul(
        li(t('MR: '), gt('magic-ring', 'magic ring')),
        li(t('ch: chain')),
        li(t('sl st: slip stitch')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('gr-cl: granny cluster, 3 tr into the same space')),
      ),
      h2('Single hexagon (3 rounds)'),
      p(t('Make a magic ring. Round 1: ch 3, work (2 tr, ch 2) into ring 6 times. Sl st to close. (6 clusters, 6 ch-2 corners.)')),
      p(t('Round 2: sl st to corner. Ch 3. (2 tr, ch 2, 3 tr) into each of the 6 corners. Sl st to close. (12 clusters.)')),
      p(t('Round 3: sl st to corner. Work (3 tr, ch 2, 3 tr) into each corner, (3 tr, ch 2) into each side space. Sl st to close. Pull in the magic ring tail. Fasten off.')),
      h2('Joining hexagons'),
      p(t('On the final round of each new hexagon, replace the ch-2 at joining sides with sl st into the matching ch-2 space of the adjacent hexagon. This is the '), gt('jayg', 'join-as-you-go'), t(' connection.')),
      h2('Layout'),
      p(t('Arrange 6 hexagons across the width and 8 rows deep (staggered). Fill straight edges with half hexagons or a border round of dc.')),
      h2('Finishing'),
      p(t('Work one border round of dc around the full perimeter. Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block to flatten the joins.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The granny square join blanket uses a similar motif approach with square geometry. Or try the c2c blanket for a diagonal take on continuous motif fabric.')),
    ],
  },
},

// ── 20 ── sedge stitch throw ──────────────────────────────────────────────────
{
  slug: 'sedge-stitch-throw',
  title: 'Sedge stitch throw',
  subtitle: 'Groups of three stitches at different heights make a tweedy surface.',
  excerpt: 'Sedge stitch groups a htr, tr, and dtr into the same stitch, making an angled fan cluster that tiles across the row. The result is a dense, tweedy surface on an aran throw.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '10 clusters × 7 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-half-treble', 'crochet-treble', 'crochet-double-treble'],
  techniqueSlugs: ['crochet-half-treble', 'crochet-treble', 'crochet-double-treble', 'crochet-sedge-stitch'],
  criticalTechniques: ['crochet-half-treble', 'crochet-treble', 'crochet-double-treble'],
  aliases: ['sedge stitch crochet', 'fan cluster throw', 'tweedy crochet blanket'],
  glossaryTerms: [
    { slug: 'double-treble', term: 'Double treble', definition: 'UK: dtr. Two yarn-overs before inserting the hook. Four draw-throughs to complete. Taller than a treble, giving the sedge cluster its lean.' },
    { slug: 'htr', term: 'Htr', definition: 'Half treble. UK abbreviation. One yarn-over before inserting the hook, then all three loops pulled through at once.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Sedge stitch from the mixed-height cluster family in Weldon\'s Practical Crochet (series 4, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A sedge stitch throw is 90 x 100 cm. Each cluster groups one '), gt('htr', 'htr'), t(', one tr, and one '), gt('double-treble', 'dtr'), t(' into the same stitch. The three different heights lean the cluster to one side and tile across the row to make a tweedy, angled surface.')),
      p(t('Aran weight in a natural or tweedy colour shows the sedge texture best. The cluster is three stitches into one point, then skip two. This gives a gentle drape with more body than a plain treble blanket. Total yardage is around 680 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn', qty: '680 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('10 sedge clusters x 7 rows = 10 x 10 cm in aran with a 5 mm hook. One cluster = htr, tr, dtr into the same base point.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('htr (UK) / hdc (US): half treble')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('dtr (UK) / tr (US): double treble')),
        li(t('sedge cluster: (htr, tr, dtr) into the same stitch')),
      ),
      h2('Foundation chain'),
      p(t('Chain 130 (43 repeats of 3 ch + 1 edge).')),
      h2('Row 1'),
      p(t('Ch 2. *Work (htr, tr, dtr) into next stitch. Skip 2 stitches*. Repeat to last stitch. Htr into last stitch. Turn. (43 clusters.)')),
      h2('Row 2 and onward'),
      p(t('Ch 2. *Work sedge cluster into the dtr (tallest stitch) of each cluster below*. Htr into turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 100 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly with steam to settle the angled clusters.')),
      h2('Care'),
      p(t('Handwash wool cool or machine wash acrylic at 40 degrees. Dry flat.')),
      h2('What to try next'),
      p(t('The shell stitch baby blanket uses a similar fan cluster with all stitches the same height. Or try the basketweave throw for a different kind of surface texture in the same weight.')),
    ],
  },
},

// ── 21 ── star stitch baby blanket ────────────────────────────────────────────
{
  slug: 'star-stitch-baby-blanket',
  title: 'Star stitch baby blanket',
  subtitle: 'Six-leg star clusters make a geometric texture across a DK cotton blanket.',
  excerpt: 'Star stitch pulls five loops into a central point and closes them, making a star shape that tiles across a flat baby blanket in DK cotton. The back side is also attractive.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '9 stars × 10 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-star-stitch'],
  techniqueSlugs: ['crochet-star-stitch', 'crochet-double-uk'],
  criticalTechniques: ['crochet-star-stitch'],
  aliases: ['star stitch crochet', 'star blanket', 'star cluster baby blanket'],
  glossaryTerms: [
    { slug: 'star-stitch', term: 'Star stitch', definition: 'Pull up five loops (from the eye of the previous star, and from four consecutive stitches), then yarn over and draw through all six. Close with ch 1. The loops radiate out like a star.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each star stitch row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Star stitch from the pulled-loop family in Weldon\'s Practical Crochet (series 4, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('star-stitch', 'star stitch'), t(' baby blanket is 75 x 90 cm. Each star pulls five loops into a central point and closes them with one yarn-over, making a geometric star shape that tiles across the fabric. The reverse side is equally textured.')),
      p(t('DK cotton shows the star points cleanly. Each star occupies 2 stitches in width so the repeat is simple once the first row is established. Total yardage is around 370 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '370 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('9 stars x 10 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Work a test row of 18 stars and measure across.')),
      h2('How to make a star'),
      p(t('*Insert hook into the ch-1 eye of the previous star and pull up loop. Pull up loops from each of the next 4 stitches or chains (6 loops total on hook). Yarn over, pull through all 6 loops. Ch 1 to form the eye of the new star*. One star made.')),
      h2('Foundation chain'),
      p(t('Chain 153 (76 star repeats x 2 ch + 1 starting chain).')),
      h2('Row 1'),
      p(t('Work a '), gt('turning-chain', 'turning chain'), t(' of ch 2. Pull up a loop from 2nd and 3rd ch from hook, and from next 3 ch (5 loops + working loop). Yarn over, pull through all 6. Ch 1 (eye made). *Work star from eye + next 4 ch*. Repeat. Turn. (76 stars.)')),
      h2('Row 2 and onward'),
      p(t('Ch 2. Pull up loops from the ch-2 turning chain, the eye of the first star, and from the next 3 ch-1 eyes. Work star. Continue along row, each new star pulling from the previous eye and the next 4 stitches. Turn.')),
      p(t('Repeat Row 2 until piece measures 90 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to even the star points.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. The star structure holds well through washing.')),
      h2('What to try next'),
      p(t('The shell stitch blanket uses a simpler fan motif in the same DK weight. Or try the bobble blanket for a raised texture that is easier to work at speed.')),
    ],
  },
},

// ── 22 ── staggered stripe throw ──────────────────────────────────────────────
{
  slug: 'staggered-stripe-throw',
  title: 'Staggered stripe throw',
  subtitle: 'Offset colour blocks in short treble sections make a brick-like stripe.',
  excerpt: 'Working short sections of colour across each row and offsetting them by half a repeat every two rows makes a staggered brick-stripe pattern on an aran-weight throw.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 tr × 8 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 100 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-colour-change', 'crochet-intarsia'],
  criticalTechniques: ['crochet-treble', 'crochet-colour-change'],
  aliases: ['brick stitch throw', 'intarsia crochet blanket', 'offset stripe blanket'],
  glossaryTerms: [
    { slug: 'colour-change-crochet', term: 'Colour change', definition: 'Pulling a new colour yarn through the final two loops of the last stitch of the old colour section, so the new colour starts cleanly.' },
    { slug: 'intarsia-crochet', term: 'Intarsia', definition: 'Working separate yarn bobbins or butterflies for each colour block in the row, leaving no floats at the back. Used when colour sections are wide and not repeated across the row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Brick-pattern intarsia from the colour-section family. No direct Weldon source; synthetic from colour-block construction principles.',
  body: {
    type: 'doc', content: [
      p(t('A staggered stripe throw is 90 x 100 cm. Each row has sections of 14 trebles in Colour A and 14 in Colour B. The sections offset by 7 stitches every two rows to make a brick-like stagger across the fabric.')),
      p(t('The '), gt('intarsia-crochet', 'intarsia'), t(' method uses a separate bobbin for each colour section. This avoids long floats on the back. A two-colour version with strong contrast gives the clearest brick pattern. Total yardage is around 700 g (350 g per colour).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, Colour A', qty: '350 g' },
        { name: 'Aran yarn, Colour B', qty: '350 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Small bobbins or butterflies', qty: '6' },
      ]),
      h2('Gauge'),
      p(t('14 tr x 8 rows = 10 x 10 cm in aran with a 5 mm hook.')),
      h2('How colour changes work'),
      p(t('To make a '), gt('colour-change-crochet', 'colour change'), t(' mid-row: work the last tr of the old colour until 2 loops remain on the hook. Drop old colour to the back and pull the new colour through the final 2 loops. The new colour begins.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
      ),
      h2('Foundation chain'),
      p(t('Using Colour A, chain 127 (126 tr + 1 turning chain).')),
      h2('Row 1 (set-up colours)'),
      p(t('Ch 3. Work 13 tr in Colour A. *Change to Colour B, work 14 tr. Change to Colour A, work 14 tr*. Repeat. Turn. (9 x A sections, 9 x B sections approximately.)')),
      h2('Row 3 (offset by 7)'),
      p(t('Shift the colour boundary by 7 stitches to the right at the start of this row and every 2 rows. This creates the stagger. Carry the change across all rows.')),
      h2('Continuing'),
      p(t('Continue for 80 rows (100 cm). Fasten off and close all bobbins.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t(', working each tail into the back of its own colour section to hide it.')),
      h2('Care'),
      p(t('Machine wash 40 degrees, normal cycle. Dry flat. Acrylic aran holds the brick pattern well through washing.')),
      h2('What to try next'),
      p(t('The chevron blanket is a simpler two-colour project without mid-row changes. Or try the c2c blanket for a diagonal colour-block approach.')),
    ],
  },
},

// ── 23 ── filet mesh baby blanket ─────────────────────────────────────────────
{
  slug: 'filet-mesh-baby-blanket',
  title: 'Filet mesh baby blanket',
  subtitle: 'An open treble grid with optional filled squares for a simple motif.',
  excerpt: 'Filet crochet uses a grid of open chain spaces and filled treble squares to make text or pictures. This baby blanket version works a simple heart motif in a treble grid.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-3-5mm',
  gauge: '14 mesh squares × 14 rows = 10 × 10 cm in DK cotton with a 3.5 mm hook.',
  finishedSize: 'Baby blanket, 70 x 80 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-filet-mesh', 'crochet-filet-fill'],
  criticalTechniques: ['crochet-treble', 'crochet-filet-mesh'],
  aliases: ['filet crochet blanket', 'filet baby blanket', 'mesh crochet blanket'],
  glossaryTerms: [
    { slug: 'filet-open-square', term: 'Open square', definition: 'In filet crochet: 2 ch, skip 2 stitches, 1 tr. The chain space forms the open hole of the mesh grid.' },
    { slug: 'filet-filled-square', term: 'Filled square', definition: 'In filet crochet: 2 tr instead of 2 ch. Filling the hole creates a solid block in the grid picture.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Filet crochet grid from Weldon\'s Practical Needlework (series 10, 1895). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A filet mesh baby blanket is 70 x 80 cm. The fabric is a grid of trebles: '), gt('filet-open-square', 'open squares'), t(' and '), gt('filet-filled-square', 'filled squares'), t(' sit on the same base to make pictures or text. This version works a heart at the centre of a plain mesh.')),
      p(t('Filet in DK cotton on a 3.5 mm hook gives a firm, clear grid with well-defined squares. The tighter hook than normal for DK stops the mesh from going too open. Total yardage is around 300 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '300 g' },
        { name: '3.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
        { name: 'Grid chart (heart motif)', qty: '1' },
      ]),
      h2('Gauge'),
      p(t('14 mesh squares x 14 rows = 10 x 10 cm in DK cotton with a 3.5 mm hook. One mesh square = one open or filled unit. Measure 14 units across, not individual trebles.')),
      h2('Reading filet charts'),
      p(t('An open square on the chart means work 2 ch, skip 2, 1 tr. A filled square means work 2 tr instead of the chain. Each square in the chart is one unit of your grid.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('tr (UK) / dc (US): treble')),
        li(t('open: 2 ch, skip 2, 1 tr')),
        li(t('fill: 2 tr instead of 2 ch')),
      ),
      h2('Foundation chain'),
      p(t('Chain 199 (66 mesh squares x 3 chains + 1 turning chain).')),
      h2('Row 1 (plain open mesh)'),
      p(t('Ch 5 (counts as tr + 2 ch). Skip 3 ch. *Work tr, ch 2, skip 2, tr*. Repeat across. Turn. (66 open squares.)')),
      h2('Working the heart motif'),
      p(t('Follow the grid chart, working filled squares where the heart falls and open squares everywhere else. The heart sits at rows 30 to 50, centred in the 66-square-wide grid. All other rows are plain open mesh.')),
      h2('Edging'),
      p(t('Work 2 rounds of dc (UK) around the perimeter: 1 dc into each tr, 2 dc into each ch-2 space, 3 dc into corners.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block firmly by wet-blocking: pin to the stated dimensions while damp and allow to dry fully. The grid squares only show clearly when blocked.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Reshape and dry flat. Reblock if the grid squares distort.')),
      h2('What to try next'),
      p(t('The v-stitch blanket is a simpler open mesh with no chart. Or try the diamond mesh throw for a different open-grid structure without filled squares.')),
    ],
  },
},

// ── 24 ── baby blanket in rows of half treble ─────────────────────────────────
{
  slug: 'third-loop-htr-blanket',
  title: 'Third loop half treble blanket',
  subtitle: 'Working into the third loop of htr makes a flat ribbed surface.',
  excerpt: 'The half treble has three loops at the top instead of the usual two. Inserting the hook into the third loop only makes a flat, ribbed fabric with a fabric-like hand on both sides.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 htr × 14 rows = 10 × 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-half-treble'],
  techniqueSlugs: ['crochet-half-treble', 'crochet-third-loop'],
  criticalTechniques: ['crochet-half-treble', 'crochet-third-loop'],
  aliases: ['third loop crochet', 'ribbed crochet baby blanket', 'flat htr blanket'],
  glossaryTerms: [
    { slug: 'third-loop-htr', term: 'Third loop', definition: 'The half treble has a third loop at the back that sits below the normal two top loops. Working into it makes a flatter, more fabric-like stitch.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each htr row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Third-loop htr is a modern technique refinement. No direct Weldon source. Synthetic from technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('third-loop-htr', 'third loop'), t(' htr baby blanket is 75 x 90 cm. The hook goes into the extra loop that sits below the two normal top loops of each half treble. Both sides of the fabric look the same and the surface is flat and smooth with a subtle horizontal rib.')),
      p(t('DK cotton shows the flat rib most clearly. The third-loop stitch uses slightly more yarn than regular htr because the loop is a little tighter. Total yardage is around 400 g.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '400 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Finding the third loop'),
      p(t('With the right side facing and the row just completed lying flat, look at the top of each htr. You will see two front loops as normal. Tilt the work away from you slightly: the third loop is the horizontal strand running behind and below the two main loops. Insert the hook under this loop only.')),
      h2('Gauge'),
      p(t('16 htr x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook. Third-loop htr has a slightly different tension from regular htr; check a full swatch.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('htr-3rd (UK) / hdc-3rd (US): half treble into the third loop only')),
      ),
      h2('Foundation chain'),
      p(t('Chain 121.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2 (counts as 1 htr). Work 1 htr into the 3rd ch from hook and every remaining chain. Turn. (120 htr.)')),
      h2('Row 2 and onward'),
      p(t('Ch 2. Work 1 htr into the third loop of every htr across. Work 1 htr into the top of the turning chain at the end. Turn. (120 htr.)')),
      p(t('Repeat Row 2 until piece measures 90 cm (about 126 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. No edging is needed: the clean rib makes a neat self-edge. Block lightly with steam.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat. The third-loop fabric holds its shape well.')),
      h2('What to try next'),
      p(t('The regular half treble baby blanket is the same stitch without the third-loop technique. Or try the waffle stitch throw for a deeper dimpled texture in aran weight.')),
    ],
  },
},

// ── 25 ── striped dc throw ────────────────────────────────────────────────────
{
  slug: 'striped-dc-throw',
  title: 'Striped double crochet throw',
  subtitle: 'Plain double crochet rows in a rotating four-colour stripe sequence.',
  excerpt: 'Double crochet rows in a four-colour stripe. The tight dc stitch in aran weight gives a dense, warm throw that is easy to work during episodes of a long series.',
  difficulty: 'BEGINNER',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '14 dc × 16 rows = 10 × 10 cm in aran yarn with a 5 mm hook.',
  finishedSize: 'Lap throw, 90 x 110 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-colour-change', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk', 'crochet-colour-change'],
  aliases: ['striped crochet throw', 'dc stripe blanket', 'four colour throw'],
  glossaryTerms: [
    { slug: 'colour-change-crochet', term: 'Colour change', definition: 'Pulling the new colour through the final loop of the last stitch in the old colour. The new colour begins on the next row.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each double crochet row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Plain dc stripe blanket. Stripe construction from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A striped dc throw is 90 x 110 cm. Each row is plain double crochet and the '), gt('colour-change-crochet', 'colour changes'), t(' every 4 rows in a four-colour rotation. Dense dc in aran weight produces a firm, warm fabric.')),
      p(t('Four colours in a rotation give a clean stripe repeat without cutting yarn every row: carry each colour up the side edge and pick it up every 16 rows. Total yardage is around 600 g (150 g per colour).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn, Colour A', qty: '150 g' },
        { name: 'Aran yarn, Colour B', qty: '150 g' },
        { name: 'Aran yarn, Colour C', qty: '150 g' },
        { name: 'Aran yarn, Colour D', qty: '150 g' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('14 dc x 16 rows = 10 x 10 cm in aran with a 5 mm hook. At this gauge a foundation chain of 127 gives 90 cm width (126 dc).')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet')),
      ),
      h2('Foundation chain (Colour A)'),
      p(t('Chain 127.')),
      h2('Row 1'),
      p(gt('turning-chain', 'turning chain'), t(' of ch 1 (does not count as a stitch). Dc into every chain. Turn. (126 dc.)')),
      h2('Rows 2 to 4 (Colour A)'),
      p(t('Ch 1. Dc into every stitch across. Turn.')),
      h2('Rows 5 to 8 (Colour B)'),
      p(t('At the end of Row 4, join Colour B by pulling it through the final 2 loops of the last dc. Work 4 rows of dc in Colour B. Do not cut Colour A; carry it up the side edge.')),
      h2('Continuing the stripe'),
      p(t('Work 4 rows each in Colour C, then Colour D, then back to Colour A. Each colour is picked up from the side edge. Work until piece measures 110 cm. Fasten off all colours.')),
      h2('Finishing'),
      p(t('Secure any remaining tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The carried yarns at the side edges make a self-finished selvedge. Block if needed.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal cycle. Tumble dry low. Acrylic aran holds the stripe colours without bleeding if pre-washed separately.')),
      h2('What to try next'),
      p(t('The granny stripe blanket uses the same colour-rotation idea with treble clusters. Or try the chevron blanket to add a wave shape to the same stripe sequence.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
