/**
 * Generator: D-Homewares Batch 6 — Dishcloths 11-25
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch6.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ── D11 ── bobble stitch dishcloth ────────────────────────────────────────────
{
  slug: 'bobble-stitch-dishcloth',
  title: 'Bobble stitch dishcloth',
  subtitle: 'Five-treble bobbles on every other stitch make a raised dot grid for scrubbing.',
  excerpt: 'A bobble of five joined trebles creates a firm raised dot. Alternating bobbles with dc stitches in a grid makes a dishcloth with excellent scrubbing texture on one side.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '14 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-bobble'],
  techniqueSlugs: ['crochet-bobble', 'crochet-double-uk'],
  criticalTechniques: ['crochet-bobble'],
  aliases: ['bobble dishcloth', 'bumpy dishcloth', 'textured scrubby cloth'],
  glossaryTerms: [
    { slug: 'bobble-st', term: 'Bobble stitch', definition: 'Five trebles into the same stitch, all left unfinished (last draw-through held), then one final draw-through to close all five at once. Pops to one side of the fabric.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each dc row; two chains at the start of bobble rows.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Bobble stitch from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('bobble-st', 'bobble stitch'), t(' dishcloth is 20 x 20 cm. Rows of dc alternate with rows placing a bobble in every other stitch. The bobbles appear on one side of the fabric, which is the scrubbing side.')),
      p(t('DK cotton on a 4 mm hook. Bobble rows are worked on the wrong side so the bobbles push to the right side. Total yarn needed is around 35 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a bobble'),
      p(t('In one stitch: *yarn over, insert hook, pull up loop, yarn over, draw through 2*. Repeat 4 more times (5 incomplete tr). Yarn over and draw through all 6 loops. Bobble made.')),
      h2('Gauge'),
      p(t('14 sts x 14 rows = 10 x 10 cm in DK cotton. Foundation chain of 29 (28 sts) gives 20 cm width. Work 28 rows for 20 cm height.')),
      h2('Foundation chain'),
      p(t('Chain 29.')),
      h2('Row 1 (plain dc)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into every chain from the 2nd. Turn. (28 dc.)')),
      h2('Row 2 (bobble row, wrong side)'),
      p(t('Ch 2. Dc into first stitch. *Bobble into next stitch, dc into next stitch*. Repeat. Turn.')),
      h2('Rows 3 onward'),
      p(t('Alternate Row 1 (plain dc) and Row 2 (bobble) for 28 rows. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The bobble side is the scrubbing face.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The puff stitch dishcloth uses puffs instead of bobbles for a softer raised dot. Or try the popcorn dishcloth for a bolder, firmer raised element.')),
    ],
  },
},

// ── D12 ── puff stitch dishcloth ──────────────────────────────────────────────
{
  slug: 'puff-stitch-dishcloth',
  title: 'Puff stitch dishcloth',
  subtitle: 'Soft half-treble puffs in a grid give a gentle raised texture.',
  excerpt: 'A puff stitch pulls up several loops from the same stitch and closes them together. The result is softer and rounder than a bobble. Puffs in a grid make a face-cloth-quality dishcloth.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '14 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-puff'],
  techniqueSlugs: ['crochet-puff', 'crochet-double-uk'],
  criticalTechniques: ['crochet-puff'],
  aliases: ['puff dishcloth', 'hdc puff cloth', 'soft texture dishcloth'],
  glossaryTerms: [
    { slug: 'puff-st', term: 'Puff stitch', definition: 'Pull up 4-5 loops from the same stitch (yarn over, insert, pull up), then close all at once with one final draw-through. Rounder and softer than a bobble.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each puff row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Puff stitch from Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('puff-st', 'puff stitch'), t(' dishcloth is 20 x 20 cm. Puffs sit in every other stitch on every other row. The round, soft raised element is gentler on delicate surfaces than a bobble.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 35 m. Puffs use slightly more yarn than dc because of the extra loops.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a puff'),
      p(t('*Yarn over, insert hook into stitch, pull up loop*. Repeat 3 times (7 loops on hook). Yarn over and draw through all 7 loops. Ch 1 to close. One puff made.')),
      h2('Foundation chain'),
      p(t('Chain 29.')),
      h2('Row 1 (plain dc)'),
      p(t('Ch 1. Dc into every chain. Turn. (28 dc.)')),
      h2('Row 2 (puff row)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2. *Puff into next stitch, dc into next stitch*. Repeat. Turn.')),
      h2('Rows 3 onward'),
      p(t('Alternate Row 1 and Row 2 for 28 rows. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The bobble stitch dishcloth uses the firmer five-treble bobble. Or try the popcorn dishcloth for the most prominent raised element.')),
    ],
  },
},

// ── D13 ── popcorn dishcloth ──────────────────────────────────────────────────
{
  slug: 'popcorn-dishcloth',
  title: 'Popcorn dishcloth',
  subtitle: 'Prominent popcorn stitches form a grid of raised domes on a firm cotton cloth.',
  excerpt: 'A popcorn is five trebles worked in one stitch, then the first and last are joined by removing the hook and re-inserting it. The dome stands off the fabric firmly.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '12 sts x 12 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-popcorn'],
  techniqueSlugs: ['crochet-popcorn', 'crochet-double-uk'],
  criticalTechniques: ['crochet-popcorn'],
  aliases: ['popcorn dishcloth', 'dome stitch dishcloth', 'textured crochet cloth'],
  glossaryTerms: [
    { slug: 'popcorn-st', term: 'Popcorn stitch', definition: 'Work 5 tr into one stitch. Remove hook from working loop. Insert hook into the top of the first of the 5 tr, then back into the dropped loop, and draw through. Ch 1. The 5 stitches fold into a dome.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of plain dc rows; two chains at the start of popcorn rows.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Popcorn stitch from Weldon\'s Practical Crochet (series 4, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('popcorn-st', 'popcorn'), t(' dishcloth is 20 x 20 cm. A grid of popcorns sits in alternating stitches on every other row. Each popcorn dome is firm and prominent.')),
      p(t('DK cotton on a 4 mm hook. Popcorn rows are worked on the wrong side so the domes face front. Total yarn needed is around 40 m because the folded domes use extra yarn.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '40 m (about 32 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 25.')),
      h2('Row 1 (plain dc)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into every chain. Turn. (24 dc.)')),
      h2('Row 2 (popcorn row, wrong side)'),
      p(t('Ch 2. Dc into first stitch. *Popcorn into next stitch, dc into next stitch*. Repeat. Turn.')),
      h2('Rows 3 onward'),
      p(t('Alternate Row 1 and Row 2 for 24 rows. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The popcorn domes should face forward on the right side.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The bobble stitch dishcloth uses a joined set of trebles for a lower, rounder raise. Or try the puff stitch dishcloth for the softest raised element.')),
    ],
  },
},

// ── D14 ── v-stitch dishcloth ─────────────────────────────────────────────────
{
  slug: 'v-stitch-dishcloth',
  title: 'V-stitch dishcloth',
  subtitle: 'Open V-stitches make a light, quick-drying dishcloth.',
  excerpt: 'V-stitches are two trebles with a chain between, worked into the same base stitch. Rows of V-stitches make an open mesh that dries quickly between uses.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '12 V-sts x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-v-stitch'],
  techniqueSlugs: ['crochet-v-stitch', 'crochet-treble'],
  criticalTechniques: ['crochet-v-stitch'],
  aliases: ['v stitch dishcloth', 'open mesh dishcloth', 'quick dry cloth'],
  glossaryTerms: [
    { slug: 'v-stitch', term: 'V-stitch', definition: 'Two trebles with one chain between, worked into the same stitch or space. Repeated across a row to make an open, stretchy mesh.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Four chains at the start of each V-stitch row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'V-stitch from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('v-stitch', 'V-stitch'), t(' dishcloth is 20 x 20 cm. Each V is two trebles sharing a base with a chain between. Rows of Vs make an open mesh cloth that dries quickly and is light enough to fold small.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 20 m because the open stitch uses less yarn than a solid fabric.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '20 m (about 16 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 45 (multiple of 3 + 3 edge chains).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 4. *Skip 2, V-stitch into next ch*. Repeat. End with tr into last ch. Turn. (14 V-sts.)')),
      h2('Row 2 and onward'),
      p(t('Ch 4. *V-stitch into each ch-1 space of each V below*. End with tr. Turn.')),
      p(t('Repeat Row 2 for 16 rows (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Hang to dry or tumble dry low.')),
      h2('What to try next'),
      p(t('The basic dc dishcloth is a denser version of a similar size. Or try the moss stitch dishcloth for a semi-open pattern.')),
    ],
  },
},

// ── D15 ── granny square dishcloth ────────────────────────────────────────────
{
  slug: 'granny-square-dishcloth',
  title: 'Granny square dishcloth',
  subtitle: 'A single 5-round granny square makes a sturdy 20 cm dishcloth.',
  excerpt: 'One granny square worked to 5 rounds in DK cotton makes a dishcloth about 20 cm across. The double-cluster structure is firm enough for washing up.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '1 round = approx 3 cm added per side. 5 rounds reach 20 cm.',
  finishedSize: 'Square dishcloth, approx 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-double-uk', 'crochet-granny-cluster', 'crochet-magic-ring'],
  techniqueSlugs: ['crochet-granny-cluster', 'crochet-magic-ring', 'crochet-double-uk'],
  criticalTechniques: ['crochet-granny-cluster', 'crochet-magic-ring'],
  aliases: ['granny dishcloth', 'granny square cloth', 'one motif dishcloth'],
  glossaryTerms: [
    { slug: 'magic-ring-dc', term: 'Magic ring', definition: 'An adjustable loop start for working in the round. Pull the tail to close the centre hole. Gives a tight, neat centre.' },
    { slug: 'granny-cl', term: 'Granny cluster', definition: 'Three trebles worked into the same chain space, forming the basic block unit of a granny square.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Granny square from Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A granny square dishcloth is a single 5-round granny motif about 20 cm across. Worked in DK cotton on a 4 mm hook, 5 rounds reach the right size for a dishcloth.')),
      p(t('Starting with a '), gt('magic-ring-dc', 'magic ring'), t(' gives a tightly closed centre. The '), gt('granny-cl', 'granny clusters'), t(' make a firm, thick fabric. Total yarn needed is around 35 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Round 1'),
      p(t('Magic ring. Ch 3, 2 tr into ring (first cluster), ch 2. *3 tr into ring (cluster), ch 2*. Repeat 3 times. Sl st to top of ch 3. Pull ring closed. (4 clusters, 4 ch-2 corners.)')),
      h2('Round 2'),
      p(t('Sl st to corner space. Ch 3, 2 tr, ch 2, 3 tr into same space (corner). *Ch 1, corner into next space*. Repeat. Ch 1. Sl st. (4 corners.)')),
      h2('Rounds 3 to 5'),
      p(t('Sl st to corner. Ch 3, 2 tr, ch 2, 3 tr into corner. *Ch 1, 3 tr into each ch-1 side space with ch 1 between, ch 1, corner into corner space*. Repeat. Sl st. Each round adds one cluster per side.')),
      h2('Finishing'),
      p(t('Fasten off after round 5. Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. No edging needed unless the edges look uneven.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang flat.')),
      h2('What to try next'),
      p(t('Work 5 rounds to a larger hook size for a bigger cloth. Or join two granny squares side by side for a longer rectangle cloth.')),
    ],
  },
},

// ── D16 ── ribbed htr washcloth ───────────────────────────────────────────────
{
  slug: 'ribbed-htr-washcloth',
  title: 'Ribbed htr washcloth',
  subtitle: 'Front and back post half trebles make a stretchy ribbed washcloth.',
  excerpt: 'Alternating FPhtr and BPhtr in a 1x1 rib makes a washcloth that stretches across and recovers. Good for face washing where some give makes the cloth easier to hold.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '20 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook, 1x1 rib.',
  finishedSize: 'Rectangle washcloth, 20 x 25 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-half-treble', 'crochet-flo-htr', 'crochet-blo-htr'],
  techniqueSlugs: ['crochet-flo-htr', 'crochet-blo-htr', 'crochet-half-treble'],
  criticalTechniques: ['crochet-flo-htr', 'crochet-blo-htr'],
  aliases: ['ribbed washcloth', 'htr rib cloth', 'stretchy face cloth'],
  glossaryTerms: [
    { slug: 'fphtr', term: 'FPhtr', definition: 'Front post half treble. Yarn over, insert hook from front to back to front around the post of the stitch below. Complete the htr. The stitch raises to the front.' },
    { slug: 'bphtr', term: 'BPhtr', definition: 'Back post half treble. Yarn over, insert hook from back to front to back around the post below. The stitch pushes to the back, forming a recessed rib.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Post stitch rib from Weldon\'s Practical Crochet (series 4, 1880s). htr rib is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A ribbed htr washcloth is 20 x 25 cm. Rows of alternating '), gt('fphtr', 'FPhtr'), t(' and '), gt('bphtr', 'BPhtr'), t(' make a 1x1 rib. The fabric stretches sideways, which makes the cloth easy to fold and drape when washing a face.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 40 m. The 1x1 rib is denser and thicker than plain htr, which makes the cloth more absorbent.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '40 m (about 32 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation'),
      p(t('Chain 41. Work one row of 40 plain htr. Turn.')),
      h2('Row 2 and onward'),
      p(t('Ch 2. *FPhtr over FPhtr, BPhtr over BPhtr from row below*. Repeat. Turn.')),
      p(t('Repeat for 35 rows (approximately 25 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block the cloth flat to even the rib.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The post stitch baby blanket uses the same rib technique in a larger format. Or try the basic dc dishcloth for a non-ribbed comparison.')),
    ],
  },
},

// ── D17 ── treble mesh dishcloth ──────────────────────────────────────────────
{
  slug: 'treble-mesh-dishcloth',
  title: 'Treble mesh dishcloth',
  subtitle: 'A simple ch-1, tr grid makes an open mesh cloth that drains and dries fast.',
  excerpt: 'Alternating trebles and chain-1 spaces in a grid make a mesh dishcloth. The open structure drains well over a sink edge and dries faster than solid fabric.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '14 sts x 8 rows = 10 x 10 cm in DK cotton with a 4 mm hook, mesh pattern.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble'],
  techniqueSlugs: ['crochet-treble', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-treble'],
  aliases: ['mesh dishcloth', 'open grid cloth', 'treble grid dishcloth'],
  glossaryTerms: [
    { slug: 'mesh-pattern', term: 'Mesh pattern', definition: 'Alternating trebles and chain-1 spaces in a regular grid. Every row places a treble into each chain space from the row below, building a stable open lattice.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Four chains at the start of each mesh row (3 for the first treble + 1 for the first chain space).' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Treble mesh from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('mesh-pattern', 'treble mesh'), t(' dishcloth is 20 x 20 cm. Trebles and ch-1 spaces alternate in a regular grid. The open structure allows water to drain through when the cloth hangs over a tap or sink edge.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 20 m because the open grid uses less yarn than solid fabric.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '20 m (about 16 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 31 (multiple of 2 + 1).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 4. *Tr into next ch, ch 1, skip 1*. Repeat. Tr into last ch. Turn.')),
      h2('Row 2 and onward'),
      p(t('Ch 4. *Tr into each ch-1 space, ch 1*. Repeat. Tr into 3rd ch of turning chain. Turn.')),
      p(t('Repeat Row 2 for 16 rows (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. No edging needed.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Hang to dry.')),
      h2('What to try next'),
      p(t('The v-stitch dishcloth is a wider open mesh. Or try the basic dc dishcloth for a dense, non-mesh version.')),
    ],
  },
},

// ── D18 ── htr blo washcloth ──────────────────────────────────────────────────
{
  slug: 'htr-blo-washcloth',
  title: 'Htr BLO washcloth',
  subtitle: 'Half treble worked into the back loop only gives a ridged corduroy-like washcloth.',
  excerpt: 'Every half treble is worked into the back loop only. Each row leaves a front loop bar as a ridge, giving the cloth a corduroy-like ribbed surface.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 htr x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook, BLO.',
  finishedSize: 'Square washcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-half-treble', 'crochet-blo-htr'],
  techniqueSlugs: ['crochet-blo-htr', 'crochet-half-treble'],
  criticalTechniques: ['crochet-blo-htr'],
  aliases: ['blo htr washcloth', 'ridged htr cloth', 'corduroy washcloth'],
  glossaryTerms: [
    { slug: 'blo-htr', term: 'BLO htr', definition: 'Half treble worked into the back loop only. The un-worked front loop becomes a horizontal bar on the surface, creating a ridge with each row.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each htr row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'BLO htr from the back-loop family in Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('An '), gt('blo-htr', 'htr BLO'), t(' washcloth is 20 x 20 cm. Working every htr into the back loop only leaves horizontal bar ridges across the surface on each row. The ridges give mild texture for washing.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 30 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 37 (36 htr).')),
      h2('Row 1 (both loops)'),
      p(t('Ch 2. Work 1 htr into every chain. Turn. (36 htr.)')),
      h2('Row 2 and onward'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2. Work 1 htr into the back loop only of every stitch across. Turn.')),
      p(t('Repeat Row 2 for 28 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The waffle stitch dishcloth uses FLO and BLO alternating in each row for a grid pattern. Or try the basic dc dishcloth for a smooth surface.')),
    ],
  },
},

// ── D19 ── corner to corner dishcloth ─────────────────────────────────────────
{
  slug: 'corner-to-corner-dishcloth',
  title: 'Corner to corner dishcloth',
  subtitle: 'The c2c method builds a diagonal grid of dc blocks from corner to corner.',
  excerpt: 'Corner to corner crochet starts with one block and increases by one block per row until the halfway point, then decreases to the opposite corner. The diagonal seams make a naturally firm cloth.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '4 blocks x 4 rows (diagonal) = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['c2c dishcloth', 'corner to corner cloth', 'diagonal dishcloth'],
  glossaryTerms: [
    { slug: 'c2c-block', term: 'C2C block', definition: 'A unit of corner-to-corner crochet: ch 6, sl st into the 4th ch to form a corner. Work 3 dc into the ch-3 loop just made. Or in later rows: ch 3, work 3 dc into the loop below.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Chain 6 at the start of increasing rows to set up the next edge block; chain 3 on decreasing rows.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'C2C crochet is a modern diagonal method. No direct Weldon source; synthetic from contemporary documentation.',
  body: {
    type: 'doc', content: [
      p(t('A corner to corner dishcloth is 20 x 20 cm. Each '), gt('c2c-block', 'c2c block'), t(' is three dc into a chain loop. The cloth grows by one block per row until reaching the widest point, then decreases. The diagonal seams make a naturally dense fabric.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 30 m. A 20 x 20 cm c2c cloth takes about 8 increase rows and 8 decrease rows.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Row 1 (1 block)'),
      p(t('Ch 6. Sl st into 4th ch from hook (makes a ch-3 loop). Ch 3, work 3 dc into the loop. Turn. (1 block.)')),
      h2('Increase rows (rows 2 to 8)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 6. Sl st into 4th ch to make new edge block. 3 dc into new loop. *Ch 3, sl st into next loop along from previous row. 3 dc into new loop*. Repeat to end. Turn. (One more block each row.)')),
      h2('Decrease rows (rows 9 to 16)'),
      p(t('Sl st across the first block of the previous row (3 sts + into the corner ch-3 loop). Ch 3, 3 dc into that loop. Continue in pattern to end. Turn. (One fewer block each row.) Last row: 1 block. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The c2c baby blanket uses the same method scaled up. Or try the basic dc dishcloth for a simpler start.')),
    ],
  },
},

// ── D20 ── double knit stitch dishcloth ────────────────────────────────────────
{
  slug: 'waistcoat-stitch-dishcloth',
  title: 'Waistcoat stitch dishcloth',
  subtitle: 'Waistcoat stitch produces a flat, knit-look fabric that makes a firm cloth.',
  excerpt: 'Waistcoat stitch inserts the hook between the two legs of each v-shaped stitch head, producing a fabric that looks like stocking stitch knitting. A firm, flat dishcloth.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-5mm',
  gauge: '18 sts x 22 rows = 10 x 10 cm in DK cotton with a 4.5 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-waistcoat-stitch'],
  techniqueSlugs: ['crochet-waistcoat-stitch', 'crochet-double-uk'],
  criticalTechniques: ['crochet-waistcoat-stitch'],
  aliases: ['waistcoat stitch cloth', 'knit look dishcloth', 'stocking stitch crochet cloth'],
  glossaryTerms: [
    { slug: 'waistcoat-st', term: 'Waistcoat stitch', definition: 'Instead of inserting the hook under the two top loops of a stitch, insert it between the two legs (under the v-shape of the stitch head from below). The dc made this way looks like a knit stitch from above.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each waistcoat stitch row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Waistcoat stitch is a modern name for a variation of dc insertion. No Weldon source; contemporary technique documentation.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('waistcoat-st', 'waistcoat stitch'), t(' dishcloth is 20 x 20 cm. Inserting the hook between the two legs of each stitch head produces a flat, dense fabric that looks like stocking stitch knitting from the front.')),
      p(t('DK cotton on a 4.5 mm hook (slightly larger than usual to keep the stitch from being too tight). Total yarn needed is around 35 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4.5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 37. Work one row of 36 dc (standard). Turn. This sets up the stitch heads for row 2.')),
      h2('Row 2 and onward'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. *Insert hook between the two legs of the next stitch v-shape, pull up loop, yarn over, draw through both loops (waistcoat dc)*. Repeat. Turn.')),
      p(t('Repeat Row 2 for 44 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The waistcoat stitch throw scales this technique into a larger project. Or try the ribbed htr washcloth for a different knit-look texture.')),
    ],
  },
},

// ── D21 ── picot edged dishcloth ──────────────────────────────────────────────
{
  slug: 'picot-edged-dishcloth',
  title: 'Picot edged dishcloth',
  subtitle: 'A plain dc body finished with a picot border on three sides.',
  excerpt: 'A 20 x 20 cm dc dishcloth with a picot stitch border worked around three edges. The small loop picots add a neat decorative trim without bulk.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-picot'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-picot'],
  criticalTechniques: ['crochet-picot'],
  aliases: ['picot edged cloth', 'decorative dishcloth', 'picot border cloth'],
  glossaryTerms: [
    { slug: 'picot-st', term: 'Picot stitch', definition: 'Work 1 dc, then ch 3, sl st back into the first ch just made to form a small standing loop. The picot sits on top of the dc and adds a decorative point.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each dc row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Picot stitch from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('picot-st', 'picot'), t(' edged dishcloth is 20 x 20 cm with a row of picot stitches on three sides. The body is plain dc. The picot border adds a small loop at every third stitch around the edge.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 35 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Body'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Work 32 dc. Turn. Repeat for 40 rows (20 cm). Fasten off.')),
      h2('Picot edging (3 sides)'),
      p(t('Join yarn at the bottom left corner. Work dc along the bottom, right, and top, with one picot (ch 3, sl st into first ch) every 3rd stitch. Work 3 dc into each corner. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The shell edged face cloth uses a more decorative border. Or try the basic dc dishcloth without a border for the fastest version.')),
    ],
  },
},

// ── D22 ── tunisian simple stitch dishcloth ────────────────────────────────────
{
  slug: 'tunisian-dishcloth',
  title: 'Tunisian simple stitch dishcloth',
  subtitle: 'A small Tunisian simple stitch cloth makes a flat, woven-look dishcloth.',
  excerpt: 'A 20 x 20 cm Tunisian simple stitch cloth uses a long hook or short Tunisian hook. The woven grid surface is firmer than a dc cloth of the same yarn.',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 tss x 14 rows = 10 x 10 cm in DK cotton with a 4 mm Tunisian hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-tunisian-simple'],
  techniqueSlugs: ['crochet-tunisian-simple'],
  criticalTechniques: ['crochet-tunisian-simple'],
  aliases: ['Tunisian dishcloth', 'afghan stitch cloth', 'tss dishcloth'],
  glossaryTerms: [
    { slug: 'tss-dc', term: 'Tunisian simple stitch', definition: 'Forward pass: insert hook under each vertical bar, pull up loop. Return pass: yarn over, draw through 2 loops at a time until 1 loop remains. Produces a woven grid surface.' },
    { slug: 'tunisian-bind-off', term: 'Tunisian bind-off', definition: 'A final row of sl st worked across all vertical bars to close off the last forward pass and make a neat edge.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Tunisian simple stitch (afghan stitch) from Weldon\'s Practical Needlework vol. 1, c.1885. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A Tunisian dishcloth is 20 x 20 cm using '), gt('tss-dc', 'Tunisian simple stitch'), t('. Each row is a forward pass loading loops and a return pass working them off. A short Tunisian hook or standard hook works for this width.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 35 m. The dense Tunisian fabric is firmer than standard dc and scrubs well.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '35 m (about 28 g)' },
        { name: '4 mm Tunisian or standard hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation'),
      p(t('Chain 37. Forward pass row 0: pull up loop from each chain back bump. (37 loops.)')),
      p(t('Return pass: yarn over, draw through 1 loop. *Yarn over, draw through 2*. Repeat.')),
      h2('Rows 1 to 28'),
      p(t('Forward pass: insert under each vertical bar, pull up loop. Return pass: yarn over, draw through 1, *yarn over, draw through 2*. Repeat for 28 rows (approximately 20 cm).')),
      h2('Bind-off'),
      p(gt('tunisian-bind-off', 'Bind-off'), t(': sl st across all vertical bars. Fasten off.')),
      h2('Finishing'),
      p(t('Block flat: the cloth will curl at edges until wet-blocked. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Pin flat while damp each wash.')),
      h2('What to try next'),
      p(t('The Tunisian simple stitch blanket uses the same technique at a larger scale. Or try the basic dc dishcloth for a cloth that does not require blocking.')),
    ],
  },
},

// ── D23 ── striped dishcloth ───────────────────────────────────────────────────
{
  slug: 'striped-dishcloth',
  title: 'Striped dishcloth',
  subtitle: 'Two-colour dc stripes in a kitchen cloth-style rectangle.',
  excerpt: 'A two-colour striped dishcloth in plain dc. Stripes of two rows each make a bold pattern. Colour changes happen at the end of each second row.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Rectangle dishcloth, 20 x 25 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-colour-change'],
  criticalTechniques: ['crochet-double-uk', 'crochet-colour-change'],
  aliases: ['striped kitchen cloth', 'two colour dishcloth', 'stripe dishcloth'],
  glossaryTerms: [
    { slug: 'colour-change-dc', term: 'Colour change', definition: 'Pull the new colour through the last loop of the last dc of the row so the next row begins cleanly in the new colour.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each dc row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Plain dc stripe from Weldon\'s Practical Crochet (series 1, 1880s). Colour-change method is a modern approach. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A striped dishcloth is 20 x 25 cm. Two-row stripes in Colour A and Colour B alternate across the cloth. '), gt('colour-change-dc', 'Colour changes'), t(' happen at the end of every 2nd row.')),
      p(t('DK cotton in two contrasting colours on a 4 mm hook. Total yarn needed is around 20 m each colour (40 m total).')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn, Colour A', qty: '20 m (about 16 g)' },
        { name: 'DK cotton yarn, Colour B', qty: '20 m (about 16 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain (Colour A)'),
      p(t('Chain 33 (32 dc).')),
      h2('Rows 1 and 2 (Colour A)'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Work 32 dc across. Turn. Work a second row. At the end of row 2, change to Colour B on the final pull-through. Carry Colour A up the side.')),
      h2('Rows 3 and 4 (Colour B), and onward'),
      p(t('Work 2 rows in Colour B, then change back to A. Repeat until piece measures 25 cm (approximately 50 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The side edges will show the carried yarn; trim or weave those in as well.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The lemon peel dishcloth adds texture to a similar stripe base. Or try the basic dc dishcloth in one colour first.')),
    ],
  },
},

// ── D24 ── htr dishcloth ──────────────────────────────────────────────────────
{
  slug: 'htr-dishcloth',
  title: 'Htr dishcloth',
  subtitle: 'Half treble rows make a slightly thicker, softer cloth than plain dc.',
  excerpt: 'Half treble is taller than dc but shorter than treble, and the fabric has a slight natural softness. A plain htr dishcloth is quick to work and slightly squishier than dc.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 htr x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-half-treble'],
  techniqueSlugs: ['crochet-half-treble'],
  criticalTechniques: ['crochet-half-treble'],
  aliases: ['htr dishcloth', 'half treble cloth', 'hdc dishcloth'],
  glossaryTerms: [
    { slug: 'htr', term: 'Half treble', definition: 'UK: htr (US: hdc). Yarn over before inserting hook, pull up loop (3 loops on hook), yarn over and draw through all 3 in one go. Taller than dc, shorter than treble.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of each htr row. Counts as the first htr.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Half treble from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('An '), gt('htr', 'htr'), t(' dishcloth is 20 x 20 cm. Plain half treble rows grow faster than dc rows because each stitch is taller. The fabric is slightly squishy and soft.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 30 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 33 (32 htr).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2. Work 1 htr into every chain from the 3rd. Turn. (32 htr.)')),
      h2('Rows 2 to 28'),
      p(t('Ch 2. Work 1 htr into every stitch. Work 1 htr into the top of the turning chain. Turn. Repeat for 28 rows (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The striped dishcloth adds two-colour stripes to the same plain structure. Or try the ribbed htr washcloth for a ribbed version of the same base stitch.')),
    ],
  },
},

// ── D25 ── double crochet rectangle dishcloth ─────────────────────────────────
{
  slug: 'rectangle-dc-dishcloth',
  title: 'Rectangle dc dishcloth',
  subtitle: 'A longer rectangle of plain dc in DK cotton for wiping down kitchen surfaces.',
  excerpt: 'A 20 x 30 cm rectangle in plain dc makes a surface-wiping cloth. The longer shape covers more area when wiping countertops or stovetops than a square cloth.',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Rectangle dishcloth, 20 x 30 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['rectangle dishcloth', 'long kitchen cloth', 'surface wipe cloth'],
  glossaryTerms: [
    { slug: 'dc-rect', term: 'Double crochet', definition: 'UK: dc. The foundation stitch for the dishcloth body. Insert hook, pull up loop, yarn over, draw through both loops.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each dc row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Plain dc row from Weldon\'s Practical Crochet (series 1, 1880s). Rectangle sizing is a modern adaptation. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A rectangle dc dishcloth is 20 x 30 cm in plain '), gt('dc-rect', 'double crochet'), t('. The longer shape covers more surface area when wiping down kitchen counters or stovetops. DK cotton on a 4 mm hook.')),
      p(t('Total yarn needed is around 40 m. Two cloths fit in one 50 g ball of DK cotton.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '40 m (about 32 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 33 (32 dc).')),
      h2('Rows 1 to 60'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Work 1 dc into every stitch across. Turn. Repeat for 60 rows (approximately 30 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. No edging needed unless the edges look uneven.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The basic dc dishcloth is the square version of this cloth. Or try the striped dishcloth to add two-colour interest to the same plain structure.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: 'homewares',
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
