/**
 * Generator: D-Homewares Batch 5 — Blankets 56-60 (final 5) + Dishcloths 1-10
 * Run: pnpm --filter "@homemade/db" exec tsx scripts/gen-crochet-d-homewares-batch5.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, 'briefs-crochet-d-homewares')
mkdirSync(OUT, { recursive: true })

function p(...nodes: object[]) { return { type: 'paragraph', content: nodes } }
function t(text: string) { return { type: 'text', text } }
function h2(text: string) { return { type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text }] } }
function gt(termSlug: string, text: string) { return { type: 'text', marks: [{ type: 'glossaryTooltip', attrs: { termSlug } }], text } }
function li(...c: object[]) { return { type: 'listItem', content: [{ type: 'paragraph', content: c }] } }
function ul(...items: object[]) { return { type: 'bulletList', content: items } }
function supplies(heading: string, items: { name: string; qty: string }[]) {
  return { type: 'suppliesCard', attrs: { heading, items } }
}

const TOOLS = [
  { slug: 'crochet-hook', isOptional: false },
  { slug: 'tapestry-needle', isOptional: false },
  { slug: 'craft-scissors', isOptional: false },
  { slug: 'measuring-tape-soft', isOptional: false },
]

const PATTERNS = [

// ══════════════════════════════════════════════════════════════════════════════
// BLANKETS 56-60 (final 5 to complete the 60-blanket quota)
// ══════════════════════════════════════════════════════════════════════════════

// ── 56 ── linked treble baby blanket ──────────────────────────────────────────
{
  slug: 'linked-treble-baby-blanket',
  title: 'Linked treble baby blanket',
  subtitle: 'Trebles linked to their neighbours produce a dense flat fabric without gaps.',
  excerpt: 'A linked treble connects each stitch to the one before by picking up a loop from the middle of the previous stitch. The resulting fabric has no gaps between stitches.',
  subCategorySlug: 'homewares',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '18 ltr x 9 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-linked-dc'],
  techniqueSlugs: ['crochet-linked-dc', 'crochet-treble'],
  criticalTechniques: ['crochet-linked-dc'],
  aliases: ['linked treble blanket', 'linked dc baby blanket', 'fabric stitch blanket'],
  glossaryTerms: [
    { slug: 'linked-tr', term: 'Linked treble', definition: 'Before inserting the hook into the next stitch, insert it into the upper horizontal loop of the previous treble and pull up a loop. Then complete the treble normally. The extra pick-up links stitches and closes the vertical gap.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of a linked treble row (the first linked treble is taller than a regular dc but shorter than a treble).' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Linked treble from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('linked-tr', 'linked treble'), t(' baby blanket is 75 x 90 cm. Each stitch picks up a loop from the side of the previous stitch before completing the treble. The fabric has no side gaps and lies almost as flat as woven cotton.')),
      p(t('DK cotton shows the dense fabric quality clearly. Total yardage is around 380 g. The linked stitch uses slightly more yarn than a standard treble because the extra loop adds height to each stitch.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '380 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work a linked treble'),
      p(t('Yarn over. Insert hook into the upper horizontal loop on the side of the previous stitch. Pull up a loop (3 loops on hook). Yarn over, insert hook into the next stitch, pull up a loop (5 loops on hook). Yarn over, draw through 2. Yarn over, draw through 2. Yarn over, draw through 2. One linked treble made.')),
      h2('Gauge'),
      p(t('18 ltr x 9 rows = 10 x 10 cm in DK cotton with a 4 mm hook. At this gauge a foundation chain of 135 gives 75 cm width (134 linked trebles).')),
      h2('Foundation chain'),
      p(t('Chain 136.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 2. Work 1 linked treble into every chain. Turn. (134 ltr.)')),
      h2('Row 2 and onward'),
      p(t('Ch 2. *Work 1 linked treble into every stitch*. Ltr into top of turning chain. Turn.')),
      p(t('Repeat Row 2 until piece measures 90 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly. The dense fabric needs minimal blocking.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The waistcoat stitch throw gives a similar woven look using a different technique. Or try the herringbone htr throw for a dense diagonal-texture fabric.')),
    ],
  },
},

// ── 57 ── fan stitch baby blanket ─────────────────────────────────────────────
{
  slug: 'fan-stitch-baby-blanket',
  title: 'Fan stitch baby blanket',
  subtitle: 'Seven-treble fans spread from single base stitches to make an arc-pattern blanket.',
  excerpt: 'A seven-treble fan opened from one base stitch gives a wide semicircular shape. Rows of fans in alternating positions fill a 75 x 90 cm baby blanket in DK cotton.',
  subCategorySlug: 'homewares',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '5 fans x 7 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-treble', 'crochet-fan-stitch'],
  techniqueSlugs: ['crochet-fan-stitch', 'crochet-treble'],
  criticalTechniques: ['crochet-fan-stitch'],
  aliases: ['fan stitch blanket', 'seven treble fan', 'arc stitch baby blanket'],
  glossaryTerms: [
    { slug: 'fan-st', term: 'Fan stitch', definition: 'Seven trebles worked into the same base stitch, spreading out in a wide arc or semicircle. Each fan takes one base stitch.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Four chains at the start of each fan row to reach the height of the first treble in the fan.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Fan stitch from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('fan-st', 'fan stitch'), t(' baby blanket is 75 x 90 cm. Seven trebles opened from one base stitch make a fan arc. In DK cotton on a 4 mm hook each fan is about 2 cm wide.')),
      p(t('The fans stack in a brick pattern: each row offsets the fans by half a repeat so every fan crown sits between two fans below. Total yardage is around 280 g. The fan stitch uses less yarn than a solid dc fabric of the same size.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '280 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work one fan'),
      p(t('Work 7 tr into the same base stitch. One fan made. Skip 3 ch (or sts) after the base before the next fan.')),
      h2('Gauge'),
      p(t('5 fans x 7 rows = 10 x 10 cm. One fan repeat = 4 stitches (1 base + 3 skipped). Foundation chain must be a multiple of 4 plus 4 edge chains.')),
      h2('Foundation chain'),
      p(t('Chain 152 (37 fans of 4 sts + 4 edge).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 4. *7 tr into next ch (fan). Skip 3 ch*. Dc into last ch. Turn. (37 fans.)')),
      h2('Row 2 (offset)'),
      p(t('Ch 4. Work fan into the 4th tr of each fan below. Dc between fans. Turn.')),
      h2('Continuing'),
      p(t('Alternate Row 1 and Row 2 until piece measures 90 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block lightly to open the fan arcs.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The petal stitch throw uses pairs of five-treble shells for a similar arc pattern with more overlap. Or try the shell stitch baby blanket for a five-treble version.')),
    ],
  },
},

// ── 58 ── spider stitch baby blanket ──────────────────────────────────────────
{
  slug: 'spider-stitch-baby-blanket',
  title: 'Spider stitch baby blanket',
  subtitle: 'Elongated loops pulled up in groups form a spider-web mesh on a DK baby blanket.',
  excerpt: 'Spider stitch pulls up groups of elongated loops and then locks them together at the top. The resulting mesh looks like a spider web and is open but stable.',
  subCategorySlug: 'homewares',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '7 spider clusters x 5 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-spider-stitch'],
  techniqueSlugs: ['crochet-spider-stitch', 'crochet-double-uk'],
  criticalTechniques: ['crochet-spider-stitch'],
  aliases: ['spider stitch blanket', 'spider web crochet', 'elongated loop mesh baby blanket'],
  glossaryTerms: [
    { slug: 'spider-st', term: 'Spider stitch', definition: 'Pull up 4-5 elongated loops from separate positions, yarn over, draw through all loops, then lock with one chain. The gathered loops spread like spider legs.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Three chains at the start of each spider stitch row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Spider stitch from Weldon\'s Practical Crochet (series 5, 1886). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('spider-st', 'spider stitch'), t(' baby blanket is 75 x 90 cm. Each stitch cluster pulls up 5 elongated loops from 5 separate points, gathers them with one yarn-over, and locks with a chain. DK cotton on a 4 mm hook gives fine spider clusters.')),
      p(t('The mesh is open enough to be lightweight but stable enough to hold its shape. Total yardage is around 250 g. The open structure uses less yarn than a solid dc fabric.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '250 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('How to work one spider cluster'),
      p(t('Pull up an elongated loop (about 1 cm) from each of 5 consecutive stitches. (6 loops on hook.) Yarn over and draw through all 6 loops. Ch 1 to lock. One spider cluster made from 5 stitches.')),
      h2('Gauge'),
      p(t('7 spider clusters x 5 rows = 10 x 10 cm in DK cotton with a 4 mm hook. One cluster uses 5 stitches. Foundation chain must be a multiple of 5 plus 2 edge chains.')),
      h2('Foundation chain'),
      p(t('Chain 107 (21 clusters of 5 ch + 2 edge).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 3. *Work one spider cluster over 5 chains, ch 1*. Repeat. Dc into last ch. Turn. (21 clusters.)')),
      h2('Row 2 and onward'),
      p(t('Ch 3. *Work spider cluster pulling up loops from the top of the 5 stitches of each cluster space*. Ch 1. Repeat. Dc into turning chain. Turn.')),
      p(t('Continue until piece measures 90 cm. Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block flat by pinning the mesh open.')),
      h2('Care'),
      p(t('Handwash cool. Pin flat while damp. The elongated loop clusters can distort if wet-bundled.')),
      h2('What to try next'),
      p(t('The Solomon\'s knot throw is another open loop-based mesh pattern. Or try the filet mesh baby blanket for a more structured open grid.')),
    ],
  },
},

// ── 59 ── magic ring granny motif blanket ─────────────────────────────────────
{
  slug: 'magic-ring-granny-motif-blanket',
  title: 'Magic ring granny motif blanket',
  subtitle: 'Small 4-round granny motifs joined as you go using the magic ring start.',
  excerpt: 'Each granny motif starts from a magic ring and is joined to its neighbours on the final round. The blanket is built motif by motif without a separate joining step.',
  subCategorySlug: 'homewares',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'aran',
  hook: 'crochet-hook-5-0mm',
  gauge: '1 motif = 8 x 8 cm blocked. 11 x 11 motifs = 88 x 88 cm.',
  finishedSize: 'Baby blanket, approx 88 x 88 cm (121 motifs).',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-granny-cluster', 'crochet-magic-ring', 'crochet-join-as-you-go'],
  techniqueSlugs: ['crochet-magic-ring', 'crochet-join-as-you-go', 'crochet-granny-cluster'],
  criticalTechniques: ['crochet-magic-ring', 'crochet-join-as-you-go'],
  aliases: ['magic ring granny blanket', 'jayg granny motif', 'join as you go blanket'],
  glossaryTerms: [
    { slug: 'magic-ring', term: 'Magic ring', definition: 'An adjustable loop start. Wind yarn around fingers to make a ring, work stitches into it, then pull the tail to close the centre hole completely.' },
    { slug: 'jayg', term: 'Join-as-you-go', definition: 'On the final round of each motif, replace one chain space with a slip stitch into the matching chain space of the adjacent motif. Joins motifs without sewing.' },
    { slug: 'granny-cluster', term: 'Granny cluster', definition: 'Three trebles worked into the same chain space, forming the basic unit of a granny square or motif.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Granny square motif from Weldon\'s Practical Crochet (series 3, 1880s). Magic ring is a modern technique. Join-as-you-go is a modern joining method. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A magic ring granny motif blanket is approximately 88 x 88 cm built from 121 small 4-round granny motifs. Each motif starts with a '), gt('magic-ring', 'magic ring'), t(' and is joined to its neighbours on round 4 using '), gt('jayg', 'join-as-you-go'), t('.')),
      p(t('No sewing is needed to assemble the blanket. Each new motif is attached as its final round is worked. Total yardage is around 800 g in aran. Using two or three colours in rotation gives a scrappy or planned-colour result.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'Aran yarn (one or more colours)', qty: '800 g total' },
        { name: '5 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Each motif (first motif only)'),
      p(t('Round 1: Magic ring. Ch 3, 2 tr into ring, ch 2. *3 tr into ring, ch 2*. Repeat 3 times. Sl st to top of ch 3. Pull ring closed. (4 groups of 3 tr with ch 2 corners.)')),
      p(t('Round 2: Sl st to corner space. Ch 3, 2 tr, ch 2, 3 tr into same space (corner made). *Ch 1, 3 tr, ch 2, 3 tr into next corner space*. Repeat 3 times. Ch 1. Sl st. (4 corners, 4 side ch-1 spaces.)')),
      p(t('Round 3: Work corners as before. Work 1 '), gt('granny-cluster', 'granny cluster'), t(' into each side ch-1 space. Ch 1 between clusters. Sl st. (4 corners, 8 side clusters.)')),
      p(t('Round 4: Repeat Round 3 structure, adding one more cluster to each side. Fasten off.')),
      h2('Each subsequent motif (join-as-you-go)'),
      p(t('Work rounds 1-3 as normal. On round 4, when working the side that meets an existing motif: replace each ch-2 corner with ch 1, sl st into matching corner space, ch 1. Replace each ch-1 side gap with sl st into matching ch-1 space. This joins the motifs on the go.')),
      h2('Assembly order'),
      p(t('Work in rows of 11 motifs. First row: 11 standalone motifs. Each subsequent motif in row 2 onward joins to the motif above and to the left on round 4.')),
      h2('Edging'),
      p(t('Work one round of dc (UK) around the full blanket perimeter. Work 3 dc into each corner of each motif at the outer edge. Work 3 dc into each outer blanket corner.')),
      h2('Finishing'),
      p(t('Secure all tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. Block each motif as it is made if using wool. Block the finished blanket flat.')),
      h2('Care'),
      p(t('Machine wash 40 degrees normal. Dry flat. The join-as-you-go seams are as strong as the motif stitches.')),
      h2('What to try next'),
      p(t('The granny square join blanket uses the same motifs sewn together rather than joined live. Or try the granny stripe baby blanket for a continuous-row approach using granny clusters without motifs.')),
    ],
  },
},

// ── 60 ── alpine stitch baby blanket ──────────────────────────────────────────
{
  slug: 'alpine-stitch-baby-blanket',
  title: 'Alpine stitch baby blanket',
  subtitle: 'Front post trebles worked in rows make a raised mountain-like texture.',
  excerpt: 'Alpine stitch alternates plain dc rows with rows of front post trebles worked into the dc 2 rows below. The front post trebles raise forward to make a sharp textured ridge.',
  subCategorySlug: 'homewares',
  difficulty: 'INTERMEDIATE',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Baby blanket, 75 x 90 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-fptr'],
  techniqueSlugs: ['crochet-fptr', 'crochet-double-uk'],
  criticalTechniques: ['crochet-fptr'],
  aliases: ['alpine stitch blanket', 'alpine crochet baby blanket', 'front post treble texture blanket'],
  glossaryTerms: [
    { slug: 'fptr', term: 'FPtr', definition: 'Front post treble. Yarn over, insert hook from front to back to front around the post of a stitch 2 rows below, and complete the treble. The stitch raises forward off the fabric surface.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'Two chains at the start of dc rows; one chain at the start of FPtr rows.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Front post treble stitch from Weldon\'s Practical Crochet (series 3, 1880s). Alpine stitch structure (alternating dc and FPtr rows) is a modern application. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('An alpine stitch baby blanket is 75 x 90 cm. Odd rows are plain dc. Even rows alternate dc and '), gt('fptr', 'FPtr'), t(' stitches, with each FPtr worked into the post of a dc 2 rows below. The front post trebles pull forward to make ridges.')),
      p(t('DK cotton shows the raised ridges clearly. The texture is regular and geometric. Total yardage is around 400 g. Alpine stitch uses slightly more yarn than plain dc because the FPtr stitches wrap around the post below.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '400 g' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook, working alpine stitch. At this gauge a foundation chain of 121 gives 75 cm width.')),
      h2('Stitches used'),
      ul(
        li(t('ch: chain')),
        li(t('dc (UK) / sc (US): double crochet')),
        li(t('FPtr: front post treble (worked into post 2 rows below)')),
      ),
      h2('Foundation chain'),
      p(t('Chain 121. Work one plain row of 120 dc. Turn.')),
      h2('Row 2 (plain dc)'),
      p(t('Ch 1. Dc into every stitch. Turn.')),
      h2('Row 3 (alpine row)'),
      p(t('Ch 1. Dc into first stitch. *FPtr into the dc 2 rows below the next stitch (skip the dc on the current row). Dc into the next stitch*. Repeat. Turn.')),
      h2('Row 4 and onward'),
      p(gt('turning-chain', 'Turning chain'), t(' pattern: work Row 2 (plain dc) then Row 3 (alpine) alternately until piece measures 90 cm (approximately 126 rows). Fasten off.')),
      h2('Finishing'),
      p(t('Work one round of dc (UK) around the perimeter. Work 3 dc into each corner. Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 30 degrees gentle. Dry flat.')),
      h2('What to try next'),
      p(t('The post stitch baby blanket uses both FPdc and BPdc for a ribbed effect. Or try the basketweave throw for a different post stitch texture in trebles.')),
    ],
  },
},

// ══════════════════════════════════════════════════════════════════════════════
// DISHCLOTHS + WASHCLOTHS 1-10
// ══════════════════════════════════════════════════════════════════════════════

// ── D1 ── basic double crochet dishcloth ───────────────────────────────────────
{
  slug: 'basic-dc-dishcloth',
  title: 'Basic dc dishcloth',
  subtitle: 'A square of plain double crochet in cotton DK. A first project for new crocheters.',
  excerpt: 'Plain double crochet rows in DK cotton make a functional dishcloth that is thick enough to scrub but soft enough for wiping. A 30-stitch square takes under two hours.',
  subCategorySlug: 'homewares',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['dc dishcloth', 'crochet face cloth', 'basic crochet cloth'],
  glossaryTerms: [
    { slug: 'dc-uk', term: 'Double crochet', definition: 'UK: dc. Insert hook, pull up loop, yarn over, draw through both loops. The shortest full stitch in standard crochet.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each dc row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Plain dc row from Weldon\'s Practical Crochet (series 1, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A basic dc dishcloth is 20 x 20 cm worked in plain '), gt('dc-uk', 'double crochet'), t('. DK cotton on a 4 mm hook gives a firm, absorbent fabric. One ball of 50 g DK cotton makes two dishcloths.')),
      p(t('This is the entry-level project for crochet beginners. The entire cloth is one stitch repeated in rows. Total yarn needed is around 30 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook. At this gauge chain 33 (32 dc) for 20 cm width. Work 40 rows for 20 cm height.')),
      h2('Foundation chain'),
      p(t('Chain 33.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1 (does not count). Work 1 dc into every chain from the 2nd. Turn. (32 dc.)')),
      h2('Rows 2 to 40'),
      p(t('Ch 1. Work 1 dc into every stitch across. Turn. Repeat for 40 rows.')),
      h2('Finishing'),
      p(t('Fasten off. Secure both tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. The cloth is ready to use without blocking.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang to dry. Cotton can withstand high temperatures.')),
      h2('What to try next'),
      p(t('The waffle stitch dishcloth adds texture using simple front loop variations. Or try the moss stitch dishcloth for a light raised-dot pattern.')),
    ],
  },
},

// ── D2 ── waffle stitch dishcloth ─────────────────────────────────────────────
{
  slug: 'waffle-stitch-dishcloth',
  title: 'Waffle stitch dishcloth',
  subtitle: 'Front loop dc and treble columns make a grid that looks and acts like waffle weave.',
  excerpt: 'Waffle stitch uses dc in the back loop and trebles in the front loop in a grid pattern. The raised columns make a textured surface that scrubs well.',
  subCategorySlug: 'homewares',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts x 10 rows = 10 x 10 cm in DK cotton with a 4 mm hook, waffle pattern.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble', 'crochet-flo-dc', 'crochet-blo-dc'],
  techniqueSlugs: ['crochet-flo-dc', 'crochet-blo-dc', 'crochet-double-uk'],
  criticalTechniques: ['crochet-flo-dc', 'crochet-blo-dc'],
  aliases: ['waffle stitch cloth', 'waffle crochet dishcloth', 'textured cotton dishcloth'],
  glossaryTerms: [
    { slug: 'flo-dc', term: 'FLO dc', definition: 'Double crochet worked into the front loop only. Leaves the back loop as a visible bar on the surface.' },
    { slug: 'blo-dc', term: 'BLO dc', definition: 'Double crochet worked into the back loop only. Leaves the front loop as a bar.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Waffle stitch from Weldon\'s Practical Crochet (series 3, 1880s), described as a ribbed dishcloth pattern. Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A waffle stitch dishcloth is 20 x 20 cm. The pattern works '), gt('flo-dc', 'FLO dc'), t(' in one stitch and '), gt('blo-dc', 'BLO dc'), t(' in the next, alternating across the row. The offset on the return row creates raised squares.')),
      p(t('The waffle grid is more absorbent than plain dc and scrubs more effectively. DK cotton on a 4 mm hook. Total yarn needed is around 30 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 sts x 10 rows = 10 x 10 cm in DK cotton with a 4 mm hook, working waffle pattern. The waffle draws in slightly; check swatch for exact row count.')),
      h2('Foundation chain'),
      p(t('Chain 33.')),
      h2('Row 1'),
      p(t('Ch 1. *1 FLO dc, 1 BLO dc*. Repeat across. Turn. (32 sts.)')),
      h2('Row 2'),
      p(t('Ch 1. *1 BLO dc, 1 FLO dc*. Repeat across. Turn.')),
      h2('Rows 3 onward'),
      p(t('Alternate Row 1 and Row 2 for 20 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('. No edging needed.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang. Cotton handles high wash temperatures well.')),
      h2('What to try next'),
      p(t('The basic dc dishcloth is the simpler starter version. Or try the moss stitch dishcloth for a raised-dot surface.')),
    ],
  },
},

// ── D3 ── moss stitch dishcloth ────────────────────────────────────────────────
{
  slug: 'moss-stitch-dishcloth',
  title: 'Moss stitch dishcloth',
  subtitle: 'Alternating dc and chain-1 spaces create a moss or seed stitch texture.',
  excerpt: 'Moss stitch alternates a dc with a skipped stitch and a chain-1 space. The offset stitches on each row make a compact raised-dot texture that looks like moss.',
  subCategorySlug: 'homewares',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts x 18 rows = 10 x 10 cm in DK cotton with a 4 mm hook, moss pattern.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-chain-foundation'],
  criticalTechniques: ['crochet-double-uk'],
  aliases: ['moss stitch cloth', 'seed stitch dishcloth', 'granite stitch dishcloth'],
  glossaryTerms: [
    { slug: 'moss-st', term: 'Moss stitch', definition: 'Also called granite or seed stitch. Work 1 dc, ch 1, skip 1. On the next row work the dc into the skipped stitch of the row below (into the ch-1 space).' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each moss stitch row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Moss/granite stitch from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('moss-st', 'moss stitch'), t(' dishcloth is 20 x 20 cm. Dc stitches sit in the chain spaces from the row below, giving a compact raised-dot pattern. DK cotton on a 4 mm hook.')),
      p(t('Moss stitch is nearly as dense as plain dc but the offset dots give more texture. Total yarn needed is around 30 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 33 (even number of stitches).')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Dc into 2nd ch. *Ch 1, skip 1, dc into next ch*. Repeat. Turn.')),
      h2('Row 2'),
      p(t('Ch 1. *Dc into ch-1 space, ch 1, skip dc*. Repeat. Turn.')),
      h2('Rows 3 onward'),
      p(t('Repeat Row 2 for 36 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The lemon peel dishcloth uses a similar offset pattern. Or try the waffle stitch dishcloth for a bolder raised grid.')),
    ],
  },
},

// ── D4 ── shell edged face cloth ─────────────────────────────────────────────
{
  slug: 'shell-edged-face-cloth',
  title: 'Shell edged face cloth',
  subtitle: 'A plain dc face cloth finished with a three-sided shell stitch border.',
  excerpt: 'A 25 x 25 cm face cloth in plain dc with a shell stitch border on three sides. The shells add a decorative edge and are worked as a final round after the main fabric.',
  subCategorySlug: 'homewares',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 dc x 20 rows = 10 x 10 cm in DK cotton with a 4 mm hook.',
  finishedSize: 'Face cloth, 25 x 25 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-shell'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-shell'],
  criticalTechniques: ['crochet-shell'],
  aliases: ['shell edged face cloth', 'decorative washcloth', 'shell border cloth'],
  glossaryTerms: [
    { slug: 'shell-st', term: 'Shell stitch', definition: 'Five trebles worked into the same stitch or space, fanning out into a decorative shell shape.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of each dc row. Does not count as a stitch.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'SYNTHESISED',
  sourceNotes: 'Shell stitch edging from Weldon\'s Practical Crochet (series 2, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A shell edged face cloth is 25 x 25 cm. The body is plain dc in DK cotton. A round of '), gt('shell-st', 'shell stitch'), t(' borders the finished cloth on three sides, with the top left plain for hanging or folding.')),
      p(t('DK cotton in a pale colour shows the shell edge clearly. Total yarn needed is around 45 m.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '45 m (about 35 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Gauge'),
      p(t('16 dc x 20 rows = 10 x 10 cm. At this gauge chain 41 (40 dc) for 25 cm width. Work 50 rows for 25 cm height.')),
      h2('Body'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. Work 1 dc into every stitch across. Turn. Repeat for 50 rows. Fasten off.')),
      h2('Shell edging (3 sides)'),
      p(t('Join yarn at the bottom left corner. Ch 1. Work 1 dc into each stitch along the bottom edge. At the corner: 3 dc into the corner stitch. Work 1 dc into each row end up the right side. At the top right corner: 3 dc, then fasten off. Left and top sides are left plain.')),
      p(t('Re-join. Work one more pass along the same 3 sides: *skip 2, 5 tr into next st (shell), skip 2, dc*. Repeat. Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The picot edged dishcloth uses a smaller decorative edge. Or try the basic dc dishcloth without a border for the simplest version.')),
    ],
  },
},

// ── D5 ── lemon peel dishcloth ────────────────────────────────────────────────
{
  slug: 'lemon-peel-dishcloth',
  title: 'Lemon peel dishcloth',
  subtitle: 'Alternating dc and treble in the same row make a pebbled lemon peel texture.',
  excerpt: 'Lemon peel stitch puts a dc and a treble into consecutive stitches, alternating on each row so the taller and shorter stitches offset into a pebbled texture.',
  subCategorySlug: 'homewares',
  difficulty: 'BEGINNER',
  yarnWeight: 'dk',
  hook: 'crochet-hook-4-0mm',
  gauge: '16 sts x 14 rows = 10 x 10 cm in DK cotton with a 4 mm hook, lemon peel pattern.',
  finishedSize: 'Square dishcloth, 20 x 20 cm.',
  stitchSlugs: ['crochet-chain', 'crochet-double-uk', 'crochet-treble'],
  techniqueSlugs: ['crochet-double-uk', 'crochet-treble'],
  criticalTechniques: ['crochet-double-uk', 'crochet-treble'],
  aliases: ['lemon peel stitch cloth', 'alternate dc tr dishcloth', 'pebble stitch dishcloth'],
  glossaryTerms: [
    { slug: 'lemon-peel-st', term: 'Lemon peel stitch', definition: 'Alternate 1 dc and 1 tr across every row, but offset the stitches so dc falls over tr and tr falls over dc on subsequent rows. The height difference puckers the fabric into small bumps.' },
    { slug: 'turning-chain', term: 'Turning chain', definition: 'One chain at the start of a lemon peel row.' },
    { slug: 'weaving-in-ends', term: 'Weaving in ends', definition: 'Threading yarn tails through stitches with the tapestry needle.' },
  ],
  sourceType: 'PUBLIC_DOMAIN',
  sourceNotes: 'Lemon peel stitch from Weldon\'s Practical Crochet (series 3, 1880s). Internet Archive.',
  body: {
    type: 'doc', content: [
      p(t('A '), gt('lemon-peel-st', 'lemon peel'), t(' dishcloth is 20 x 20 cm. Each row alternates dc and tr stitches. The next row places the opposite stitch over each, so the short and tall stitches offset to make small bumps across the surface.')),
      p(t('DK cotton on a 4 mm hook. Total yarn needed is around 30 m. The pebbled texture scrubs better than plain dc.')),
      h2('What you need'),
      supplies('Materials', [
        { name: 'DK cotton yarn', qty: '30 m (about 25 g)' },
        { name: '4 mm crochet hook', qty: '1' },
        { name: 'Tapestry needle', qty: '1' },
        { name: 'Scissors', qty: '1 pair' },
      ]),
      h2('Foundation chain'),
      p(t('Chain 33.')),
      h2('Row 1'),
      p(gt('turning-chain', 'Turning chain'), t(' of ch 1. *1 dc, 1 tr*. Repeat across. Last stitch dc. Turn. (32 sts.)')),
      h2('Row 2'),
      p(t('Ch 1. *1 tr, 1 dc*. Repeat. Last stitch tr. Turn.')),
      h2('Rows 3 onward'),
      p(t('Alternate Row 1 and Row 2 for 28 rows total (approximately 20 cm). Fasten off.')),
      h2('Finishing'),
      p(t('Secure tails with '), gt('weaving-in-ends', 'weaving in ends'), t('.')),
      h2('Care'),
      p(t('Machine wash 60 degrees normal. Tumble dry or hang.')),
      h2('What to try next'),
      p(t('The moss stitch dishcloth uses a similar offset pattern with chain spaces. Or try the waffle stitch dishcloth for a bolder grid texture.')),
    ],
  },
},

]

// ── write files ───────────────────────────────────────────────────────────────
for (const pat of PATTERNS) {
  const out = {
    slug: pat.slug,
    title: pat.title,
    subtitle: pat.subtitle,
    excerpt: pat.excerpt,
    type: 'PATTERN',
    categorySlug: 'crochet',
    subCategorySlug: pat.subCategorySlug,
    difficulty: pat.difficulty,
    sourceType: pat.sourceType,
    sourceNotes: pat.sourceNotes,
    techniqueSlugs: pat.techniqueSlugs,
    criticalTechniques: pat.criticalTechniques,
    aliases: pat.aliases,
    glossaryTerms: pat.glossaryTerms,
    crochet: {
      primaryYarnWeightSlug: pat.yarnWeight,
      primaryHookSlug: pat.hook,
      gaugeText: pat.gauge,
      finishedSizeText: pat.finishedSize,
      terminologyConvention: 'uk',
      craftStitchSlugs: pat.stitchSlugs,
      craftTechniqueTags: pat.techniqueSlugs,
    },
    recipeTools: TOOLS,
    body: pat.body,
  }
  writeFileSync(join(OUT, `${pat.slug}.json`), JSON.stringify(out, null, 2))
  console.log(`Written: ${pat.slug}`)
}
console.log(`\nDone: ${PATTERNS.length} patterns`)
