/**
 * Builds the master ingredient + tool lookup blocks the body-authoring prompt
 * in `docs/tutorial-author.md` references. The output is a compact text table
 * a model can scan to pick the right `ingredientSlug` / tool slug for a recipe.
 *
 * Run:
 *   pnpm --filter "@homemade/db" exec tsx scripts/generate-master-lookup.ts
 *
 * Behaviour:
 *   - Reads `packages/db/scripts/data/ingredients.ts` and `tools.ts`.
 *   - Replaces the content between fence markers in `docs/tutorial-author.md`:
 *
 *       <!-- BEGIN INGREDIENT_LOOKUP (generated by generate-master-lookup.ts) -->
 *       … table …
 *       <!-- END INGREDIENT_LOOKUP -->
 *
 *       <!-- BEGIN TOOL_LOOKUP (generated by generate-master-lookup.ts) -->
 *       … table …
 *       <!-- END TOOL_LOOKUP -->
 *
 *   - If `--stdout` is passed, prints the blocks instead of patching the file
 *     (useful for diffing or eyeballing).
 *
 * Format:
 *   - Ingredients are grouped by `category` (flour, dairy, …). One row per line.
 *   - Each row: `slug | name | unit | dietary | aliases`.
 *   - Tools are grouped by `category` and follow `slug | name | aliases`.
 *
 * The format is built for token economy: pipes as separators, no markdown
 * table syntax, no per-line whitespace padding. Categories give the model
 * structure to scan; the dietary column lets it filter recipes without a
 * second lookup pass.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { INGREDIENTS } from './data/ingredients.js'
import { TOOLS } from './data/tools.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

function categoryOrder<T extends string>(values: readonly T[]): Map<T, number> {
  const out = new Map<T, number>()
  values.forEach((v, i) => out.set(v, i))
  return out
}

// Stable category order — keeps diffs small across regenerations.
const INGREDIENT_CATEGORY_ORDER = categoryOrder<string>([
  'flour',
  'grain',
  'dairy',
  'meat',
  'fish',
  'vegetable',
  'fruit',
  'herb',
  'spice',
  'condiment',
  'pulse',
  'nut',
  'seed',
  'baking',
  'oil',
  'sweetener',
  'alcohol',
  'other',
])

const TOOL_CATEGORY_ORDER = categoryOrder<string>([
  'knife',
  'pan',
  'pot',
  'oven',
  'mixer',
  'processor',
  'measuring',
  'bowl',
  'tray',
  'tin',
  'board',
  'utensil',
  'thermometer',
  'scale',
  'appliance',
  'electrical',
  'other',
])

function sortKey(category: string, order: Map<string, number>): number {
  return order.has(category) ? order.get(category)! : 999
}

function buildIngredientBlock(): string {
  const lines: string[] = []
  lines.push('Format: slug | name | unit | dietary | aliases')
  lines.push('Dietary flags are abbreviated (v=vegetarian, V=vegan, gf=glutenFree, df=dairyFree, nf=nutFree). Empty when none.')
  lines.push('')

  const byCategory = new Map<string, typeof INGREDIENTS>()
  for (const ing of INGREDIENTS) {
    const list = byCategory.get(ing.category) ?? []
    list.push(ing)
    byCategory.set(ing.category, list)
  }

  const categories = Array.from(byCategory.keys()).sort(
    (a, b) => sortKey(a, INGREDIENT_CATEGORY_ORDER) - sortKey(b, INGREDIENT_CATEGORY_ORDER),
  )

  for (const cat of categories) {
    lines.push(`### ${cat}`)
    const items = (byCategory.get(cat) ?? []).slice().sort((a, b) => a.slug.localeCompare(b.slug))
    for (const ing of items) {
      const dietary = abbreviateDietary(ing.dietaryFlags)
      const aliases = ing.aliases.length > 0 ? ing.aliases.join(', ') : '-'
      lines.push(`${ing.slug} | ${ing.name} | ${ing.defaultUnit} | ${dietary || '-'} | ${aliases}`)
    }
    lines.push('')
  }

  return lines.join('\n').trimEnd()
}

function abbreviateDietary(flags: readonly string[]): string {
  const map: Record<string, string> = {
    vegetarian: 'v',
    vegan: 'V',
    glutenFree: 'gf',
    dairyFree: 'df',
    nutFree: 'nf',
    halal: 'h',
    kosher: 'k',
  }
  return flags
    .map((f) => map[f] ?? f)
    .filter(Boolean)
    .join(',')
}

function buildToolBlock(): string {
  const lines: string[] = []
  lines.push('Format: slug | name | aliases')
  lines.push('')

  const byCategory = new Map<string, typeof TOOLS>()
  for (const tool of TOOLS) {
    const list = byCategory.get(tool.category) ?? []
    list.push(tool)
    byCategory.set(tool.category, list)
  }

  const categories = Array.from(byCategory.keys()).sort(
    (a, b) => sortKey(a, TOOL_CATEGORY_ORDER) - sortKey(b, TOOL_CATEGORY_ORDER),
  )

  for (const cat of categories) {
    lines.push(`### ${cat}`)
    const items = (byCategory.get(cat) ?? []).slice().sort((a, b) => a.slug.localeCompare(b.slug))
    for (const tool of items) {
      const aliases = tool.aliases.length > 0 ? tool.aliases.join(', ') : '-'
      lines.push(`${tool.slug} | ${tool.name} | ${aliases}`)
    }
    lines.push('')
  }

  return lines.join('\n').trimEnd()
}

function replaceFence(text: string, marker: string, body: string): string {
  const start = `<!-- BEGIN ${marker} (generated by generate-master-lookup.ts) -->`
  const end = `<!-- END ${marker} -->`
  const startIdx = text.indexOf(start)
  const endIdx = text.indexOf(end, startIdx)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `Could not find fence markers for "${marker}" in tutorial-author.md. Add a block:\n${start}\n\n${end}`,
    )
  }
  const head = text.slice(0, startIdx + start.length)
  const tail = text.slice(endIdx)
  return `${head}\n${body}\n${tail}`
}

async function main(): Promise<void> {
  const ingredientBlock = buildIngredientBlock()
  const toolBlock = buildToolBlock()

  const stdoutOnly = process.argv.includes('--stdout')

  if (stdoutOnly) {
    console.log('--- INGREDIENT_LOOKUP ---')
    console.log(ingredientBlock)
    console.log()
    console.log('--- TOOL_LOOKUP ---')
    console.log(toolBlock)
    return
  }

  const docPath = resolve(__dirname, '../../..', 'docs', 'tutorial-author.md')
  if (!existsSync(docPath)) {
    throw new Error(`docs/tutorial-author.md not found at ${docPath}`)
  }
  let text = readFileSync(docPath, 'utf8')
  text = replaceFence(text, 'INGREDIENT_LOOKUP', ingredientBlock)
  text = replaceFence(text, 'TOOL_LOOKUP', toolBlock)
  writeFileSync(docPath, text, 'utf8')

  console.log(`[generate-master-lookup] wrote ${INGREDIENTS.length} ingredients + ${TOOLS.length} tools into ${docPath}`)
}

main().catch((err) => {
  console.error('[generate-master-lookup] failed:', err)
  process.exit(1)
})
