import { NextResponse } from 'next/server'
import {
  prisma,
  parsePatternData,
  estimateSkeinCount,
} from '@homemade/db'
import { getCurrentDbUser } from '@/lib/get-current-user'
import { hasPremium } from '@/lib/entitlements'
import { isLibraryPattern } from '@/lib/studio/library-visibility'

export const dynamic = 'force-dynamic'

interface Ctx {
  params: Promise<{ id: string }>
}

/**
 * GET /api/studio/patterns/[id]/floss-list — plain-text shopping list.
 *
 * Format:
 *
 *   Pattern name
 *   Brand Code   Name                          Stitches    Skeins
 *   DMC   310    Black                              1,247      2.5
 *
 * The mono-font alignment is the point — copy into a notepad, take it
 * to the shop. PDF version is a separate endpoint and lives inside the
 * "Export as PDF" workflow.
 */
export async function GET(_req: Request, ctx: Ctx) {
  const { id } = await ctx.params

  // Downloading the floss list is a premium action (universal print/download gate).
  const user = await getCurrentDbUser()
  if (!hasPremium(user)) {
    return new NextResponse('Homemade Premium is required to download the floss list.', { status: 402 })
  }

  const row = await prisma.pattern.findUnique({
    where: { id },
    select: {
      id: true,
      name: true,
      data: true,
      ownerUserId: true,
      visibility: true,
    },
  })
  if (!row) return new NextResponse('Not found', { status: 404 })

  const isLibrary = isLibraryPattern(row)
  if (!isLibrary && row.ownerUserId !== user!.id) {
    return new NextResponse('Not authorised', { status: 403 })
  }

  let data
  try { data = parsePatternData(row.data) } catch {
    return new NextResponse('Pattern data is malformed', { status: 500 })
  }

  const rows = data.palette.map((entry) => {
    let stitches = 0
    for (const cell of data.grid.cells) if (cell.s === entry.symbol) stitches++
    return {
      brand: entry.brand,
      code: entry.code,
      name: entry.name,
      stitches,
      skeins: estimateSkeinCount(data, entry.symbol),
    }
  })

  const lines: string[] = []
  lines.push(row.name)
  lines.push(''.padEnd(row.name.length, '─'))
  lines.push(pad('Brand', 7) + pad('Code', 8) + pad('Name', 28) + pad('Stitches', 10) + 'Skeins')
  for (const r of rows) {
    lines.push(
      pad(r.brand, 7) +
        pad(r.code, 8) +
        pad(r.name.slice(0, 26), 28) +
        pad(r.stitches.toLocaleString(), 10) +
        formatSkein(r.skeins),
    )
  }
  lines.push('')
  lines.push('Skein estimates include a 25% safety margin.')
  lines.push('Generated by homemade.education')

  return new NextResponse(lines.join('\n'), {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'content-disposition': `inline; filename="${slugify(row.name)}-floss-list.txt"`,
    },
  })
}

function pad(s: string, width: number): string {
  if (s.length >= width) return s.slice(0, width)
  return s + ' '.repeat(width - s.length)
}
function formatSkein(n: number): string {
  return Number.isInteger(n) ? `${n}` : n.toFixed(1)
}
function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60) || 'pattern'
}
