/**
 * GENERATED by `scripts/loom-preset-sizes.ts` — do not hand-edit.
 *
 * Measured sizes off the settled, relaxed, audit-gated geometry — the same
 * pipeline the render compiles. Regenerate with:
 *
 *   cd apps/web && npx tsx scripts/loom-preset-sizes.ts
 *
 * `amigurumi-presets.test.ts` re-measures on every run and fails the build if
 * either table below has drifted more than 10% from what a fresh compile
 * settles to, so a re-cut round builder can never leave this file stale.
 */

/** One piece's settled width x height in mm at worsted weight, by round profile
 *  (`rounds.join(',')`). Built and measured standing alone on the ground. */
export const PROFILE_SIZE_MM_GENERATED: Record<string, { width: number; height: number }> = {
  "6,12,12,6": {
    "width": 25.1,
    "height": 15.4
  },
  "6,12,12,12,6": {
    "width": 26.1,
    "height": 20.7
  },
  "6,12,12,12,12,6": {
    "width": 26.2,
    "height": 26
  },
  "6,12,12,12,12,12,6": {
    "width": 26.3,
    "height": 31.4
  },
  "6,12,12,12,12,12,12,12,6": {
    "width": 26.3,
    "height": 41.8
  },
  "6,12,18,18,18,12,6": {
    "width": 38,
    "height": 24.4
  },
  "6,12,18,18,18,18,12,6": {
    "width": 38,
    "height": 29.4
  },
  "6,12,18,18,18,18,18,18,18,18,18,12,6": {
    "width": 38.5,
    "height": 56.1
  },
  "6,12,18,24,24,24,24,24,18,12,6": {
    "width": 50.4,
    "height": 38
  },
  "6,12,18,24,24,24,24,24,24,24,24,18,12,6": {
    "width": 50.5,
    "height": 53.9
  },
  "6,12,18,24,24,24,24,24,24,24,24,24,24,18,12,6": {
    "width": 50.5,
    "height": 64.3
  },
  "6,12,18,24,30,30,30,30,30,30,24,18,12,6": {
    "width": 62.7,
    "height": 46.4
  },
  "6,12,18,24,30,30,30,30,30,30,30,24,18,12,6": {
    "width": 62.8,
    "height": 51.7
  },
  "6,12,18,24,30,36,36,36,36,36,36,30,24,18,12,6": {
    "width": 74.7,
    "height": 49.6
  },
  "6,12,18,24,30,36,36,36,36,36,36,36,36,30,24,18,12,6": {
    "width": 74.7,
    "height": 60.2
  },
  "6,12,12,12,12,10,8,6": {
    "width": 26.3,
    "height": 38.9
  },
  "6,12,12,12,12,12,10,8,6": {
    "width": 26.3,
    "height": 44.2
  },
  "6,12,12,12,12,12,12,12,10,8,6": {
    "width": 26.8,
    "height": 54.8
  }
}

/** The whole finished piece's settled size (rounded to the nearest 5 mm, the
 *  way a pattern's finished-size line is), by `${base}-${size}`. */
export const PRESET_SETTLED_SIZE_MM_GENERATED: Record<string, { width: number; height: number }> = {
  "ball-S": {
    "width": 25,
    "height": 30
  },
  "ball-M": {
    "width": 50,
    "height": 55
  },
  "ball-L": {
    "width": 75,
    "height": 60
  },
  "egg-S": {
    "width": 25,
    "height": 40
  },
  "egg-M": {
    "width": 40,
    "height": 55
  },
  "egg-L": {
    "width": 50,
    "height": 65
  },
  "bear-S": {
    "width": 90,
    "height": 85
  },
  "bear-M": {
    "width": 100,
    "height": 115
  },
  "bear-L": {
    "width": 130,
    "height": 130
  },
  "bunny-S": {
    "width": 90,
    "height": 105
  },
  "bunny-M": {
    "width": 100,
    "height": 140
  },
  "bunny-L": {
    "width": 130,
    "height": 150
  }
}
