/**
 * GENERATED by `scripts/loom-preset-sizes.ts` — do not hand-edit.
 *
 * Measured sizes off the settled, relaxed, audit-gated geometry — the same
 * pipeline the render compiles. Regenerate with:
 *
 *   cd apps/web && npx tsx scripts/loom-preset-sizes.ts
 *
 * `amigurumi-presets.test.ts` re-measures on every run and fails the build if
 * either table below has drifted more than 10% from what a fresh compile
 * settles to, so a re-cut round builder can never leave this file stale.
 */

/** One piece's settled width x height in mm at worsted weight, by round profile
 *  (`rounds.join(',')`). Built and measured standing alone on the ground. */
export const PROFILE_SIZE_MM_GENERATED: Record<string, { width: number; height: number }> = {
  "6,12,12,6": {
    "width": 23.1,
    "height": 14.5
  },
  "6,12,12,12,6": {
    "width": 24.5,
    "height": 19.8
  },
  "6,12,12,12,12,6": {
    "width": 24.7,
    "height": 24.8
  },
  "6,12,12,12,12,12,6": {
    "width": 24.7,
    "height": 30.2
  },
  "6,12,12,12,12,12,12,12,6": {
    "width": 24.9,
    "height": 40.8
  },
  "6,12,18,18,18,12,6": {
    "width": 35.3,
    "height": 22.5
  },
  "6,12,18,18,18,18,12,6": {
    "width": 35.5,
    "height": 27.8
  },
  "6,12,18,18,18,18,18,18,18,18,18,12,6": {
    "width": 35.5,
    "height": 54
  },
  "6,12,18,24,24,24,24,24,18,12,6": {
    "width": 46.5,
    "height": 35.9
  },
  "6,12,18,24,24,24,24,24,24,24,24,18,12,6": {
    "width": 47.1,
    "height": 51.5
  },
  "6,12,18,24,24,24,24,24,24,24,24,24,24,18,12,6": {
    "width": 47.3,
    "height": 62
  },
  "6,12,18,24,30,30,30,30,30,30,24,18,12,6": {
    "width": 57.2,
    "height": 43.4
  },
  "6,12,18,24,30,30,30,30,30,30,30,24,18,12,6": {
    "width": 57.8,
    "height": 49
  },
  "6,12,18,24,30,36,36,36,36,36,36,30,24,18,12,6": {
    "width": 68.7,
    "height": 46
  },
  "6,12,18,24,30,36,36,36,36,36,36,36,36,30,24,18,12,6": {
    "width": 68.7,
    "height": 56.6
  },
  "6,12,12,12,12,10,8,6": {
    "width": 24.7,
    "height": 38.5
  },
  "6,12,12,12,12,12,10,8,6": {
    "width": 24.7,
    "height": 43.8
  },
  "6,12,12,12,12,12,12,12,10,8,6": {
    "width": 24.8,
    "height": 54.4
  }
}

/** The whole finished piece's settled size (rounded to the nearest 5 mm, the
 *  way a pattern's finished-size line is), by `${base}-${size}`. */
export const PRESET_SETTLED_SIZE_MM_GENERATED: Record<string, { width: number; height: number }> = {
  "ball-S": {
    "width": 25,
    "height": 30
  },
  "ball-M": {
    "width": 45,
    "height": 50
  },
  "ball-L": {
    "width": 70,
    "height": 55
  },
  "egg-S": {
    "width": 25,
    "height": 40
  },
  "egg-M": {
    "width": 35,
    "height": 55
  },
  "egg-L": {
    "width": 45,
    "height": 60
  },
  "bear-S": {
    "width": 85,
    "height": 80
  },
  "bear-M": {
    "width": 95,
    "height": 105
  },
  "bear-L": {
    "width": 125,
    "height": 120
  },
  "bunny-S": {
    "width": 85,
    "height": 100
  },
  "bunny-M": {
    "width": 95,
    "height": 135
  },
  "bunny-L": {
    "width": 125,
    "height": 145
  }
}
