/**
 * GENERATED by `scripts/loom-preset-sizes.ts` — do not hand-edit.
 *
 * Measured sizes off the settled, relaxed, audit-gated geometry — the same
 * pipeline the render compiles. Regenerate with:
 *
 *   cd apps/web && npx tsx scripts/loom-preset-sizes.ts
 *
 * `amigurumi-presets.test.ts` re-measures on every run and fails the build if
 * either table below has drifted more than 10% from what a fresh compile
 * settles to, so a re-cut round builder can never leave this file stale.
 */

/** One piece's settled width x height in mm at worsted weight, by round profile
 *  (`rounds.join(',')`). Built and measured standing alone on the ground. */
export const PROFILE_SIZE_MM_GENERATED: Record<string, { width: number; height: number }> = {
  "6,11,12,12,11,6": {
    "width": 26.1,
    "height": 28.8
  },
  "6,11,12,12,12,12,12,11,6": {
    "width": 26.7,
    "height": 44.5
  },
  "6,12,16,18,18,18,16,12,6": {
    "width": 37.9,
    "height": 39
  },
  "6,12,16,18,18,18,18,18,18,18,16,12,6": {
    "width": 38.7,
    "height": 60.2
  },
  "6,12,17,21,23,24,24,23,21,17,12,6": {
    "width": 50.4,
    "height": 50.5
  },
  "6,12,17,21,23,24,24,24,24,24,24,23,21,17,12,6": {
    "width": 50.5,
    "height": 71.5
  },
  "6,12,18,22,26,28,30,30,30,28,26,22,18,12,6": {
    "width": 62.6,
    "height": 60.4
  },
  "6,12,18,23,28,31,33,35,36,36,36,35,33,31,28,23,18,12,6": {
    "width": 74.7,
    "height": 76.3
  },
  "6,12,12,6": {
    "width": 25.1,
    "height": 15.4
  },
  "6,12,12,12,6": {
    "width": 26.1,
    "height": 20.7
  },
  "6,12,12,12,12,6": {
    "width": 26.2,
    "height": 26
  },
  "6,12,18,18,18,12,6": {
    "width": 38,
    "height": 24.4
  },
  "6,12,12,12,12,10,8,6": {
    "width": 26.3,
    "height": 38.9
  },
  "6,12,12,12,12,12,10,8,6": {
    "width": 26.3,
    "height": 44.2
  },
  "6,12,12,12,12,12,12,12,10,8,6": {
    "width": 26.8,
    "height": 54.8
  },
  "6,12,12,12,10,8,6": {
    "width": 25.7,
    "height": 33.6
  },
  "6,12,10,8,6": {
    "width": 23.7,
    "height": 24.7
  },
  "6,12,12,10,8,6": {
    "width": 24.9,
    "height": 28.3
  },
  "6,6,6,6,6": {
    "width": 14,
    "height": 27.4
  },
  "6,6,6,6,6,6,6,6,6": {
    "width": 14.1,
    "height": 48.5
  }
}

/** The whole finished piece's settled size (rounded to the nearest 5 mm, the
 *  way a pattern's finished-size line is), by `${base}-${size}`. */
export const PRESET_SETTLED_SIZE_MM_GENERATED: Record<string, { width: number; height: number }> = {
  "ball-S": {
    "width": 25,
    "height": 30
  },
  "ball-M": {
    "width": 50,
    "height": 50
  },
  "ball-L": {
    "width": 75,
    "height": 75
  },
  "egg-S": {
    "width": 25,
    "height": 45
  },
  "egg-M": {
    "width": 40,
    "height": 60
  },
  "egg-L": {
    "width": 50,
    "height": 70
  },
  "bear-S": {
    "width": 75,
    "height": 105
  },
  "bear-M": {
    "width": 85,
    "height": 125
  },
  "bear-L": {
    "width": 120,
    "height": 160
  },
  "bunny-S": {
    "width": 95,
    "height": 125
  },
  "bunny-M": {
    "width": 105,
    "height": 155
  },
  "bunny-L": {
    "width": 140,
    "height": 185
  },
  "cat-S": {
    "width": 95,
    "height": 105
  },
  "cat-M": {
    "width": 105,
    "height": 130
  },
  "cat-L": {
    "width": 140,
    "height": 170
  },
  "dog-S": {
    "width": 95,
    "height": 95
  },
  "dog-M": {
    "width": 105,
    "height": 115
  },
  "dog-L": {
    "width": 140,
    "height": 150
  },
  "bird-S": {
    "width": 40,
    "height": 65
  },
  "bird-M": {
    "width": 60,
    "height": 90
  },
  "bird-L": {
    "width": 80,
    "height": 110
  },
  "chick-S": {
    "width": 45,
    "height": 65
  },
  "chick-M": {
    "width": 65,
    "height": 85
  },
  "chick-L": {
    "width": 80,
    "height": 105
  }
}

/** The settled GEOMETRY HASH of every preset (first 8 hex of
 *  `compileComposition(...).geometryHash`), by `${base}-${size}`. The hash
 *  guard: `amigurumi-presets.test.ts` fails if a fresh compile moves any of
 *  these, so a change can only move the presets it meant to — and every one
 *  that moves needs a fresh look against its reference before it ships. */
export const PRESET_GEOMETRY_HASH_GENERATED: Record<string, string> = {
  "ball-S": "5867862c",
  "ball-M": "532617ca",
  "ball-L": "b7819654",
  "egg-S": "b66b1897",
  "egg-M": "257908e7",
  "egg-L": "3f11a2c3",
  "bear-S": "6938c75e",
  "bear-M": "7c83a4c8",
  "bear-L": "c9a7054a",
  "bunny-S": "66ccb78a",
  "bunny-M": "3ad55da3",
  "bunny-L": "cf20b836",
  "cat-S": "393281f6",
  "cat-M": "bdb741b0",
  "cat-L": "5f10b0c8",
  "dog-S": "1228be29",
  "dog-M": "f60359f1",
  "dog-L": "1b0a6e40",
  "bird-S": "01ffe84b",
  "bird-M": "1a86c933",
  "bird-L": "e4091d8e",
  "chick-S": "81066222",
  "chick-M": "55ebb3e8",
  "chick-L": "ee42d27c"
}
